This notebook is for the very initial preprocessing of our chosen data.
Author: loua

Choices made regarding missing data:
Since we are dealing with just one data type - that is, the number of people (integers) - we do the following: If a column has some cells with data > 0, then we set cells with missing data in that column to 0. If a column only has rows with missing data, we set all 0/'-' to NaN and drop the column.

#### Done
- socioeconomy
- citizenship (and age and sex)
- education
- immigrants
- tenure
- type
- simple (contains income, car, benefit type, arrests)
- builtyear (housing construction year)

#### Extras
- [] Add valgsted navn(e), kredsnavn
- [] Area in sq metres
- [] Put election data in same format (one csv for each year)

#### TO DO
- [] Citizenship but only for 20+ years

In [1]:
# Libraries
import pandas as pd
import combine_raw_data as cb

# Configuration
from combine_raw_data import ROOT, PARENT_PATH, PATH, OUTPUT_PATH, YEARS, MUNICIPALITY_IDS, COMMON_COLS, PREFIX, CPH_AREAS

## PersonsBySocioeconomyIndustry

We want data for arbejdsløse, topledere and selvstændige. But there are similar column names for both topledere and selvstændige - we need to check these columns to see if data is duplicated, different, or only exists in one of the similarly named columns.

In [2]:
# Socio-økonomisk status og brancher fordelt på afstemningsområder,Population_PersonsBySocioeconomyIndustry.csv
path = PATH + 'PersonsBySocioeconomyIndustry.csv'
prefixes = [f"{PREFIX}{year}" for year in YEARS]
pattern = ' - Socio-økonomisk status og brancher fordelt på afstemningsområder_'
wanted_cols = [
    '07. Arbejdsløse_',
    '02. Topledere_',
    '01. Selvstændig og medhj._'
]
cols = []

df = pd.read_csv(path, sep=';', dtype=str)
df = df[df['Gruppe'].isin(CPH_AREAS)]

for prefix in prefixes:
    for name in wanted_cols:
        colname_start = f'{prefix}{pattern}{name}'
        for col in df.columns:
            if col.startswith(colname_start):
                cols.append(col)

final_cols = COMMON_COLS + cols
df = df[final_cols]

df_transposed = df.transpose()

df_transposed.tail()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Information og kommunikation,74,43,76,47,46,46,129,54,119,57,...,47,51,19,69,62,63,41,39,28,77
KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Kultur fritid og anden service,73,41,88,62,48,56,158,78,156,50,...,40,89,35,68,57,72,62,47,45,112
KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Landbrug skovbrug og fiskeri,3,4,5,-,2,2,5,-,9,7,...,4,1,2,5,1,1,3,1,4,2
KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Offentlig administration undervisning og sundhed,95,50,100,60,76,49,157,53,133,82,...,73,27,24,84,92,103,70,66,67,144
KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Uoplyst aktivitet,-,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [3]:
cb.inspect_socioeconomy_duplicates(2001, 20) # don't use any - no data at all
cb.inspect_socioeconomy_duplicates(2005, 20) # don't use any - no data at all
cb.inspect_socioeconomy_duplicates(2009, 20) # use cols with no number (numbered cols don't have data)
cb.inspect_socioeconomy_duplicates(2013, 20) # use cols with no number (numbered cols don't have data)
cb.inspect_socioeconomy_duplicates(2017, 20) # use cols with no number (numbered cols don't have data)
cb.inspect_socioeconomy_duplicates(2021, 20) # use either one - both have data - data is different, but with high correlation for most columns

================================================================================
SOCIOECONOMY DUPLICATE INSPECTION - Year 2001
================================================================================


01. Selvstændig og medhj.:
  Found 23 columns
  Industries with duplicates: 11
  Industries with single column: 1

  Analyzing 11 duplicate pairs:

  Industry: Landbrug skovbrug og fiskeri
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Industri råstofindvinding og forsyningsvirksomhed
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Bygge og anlæg
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Handel og transport mv.
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Information og kommunikation
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Finansiering og forsikring
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Ejendomshandel og udlejning
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Erhvervsservice
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Offentlig administration undervisning og sundhed
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Kultur fritid og anden service
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Ikke beskæftiget
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00


02. Topledere:
  Found 23 columns
  Industries with duplicates: 11
  Industries with single column: 1

  Analyzing 11 duplicate pairs:

  Industry: Landbrug skovbrug og fiskeri
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Industri råstofindvinding og forsyningsvirksomhed
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Bygge og anlæg
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Handel og transport mv.
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Information og kommunikation
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Finansiering og forsikring
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Ejendomshandel og udlejning
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Erhvervsservice
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Offentlig administration undervisning og sundhed
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Kultur fritid og anden service
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Ikke beskæftiget
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00


07. Arbejdsløse:
  Found 13 columns
  Industries with duplicates: 1
  Industries with single column: 11

  Analyzing 1 duplicate pairs:

  Industry: Uoplyst aktivitet
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00


================================================================================
SOCIOECONOMY DUPLICATE INSPECTION - Year 2005
================================================================================


01. Selvstændig og medhj.:
  Found 23 columns
  Industries with duplicates: 11
  Industries with single column: 1

  Analyzing 11 duplicate pairs:

  Industry: Landbrug skovbrug og fiskeri
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Industri råstofindvinding og forsyningsvirksomhed
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Bygge og anlæg
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Handel og transport mv.
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Information og kommunikation
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Finansiering og forsikring
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Ejendomshandel og udlejning
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Erhvervsservice
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Offentlig administration undervisning og sundhed
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Kultur fritid og anden service
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Ikke beskæftiget
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00


02. Topledere:
  Found 23 columns
  Industries with duplicates: 11
  Industries with single column: 1

  Analyzing 11 duplicate pairs:

  Industry: Landbrug skovbrug og fiskeri
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Industri råstofindvinding og forsyningsvirksomhed
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Bygge og anlæg
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Handel og transport mv.
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Information og kommunikation
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Finansiering og forsikring
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Ejendomshandel og udlejning
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Erhvervsservice
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Offentlig administration undervisning og sundhed
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Kultur fritid og anden service
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00

  Industry: Ikke beskæftiget
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00


07. Arbejdsløse:
  Found 13 columns
  Industries with duplicates: 1
  Industries with single column: 11

  Analyzing 1 duplicate pairs:

  Industry: Uoplyst aktivitet
    Version 1 (numbered):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 58/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True

{'01. Selvstændig og medhj.': ['KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._01. Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._02. Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._03. Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._04. Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._05. Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._06. Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._07. Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._08. Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._09. Offentlig administration undervisning og sundhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._10. Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._11. Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Offentlig administration undervisning og sundhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Uoplyst aktivitet'],
 '02. Topledere': ['KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_01. Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_02. Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_03. Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_04. Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_05. Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_06. Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_07. Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_08. Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_09. Offentlig administration undervisning og sundhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_10. Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_11. Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Offentlig administration undervisning og sundhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Uoplyst aktivitet'],
 '07. Arbejdsløse': ['KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_12. Uoplyst aktivitet',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Offentlig administration undervisning og sundhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Uoplyst aktivitet']}

In [4]:
socio_2001 = cb.preprocess_socioeconomy(2001)
socio_2005 = cb.preprocess_socioeconomy(2005)
socio_2009 = cb.preprocess_socioeconomy(2009)
socio_2013 = cb.preprocess_socioeconomy(2013)
socio_2017 = cb.preprocess_socioeconomy(2017)
socio_2021 = cb.preprocess_socioeconomy(2021)

2001
    01. Selvstændig og medhj.: Using 12 unnumbered columns
    02. Topledere: Using 12 unnumbered columns
    07. Arbejdsløse: Using 12 unnumbered columns
2005
    01. Selvstændig og medhj.: Using 12 unnumbered columns
    02. Topledere: Using 12 unnumbered columns
    07. Arbejdsløse: Using 12 unnumbered columns
2009
    01. Selvstændig og medhj.: Using 12 unnumbered columns
    02. Topledere: Using 12 unnumbered columns
    07. Arbejdsløse: Using 12 unnumbered columns
2013
    01. Selvstændig og medhj.: Using 12 unnumbered columns
    02. Topledere: Using 12 unnumbered columns
    07. Arbejdsløse: Using 12 unnumbered columns
2017
    01. Selvstændig og medhj.: Using 12 unnumbered columns
    02. Topledere: Using 12 unnumbered columns
    07. Arbejdsløse: Using 12 unnumbered columns
2021
    01. Selvstændig og medhj.: Using 12 unnumbered columns
    02. Topledere: Using 12 unnumbered columns
    07. Arbejdsløse: Using 12 unnumbered columns

In [5]:
print(f"{'='*80}\n  2001\n")
print(socio_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(socio_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(socio_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(socio_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(socio_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(socio_2021.info())

================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gruppe                      58 non-null     object
 1   ValgstedId                  58 non-null     object
 2   KredsNr                     58 non-null     object
 3   StorKredsNr                 58 non-null     object
 4   LandsdelsNr                 58 non-null     object
 5   Socioeconomy_Selvstaendige  0 non-null      float64
 6   Socioeconomy_Topledere      0 non-null      float64
 7   Socioeconomy_Arbejdsloese   0 non-null      float64
 8   Socioeconomy_Total          58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gruppe                      58 non-null     object
 1   ValgstedId                  58 non-null     object
 2   KredsNr                     58 non-null     object
 3   StorKredsNr                 58 non-null     object
 4   LandsdelsNr                 58 non-null     object
 5   Socioeconomy_Selvstaendige  0 non-null      float64
 6   Socioeconomy_Topledere      0 non-null      float64
 7   Socioeconomy_Arbejdsloese   0 non-null      float64
 8   Socioeconomy_Total          58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gruppe                      58 non-null     object
 1   ValgstedId                  58 non-null     object
 2   KredsNr                     58 non-null     object
 3   StorKredsNr                 58 non-null     object
 4   LandsdelsNr                 58 non-null     object
 5   Socioeconomy_Selvstaendige  58 non-null     float64
 6   Socioeconomy_Topledere      58 non-null     float64
 7   Socioeconomy_Arbejdsloese   58 non-null     float64
 8   Socioeconomy_Total          58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gruppe                      58 non-null     object
 1   ValgstedId                  58 non-null     object
 2   KredsNr                     58 non-null     object
 3   StorKredsNr                 58 non-null     object
 4   LandsdelsNr                 58 non-null     object
 5   Socioeconomy_Selvstaendige  58 non-null     float64
 6   Socioeconomy_Topledere      58 non-null     float64
 7   Socioeconomy_Arbejdsloese   58 non-null     float64
 8   Socioeconomy_Total          58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gruppe                      58 non-null     object
 1   ValgstedId                  58 non-null     object
 2   KredsNr                     58 non-null     object
 3   StorKredsNr                 58 non-null     object
 4   LandsdelsNr                 58 non-null     object
 5   Socioeconomy_Selvstaendige  58 non-null     float64
 6   Socioeconomy_Topledere      58 non-null     float64
 7   Socioeconomy_Arbejdsloese   58 non-null     float64
 8   Socioeconomy_Total          58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gruppe                      58 non-null     object
 1   ValgstedId                  58 non-null     object
 2   KredsNr                     58 non-null     object
 3   StorKredsNr                 58 non-null     object
 4   LandsdelsNr                 58 non-null     object
 5   Socioeconomy_Selvstaendige  58 non-null     float64
 6   Socioeconomy_Topledere      58 non-null     float64
 7   Socioeconomy_Arbejdsloese   58 non-null     float64
 8   Socioeconomy_Total          58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

In [6]:
socio_2021.head()

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Socioeconomy_Selvstaendige,Socioeconomy_Topledere,Socioeconomy_Arbejdsloese,Socioeconomy_Total
0,101001,101001,1,1,1,563.0,383.0,305.0,1251.0
1,101002,101002,1,1,1,357.0,221.0,137.0,715.0
2,101003,101003,1,1,1,632.0,401.0,277.0,1310.0
3,101005,101005,1,1,1,396.0,230.0,312.0,938.0
4,101006,101006,1,1,1,410.0,246.0,302.0,958.0

The total calculated before is wrong - need to total across all columns in the csv, incl the ones we're not using. Using a different function:

In [7]:
socio_2001 = cb.preprocess_socioeconomy2(2001)
socio_2005 = cb.preprocess_socioeconomy2(2005)
socio_2009 = cb.preprocess_socioeconomy2(2009)
socio_2013 = cb.preprocess_socioeconomy2(2013)
socio_2017 = cb.preprocess_socioeconomy2(2017)
socio_2021 = cb.preprocess_socioeconomy2(2021)

print(f"{'='*80}\n  2001\n")
print(socio_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(socio_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(socio_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(socio_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(socio_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(socio_2021.info())

2001
2005
2009
2013
2017
2021
================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Socioeconomy_Self-employed   58 non-null     float64
 6   Socioeconomy_Top executives  58 non-null     float64
 7   Socioeconomy_Unemployed      58 non-null     float64
 8   Socioeconomy_Total           58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Socioeconomy_Self-employed   58 non-null     float64
 6   Socioeconomy_Top executives  58 non-null     float64
 7   Socioeconomy_Unemployed      58 non-null     float64
 8   Socioeconomy_Total           58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Socioeconomy_Self-employed   58 non-null     float64
 6   Socioeconomy_Top executives  58 non-null     float64
 7   Socioeconomy_Unemployed      58 non-null     float64
 8   Socioeconomy_Total           58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Socioeconomy_Self-employed   58 non-null     float64
 6   Socioeconomy_Top executives  58 non-null     float64
 7   Socioeconomy_Unemployed      58 non-null     float64
 8   Socioeconomy_Total           58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Socioeconomy_Self-employed   58 non-null     float64
 6   Socioeconomy_Top executives  58 non-null     float64
 7   Socioeconomy_Unemployed      58 non-null     float64
 8   Socioeconomy_Total           58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Socioeconomy_Self-employed   58 non-null     float64
 6   Socioeconomy_Top executives  58 non-null     float64
 7   Socioeconomy_Unemployed      58 non-null     float64
 8   Socioeconomy_Total           58 non-null     float64
dtypes: float64(4), object(5)
memory usage: 4.5+ KB
None

In [8]:
socio_2021.head()

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Socioeconomy_Self-employed,Socioeconomy_Top executives,Socioeconomy_Unemployed,Socioeconomy_Total
0,101001,101001,1,1,1,563.0,383.0,305.0,15540.0
1,101002,101002,1,1,1,357.0,221.0,137.0,8366.0
2,101003,101003,1,1,1,632.0,401.0,277.0,15838.0
3,101005,101005,1,1,1,396.0,230.0,312.0,15817.0
4,101006,101006,1,1,1,410.0,246.0,302.0,13473.0

### Conclusion

There are no data for 2001 and 2005, but there are data for the other years. HOWEVER, I think we might be able to get the 2001-2005 data from 'PersonsByOccupationalStatusIndustry.csv' - the column names are basically identical to to the column names from the socioeconomy csv, but it might not be comparable to the other years since it's not in the same csv. Because of that, I don't think we should include it - but if we have time, we can.

We went with the unnumbered columns (of the duplicate ones), because they were the only ones containing data for 2009, 2013 and 2017. Both the numbered and unnumbered columns had data for 2021, but we went with the unnumbered ones to match the previous years.

Use socio_2009, socio_2013, socio_2017 and socio_2021 to outerjoin with the final year-dataframes.

Note: Is total calculated correctly? Or should it be summed across all columns, incl. the ones we are not using? Edit: Now it is!

## PersonsByCitizenshipSexAge

In [9]:
cb.inspect_citizenship_duplicates(2001, 20)
cb.inspect_citizenship_duplicates(2005, 20)
cb.inspect_citizenship_duplicates(2009, 20)
cb.inspect_citizenship_duplicates(2013, 20)
cb.inspect_citizenship_duplicates(2017, 20)
cb.inspect_citizenship_duplicates(2021, 20)

================================================================================
CITIZENSHIP DUPLICATE INSPECTION - Year 2001
================================================================================


01. []:
  Found 64 columns
  Citizenship variants with duplicates: 1
  Citizenship variants with single column: 0

  Analyzing 1 duplicate pairs:

  Citizenship: 01.Danmark
    Version 1 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 14818.98, Mean: 255.50
      Sample values: [364.91, 188.0, 449.14]
    Version 3 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 4 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 7784.01, Mean: 134.21
      Sample values: [171.23, 85.0, 145.54]
    Version 5 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 6 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 4022.02, Mean: 69.35
      Sample values: [68.77, 55.0, 85.77]
    Version 7 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 8 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 3949.00, Mean: 68.09
      Sample values: [73.68, 42.0, 86.14]
    Version 9 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 10 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 29176.99, Mean: 503.05
      Sample values: [661.06, 322.0, 732.14]
    Version 11 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 12 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 36579.99, Mean: 630.69
      Sample values: [1071.58, 385.0, 1234.07]
    Version 13 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 14 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 25780.99, Mean: 444.50
      Sample values: [762.11, 315.0, 887.75]
    Version 15 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 16 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 17808.00, Mean: 307.03
      Sample values: [458.95, 206.0, 512.35]
    Version 17 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 18 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 13997.99, Mean: 241.34
      Sample values: [310.18, 178.0, 364.7]
    Version 19 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 20 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 14048.01, Mean: 242.21
      Sample values: [315.09, 192.0, 376.64]
    Version 21 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 22 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 15395.04, Mean: 265.43
      Sample values: [314.39, 233.0, 411.39]
    Version 23 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 24 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 13073.99, Mean: 225.41
      Sample values: [279.3, 203.0, 327.98]
    Version 25 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 26 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 10436.02, Mean: 179.93
      Sample values: [192.28, 124.0, 273.29]
    Version 27 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 28 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 9933.98, Mean: 171.28
      Sample values: [162.81, 163.0, 206.79]
    Version 29 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 30 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 9397.02, Mean: 162.02
      Sample values: [136.84, 148.0, 208.1]
    Version 31 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 32 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 44662.00, Mean: 770.03
      Sample values: [570.53, 900.0, 824.64]
    Version 33 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 34 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 15417.99, Mean: 265.83
      Sample values: [355.79, 191.0, 449.73]
    Version 35 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 36 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 8182.02, Mean: 141.07
      Sample values: [148.07, 85.0, 180.24]
    Version 37 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 38 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 4284.00, Mean: 73.86
      Sample values: [88.42, 55.0, 69.3]
    Version 39 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 40 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 3575.00, Mean: 61.64
      Sample values: [66.67, 45.0, 67.76]
    Version 41 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 42 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 24275.02, Mean: 418.53
      Sample values: [508.07, 242.0, 565.03]
    Version 43 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 44 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 37006.01, Mean: 638.03
      Sample values: [964.22, 373.0, 1052.15]
    Version 45 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 46 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 29157.99, Mean: 502.72
      Sample values: [793.69, 316.0, 878.15]
    Version 47 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 48 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 21102.01, Mean: 363.83
      Sample values: [537.55, 230.0, 600.38]
    Version 49 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 50 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 16067.00, Mean: 277.02
      Sample values: [312.28, 198.0, 391.97]
    Version 51 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 52 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 14637.00, Mean: 252.36
      Sample values: [248.42, 180.0, 354.53]
    Version 53 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 54 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 15804.99, Mean: 272.50
      Sample values: [295.44, 175.0, 386.61]
    Version 55 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 56 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 12868.02, Mean: 221.86
      Sample values: [250.53, 162.0, 287.47]
    Version 57 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 58 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 10795.99, Mean: 186.14
      Sample values: [228.77, 129.0, 266.09]
    Version 59 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 60 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 9090.01, Mean: 156.72
      Sample values: [163.51, 148.0, 205.31]
    Version 61 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 62 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 7305.98, Mean: 125.97
      Sample values: [113.68, 107.0, 134.06]
    Version 63 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 64 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 20414.01, Mean: 351.97
      Sample values: [277.9, 353.0, 346.32]


02. []:
  Found 64 columns
  Citizenship variants with duplicates: 1
  Citizenship variants with single column: 0

  Analyzing 1 duplicate pairs:

  Citizenship: 02.Nordiske lande
    Version 1 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no space):
      Non-null: 58/58, Non-zero: 54, Sum: 173.02, Mean: 2.98
      Sample values: [3.51, 1.0, 6.89]
    Version 3 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 4 (no space):
      Non-null: 58/58, Non-zero: 44, Sum: 86.98, Mean: 1.50
      Sample values: [1.4, 3.0, 2.09]
    Version 5 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 6 (no space):
      Non-null: 58/58, Non-zero: 39, Sum: 48.02, Mean: 0.83
      Sample values: [0.0, 0.0, 0.68]
    Version 7 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 8 (no space):
      Non-null: 58/58, Non-zero: 45, Sum: 69.03, Mean: 1.19
      Sample values: [0.7, 0.0, 1.39]
    Version 9 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 10 (no space):
      Non-null: 58/58, Non-zero: 57, Sum: 737.99, Mean: 12.72
      Sample values: [21.05, 7.0, 23.05]
    Version 11 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 12 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 882.00, Mean: 15.21
      Sample values: [25.97, 6.0, 41.16]
    Version 13 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 14 (no space):
      Non-null: 58/58, Non-zero: 57, Sum: 532.01, Mean: 9.17
      Sample values: [14.04, 5.0, 31.02]
    Version 15 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 16 (no space):
      Non-null: 58/58, Non-zero: 56, Sum: 340.98, Mean: 5.88
      Sample values: [7.72, 7.0, 19.17]
    Version 17 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 18 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 269.00, Mean: 4.64
      Sample values: [5.61, 1.0, 9.69]
    Version 19 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 20 (no space):
      Non-null: 58/58, Non-zero: 57, Sum: 278.01, Mean: 4.79
      Sample values: [3.51, 6.0, 7.57]
    Version 21 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 22 (no space):
      Non-null: 58/58, Non-zero: 57, Sum: 277.03, Mean: 4.78
      Sample values: [3.51, 3.0, 7.21]
    Version 23 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 24 (no space):
      Non-null: 58/58, Non-zero: 55, Sum: 226.03, Mean: 3.90
      Sample values: [3.51, 6.0, 7.94]
    Version 25 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 26 (no space):
      Non-null: 58/58, Non-zero: 49, Sum: 118.02, Mean: 2.03
      Sample values: [2.11, 3.0, 4.8]
    Version 27 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 28 (no space):
      Non-null: 58/58, Non-zero: 54, Sum: 121.03, Mean: 2.09
      Sample values: [2.81, 3.0, 5.5]
    Version 29 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 30 (no space):
      Non-null: 58/58, Non-zero: 46, Sum: 79.01, Mean: 1.36
      Sample values: [0.7, 4.0, 1.71]
    Version 31 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 32 (no space):
      Non-null: 58/58, Non-zero: 55, Sum: 224.02, Mean: 3.86
      Sample values: [2.11, 15.0, 8.57]
    Version 33 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 34 (no space):
      Non-null: 58/58, Non-zero: 55, Sum: 223.01, Mean: 3.84
      Sample values: [2.81, 2.0, 13.04]
    Version 35 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 36 (no space):
      Non-null: 58/58, Non-zero: 46, Sum: 114.98, Mean: 1.98
      Sample values: [5.61, 0.0, 3.92]
    Version 37 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 38 (no space):
      Non-null: 58/58, Non-zero: 37, Sum: 42.02, Mean: 0.72
      Sample values: [0.7, 0.0, 1.02]
    Version 39 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 40 (no space):
      Non-null: 58/58, Non-zero: 36, Sum: 36.02, Mean: 0.62
      Sample values: [1.4, 1.0, 0.73]
    Version 41 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 42 (no space):
      Non-null: 58/58, Non-zero: 56, Sum: 392.98, Mean: 6.78
      Sample values: [7.72, 5.0, 9.45]
    Version 43 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 44 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 624.04, Mean: 10.76
      Sample values: [21.75, 5.0, 23.8]
    Version 45 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 46 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 503.02, Mean: 8.67
      Sample values: [11.23, 2.0, 18.66]
    Version 47 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 48 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 346.00, Mean: 5.97
      Sample values: [6.32, 3.0, 18.16]
    Version 49 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 50 (no space):
      Non-null: 58/58, Non-zero: 57, Sum: 305.04, Mean: 5.26
      Sample values: [8.42, 3.0, 8.43]
    Version 51 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 52 (no space):
      Non-null: 58/58, Non-zero: 56, Sum: 264.02, Mean: 4.55
      Sample values: [4.91, 3.0, 2.9]
    Version 53 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 54 (no space):
      Non-null: 58/58, Non-zero: 56, Sum: 242.99, Mean: 4.19
      Sample values: [2.11, 5.0, 5.84]
    Version 55 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 56 (no space):
      Non-null: 58/58, Non-zero: 53, Sum: 189.01, Mean: 3.26
      Sample values: [2.81, 3.0, 2.14]
    Version 57 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 58 (no space):
      Non-null: 58/58, Non-zero: 51, Sum: 123.99, Mean: 2.14
      Sample values: [2.81, 2.0, 6.82]
    Version 59 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 60 (no space):
      Non-null: 58/58, Non-zero: 44, Sum: 105.01, Mean: 1.81
      Sample values: [1.4, 1.0, 5.14]
    Version 61 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 62 (no space):
      Non-null: 58/58, Non-zero: 43, Sum: 78.02, Mean: 1.35
      Sample values: [2.81, 1.0, 3.78]
    Version 63 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 64 (no space):
      Non-null: 58/58, Non-zero: 50, Sum: 115.02, Mean: 1.98
      Sample values: [2.11, 5.0, 1.44]


03. []:
  Found 64 columns
  Citizenship variants with duplicates: 1
  Citizenship variants with single column: 0

  Analyzing 1 duplicate pairs:

  Citizenship: 03.Tyrkiet
    Version 1 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no space):
      Non-null: 58/58, Non-zero: 53, Sum: 353.98, Mean: 6.10
      Sample values: [0.7, 4.0, 0.02]
    Version 3 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 4 (no space):
      Non-null: 58/58, Non-zero: 49, Sum: 287.97, Mean: 4.97
      Sample values: [0.7, 0.0, 0.02]
    Version 5 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 6 (no space):
      Non-null: 58/58, Non-zero: 44, Sum: 135.00, Mean: 2.33
      Sample values: [1.4, 0.0, 0.05]
    Version 7 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 8 (no space):
      Non-null: 58/58, Non-zero: 45, Sum: 109.00, Mean: 1.88
      Sample values: [1.4, 0.0, 0.05]
    Version 9 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 10 (no space):
      Non-null: 58/58, Non-zero: 58, Sum: 306.00, Mean: 5.28
      Sample values: [2.11, 4.0, 0.76]
    Version 11 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 12 (no space):
      Non-null: 58/58, Non-zero: 54, Sum: 379.00, Mean: 6.53
      Sample values: [0.7, 3.0, 2.07]
    Version 13 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 14 (no space):
      Non-null: 58/58, Non-zero: 48, Sum: 331.00, Mean: 5.71
      Sample values: [0.0, 0.0, 0.0]
    Version 15 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 16 (no space):
      Non-null: 58/58, Non-zero: 50, Sum: 256.00, Mean: 4.41
      Sample values: [0.7, 0.0, 0.71]
    Version 17 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 18 (no space):
      Non-null: 58/58, Non-zero: 51, Sum: 162.98, Mean: 2.81
      Sample values: [0.7, 0.0, 0.71]
    Version 19 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 20 (no space):
      Non-null: 58/58, Non-zero: 44, Sum: 133.01, Mean: 2.29
      Sample values: [1.4, 1.0, 0.05]
    Version 21 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 22 (no space):
      Non-null: 58/58, Non-zero: 52, Sum: 117.99, Mean: 2.03
      Sample values: [0.7, 1.0, 0.02]
    Version 23 (with space):
      Non-null: 0/58, Non-zero: 58, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 24 (no space):
      Non-null: 58/58, Non-zero: 38, Sum: 87.00, Mean: 1.50
      Sample values: [0.7, 0.0, 0.02]

{'01.': [],
 '02.': [],
 '03.': [],
 '04.': [],
 '05.': [],
 '06.': [],
 '07.': [],
 '08.': [],
 '09.': [],
 '10.': [],
 '11.': [],
 '12.': []}

In [10]:
cb.inspect_citizenship_duplicates_simple(2001, 20)
# Conclusion: Use columns WITHOUT space for 2001

================================================================================
CITIZENSHIP DUPLICATE INSPECTION - Year 2001
================================================================================

Total columns found: 768
  With space (e.g. '01. Danmark'): 384
  Without space (e.g. '01.Danmark'): 384

SUMMARY:
  Columns WITH space:
    Columns with data: 0/384
    Total sum across all: 0.00
  Columns WITHOUT space:
    Columns with data: 384/384
    Total sum across all: 586026.28

CONCLUSION:
  USE columns WITHOUT space (no space after dot)
  IGNORE columns WITH space (they are empty)

In [11]:
cb.inspect_citizenship_duplicates_simple(2005, 20)
# Conclusion: Use columns WITHOUT space for 2005

================================================================================
CITIZENSHIP DUPLICATE INSPECTION - Year 2005
================================================================================

Total columns found: 768
  With space (e.g. '01. Danmark'): 384
  Without space (e.g. '01.Danmark'): 384

SUMMARY:
  Columns WITH space:
    Columns with data: 0/384
    Total sum across all: 0.00
  Columns WITHOUT space:
    Columns with data: 384/384
    Total sum across all: 576873.78

CONCLUSION:
  USE columns WITHOUT space (no space after dot)
  IGNORE columns WITH space (they are empty)

In [12]:
cb.inspect_citizenship_duplicates_simple(2009, 20)
# Conclusion: Use columns WITH space for 2009

================================================================================
CITIZENSHIP DUPLICATE INSPECTION - Year 2009
================================================================================

Total columns found: 768
  With space (e.g. '01. Danmark'): 384
  Without space (e.g. '01.Danmark'): 384

SUMMARY:
  Columns WITH space:
    Columns with data: 384/384
    Total sum across all: 624926.23
  Columns WITHOUT space:
    Columns with data: 0/384
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

In [13]:
cb.inspect_citizenship_duplicates_simple(2013, 20)
# Conclusion: Use columns WITH space for 2013

================================================================================
CITIZENSHIP DUPLICATE INSPECTION - Year 2013
================================================================================

Total columns found: 768
  With space (e.g. '01. Danmark'): 384
  Without space (e.g. '01.Danmark'): 384

SUMMARY:
  Columns WITH space:
    Columns with data: 384/384
    Total sum across all: 683375.58
  Columns WITHOUT space:
    Columns with data: 0/384
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

In [14]:
cb.inspect_citizenship_duplicates_simple(2017, 20)
# Conclusion: Use columns WITH space for 2017

================================================================================
CITIZENSHIP DUPLICATE INSPECTION - Year 2017
================================================================================

Total columns found: 768
  With space (e.g. '01. Danmark'): 384
  Without space (e.g. '01.Danmark'): 384

SUMMARY:
  Columns WITH space:
    Columns with data: 384/384
    Total sum across all: 683376.18
  Columns WITHOUT space:
    Columns with data: 0/384
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

In [15]:
cb.inspect_citizenship_duplicates_simple(2021, 20)
# Conclusion: Use columns WITH space for 2021

================================================================================
CITIZENSHIP DUPLICATE INSPECTION - Year 2021
================================================================================

Total columns found: 768
  With space (e.g. '01. Danmark'): 384
  Without space (e.g. '01.Danmark'): 384

SUMMARY:
  Columns WITH space:
    Columns with data: 384/384
    Total sum across all: 736645.00
  Columns WITHOUT space:
    Columns with data: 0/384
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

In [16]:
citizenship_2001 = cb.preprocess_citizenship_sex_age(2001)
citizenship_2005 = cb.preprocess_citizenship_sex_age(2005)
citizenship_2009 = cb.preprocess_citizenship_sex_age(2009)
citizenship_2013 = cb.preprocess_citizenship_sex_age(2013)
citizenship_2017 = cb.preprocess_citizenship_sex_age(2017)
citizenship_2021 = cb.preprocess_citizenship_sex_age(2021)

    Citizenship data: Using no-space format for year 2001
    Citizenship data: Using no-space format for year 2005
    Citizenship data: Using with-space format for year 2009
    Citizenship data: Using with-space format for year 2013
    Citizenship data: Using with-space format for year 2017
    Citizenship data: Using with-space format for year 2021

In [17]:
print(f"{'='*80}\n  2001\n")
print(citizenship_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(citizenship_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(citizenship_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(citizenship_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(citizenship_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(citizenship_2021.info())

================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 36 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gruppe                                 58 non-null     object
 1   ValgstedId                             58 non-null     object
 2   KredsNr                                58 non-null     object
 3   StorKredsNr                            58 non-null     object
 4   LandsdelsNr                            58 non-null     object
 5   Sex_Male                               58 non-null     float64
 6   Sex_Female                             58 non-null     float64
 7   Age_0-4 years                          58 non-null     float64
 8   Age_5-9 years                          58 non-null     float64
 9   Age_10-14 years                        58 non-null     float64
 10  Age_15-17 years                        58 non-null     float64
 11  Age_18-19 years                        58 non-null     float64
 12  Age_20-24 years                        58 non-null     float64
 13  Age_25-29 years                        58 non-null     float64
 14  Age_30-34 years                        58 non-null     float64
 15  Age_35-39 years                        58 non-null     float64
 16  Age_40-44 years                        58 non-null     float64
 17  Age_45-49 years                        58 non-null     float64
 18  Age_50-54 years                        58 non-null     float64
 19  Age_55-59 years                        58 non-null     float64
 20  Age_60-64 years                        58 non-null     float64
 21  Age_65-69 years                        58 non-null     float64
 22  Age_70- years                          58 non-null     float64
 23  Citizenship_Denmark                    58 non-null     float64
 24  Citizenship_Nordic                     58 non-null     float64
 25  Citizenship_Turkey                     58 non-null     float64
 26  Citizenship_Former Yugoslavia          58 non-null     float64
 27  Citizenship_Old EU countries           58 non-null     float64
 28  Citizenship_New EU countries           58 non-null     float64
 29  Citizenship_Other Europe               58 non-null     float64
 30  Citizenship_Africa                     58 non-null     float64
 31  Citizenship_North America              58 non-null     float64
 32  Citizenship_South and Central America  58 non-null     float64
 33  Citizenship_Asia and Oceania           58 non-null     float64
 34  Citizenship_Not specified              58 non-null     float64
 35  Citizenship_Total                      58 non-null     float64
dtypes: float64(31), object(5)
memory usage: 16.8+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 36 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gruppe                                 58 non-null     object
 1   ValgstedId                             58 non-null     object
 2   KredsNr                                58 non-null     object
 3   StorKredsNr                            58 non-null     object
 4   LandsdelsNr                            58 non-null     object
 5   Sex_Male                               58 non-null     float64
 6   Sex_Female                             58 non-null     float64
 7   Age_0-4 years                          58 non-null     float64
 8   Age_5-9 years                          58 non-null     float64
 9   Age_10-14 years                        58 non-null     float64
 10  Age_15-17 years                        58 non-null     float64
 11  Age_18-19 years                        58 non-null     float64
 12  Age_20-24 years                        58 non-null     float64
 13  Age_25-29 years                        58 non-null     float64
 14  Age_30-34 years                        58 non-null     float64
 15  Age_35-39 years                        58 non-null     float64
 16  Age_40-44 years                        58 non-null     float64
 17  Age_45-49 years                        58 non-null     float64
 18  Age_50-54 years                        58 non-null     float64
 19  Age_55-59 years                        58 non-null     float64
 20  Age_60-64 years                        58 non-null     float64
 21  Age_65-69 years                        58 non-null     float64
 22  Age_70- years                          58 non-null     float64
 23  Citizenship_Denmark                    58 non-null     float64
 24  Citizenship_Nordic                     58 non-null     float64
 25  Citizenship_Turkey                     58 non-null     float64
 26  Citizenship_Former Yugoslavia          58 non-null     float64
 27  Citizenship_Old EU countries           58 non-null     float64
 28  Citizenship_New EU countries           58 non-null     float64
 29  Citizenship_Other Europe               58 non-null     float64
 30  Citizenship_Africa                     58 non-null     float64
 31  Citizenship_North America              58 non-null     float64
 32  Citizenship_South and Central America  58 non-null     float64
 33  Citizenship_Asia and Oceania           58 non-null     float64
 34  Citizenship_Not specified              58 non-null     float64
 35  Citizenship_Total                      58 non-null     float64
dtypes: float64(31), object(5)
memory usage: 16.8+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 36 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gruppe                                 58 non-null     object
 1   ValgstedId                             58 non-null     object
 2   KredsNr                                58 non-null     object
 3   StorKredsNr                            58 non-null     object
 4   LandsdelsNr                            58 non-null     object
 5   Sex_Male                               58 non-null     float64
 6   Sex_Female                             58 non-null     float64
 7   Age_0-4 years                          58 non-null     float64
 8   Age_5-9 years                          58 non-null     float64
 9   Age_10-14 years                        58 non-null     float64
 10  Age_15-17 years                        58 non-null     float64
 11  Age_18-19 years                        58 non-null     float64
 12  Age_20-24 years                        58 non-null     float64
 13  Age_25-29 years                        58 non-null     float64
 14  Age_30-34 years                        58 non-null     float64
 15  Age_35-39 years                        58 non-null     float64
 16  Age_40-44 years                        58 non-null     float64
 17  Age_45-49 years                        58 non-null     float64
 18  Age_50-54 years                        58 non-null     float64
 19  Age_55-59 years                        58 non-null     float64
 20  Age_60-64 years                        58 non-null     float64
 21  Age_65-69 years                        58 non-null     float64
 22  Age_70- years                          58 non-null     float64
 23  Citizenship_Denmark                    58 non-null     float64
 24  Citizenship_Nordic                     58 non-null     float64
 25  Citizenship_Turkey                     58 non-null     float64
 26  Citizenship_Former Yugoslavia          58 non-null     float64
 27  Citizenship_Old EU countries           58 non-null     float64
 28  Citizenship_New EU countries           58 non-null     float64
 29  Citizenship_Other Europe               58 non-null     float64
 30  Citizenship_Africa                     58 non-null     float64
 31  Citizenship_North America              58 non-null     float64
 32  Citizenship_South and Central America  58 non-null     float64
 33  Citizenship_Asia and Oceania           58 non-null     float64
 34  Citizenship_Not specified              0 non-null      float64
 35  Citizenship_Total                      58 non-null     float64
dtypes: float64(31), object(5)
memory usage: 16.8+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 36 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gruppe                                 58 non-null     object
 1   ValgstedId                             58 non-null     object
 2   KredsNr                                58 non-null     object
 3   StorKredsNr                            58 non-null     object
 4   LandsdelsNr                            58 non-null     object
 5   Sex_Male                               58 non-null     float64
 6   Sex_Female                             58 non-null     float64
 7   Age_0-4 years                          58 non-null     float64
 8   Age_5-9 years                          58 non-null     float64
 9   Age_10-14 years                        58 non-null     float64
 10  Age_15-17 years                        58 non-null     float64
 11  Age_18-19 years                        58 non-null     float64
 12  Age_20-24 years                        58 non-null     float64
 13  Age_25-29 years                        58 non-null     float64
 14  Age_30-34 years                        58 non-null     float64
 15  Age_35-39 years                        58 non-null     float64
 16  Age_40-44 years                        58 non-null     float64
 17  Age_45-49 years                        58 non-null     float64
 18  Age_50-54 years                        58 non-null     float64
 19  Age_55-59 years                        58 non-null     float64
 20  Age_60-64 years                        58 non-null     float64
 21  Age_65-69 years                        58 non-null     float64
 22  Age_70- years                          58 non-null     float64
 23  Citizenship_Denmark                    58 non-null     float64
 24  Citizenship_Nordic                     58 non-null     float64
 25  Citizenship_Turkey                     58 non-null     float64
 26  Citizenship_Former Yugoslavia          58 non-null     float64
 27  Citizenship_Old EU countries           58 non-null     float64
 28  Citizenship_New EU countries           58 non-null     float64
 29  Citizenship_Other Europe               58 non-null     float64
 30  Citizenship_Africa                     58 non-null     float64
 31  Citizenship_North America              58 non-null     float64
 32  Citizenship_South and Central America  58 non-null     float64
 33  Citizenship_Asia and Oceania           58 non-null     float64
 34  Citizenship_Not specified              58 non-null     float64
 35  Citizenship_Total                      58 non-null     float64
dtypes: float64(31), object(5)
memory usage: 16.8+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 36 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gruppe                                 58 non-null     object
 1   ValgstedId                             58 non-null     object
 2   KredsNr                                58 non-null     object
 3   StorKredsNr                            58 non-null     object
 4   LandsdelsNr                            58 non-null     object
 5   Sex_Male                               58 non-null     float64
 6   Sex_Female                             58 non-null     float64
 7   Age_0-4 years                          58 non-null     float64
 8   Age_5-9 years                          58 non-null     float64
 9   Age_10-14 years                        58 non-null     float64
 10  Age_15-17 years                        58 non-null     float64
 11  Age_18-19 years                        58 non-null     float64
 12  Age_20-24 years                        58 non-null     float64
 13  Age_25-29 years                        58 non-null     float64
 14  Age_30-34 years                        58 non-null     float64
 15  Age_35-39 years                        58 non-null     float64
 16  Age_40-44 years                        58 non-null     float64
 17  Age_45-49 years                        58 non-null     float64
 18  Age_50-54 years                        58 non-null     float64
 19  Age_55-59 years                        58 non-null     float64
 20  Age_60-64 years                        58 non-null     float64
 21  Age_65-69 years                        58 non-null     float64
 22  Age_70- years                          58 non-null     float64
 23  Citizenship_Denmark                    58 non-null     float64
 24  Citizenship_Nordic                     58 non-null     float64
 25  Citizenship_Turkey                     58 non-null     float64
 26  Citizenship_Former Yugoslavia          58 non-null     float64
 27  Citizenship_Old EU countries           58 non-null     float64
 28  Citizenship_New EU countries           58 non-null     float64
 29  Citizenship_Other Europe               58 non-null     float64
 30  Citizenship_Africa                     58 non-null     float64
 31  Citizenship_North America              58 non-null     float64
 32  Citizenship_South and Central America  58 non-null     float64
 33  Citizenship_Asia and Oceania           58 non-null     float64
 34  Citizenship_Not specified              58 non-null     float64
 35  Citizenship_Total                      58 non-null     float64
dtypes: float64(31), object(5)
memory usage: 16.8+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 36 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Gruppe                                 58 non-null     object
 1   ValgstedId                             58 non-null     object
 2   KredsNr                                58 non-null     object
 3   StorKredsNr                            58 non-null     object
 4   LandsdelsNr                            58 non-null     object
 5   Sex_Male                               58 non-null     float64
 6   Sex_Female                             58 non-null     float64
 7   Age_0-4 years                          58 non-null     float64
 8   Age_5-9 years                          58 non-null     float64
 9   Age_10-14 years                        58 non-null     float64
 10  Age_15-17 years                        58 non-null     float64
 11  Age_18-19 years                        58 non-null     float64
 12  Age_20-24 years                        58 non-null     float64
 13  Age_25-29 years                        58 non-null     float64
 14  Age_30-34 years                        58 non-null     float64
 15  Age_35-39 years                        58 non-null     float64
 16  Age_40-44 years                        58 non-null     float64
 17  Age_45-49 years                        58 non-null     float64
 18  Age_50-54 years                        58 non-null     float64
 19  Age_55-59 years                        58 non-null     float64
 20  Age_60-64 years                        58 non-null     float64
 21  Age_65-69 years                        58 non-null     float64
 22  Age_70- years                          58 non-null     float64
 23  Citizenship_Denmark                    58 non-null     float64
 24  Citizenship_Nordic                     58 non-null     float64
 25  Citizenship_Turkey                     58 non-null     float64
 26  Citizenship_Former Yugoslavia          58 non-null     float64
 27  Citizenship_Old EU countries           58 non-null     float64
 28  Citizenship_New EU countries           58 non-null     float64
 29  Citizenship_Other Europe               58 non-null     float64
 30  Citizenship_Africa                     58 non-null     float64
 31  Citizenship_North America              58 non-null     float64
 32  Citizenship_South and Central America  58 non-null     float64
 33  Citizenship_Asia and Oceania           58 non-null     float64
 34  Citizenship_Not specified              58 non-null     float64
 35  Citizenship_Total                      58 non-null     float64
dtypes: float64(31), object(5)
memory usage: 16.8+ KB
None

### Conclusion

For 2001 and 2005: Use columns without space
For all subsequent years: Use columns with space

Since the socioeconomy data also is different for 2001 and 2005 compared to subsequent years, maybe we should drop those two early years? It also makes sense, since there was a big policy in Denmark that changed the numbers and borders of municipalities in 2007 ('Kommunalreformen'). That could explain why data from before that might be difficult to compare with data after that.

My opinion is that we should probably just drop 2001 and 2005 for the whole project and only focus on 2009, 2013, 2017 and 2021 (and 2025, of course).

Another small note:
While writing the function `preprocess_citizenship_sex_age(year)`, I realised that columns without citizenship in the column name, e.g. 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år' or 'KV2001 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Mænd 0-4 år' were empty, so data for total female, total male, and total within age groups is found by summing up data from each citizenship column.

Also, for the year 20009, the column 'Citizenship_Uoplyst' only has NaN values, so this column should be dropped.

## HighestCompletedEducationByAge

In [18]:
cb.inspect_education_duplicates(2001, 20) # Use '70 år -' format
cb.inspect_education_duplicates(2005, 20) # Use '70 år -' format
cb.inspect_education_duplicates(2009, 20) # Use '70 år -' format
cb.inspect_education_duplicates(2013, 20) # Use '70- år' format
cb.inspect_education_duplicates(2017, 20) # Use '70- år' format
cb.inspect_education_duplicates(2021, 20) # Use '70- år' format

================================================================================
EDUCATION DUPLICATE INSPECTION - Year 2001
================================================================================

Age variant '70- år': 8 columns found
  Columns with data: 0/8
  Total sum: 0.00
Age variant '70 år -': 8 columns found
  Columns with data: 8/8
  Total sum: 65076.05

CONCLUSION:
  ✓ Use '70 år -' format (has data)
  ✗ Ignore '70- år' format (empty)

================================================================================
EDUCATION DUPLICATE INSPECTION - Year 2005
================================================================================

Age variant '70- år': 8 columns found
  Columns with data: 0/8
  Total sum: 0.00
Age variant '70 år -': 8 columns found
  Columns with data: 8/8
  Total sum: 51866.98

CONCLUSION:
  ✓ Use '70 år -' format (has data)
  ✗ Ignore '70- år' format (empty)

================================================================================
EDUCATION DUPLICATE INSPECTION - Year 2009
================================================================================

Age variant '70- år': 8 columns found
  Columns with data: 0/8
  Total sum: 0.00
Age variant '70 år -': 8 columns found
  Columns with data: 8/8
  Total sum: 47885.05

CONCLUSION:
  ✓ Use '70 år -' format (has data)
  ✗ Ignore '70- år' format (empty)

================================================================================
EDUCATION DUPLICATE INSPECTION - Year 2013
================================================================================

Age variant '70- år': 8 columns found
  Columns with data: 8/8
  Total sum: 49770.00
Age variant '70 år -': 8 columns found
  Columns with data: 0/8
  Total sum: 0.00

CONCLUSION:
  ✓ Use '70- år' format (has data)
  ✗ Ignore '70 år -' format (empty)

================================================================================
EDUCATION DUPLICATE INSPECTION - Year 2017
================================================================================

Age variant '70- år': 8 columns found
  Columns with data: 8/8
  Total sum: 49770.00
Age variant '70 år -': 8 columns found
  Columns with data: 0/8
  Total sum: 0.00

CONCLUSION:
  ✓ Use '70- år' format (has data)
  ✗ Ignore '70 år -' format (empty)

================================================================================
EDUCATION DUPLICATE INSPECTION - Year 2021
================================================================================

Age variant '70- år': 8 columns found
  Columns with data: 8/8
  Total sum: 58022.00
Age variant '70 år -': 8 columns found
  Columns with data: 0/8
  Total sum: 0.00

CONCLUSION:
  ✓ Use '70- år' format (has data)
  ✗ Ignore '70 år -' format (empty)

In [19]:
education_2001 = cb.preprocess_education(2001)
education_2005 = cb.preprocess_education(2005)
education_2009 = cb.preprocess_education(2009)
education_2013 = cb.preprocess_education(2013)
education_2017 = cb.preprocess_education(2017)
education_2021 = cb.preprocess_education(2021)

    Education data: Using '70 år -' for 70+ age group
    Education data: Using '70 år -' for 70+ age group
    Education data: Using '70 år -' for 70+ age group
    Education data: Using '70- år' for 70+ age group
    Education data: Using '70- år' for 70+ age group
    Education data: Using '70- år' for 70+ age group

In [20]:
print(f"{'='*80}\n  2001\n")
print(education_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(education_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(education_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(education_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(education_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(education_2021.info())

================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 24 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Education_18-29 years_Primary and lower secondary   58 non-null     float64
 6   Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 7   Education_18-29 years_General upper secondary       58 non-null     float64
 8   Education_30-70+ years_General upper secondary      58 non-null     float64
 9   Education_18-29 years_Vocational upper secondary    58 non-null     float64
 10  Education_30-70+ years_Vocational upper secondary   58 non-null     float64
 11  Education_18-29 years_Vocational training           58 non-null     float64
 12  Education_30-70+ years_Vocational training          58 non-null     float64
 13  Education_18-29 years_Short higher education        58 non-null     float64
 14  Education_30-70+ years_Short higher education       58 non-null     float64
 15  Education_18-29 years_Medium higher education       58 non-null     float64
 16  Education_30-70+ years_Medium higher education      58 non-null     float64
 17  Education_18-29 years_Long higher education         58 non-null     float64
 18  Education_30-70+ years_Long higher education        58 non-null     float64
 19  Education_18-29 years_Not specified                 58 non-null     float64
 20  Education_30-70+ years_Not specified                58 non-null     float64
 21  Education_Total 18-29 years                         58 non-null     float64
 22  Education_Total 30-70+ years                        58 non-null     float64
 23  Education_Total                                     58 non-null     float64
dtypes: float64(19), object(5)
memory usage: 11.3+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 24 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Education_18-29 years_Primary and lower secondary   58 non-null     float64
 6   Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 7   Education_18-29 years_General upper secondary       58 non-null     float64
 8   Education_30-70+ years_General upper secondary      58 non-null     float64
 9   Education_18-29 years_Vocational upper secondary    58 non-null     float64
 10  Education_30-70+ years_Vocational upper secondary   58 non-null     float64
 11  Education_18-29 years_Vocational training           58 non-null     float64
 12  Education_30-70+ years_Vocational training          58 non-null     float64
 13  Education_18-29 years_Short higher education        58 non-null     float64
 14  Education_30-70+ years_Short higher education       58 non-null     float64
 15  Education_18-29 years_Medium higher education       58 non-null     float64
 16  Education_30-70+ years_Medium higher education      58 non-null     float64
 17  Education_18-29 years_Long higher education         58 non-null     float64
 18  Education_30-70+ years_Long higher education        58 non-null     float64
 19  Education_18-29 years_Not specified                 58 non-null     float64
 20  Education_30-70+ years_Not specified                58 non-null     float64
 21  Education_Total 18-29 years                         58 non-null     float64
 22  Education_Total 30-70+ years                        58 non-null     float64
 23  Education_Total                                     58 non-null     float64
dtypes: float64(19), object(5)
memory usage: 11.3+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 24 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Education_18-29 years_Primary and lower secondary   58 non-null     float64
 6   Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 7   Education_18-29 years_General upper secondary       58 non-null     float64
 8   Education_30-70+ years_General upper secondary      58 non-null     float64
 9   Education_18-29 years_Vocational upper secondary    58 non-null     float64
 10  Education_30-70+ years_Vocational upper secondary   58 non-null     float64
 11  Education_18-29 years_Vocational training           58 non-null     float64
 12  Education_30-70+ years_Vocational training          58 non-null     float64
 13  Education_18-29 years_Short higher education        58 non-null     float64
 14  Education_30-70+ years_Short higher education       58 non-null     float64
 15  Education_18-29 years_Medium higher education       58 non-null     float64
 16  Education_30-70+ years_Medium higher education      58 non-null     float64
 17  Education_18-29 years_Long higher education         58 non-null     float64
 18  Education_30-70+ years_Long higher education        58 non-null     float64
 19  Education_18-29 years_Not specified                 58 non-null     float64
 20  Education_30-70+ years_Not specified                58 non-null     float64
 21  Education_Total 18-29 years                         58 non-null     float64
 22  Education_Total 30-70+ years                        58 non-null     float64
 23  Education_Total                                     58 non-null     float64
dtypes: float64(19), object(5)
memory usage: 11.3+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 24 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Education_18-29 years_Primary and lower secondary   58 non-null     float64
 6   Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 7   Education_18-29 years_General upper secondary       58 non-null     float64
 8   Education_30-70+ years_General upper secondary      58 non-null     float64
 9   Education_18-29 years_Vocational upper secondary    58 non-null     float64
 10  Education_30-70+ years_Vocational upper secondary   58 non-null     float64
 11  Education_18-29 years_Vocational training           58 non-null     float64
 12  Education_30-70+ years_Vocational training          58 non-null     float64
 13  Education_18-29 years_Short higher education        58 non-null     float64
 14  Education_30-70+ years_Short higher education       58 non-null     float64
 15  Education_18-29 years_Medium higher education       58 non-null     float64
 16  Education_30-70+ years_Medium higher education      58 non-null     float64
 17  Education_18-29 years_Long higher education         58 non-null     float64
 18  Education_30-70+ years_Long higher education        58 non-null     float64
 19  Education_18-29 years_Not specified                 58 non-null     float64
 20  Education_30-70+ years_Not specified                58 non-null     float64
 21  Education_Total 18-29 years                         58 non-null     float64
 22  Education_Total 30-70+ years                        58 non-null     float64
 23  Education_Total                                     58 non-null     float64
dtypes: float64(19), object(5)
memory usage: 11.3+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 24 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Education_18-29 years_Primary and lower secondary   58 non-null     float64
 6   Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 7   Education_18-29 years_General upper secondary       58 non-null     float64
 8   Education_30-70+ years_General upper secondary      58 non-null     float64
 9   Education_18-29 years_Vocational upper secondary    58 non-null     float64
 10  Education_30-70+ years_Vocational upper secondary   58 non-null     float64
 11  Education_18-29 years_Vocational training           58 non-null     float64
 12  Education_30-70+ years_Vocational training          58 non-null     float64
 13  Education_18-29 years_Short higher education        58 non-null     float64
 14  Education_30-70+ years_Short higher education       58 non-null     float64
 15  Education_18-29 years_Medium higher education       58 non-null     float64
 16  Education_30-70+ years_Medium higher education      58 non-null     float64
 17  Education_18-29 years_Long higher education         58 non-null     float64
 18  Education_30-70+ years_Long higher education        58 non-null     float64
 19  Education_18-29 years_Not specified                 58 non-null     float64
 20  Education_30-70+ years_Not specified                58 non-null     float64
 21  Education_Total 18-29 years                         58 non-null     float64
 22  Education_Total 30-70+ years                        58 non-null     float64
 23  Education_Total                                     58 non-null     float64
dtypes: float64(19), object(5)
memory usage: 11.3+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 24 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Education_18-29 years_Primary and lower secondary   58 non-null     float64
 6   Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 7   Education_18-29 years_General upper secondary       58 non-null     float64
 8   Education_30-70+ years_General upper secondary      58 non-null     float64
 9   Education_18-29 years_Vocational upper secondary    58 non-null     float64
 10  Education_30-70+ years_Vocational upper secondary   58 non-null     float64
 11  Education_18-29 years_Vocational training           58 non-null     float64
 12  Education_30-70+ years_Vocational training          58 non-null     float64
 13  Education_18-29 years_Short higher education        58 non-null     float64
 14  Education_30-70+ years_Short higher education       58 non-null     float64
 15  Education_18-29 years_Medium higher education       58 non-null     float64
 16  Education_30-70+ years_Medium higher education      58 non-null     float64
 17  Education_18-29 years_Long higher education         58 non-null     float64
 18  Education_30-70+ years_Long higher education        58 non-null     float64
 19  Education_18-29 years_Not specified                 58 non-null     float64
 20  Education_30-70+ years_Not specified                58 non-null     float64
 21  Education_Total 18-29 years                         58 non-null     float64
 22  Education_Total 30-70+ years                        58 non-null     float64
 23  Education_Total                                     58 non-null     float64
dtypes: float64(19), object(5)
memory usage: 11.3+ KB
None

In [21]:
education_2021.head(10)

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Education_18-29 years_Primary and lower secondary,Education_30-70+ years_Primary and lower secondary,Education_18-29 years_General upper secondary,Education_30-70+ years_General upper secondary,Education_18-29 years_Vocational upper secondary,...,Education_30-70+ years_Short higher education,Education_18-29 years_Medium higher education,Education_30-70+ years_Medium higher education,Education_18-29 years_Long higher education,Education_30-70+ years_Long higher education,Education_18-29 years_Not specified,Education_30-70+ years_Not specified,Education_Total 18-29 years,Education_Total 30-70+ years,Education_Total
0,101001,101001,1,1,1,453.0,885.0,1243.0,569.0,153.0,...,401.0,415.0,1927.0,1433.0,3497.0,21.0,154.0,4060.0,8982.0,13042.0
1,101002,101002,1,1,1,249.0,653.0,519.0,323.0,70.0,...,224.0,195.0,1014.0,577.0,1834.0,17.0,106.0,1837.0,5145.0,6982.0
2,101003,101003,1,1,1,447.0,779.0,1169.0,583.0,126.0,...,387.0,362.0,1964.0,1205.0,3930.0,16.0,139.0,3615.0,9204.0,12819.0
3,101005,101005,1,1,1,438.0,1423.0,1138.0,553.0,167.0,...,403.0,718.0,1709.0,1266.0,2814.0,21.0,220.0,4251.0,9197.0,13448.0
4,101006,101006,1,1,1,479.0,1087.0,980.0,431.0,177.0,...,374.0,407.0,1450.0,1115.0,2466.0,17.0,169.0,3532.0,7720.0,11252.0
5,101007,101007,2,1,1,638.0,2013.0,896.0,476.0,148.0,...,424.0,330.0,1241.0,555.0,1710.0,15.0,239.0,3010.0,8578.0,11588.0
6,101008,101010;101008,2,1,1,991.0,2873.0,2264.0,1117.0,404.0,...,1025.0,915.0,3479.0,2453.0,6417.0,42.0,433.0,8181.0,19681.0,27862.0
7,101009,101057;101009,2,1,1,1166.0,2078.0,2937.0,844.0,592.0,...,874.0,1224.0,2656.0,2232.0,4833.0,62.0,349.0,9320.0,15055.0,24375.0
8,101011,101011,3,1,1,923.0,1575.0,1775.0,889.0,220.0,...,451.0,700.0,1977.0,2012.0,4642.0,73.0,323.0,6424.0,11563.0,17987.0
9,101012,101012,3,1,1,234.0,427.0,605.0,394.0,60.0,...,212.0,185.0,1148.0,553.0,2655.0,13.0,99.0,1776.0,5719.0,7495.0

### Conclusion

Again, there are similarly named columns - but this time only for the last age group 70+, so we just check those. And once again, only one of the two actually contains any data - but it differs from year to year.

For 2001, 2005 and 2009: Use '70 år -' format.

For 2013, 2017 and 2021: Use '70- år' format

We can consider only using the two extremes when we combine the final df - 'Primary and lower secondary' and 'Long higher education' (both of them for both under and over 30)

## ImmigrantsDescendantsByCountryOfOrigin

In [22]:
cb.inspect_immigrants_duplicates(2001, 20) # use columns without space
cb.inspect_immigrants_duplicates(2005, 20) # use columns without space
cb.inspect_immigrants_duplicates(2009, 20) # use columns with space
cb.inspect_immigrants_duplicates(2013, 20) # use columns with space
cb.inspect_immigrants_duplicates(2017, 20) # use columns with space
cb.inspect_immigrants_duplicates(2021, 20) # use columns with space

================================================================================
IMMIGRANTS/DESCENDANTS DUPLICATE INSPECTION - Year 2001
================================================================================

Total columns found: 704
  With space (e.g. '01. Danmark'): 352
  Without space (e.g. '01.Danmark'): 352

SUMMARY:
  Columns WITH space:
    Columns with data: 0/352
    Total sum across all: 0.00
  Columns WITHOUT space:
    Columns with data: 352/352
    Total sum across all: 95053.72

CONCLUSION:
  USE columns WITHOUT space (no space after dot)
  IGNORE columns WITH space (they are empty)

================================================================================
IMMIGRANTS/DESCENDANTS DUPLICATE INSPECTION - Year 2005
================================================================================

Total columns found: 704
  With space (e.g. '01. Danmark'): 352
  Without space (e.g. '01.Danmark'): 352

SUMMARY:
  Columns WITH space:
    Columns with data: 0/352
    Total sum across all: 0.00
  Columns WITHOUT space:
    Columns with data: 352/352
    Total sum across all: 105601.61

CONCLUSION:
  USE columns WITHOUT space (no space after dot)
  IGNORE columns WITH space (they are empty)

================================================================================
IMMIGRANTS/DESCENDANTS DUPLICATE INSPECTION - Year 2009
================================================================================

Total columns found: 704
  With space (e.g. '01. Danmark'): 352
  Without space (e.g. '01.Danmark'): 352

SUMMARY:
  Columns WITH space:
    Columns with data: 352/352
    Total sum across all: 129564.04
  Columns WITHOUT space:
    Columns with data: 0/352
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

================================================================================
IMMIGRANTS/DESCENDANTS DUPLICATE INSPECTION - Year 2013
================================================================================

Total columns found: 704
  With space (e.g. '01. Danmark'): 352
  Without space (e.g. '01.Danmark'): 352

SUMMARY:
  Columns WITH space:
    Columns with data: 352/352
    Total sum across all: 152851.99
  Columns WITHOUT space:
    Columns with data: 0/352
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

================================================================================
IMMIGRANTS/DESCENDANTS DUPLICATE INSPECTION - Year 2017
================================================================================

Total columns found: 704
  With space (e.g. '01. Danmark'): 352
  Without space (e.g. '01.Danmark'): 352

SUMMARY:
  Columns WITH space:
    Columns with data: 352/352
    Total sum across all: 152852.28
  Columns WITHOUT space:
    Columns with data: 0/352
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

================================================================================
IMMIGRANTS/DESCENDANTS DUPLICATE INSPECTION - Year 2021
================================================================================

Total columns found: 704
  With space (e.g. '01. Danmark'): 352
  Without space (e.g. '01.Danmark'): 352

SUMMARY:
  Columns WITH space:
    Columns with data: 350/352
    Total sum across all: 181923.00
  Columns WITHOUT space:
    Columns with data: 0/352
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

In [23]:
immigrants_2001 = cb.preprocess_immigrants(2001)
immigrants_2005 = cb.preprocess_immigrants(2005)
immigrants_2009 = cb.preprocess_immigrants(2009)
immigrants_2013 = cb.preprocess_immigrants(2013)
immigrants_2017 = cb.preprocess_immigrants(2017)
immigrants_2021 = cb.preprocess_immigrants(2021)

    Immigrants/descendants data: Using no-space format for year 2001
    Immigrants/descendants data: Using no-space format for year 2005
    Immigrants/descendants data: Using with-space format for year 2009
    Immigrants/descendants data: Using with-space format for year 2013
    Immigrants/descendants data: Using with-space format for year 2017
    Immigrants/descendants data: Using with-space format for year 2021

In [24]:
print(f"{'='*80}\n  2001\n")
print(immigrants_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(immigrants_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(immigrants_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(immigrants_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(immigrants_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(immigrants_2021.info())

================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Immigrants_Denmark                    0 non-null      float64
 6   Immigrants_Nordic                     58 non-null     float64
 7   Immigrants_Turkey                     58 non-null     float64
 8   Immigrants_Former Yugoslavia          58 non-null     float64
 9   Immigrants_Old EU countries           58 non-null     float64
 10  Immigrants_New EU countries           58 non-null     float64
 11  Immigrants_Other Europe               58 non-null     float64
 12  Immigrants_Africa                     58 non-null     float64
 13  Immigrants_North America              58 non-null     float64
 14  Immigrants_South and Central America  58 non-null     float64
 15  Immigrants_Asia and Oceania           58 non-null     float64
 16  Immigrants_Not specified              58 non-null     float64
 17  Immigrants_Total                      58 non-null     float64
dtypes: float64(13), object(5)
memory usage: 8.6+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Immigrants_Denmark                    0 non-null      float64
 6   Immigrants_Nordic                     58 non-null     float64
 7   Immigrants_Turkey                     58 non-null     float64
 8   Immigrants_Former Yugoslavia          58 non-null     float64
 9   Immigrants_Old EU countries           58 non-null     float64
 10  Immigrants_New EU countries           58 non-null     float64
 11  Immigrants_Other Europe               58 non-null     float64
 12  Immigrants_Africa                     58 non-null     float64
 13  Immigrants_North America              58 non-null     float64
 14  Immigrants_South and Central America  58 non-null     float64
 15  Immigrants_Asia and Oceania           58 non-null     float64
 16  Immigrants_Not specified              58 non-null     float64
 17  Immigrants_Total                      58 non-null     float64
dtypes: float64(13), object(5)
memory usage: 8.6+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Immigrants_Denmark                    0 non-null      float64
 6   Immigrants_Nordic                     58 non-null     float64
 7   Immigrants_Turkey                     58 non-null     float64
 8   Immigrants_Former Yugoslavia          58 non-null     float64
 9   Immigrants_Old EU countries           58 non-null     float64
 10  Immigrants_New EU countries           58 non-null     float64
 11  Immigrants_Other Europe               58 non-null     float64
 12  Immigrants_Africa                     58 non-null     float64
 13  Immigrants_North America              58 non-null     float64
 14  Immigrants_South and Central America  58 non-null     float64
 15  Immigrants_Asia and Oceania           58 non-null     float64
 16  Immigrants_Not specified              58 non-null     float64
 17  Immigrants_Total                      58 non-null     float64
dtypes: float64(13), object(5)
memory usage: 8.6+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Immigrants_Denmark                    0 non-null      float64
 6   Immigrants_Nordic                     58 non-null     float64
 7   Immigrants_Turkey                     58 non-null     float64
 8   Immigrants_Former Yugoslavia          58 non-null     float64
 9   Immigrants_Old EU countries           58 non-null     float64
 10  Immigrants_New EU countries           58 non-null     float64
 11  Immigrants_Other Europe               58 non-null     float64
 12  Immigrants_Africa                     58 non-null     float64
 13  Immigrants_North America              58 non-null     float64
 14  Immigrants_South and Central America  58 non-null     float64
 15  Immigrants_Asia and Oceania           58 non-null     float64
 16  Immigrants_Not specified              58 non-null     float64
 17  Immigrants_Total                      58 non-null     float64
dtypes: float64(13), object(5)
memory usage: 8.6+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Immigrants_Denmark                    0 non-null      float64
 6   Immigrants_Nordic                     58 non-null     float64
 7   Immigrants_Turkey                     58 non-null     float64
 8   Immigrants_Former Yugoslavia          58 non-null     float64
 9   Immigrants_Old EU countries           58 non-null     float64
 10  Immigrants_New EU countries           58 non-null     float64
 11  Immigrants_Other Europe               58 non-null     float64
 12  Immigrants_Africa                     58 non-null     float64
 13  Immigrants_North America              58 non-null     float64
 14  Immigrants_South and Central America  58 non-null     float64
 15  Immigrants_Asia and Oceania           58 non-null     float64
 16  Immigrants_Not specified              58 non-null     float64
 17  Immigrants_Total                      58 non-null     float64
dtypes: float64(13), object(5)
memory usage: 8.6+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 18 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Immigrants_Denmark                    0 non-null      float64
 6   Immigrants_Nordic                     58 non-null     float64
 7   Immigrants_Turkey                     58 non-null     float64
 8   Immigrants_Former Yugoslavia          58 non-null     float64
 9   Immigrants_Old EU countries           58 non-null     float64
 10  Immigrants_New EU countries           58 non-null     float64
 11  Immigrants_Other Europe               58 non-null     float64
 12  Immigrants_Africa                     58 non-null     float64
 13  Immigrants_North America              58 non-null     float64
 14  Immigrants_South and Central America  58 non-null     float64
 15  Immigrants_Asia and Oceania           58 non-null     float64
 16  Immigrants_Not specified              58 non-null     float64
 17  Immigrants_Total                      58 non-null     float64
dtypes: float64(13), object(5)
memory usage: 8.6+ KB
None

In [25]:
immigrants_2021.head(10)

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Immigrants_Denmark,Immigrants_Nordic,Immigrants_Turkey,Immigrants_Former Yugoslavia,Immigrants_Old EU countries,Immigrants_New EU countries,Immigrants_Other Europe,Immigrants_Africa,Immigrants_North America,Immigrants_South and Central America,Immigrants_Asia and Oceania,Immigrants_Not specified,Immigrants_Total
0,101001,101001,1,1,1,NaN,388.0,40.0,80.0,895.0,275.0,88.0,201.0,168.0,161.0,586.0,1.0,2883.0
1,101002,101002,1,1,1,NaN,148.0,57.0,78.0,360.0,153.0,77.0,120.0,58.0,88.0,525.0,0.0,1664.0
2,101003,101003,1,1,1,NaN,359.0,52.0,39.0,729.0,189.0,83.0,128.0,151.0,212.0,560.0,1.0,2503.0
3,101005,101005,1,1,1,NaN,303.0,136.0,306.0,799.0,406.0,166.0,307.0,194.0,214.0,1113.0,3.0,3947.0
4,101006,101006,1,1,1,NaN,236.0,94.0,199.0,579.0,326.0,118.0,301.0,76.0,130.0,984.0,0.0,3043.0
5,101007,101007,2,1,1,NaN,204.0,320.0,170.0,414.0,442.0,51.0,533.0,55.0,125.0,1537.0,11.0,3862.0
6,101008,101008;101010,2,1,1,NaN,746.0,492.0,327.0,1269.0,663.0,224.0,783.0,219.0,322.0,2396.0,8.0,7449.0
7,101009,101009;101057,2,1,1,NaN,785.0,316.0,398.0,1660.0,1796.0,392.0,676.0,225.0,500.0,3454.0,2.0,10204.0
8,101011,101011,3,1,1,NaN,903.0,130.0,148.0,1575.0,502.0,164.0,528.0,327.0,353.0,1216.0,4.0,5850.0
9,101012,101012,3,1,1,NaN,229.0,24.0,31.0,574.0,124.0,57.0,63.0,136.0,77.0,274.0,0.0,1589.0

### Conclusion
Once again, we have different formats for [2001, 2005] and all other years.

And for obvious reasons, the Denmark column is all-null for all years (no immigrants have immigrated to Denmark from Denmark...), so these columns should be dropped.

## HousingTenure

We might only want to get amount of and no. of people living in either'01. Ejerbolig': 'Owner-occupied housing (ejer)', '02. Andelsbolig': 'Cooperative housing (andel)', '03. Almennyttig bolig': 'Social housing (almen)' or '05. Privat lejerbolig': 'Private rental' and ignore the rest

In [26]:
cb.inspect_housingtenure_duplicates(2001, 20) # use columns with space
cb.inspect_housingtenure_duplicates(2005, 20) # use columns with space
cb.inspect_housingtenure_duplicates(2009, 20) # use columns with space
cb.inspect_housingtenure_duplicates(2013, 20) # use columns with underscore
cb.inspect_housingtenure_duplicates(2017, 20) # use columns with underscore
cb.inspect_housingtenure_duplicates(2021, 20) # use columns with underscore

================================================================================
HOUSING TENURE DUPLICATE INSPECTION - Year 2001
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 14/14
    Total sum across all: 910762.02
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 0/12
    Total sum across all: 0.00

CONCLUSION:
  USE columns with SPACES ('Antal boliger', 'Antal personer').
  IGNORE columns with underscores (they appear empty).

================================================================================


================================================================================
HOUSING TENURE DUPLICATE INSPECTION - Year 2005
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 14/14
    Total sum across all: 889999.96
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 0/12
    Total sum across all: 0.00

CONCLUSION:
  USE columns with SPACES ('Antal boliger', 'Antal personer').
  IGNORE columns with underscores (they appear empty).

================================================================================


================================================================================
HOUSING TENURE DUPLICATE INSPECTION - Year 2009
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 12/14
    Total sum across all: 955338.94
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 0/12
    Total sum across all: 0.00

CONCLUSION:
  USE columns with SPACES ('Antal boliger', 'Antal personer').
  IGNORE columns with underscores (they appear empty).

================================================================================


================================================================================
HOUSING TENURE DUPLICATE INSPECTION - Year 2013
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 0/14
    Total sum across all: 0.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 12/12
    Total sum across all: 1025654.97

CONCLUSION:
  USE columns with UNDERSCORES ('Antal_boliger', 'Antal_personer').
  IGNORE columns with spaces (they appear empty).

================================================================================


================================================================================
HOUSING TENURE DUPLICATE INSPECTION - Year 2017
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 0/14
    Total sum across all: 0.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 12/12
    Total sum across all: 1025655.03

CONCLUSION:
  USE columns with UNDERSCORES ('Antal_boliger', 'Antal_personer').
  IGNORE columns with spaces (they appear empty).

================================================================================


================================================================================
HOUSING TENURE DUPLICATE INSPECTION - Year 2021
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 0/14
    Total sum across all: 0.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 12/12
    Total sum across all: 1100299.00

CONCLUSION:
  USE columns with UNDERSCORES ('Antal_boliger', 'Antal_personer').
  IGNORE columns with spaces (they appear empty).

================================================================================

In [27]:
tenure_2001 = cb.preprocess_housingtenure(2001) # use columns with space
tenure_2005 = cb.preprocess_housingtenure(2005) # use columns with space
tenure_2009 = cb.preprocess_housingtenure(2009) # use columns with space
tenure_2013 = cb.preprocess_housingtenure(2013) # use columns with underscore
tenure_2017 = cb.preprocess_housingtenure(2017) # use columns with underscore
tenure_2021 = cb.preprocess_housingtenure(2021) # use columns with underscore

    Housing tenure data: Using spaced format for year 2001
    Housing tenure data: Using spaced format for year 2005
    Housing tenure data: Using spaced format for year 2009
    Housing tenure data: Using underscored format for year 2013
    Housing tenure data: Using underscored format for year 2017
    Housing tenure data: Using underscored format for year 2021

In [28]:
print(f"{'='*80}\n  2001\n")
print(tenure_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(tenure_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(tenure_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(tenure_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(tenure_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(tenure_2021.info())

================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Housing tenure_Homes_Ejer             58 non-null     float64
 6   Housing tenure_Homes_Andel            58 non-null     float64
 7   Housing tenure_Homes_Almen            58 non-null     float64
 8   Housing tenure_Homes_Private rental   58 non-null     float64
 9   Housing tenure_People_Ejer            58 non-null     float64
 10  Housing tenure_People_Andel           58 non-null     float64
 11  Housing tenure_People_Almen           58 non-null     float64
 12  Housing tenure_People_Private rental  58 non-null     float64
 13  Housing tenure_Total people           58 non-null     float64
 14  Housing tenure_Total homes            58 non-null     float64
dtypes: float64(10), object(5)
memory usage: 7.2+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Housing tenure_Homes_Ejer             58 non-null     float64
 6   Housing tenure_Homes_Andel            58 non-null     float64
 7   Housing tenure_Homes_Almen            58 non-null     float64
 8   Housing tenure_Homes_Private rental   58 non-null     float64
 9   Housing tenure_People_Ejer            58 non-null     float64
 10  Housing tenure_People_Andel           58 non-null     float64
 11  Housing tenure_People_Almen           58 non-null     float64
 12  Housing tenure_People_Private rental  58 non-null     float64
 13  Housing tenure_Total people           58 non-null     float64
 14  Housing tenure_Total homes            58 non-null     float64
dtypes: float64(10), object(5)
memory usage: 7.2+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Housing tenure_Homes_Ejer             58 non-null     float64
 6   Housing tenure_Homes_Andel            58 non-null     float64
 7   Housing tenure_Homes_Almen            58 non-null     float64
 8   Housing tenure_Homes_Private rental   58 non-null     float64
 9   Housing tenure_People_Ejer            58 non-null     float64
 10  Housing tenure_People_Andel           58 non-null     float64
 11  Housing tenure_People_Almen           58 non-null     float64
 12  Housing tenure_People_Private rental  58 non-null     float64
 13  Housing tenure_Total people           58 non-null     float64
 14  Housing tenure_Total homes            58 non-null     float64
dtypes: float64(10), object(5)
memory usage: 7.2+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Housing tenure_Homes_Ejer             58 non-null     float64
 6   Housing tenure_Homes_Andel            58 non-null     float64
 7   Housing tenure_Homes_Almen            58 non-null     float64
 8   Housing tenure_Homes_Private rental   58 non-null     float64
 9   Housing tenure_People_Ejer            58 non-null     float64
 10  Housing tenure_People_Andel           58 non-null     float64
 11  Housing tenure_People_Almen           58 non-null     float64
 12  Housing tenure_People_Private rental  58 non-null     float64
 13  Housing tenure_Total people           58 non-null     float64
 14  Housing tenure_Total homes            58 non-null     float64
dtypes: float64(10), object(5)
memory usage: 7.2+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Housing tenure_Homes_Ejer             58 non-null     float64
 6   Housing tenure_Homes_Andel            58 non-null     float64
 7   Housing tenure_Homes_Almen            58 non-null     float64
 8   Housing tenure_Homes_Private rental   58 non-null     float64
 9   Housing tenure_People_Ejer            58 non-null     float64
 10  Housing tenure_People_Andel           58 non-null     float64
 11  Housing tenure_People_Almen           58 non-null     float64
 12  Housing tenure_People_Private rental  58 non-null     float64
 13  Housing tenure_Total people           58 non-null     float64
 14  Housing tenure_Total homes            58 non-null     float64
dtypes: float64(10), object(5)
memory usage: 7.2+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 15 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Gruppe                                58 non-null     object
 1   ValgstedId                            58 non-null     object
 2   KredsNr                               58 non-null     object
 3   StorKredsNr                           58 non-null     object
 4   LandsdelsNr                           58 non-null     object
 5   Housing tenure_Homes_Ejer             58 non-null     float64
 6   Housing tenure_Homes_Andel            58 non-null     float64
 7   Housing tenure_Homes_Almen            58 non-null     float64
 8   Housing tenure_Homes_Private rental   58 non-null     float64
 9   Housing tenure_People_Ejer            58 non-null     float64
 10  Housing tenure_People_Andel           58 non-null     float64
 11  Housing tenure_People_Almen           58 non-null     float64
 12  Housing tenure_People_Private rental  58 non-null     float64
 13  Housing tenure_Total people           58 non-null     float64
 14  Housing tenure_Total homes            58 non-null     float64
dtypes: float64(10), object(5)
memory usage: 7.2+ KB
None

In [29]:
tenure_2021.head(10)

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Housing tenure_Homes_Ejer,Housing tenure_Homes_Andel,Housing tenure_Homes_Almen,Housing tenure_Homes_Private rental,Housing tenure_People_Ejer,Housing tenure_People_Andel,Housing tenure_People_Almen,Housing tenure_People_Private rental,Housing tenure_Total people,Housing tenure_Total homes
0,101001,101001,1,1,1,1248.0,2823.0,1026.0,861.0,2719.0,5490.0,1703.0,1526.0,11438.0,5958.0
1,101002,101002,1,1,1,1097.0,1550.0,562.0,373.0,2503.0,2933.0,918.0,663.0,7017.0,3582.0
2,101003,101003,1,1,1,1181.0,3492.0,254.0,676.0,2834.0,7613.0,424.0,1322.0,12193.0,5603.0
3,101005,101005,1,1,1,1137.0,3335.0,1196.0,576.0,2550.0,6783.0,1945.0,1072.0,12350.0,6244.0
4,101006,101006,1,1,1,1276.0,2378.0,1354.0,591.0,2845.0,4483.0,2578.0,1117.0,11023.0,5599.0
5,101007,101007,2,1,1,1511.0,1769.0,2721.0,402.0,4063.0,3167.0,4830.0,840.0,12900.0,6403.0
6,101008,101010;101008,2,1,1,2780.0,6860.0,2828.0,1484.0,6270.0,13391.0,5514.0,2847.0,28022.0,13952.0
7,101009,101057;101009,2,1,1,4357.0,432.0,2897.0,552.0,11579.0,829.0,6107.0,1298.0,19813.0,8238.0
8,101011,101011,3,1,1,1517.0,2162.0,112.0,1216.0,3073.0,4524.0,185.0,2385.0,10167.0,5007.0
9,101012,101012,3,1,1,1155.0,976.0,0.0,706.0,2928.0,2002.0,0.0,1514.0,6444.0,2837.0

## HousingType

DST says:

1. Enfamilie-, stue-, parcelhus (BBR-koder (110 Stuehus til landbrugsejendom og 120 Fritliggende enfamilieshus (parcelhus)).
2. Række-, kæde- dobbelthus (BBR-kode 130 Række-, kæde- eller dobbelthus (lodret adskillelse mellem enhederne)).
3. Etagebolig (BBR-kode 140 Etageboligbebyggelse (flerfamiliehus, herunder tofamiliehus (vandret adskillelse mellem enhederne))).
4. Kollegiebolig (BBR-kode 150 Kollegium)
6. Fritidshus (BBR-koder 510 Sommerhus. 540 Kolonihavehus.590 Anden enhed til fritidsformål)

In our data, we have:
- 01. Stuehuse og parcelhuse (detached houses/villas)
- 02. Række- og kædehuse (terraced houses)
- 03. Flerfamiliehuse (multi-family/block of flats)
- 04. Kollegier (student halls)
- 05. Sommerhuse (holiday homes)

So 'flerfamiliehuse' is apartment buildings/multi-storey residential buildings - or just two-family-houses, where the two homes are separated horizontally (as opposed to vertically, which would go under 'række- og kædehuse')
We will assume that 05. sommerhuse also covers kolonihavehuse, which we have a few of in cph.

I think we should put detached and terraced houses together in one column, blocks in one column. And ignore the rest.

In [30]:
cb.inspect_housingtype_duplicates(2001, 20) # use columns with space
cb.inspect_housingtype_duplicates(2005, 20) # use columns with space
cb.inspect_housingtype_duplicates(2009, 20) # use columns with space
cb.inspect_housingtype_duplicates(2013, 20) # use columns with underscore
cb.inspect_housingtype_duplicates(2017, 20) # use columns with underscore
cb.inspect_housingtype_duplicates(2021, 20) # use columns with underscore

================================================================================
HOUSING TYPE DUPLICATE INSPECTION - Year 2001
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 14/14
    Total sum across all: 910761.96
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 0/12
    Total sum across all: 0.00

CONCLUSION:
  USE columns with SPACES ('Antal boliger', 'Antal personer').
  IGNORE columns with underscores (they appear empty).

================================================================================


================================================================================
HOUSING TYPE DUPLICATE INSPECTION - Year 2005
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 14/14
    Total sum across all: 889999.89
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 0/12
    Total sum across all: 0.00

CONCLUSION:
  USE columns with SPACES ('Antal boliger', 'Antal personer').
  IGNORE columns with underscores (they appear empty).

================================================================================


================================================================================
HOUSING TYPE DUPLICATE INSPECTION - Year 2009
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 12/14
    Total sum across all: 955339.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 0/12
    Total sum across all: 0.00

CONCLUSION:
  USE columns with SPACES ('Antal boliger', 'Antal personer').
  IGNORE columns with underscores (they appear empty).

================================================================================


================================================================================
HOUSING TYPE DUPLICATE INSPECTION - Year 2013
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 0/14
    Total sum across all: 0.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 12/12
    Total sum across all: 1025655.01

CONCLUSION:
  USE columns with UNDERSCORES ('Antal_boliger', 'Antal_personer').
  IGNORE columns with spaces (they appear empty).

================================================================================


================================================================================
HOUSING TYPE DUPLICATE INSPECTION - Year 2017
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 0/14
    Total sum across all: 0.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 12/12
    Total sum across all: 1025654.95

CONCLUSION:
  USE columns with UNDERSCORES ('Antal_boliger', 'Antal_personer').
  IGNORE columns with spaces (they appear empty).

================================================================================


================================================================================
HOUSING TYPE DUPLICATE INSPECTION - Year 2021
================================================================================

Total columns found: 26

  Spaced columns     (e.g. 'Antal boliger'):   14
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 0/14
    Total sum across all: 0.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 12/12
    Total sum across all: 1100299.00

CONCLUSION:
  USE columns with UNDERSCORES ('Antal_boliger', 'Antal_personer').
  IGNORE columns with spaces (they appear empty).

================================================================================

In [31]:
type_2001 = cb.preprocess_housingtype(2001) # use columns with space
type_2005 = cb.preprocess_housingtype(2005) # use columns with space
type_2009 = cb.preprocess_housingtype(2009) # use columns with space
type_2013 = cb.preprocess_housingtype(2013) # use columns with underscore
type_2017 = cb.preprocess_housingtype(2017) # use columns with underscore
type_2021 = cb.preprocess_housingtype(2021) # use columns with underscore

    Housing type data: Using spaced format for year 2001
    Housing type data: Using spaced format for year 2005
    Housing type data: Using spaced format for year 2009
    Housing type data: Using underscored format for year 2013
    Housing type data: Using underscored format for year 2017
    Housing type data: Using underscored format for year 2021

In [32]:
print(f"{'='*80}\n  2001\n")
print(type_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(type_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(type_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(type_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(type_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(type_2021.info())

================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 21 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Gruppe                                   58 non-null     object
 1   ValgstedId                               58 non-null     object
 2   KredsNr                                  58 non-null     object
 3   StorKredsNr                              58 non-null     object
 4   LandsdelsNr                              58 non-null     object
 5   Housing type_Homes_Detached house        58 non-null     float64
 6   Housing type_Homes_Terraced house        58 non-null     float64
 7   Housing type_Homes_Apartment buildings   58 non-null     float64
 8   Housing type_Homes_Student halls         58 non-null     float64
 9   Housing type_Homes_Holiday homes         58 non-null     float64
 10  Housing type_Homes_Other homes           58 non-null     float64
 11  Housing type_Homes_No BBR information    58 non-null     float64
 12  Housing type_People_Detached house       58 non-null     float64
 13  Housing type_People_Terraced house       58 non-null     float64
 14  Housing type_People_Apartment buildings  58 non-null     float64
 15  Housing type_People_Student halls        58 non-null     float64
 16  Housing type_People_Holiday homes        58 non-null     float64
 17  Housing type_People_Other homes          58 non-null     float64
 18  Housing type_People_No BBR information   58 non-null     float64
 19  Housing type_Total people                58 non-null     float64
 20  Housing type_Total homes                 58 non-null     float64
dtypes: float64(16), object(5)
memory usage: 10.0+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 21 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Gruppe                                   58 non-null     object
 1   ValgstedId                               58 non-null     object
 2   KredsNr                                  58 non-null     object
 3   StorKredsNr                              58 non-null     object
 4   LandsdelsNr                              58 non-null     object
 5   Housing type_Homes_Detached house        58 non-null     float64
 6   Housing type_Homes_Terraced house        58 non-null     float64
 7   Housing type_Homes_Apartment buildings   58 non-null     float64
 8   Housing type_Homes_Student halls         58 non-null     float64
 9   Housing type_Homes_Holiday homes         58 non-null     float64
 10  Housing type_Homes_Other homes           58 non-null     float64
 11  Housing type_Homes_No BBR information    58 non-null     float64
 12  Housing type_People_Detached house       58 non-null     float64
 13  Housing type_People_Terraced house       58 non-null     float64
 14  Housing type_People_Apartment buildings  58 non-null     float64
 15  Housing type_People_Student halls        58 non-null     float64
 16  Housing type_People_Holiday homes        58 non-null     float64
 17  Housing type_People_Other homes          58 non-null     float64
 18  Housing type_People_No BBR information   58 non-null     float64
 19  Housing type_Total people                58 non-null     float64
 20  Housing type_Total homes                 58 non-null     float64
dtypes: float64(16), object(5)
memory usage: 10.0+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 21 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Gruppe                                   58 non-null     object
 1   ValgstedId                               58 non-null     object
 2   KredsNr                                  58 non-null     object
 3   StorKredsNr                              58 non-null     object
 4   LandsdelsNr                              58 non-null     object
 5   Housing type_Homes_Detached house        58 non-null     float64
 6   Housing type_Homes_Terraced house        58 non-null     float64
 7   Housing type_Homes_Apartment buildings   58 non-null     float64
 8   Housing type_Homes_Student halls         58 non-null     float64
 9   Housing type_Homes_Holiday homes         58 non-null     float64
 10  Housing type_Homes_Other homes           58 non-null     float64
 11  Housing type_Homes_No BBR information    0 non-null      float64
 12  Housing type_People_Detached house       58 non-null     float64
 13  Housing type_People_Terraced house       58 non-null     float64
 14  Housing type_People_Apartment buildings  58 non-null     float64
 15  Housing type_People_Student halls        58 non-null     float64
 16  Housing type_People_Holiday homes        58 non-null     float64
 17  Housing type_People_Other homes          58 non-null     float64
 18  Housing type_People_No BBR information   0 non-null      float64
 19  Housing type_Total people                58 non-null     float64
 20  Housing type_Total homes                 58 non-null     float64
dtypes: float64(16), object(5)
memory usage: 10.0+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 21 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Gruppe                                   58 non-null     object
 1   ValgstedId                               58 non-null     object
 2   KredsNr                                  58 non-null     object
 3   StorKredsNr                              58 non-null     object
 4   LandsdelsNr                              58 non-null     object
 5   Housing type_Homes_Detached house        58 non-null     float64
 6   Housing type_Homes_Terraced house        58 non-null     float64
 7   Housing type_Homes_Apartment buildings   58 non-null     float64
 8   Housing type_Homes_Student halls         58 non-null     float64
 9   Housing type_Homes_Holiday homes         58 non-null     float64
 10  Housing type_Homes_Other homes           58 non-null     float64
 11  Housing type_Homes_No BBR information    0 non-null      float64
 12  Housing type_People_Detached house       58 non-null     float64
 13  Housing type_People_Terraced house       58 non-null     float64
 14  Housing type_People_Apartment buildings  58 non-null     float64
 15  Housing type_People_Student halls        58 non-null     float64
 16  Housing type_People_Holiday homes        58 non-null     float64
 17  Housing type_People_Other homes          58 non-null     float64
 18  Housing type_People_No BBR information   0 non-null      float64
 19  Housing type_Total people                58 non-null     float64
 20  Housing type_Total homes                 58 non-null     float64
dtypes: float64(16), object(5)
memory usage: 10.0+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 21 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Gruppe                                   58 non-null     object
 1   ValgstedId                               58 non-null     object
 2   KredsNr                                  58 non-null     object
 3   StorKredsNr                              58 non-null     object
 4   LandsdelsNr                              58 non-null     object
 5   Housing type_Homes_Detached house        58 non-null     float64
 6   Housing type_Homes_Terraced house        58 non-null     float64
 7   Housing type_Homes_Apartment buildings   58 non-null     float64
 8   Housing type_Homes_Student halls         58 non-null     float64
 9   Housing type_Homes_Holiday homes         58 non-null     float64
 10  Housing type_Homes_Other homes           58 non-null     float64
 11  Housing type_Homes_No BBR information    0 non-null      float64
 12  Housing type_People_Detached house       58 non-null     float64
 13  Housing type_People_Terraced house       58 non-null     float64
 14  Housing type_People_Apartment buildings  58 non-null     float64
 15  Housing type_People_Student halls        58 non-null     float64
 16  Housing type_People_Holiday homes        58 non-null     float64
 17  Housing type_People_Other homes          58 non-null     float64
 18  Housing type_People_No BBR information   0 non-null      float64
 19  Housing type_Total people                58 non-null     float64
 20  Housing type_Total homes                 58 non-null     float64
dtypes: float64(16), object(5)
memory usage: 10.0+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 21 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Gruppe                                   58 non-null     object
 1   ValgstedId                               58 non-null     object
 2   KredsNr                                  58 non-null     object
 3   StorKredsNr                              58 non-null     object
 4   LandsdelsNr                              58 non-null     object
 5   Housing type_Homes_Detached house        58 non-null     float64
 6   Housing type_Homes_Terraced house        58 non-null     float64
 7   Housing type_Homes_Apartment buildings   58 non-null     int64
 8   Housing type_Homes_Student halls         58 non-null     float64
 9   Housing type_Homes_Holiday homes         58 non-null     float64
 10  Housing type_Homes_Other homes           58 non-null     float64
 11  Housing type_Homes_No BBR information    0 non-null      float64
 12  Housing type_People_Detached house       58 non-null     float64
 13  Housing type_People_Terraced house       58 non-null     float64
 14  Housing type_People_Apartment buildings  58 non-null     int64
 15  Housing type_People_Student halls        58 non-null     float64
 16  Housing type_People_Holiday homes        58 non-null     float64
 17  Housing type_People_Other homes          58 non-null     float64
 18  Housing type_People_No BBR information   0 non-null      float64
 19  Housing type_Total people                58 non-null     float64
 20  Housing type_Total homes                 58 non-null     float64
dtypes: float64(14), int64(2), object(5)
memory usage: 10.0+ KB
None

In [33]:
type_2017.head(10)

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Housing type_Homes_Detached house,Housing type_Homes_Terraced house,Housing type_Homes_Apartment buildings,Housing type_Homes_Student halls,Housing type_Homes_Holiday homes,...,Housing type_Homes_No BBR information,Housing type_People_Detached house,Housing type_People_Terraced house,Housing type_People_Apartment buildings,Housing type_People_Student halls,Housing type_People_Holiday homes,Housing type_People_Other homes,Housing type_People_No BBR information,Housing type_Total people,Housing type_Total homes
0,101001,101001,1,1,1,1.49,35.05,7115.07,0.00,0.75,...,NaN,7.46,107.37,13556.81,0.00,1.49,76.06,NaN,13749.19,7188.90
1,101002,101002,1,1,1,218.00,81.00,3748.00,7.00,1.00,...,NaN,812.00,232.00,6782.00,7.00,1.00,121.00,NaN,7955.00,4075.00
2,101003,101003,1,1,1,18.80,5.48,7624.50,206.77,0.78,...,NaN,65.79,12.53,15383.70,217.73,0.78,112.00,NaN,15792.53,7900.97
3,101005,101005,1,1,1,5.00,141.00,7916.00,162.00,4.00,...,NaN,10.00,515.00,14500.00,229.00,4.00,82.00,NaN,15340.00,8284.00
4,101006,101006,1,1,1,14.00,364.00,6486.00,85.00,0.00,...,NaN,40.00,1158.00,11781.00,91.00,0.00,137.00,NaN,13207.00,7013.00
5,101007,101007,2,1,1,1138.98,475.69,4961.62,119.11,1.49,...,NaN,3198.06,1452.38,9216.77,141.44,2.23,64.77,NaN,14075.65,6739.32
6,101008,101010;101008,2,1,1,7.00,135.00,15039.00,565.00,9.00,...,NaN,19.00,468.00,29609.00,690.00,57.00,396.00,NaN,31239.00,15814.00
7,101009,101057;101009,2,1,1,1343.02,547.31,5773.38,1456.89,20.51,...,NaN,3738.94,1586.62,12362.23,1691.56,45.77,217.23,NaN,19642.35,9259.68
8,101011,101011,3,1,1,6.00,8.00,7257.00,311.00,4.00,...,NaN,12.00,20.00,14634.00,442.00,6.00,4147.00,NaN,19261.00,7724.00
9,101012,101012,3,1,1,5.00,430.00,3636.00,1.00,1.00,...,NaN,14.00,1282.00,7641.00,60.00,3.00,60.00,NaN,9060.00,4097.00

In [34]:
type_2021.describe()

,Housing type_Homes_Detached house,Housing type_Homes_Terraced house,Housing type_Homes_Apartment buildings,Housing type_Homes_Student halls,Housing type_Homes_Holiday homes,Housing type_Homes_Other homes,Housing type_Homes_No BBR information,Housing type_People_Detached house,Housing type_People_Terraced house,Housing type_People_Apartment buildings,Housing type_People_Student halls,Housing type_People_Holiday homes,Housing type_People_Other homes,Housing type_People_No BBR information,Housing type_Total people,Housing type_Total homes
count,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,0.0,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,0.0,58.000000,58.000000
mean,268.689655,170.086207,5633.810345,163.500000,1.706897,32.103448,NaN,827.189655,502.155172,10991.413793,208.948276,3.189655,167.879310,NaN,12700.775862,6269.896552
std,419.681634,226.612296,2486.069289,331.866717,3.815980,36.721660,NaN,1277.016609,665.350872,4862.007220,414.462087,8.038192,503.385907,NaN,5285.771022,2643.388453
min,0.000000,0.000000,1614.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,2787.000000,0.000000,0.000000,0.000000,NaN,4468.000000,2497.000000
25%,4.000000,12.250000,4015.250000,0.000000,0.000000,9.000000,NaN,13.250000,36.250000,8083.250000,0.000000,0.000000,20.750000,NaN,9372.500000,4702.750000
50%,63.500000,88.500000,5296.500000,18.000000,0.000000,16.000000,NaN,221.000000,266.500000,10633.000000,48.000000,0.000000,53.500000,NaN,11982.500000,5699.000000
75%,365.000000,275.500000,7129.500000,170.750000,2.000000,47.000000,NaN,1062.500000,844.500000,13703.750000,221.250000,2.750000,159.000000,NaN,14489.750000,7392.750000
max,1956.000000,1312.000000,15867.000000,1841.000000,19.000000,148.000000,NaN,5569.000000,4016.000000,31287.000000,2232.000000,47.000000,3831.000000,NaN,33643.000000,16761.000000

In [35]:
type_2021[type_2021['Housing type_Homes_Detached house'] == type_2021['Housing type_Homes_Detached house'].max()]

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Housing type_Homes_Detached house,Housing type_Homes_Terraced house,Housing type_Homes_Apartment buildings,Housing type_Homes_Student halls,Housing type_Homes_Holiday homes,...,Housing type_Homes_No BBR information,Housing type_People_Detached house,Housing type_People_Terraced house,Housing type_People_Apartment buildings,Housing type_People_Student halls,Housing type_People_Holiday homes,Housing type_People_Other homes,Housing type_People_No BBR information,Housing type_Total people,Housing type_Total homes
7,101009,101057;101009,2,1,1,1956.0,1312.0,8413,1841.0,19.0,...,NaN,5569.0,4016.0,19050,2232.0,32.0,163.0,NaN,31062.0,13616.0

### Conclusion

In the final combined df:
- Combine detached and terraced into one column
- Use apartments, the combined column and the total columns, but none of the other

## Income, benefit type, cars, crime

In [36]:
simple_2001 = cb.preprocess_simple(2001) 
simple_2005 = cb.preprocess_simple(2005) 
simple_2009 = cb.preprocess_simple(2009) 
simple_2013 = cb.preprocess_simple(2013)
simple_2017 = cb.preprocess_simple(2017)
simple_2021 = cb.preprocess_simple(2021)

    Extracting from PersonsByBenefitType.csv...
    Extracting from CrimeArrests.csv...
    Extracting from HouseholdIncomes.csv...
    Extracting from HouseholdsCarOwnership.csv...
    Extracting from PersonsByBenefitType.csv...
    Extracting from CrimeArrests.csv...
    Extracting from HouseholdIncomes.csv...
    Extracting from HouseholdsCarOwnership.csv...
    Extracting from PersonsByBenefitType.csv...
    Extracting from CrimeArrests.csv...
    Extracting from HouseholdIncomes.csv...
    Extracting from HouseholdsCarOwnership.csv...
    Extracting from PersonsByBenefitType.csv...
    Extracting from CrimeArrests.csv...
    Extracting from HouseholdIncomes.csv...
    Extracting from HouseholdsCarOwnership.csv...
    Extracting from PersonsByBenefitType.csv...
    Extracting from CrimeArrests.csv...
    Extracting from HouseholdIncomes.csv...
    Extracting from HouseholdsCarOwnership.csv...
    Extracting from PersonsByBenefitType.csv...
    Extracting from CrimeArrests.csv...
    Extracting from HouseholdIncomes.csv...
    Extracting from HouseholdsCarOwnership.csv...

In [37]:
print(f"{'='*80}\n  2001\n")
print(simple_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(simple_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(simple_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(simple_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(simple_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(simple_2021.info())

================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Gruppe                              58 non-null     object
 1   ValgstedId                          58 non-null     object
 2   KredsNr                             58 non-null     object
 3   StorKredsNr                         58 non-null     object
 4   LandsdelsNr                         58 non-null     object
 5   Benefit type_Kontanthjaelp          0 non-null      float64
 6   Benefit type_Foertidspension        0 non-null      float64
 7   Benefit type_Folkepension           0 non-null      float64
 8   Benefit type_Modtager ikke ydelser  0 non-null      float64
 9   Benefit type_Antal personer i alt   0 non-null      float64
 10  Crime_Number of arrests             0 non-null      float64
 11  Income_Median household income      0 non-null      float64
 12  Income_Total households             0 non-null      float64
 13  Income_Gross income top20pct        0 non-null      float64
 14  Car_Households with no car          0 non-null      float64
 15  Car_Households with 1 car           0 non-null      float64
 16  Car_Households with 2+ cars         0 non-null      float64
dtypes: float64(12), object(5)
memory usage: 7.8+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Gruppe                              58 non-null     object
 1   ValgstedId                          58 non-null     object
 2   KredsNr                             58 non-null     object
 3   StorKredsNr                         58 non-null     object
 4   LandsdelsNr                         58 non-null     object
 5   Benefit type_Kontanthjaelp          0 non-null      float64
 6   Benefit type_Foertidspension        0 non-null      float64
 7   Benefit type_Folkepension           0 non-null      float64
 8   Benefit type_Modtager ikke ydelser  0 non-null      float64
 9   Benefit type_Antal personer i alt   0 non-null      float64
 10  Crime_Number of arrests             0 non-null      float64
 11  Income_Median household income      0 non-null      float64
 12  Income_Total households             0 non-null      float64
 13  Income_Gross income top20pct        0 non-null      float64
 14  Car_Households with no car          0 non-null      float64
 15  Car_Households with 1 car           0 non-null      float64
 16  Car_Households with 2+ cars         0 non-null      float64
dtypes: float64(12), object(5)
memory usage: 7.8+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Gruppe                              58 non-null     object
 1   ValgstedId                          58 non-null     object
 2   KredsNr                             58 non-null     object
 3   StorKredsNr                         58 non-null     object
 4   LandsdelsNr                         58 non-null     object
 5   Benefit type_Kontanthjaelp          58 non-null     float64
 6   Benefit type_Foertidspension        58 non-null     float64
 7   Benefit type_Folkepension           58 non-null     float64
 8   Benefit type_Modtager ikke ydelser  58 non-null     float64
 9   Benefit type_Antal personer i alt   58 non-null     float64
 10  Crime_Number of arrests             0 non-null      float64
 11  Income_Median household income      58 non-null     float64
 12  Income_Total households             58 non-null     float64
 13  Income_Gross income top20pct        58 non-null     float64
 14  Car_Households with no car          58 non-null     float64
 15  Car_Households with 1 car           58 non-null     float64
 16  Car_Households with 2+ cars         58 non-null     float64
dtypes: float64(12), object(5)
memory usage: 7.8+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Gruppe                              58 non-null     object
 1   ValgstedId                          58 non-null     object
 2   KredsNr                             58 non-null     object
 3   StorKredsNr                         58 non-null     object
 4   LandsdelsNr                         58 non-null     object
 5   Benefit type_Kontanthjaelp          58 non-null     float64
 6   Benefit type_Foertidspension        58 non-null     float64
 7   Benefit type_Folkepension           58 non-null     float64
 8   Benefit type_Modtager ikke ydelser  58 non-null     float64
 9   Benefit type_Antal personer i alt   58 non-null     float64
 10  Crime_Number of arrests             58 non-null     float64
 11  Income_Median household income      58 non-null     float64
 12  Income_Total households             58 non-null     float64
 13  Income_Gross income top20pct        58 non-null     float64
 14  Car_Households with no car          58 non-null     float64
 15  Car_Households with 1 car           58 non-null     float64
 16  Car_Households with 2+ cars         58 non-null     float64
dtypes: float64(12), object(5)
memory usage: 7.8+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Gruppe                              58 non-null     object
 1   ValgstedId                          58 non-null     object
 2   KredsNr                             58 non-null     object
 3   StorKredsNr                         58 non-null     object
 4   LandsdelsNr                         58 non-null     object
 5   Benefit type_Kontanthjaelp          58 non-null     float64
 6   Benefit type_Foertidspension        58 non-null     float64
 7   Benefit type_Folkepension           58 non-null     float64
 8   Benefit type_Modtager ikke ydelser  58 non-null     float64
 9   Benefit type_Antal personer i alt   58 non-null     float64
 10  Crime_Number of arrests             58 non-null     float64
 11  Income_Median household income      58 non-null     float64
 12  Income_Total households             58 non-null     float64
 13  Income_Gross income top20pct        58 non-null     float64
 14  Car_Households with no car          58 non-null     float64
 15  Car_Households with 1 car           58 non-null     float64
 16  Car_Households with 2+ cars         58 non-null     float64
dtypes: float64(12), object(5)
memory usage: 7.8+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Gruppe                              58 non-null     object
 1   ValgstedId                          58 non-null     object
 2   KredsNr                             58 non-null     object
 3   StorKredsNr                         58 non-null     object
 4   LandsdelsNr                         58 non-null     object
 5   Benefit type_Kontanthjaelp          58 non-null     int64
 6   Benefit type_Foertidspension        58 non-null     int64
 7   Benefit type_Folkepension           58 non-null     int64
 8   Benefit type_Modtager ikke ydelser  58 non-null     int64
 9   Benefit type_Antal personer i alt   58 non-null     int64
 10  Crime_Number of arrests             58 non-null     float64
 11  Income_Median household income      58 non-null     int64
 12  Income_Total households             58 non-null     int64
 13  Income_Gross income top20pct        58 non-null     int64
 14  Car_Households with no car          58 non-null     int64
 15  Car_Households with 1 car           58 non-null     int64
 16  Car_Households with 2+ cars         58 non-null     int64
dtypes: float64(1), int64(11), object(5)
memory usage: 7.8+ KB
None

In [38]:
simple_2021.head(10)

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Benefit type_Kontanthjaelp,Benefit type_Foertidspension,Benefit type_Folkepension,Benefit type_Modtager ikke ydelser,Benefit type_Antal personer i alt,Crime_Number of arrests,Income_Median household income,Income_Total households,Income_Gross income top20pct,Car_Households with no car,Car_Households with 1 car,Car_Households with 2+ cars
0,101001,101001,1,1,1,259,244,1646,11236,15562,40.0,491202,7928,2353964408,5056,956,2032
1,101002,101002,1,1,1,184,160,1307,5669,8378,29.0,469505,4351,1813280147,2385,658,1256
2,101003,101003,1,1,1,170,177,1579,11748,15846,41.0,542786,7547,2551615423,4591,807,2229
3,101005,101005,1,1,1,314,376,2038,10767,15854,68.0,438719,8208,1974027178,5361,1057,1958
4,101006,101006,1,1,1,307,372,1617,9086,13487,38.0,449840,7164,1844543365,4349,954,1802
5,101007,101007,2,1,1,572,510,1997,9065,14265,126.0,401150,7081,1750447556,4173,856,2084
6,101008,101010;101008,2,1,1,892,807,3109,23509,33643,182.0,1070952,16801,4777664075,10037,2049,4675
7,101009,101057;101009,2,1,1,480,551,1795,23792,31062,92.0,997902,14163,3800875512,8164,1193,4259
8,101011,101011,3,1,1,1006,242,1698,15027,20283,639.0,545166,8024,3085311495,5368,916,1838
9,101012,101012,3,1,1,74,65,1271,6748,9176,15.0,649124,4072,2114427532,2045,518,1565

In [39]:
simple_2021.describe()

,Benefit type_Kontanthjaelp,Benefit type_Foertidspension,Benefit type_Folkepension,Benefit type_Modtager ikke ydelser,Benefit type_Antal personer i alt,Crime_Number of arrests,Income_Median household income,Income_Total households,Income_Gross income top20pct,Car_Households with no car,Car_Households with 1 car,Car_Households with 2+ cars
count,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,5.800000e+01,58.000000,5.800000e+01,58.000000,58.000000,58.000000
mean,335.741379,319.827586,1326.189655,8787.931034,12700.775862,73.396552,5.016165e+05,6271.672414,1.738676e+09,3802.155172,753.689655,1714.034483
std,200.674263,169.927140,688.845779,3912.312727,5285.771022,85.355591,1.490076e+05,2656.540907,8.520362e+08,1749.392324,333.382990,776.124718
min,74.000000,65.000000,383.000000,2969.000000,4468.000000,0.000000,2.764210e+05,2484.000000,4.069871e+08,1090.000000,236.000000,289.000000
25%,181.000000,201.500000,765.000000,6722.500000,9372.500000,34.000000,4.176092e+05,4544.250000,1.203761e+09,2658.000000,518.250000,1164.750000
50%,301.000000,257.000000,1232.000000,8250.500000,11982.500000,56.500000,4.687070e+05,5673.500000,1.521289e+09,3399.500000,726.000000,1598.500000
75%,417.500000,392.000000,1692.750000,9902.000000,14489.750000,91.250000,5.385520e+05,7493.500000,2.201399e+09,4755.000000,909.250000,2106.250000
max,1006.000000,807.000000,3608.000000,23792.000000,33643.000000,639.000000,1.070952e+06,16801.000000,4.777664e+09,10037.000000,2049.000000,4675.000000

### Conclusion
Again, no data for any of the features for 2001 and 2005.

Crime data missing for 2009.

## HousingByYearOfConstruction

In [40]:
cb.inspect_constructionyear_duplicates(2001, 20) # use columns with space, but drop columns with 2000- 
cb.inspect_constructionyear_duplicates(2005, 20) # use columns with space
cb.inspect_constructionyear_duplicates(2009, 20) # use columns with space
cb.inspect_constructionyear_duplicates(2013, 20) # use underscored columns (make sure to get Antal_boliger_Før 1940 and Antal_personer_Før 1940)
cb.inspect_constructionyear_duplicates(2017, 20) # use underscored columns (make sure to get Antal_boliger_Før 1940 and Antal_personer_Før 1940)
cb.inspect_constructionyear_duplicates(2021, 20) # use underscored columns (make sure to get Antal_boliger_Før 1940 and Antal_personer_Før 1940)

================================================================================
CONSTRUCTION YEAR INSPECTION - Year 2001
================================================================================

Total columns found: 30

Columns with SPACE (e.g., 'Antal boliger_...'):
  Total: 16
  With data: 12
    ✓ Antal boliger_1940-1959                                      sum=45285
    ✓ Antal boliger_1960-1969                                      sum=18488
    ✓ Antal boliger_1970-1979                                      sum=20009
    ✓ Antal boliger_1980-1989                                      sum=11522
    ✓ Antal boliger_1990-1999                                      sum=7816
    ✗ Antal boliger_2000-                                          sum=0
    ✓ Antal boliger_Før 1940                                       sum=221616
    ✓ Antal personer_1940-1959                                     sum=74006
    ✓ Antal personer_1960-1969                                     sum=31599
    ✓ Antal personer_1970-1979                                     sum=35223
    ✓ Antal personer_1980-1989                                     sum=29493
    ✓ Antal personer_1990-1999                                     sum=17235
    ✗ Antal personer_2000-                                         sum=0
    ✓ Antal personer_Før 1940                                      sum=398470
    ✗ Antal_boliger_Før 1940                                       sum=0
    ✗ Antal_personer_Før 1940                                      sum=0

Columns with UNDERSCORE (e.g., 'Antal_boliger_...'):
  Total: 14
  With data: 0
    ✗ Antal_boliger_1940-1959                                      sum=0
    ✗ Antal_boliger_1960-1969                                      sum=0
    ✗ Antal_boliger_1970-1979                                      sum=0
    ✗ Antal_boliger_1980-1989                                      sum=0
    ✗ Antal_boliger_1990-1999                                      sum=0
    ✗ Antal_boliger_2000-2009                                      sum=0
    ✗ Antal_boliger_2010-9999                                      sum=0
    ✗ Antal_personer_1940-1959                                     sum=0
    ✗ Antal_personer_1960-1969                                     sum=0
    ✗ Antal_personer_1970-1979                                     sum=0
    ✗ Antal_personer_1980-1989                                     sum=0
    ✗ Antal_personer_1990-1999                                     sum=0
    ✗ Antal_personer_2000-2009                                     sum=0
    ✗ Antal_personer_2010-9999                                     sum=0

CONCLUSION:
  ✓ USE spaced columns (Antal boliger/Antal personer)
    12 columns have data vs 0 underscore columns

================================================================================


================================================================================
CONSTRUCTION YEAR INSPECTION - Year 2005
================================================================================

Total columns found: 30

Columns with SPACE (e.g., 'Antal boliger_...'):
  Total: 16
  With data: 14
    ✓ Antal boliger_1940-1959                                      sum=44375
    ✓ Antal boliger_1960-1969                                      sum=18593
    ✓ Antal boliger_1970-1979                                      sum=19470
    ✓ Antal boliger_1980-1989                                      sum=11289
    ✓ Antal boliger_1990-1999                                      sum=7728
    ✓ Antal boliger_2000-                                          sum=2575
    ✓ Antal boliger_Før 1940                                       sum=209095
    ✓ Antal personer_1940-1959                                     sum=73549
    ✓ Antal personer_1960-1969                                     sum=31529
    ✓ Antal personer_1970-1979                                     sum=34039
    ✓ Antal personer_1980-1989                                     sum=28752
    ✓ Antal personer_1990-1999                                     sum=16975
    ✓ Antal personer_2000-                                         sum=5327
    ✓ Antal personer_Før 1940                                      sum=386704
    ✗ Antal_boliger_Før 1940                                       sum=0
    ✗ Antal_personer_Før 1940                                      sum=0

Columns with UNDERSCORE (e.g., 'Antal_boliger_...'):
  Total: 14
  With data: 0
    ✗ Antal_boliger_1940-1959                                      sum=0
    ✗ Antal_boliger_1960-1969                                      sum=0
    ✗ Antal_boliger_1970-1979                                      sum=0
    ✗ Antal_boliger_1980-1989                                      sum=0
    ✗ Antal_boliger_1990-1999                                      sum=0
    ✗ Antal_boliger_2000-2009                                      sum=0
    ✗ Antal_boliger_2010-9999                                      sum=0
    ✗ Antal_personer_1940-1959                                     sum=0
    ✗ Antal_personer_1960-1969                                     sum=0
    ✗ Antal_personer_1970-1979                                     sum=0
    ✗ Antal_personer_1980-1989                                     sum=0
    ✗ Antal_personer_1990-1999                                     sum=0
    ✗ Antal_personer_2000-2009                                     sum=0
    ✗ Antal_personer_2010-9999                                     sum=0

CONCLUSION:
  ✓ USE spaced columns (Antal boliger/Antal personer)
    14 columns have data vs 0 underscore columns

================================================================================


================================================================================
CONSTRUCTION YEAR INSPECTION - Year 2009
================================================================================

Total columns found: 30

Columns with SPACE (e.g., 'Antal boliger_...'):
  Total: 16
  With data: 14
    ✓ Antal boliger_1940-1959                                      sum=44410
    ✓ Antal boliger_1960-1969                                      sum=18255
    ✓ Antal boliger_1970-1979                                      sum=19426
    ✓ Antal boliger_1980-1989                                      sum=11579
    ✓ Antal boliger_1990-1999                                      sum=7966
    ✓ Antal boliger_2000-                                          sum=13841
    ✓ Antal boliger_Før 1940                                       sum=215517
    ✓ Antal personer_1940-1959                                     sum=74569
    ✓ Antal personer_1960-1969                                     sum=31310
    ✓ Antal personer_1970-1979                                     sum=33184
    ✓ Antal personer_1980-1989                                     sum=27884
    ✓ Antal personer_1990-1999                                     sum=16788
    ✓ Antal personer_2000-                                         sum=29649
    ✓ Antal personer_Før 1940                                      sum=410961
    ✗ Antal_boliger_Før 1940                                       sum=0
    ✗ Antal_personer_Før 1940                                      sum=0

Columns with UNDERSCORE (e.g., 'Antal_boliger_...'):
  Total: 14
  With data: 0
    ✗ Antal_boliger_1940-1959                                      sum=0
    ✗ Antal_boliger_1960-1969                                      sum=0
    ✗ Antal_boliger_1970-1979                                      sum=0
    ✗ Antal_boliger_1980-1989                                      sum=0
    ✗ Antal_boliger_1990-1999                                      sum=0
    ✗ Antal_boliger_2000-2009                                      sum=0
    ✗ Antal_boliger_2010-9999                                      sum=0
    ✗ Antal_personer_1940-1959                                     sum=0
    ✗ Antal_personer_1960-1969                                     sum=0
    ✗ Antal_personer_1970-1979                                     sum=0
    ✗ Antal_personer_1980-1989                                     sum=0
    ✗ Antal_personer_1990-1999                                     sum=0
    ✗ Antal_personer_2000-2009                                     sum=0
    ✗ Antal_personer_2010-9999                                     sum=0

CONCLUSION:
  ✓ USE spaced columns (Antal boliger/Antal personer)
    14 columns have data vs 0 underscore columns

================================================================================


================================================================================
CONSTRUCTION YEAR INSPECTION - Year 2013
================================================================================

Total columns found: 30

Columns with SPACE (e.g., 'Antal boliger_...'):
  Total: 16
  With data: 2
    ✗ Antal boliger_1940-1959                                      sum=0
    ✗ Antal boliger_1960-1969                                      sum=0
    ✗ Antal boliger_1970-1979                                      sum=0
    ✗ Antal boliger_1980-1989                                      sum=0
    ✗ Antal boliger_1990-1999                                      sum=0
    ✗ Antal boliger_2000-                                          sum=0
    ✗ Antal boliger_Før 1940                                       sum=0
    ✗ Antal personer_1940-1959                                     sum=0
    ✗ Antal personer_1960-1969                                     sum=0
    ✗ Antal personer_1970-1979                                     sum=0
    ✗ Antal personer_1980-1989                                     sum=0
    ✗ Antal personer_1990-1999                                     sum=0
    ✗ Antal personer_2000-                                         sum=0
    ✗ Antal personer_Før 1940                                      sum=0
    ✓ Antal_boliger_Før 1940                                       sum=219242
    ✓ Antal_personer_Før 1940                                      sum=443050

Columns with UNDERSCORE (e.g., 'Antal_boliger_...'):
  Total: 14
  With data: 14
    ✓ Antal_boliger_1940-1959                                      sum=44964
    ✓ Antal_boliger_1960-1969                                      sum=18549
    ✓ Antal_boliger_1970-1979                                      sum=19449
    ✓ Antal_boliger_1980-1989                                      sum=11430
    ✓ Antal_boliger_1990-1999                                      sum=8063
    ✓ Antal_boliger_2000-2009                                      sum=15304
    ✓ Antal_boliger_2010-9999                                      sum=5278
    ✓ Antal_personer_1940-1959                                     sum=81109
    ✓ Antal_personer_1960-1969                                     sum=33392
    ✓ Antal_personer_1970-1979                                     sum=34345
    ✓ Antal_personer_1980-1989                                     sum=27551
    ✓ Antal_personer_1990-1999                                     sum=17033
    ✓ Antal_personer_2000-2009                                     sum=34473
    ✓ Antal_personer_2010-9999                                     sum=12423

CONCLUSION:
  ✓ USE underscore columns (Antal_boliger/Antal_personer)
    14 columns have data vs 2 spaced columns

================================================================================


================================================================================
CONSTRUCTION YEAR INSPECTION - Year 2017
================================================================================

Total columns found: 30

Columns with SPACE (e.g., 'Antal boliger_...'):
  Total: 16
  With data: 2
    ✗ Antal boliger_1940-1959                                      sum=0
    ✗ Antal boliger_1960-1969                                      sum=0
    ✗ Antal boliger_1970-1979                                      sum=0
    ✗ Antal boliger_1980-1989                                      sum=0
    ✗ Antal boliger_1990-1999                                      sum=0
    ✗ Antal boliger_2000-                                          sum=0
    ✗ Antal boliger_Før 1940                                       sum=0
    ✗ Antal personer_1940-1959                                     sum=0
    ✗ Antal personer_1960-1969                                     sum=0
    ✗ Antal personer_1970-1979                                     sum=0
    ✗ Antal personer_1980-1989                                     sum=0
    ✗ Antal personer_1990-1999                                     sum=0
    ✗ Antal personer_2000-                                         sum=0
    ✗ Antal personer_Før 1940                                      sum=0
    ✓ Antal_boliger_Før 1940                                       sum=219242
    ✓ Antal_personer_Før 1940                                      sum=443050

Columns with UNDERSCORE (e.g., 'Antal_boliger_...'):
  Total: 14
  With data: 14
    ✓ Antal_boliger_1940-1959                                      sum=44964
    ✓ Antal_boliger_1960-1969                                      sum=18549
    ✓ Antal_boliger_1970-1979                                      sum=19449
    ✓ Antal_boliger_1980-1989                                      sum=11430
    ✓ Antal_boliger_1990-1999                                      sum=8063
    ✓ Antal_boliger_2000-2009                                      sum=15304
    ✓ Antal_boliger_2010-9999                                      sum=5278
    ✓ Antal_personer_1940-1959                                     sum=81109
    ✓ Antal_personer_1960-1969                                     sum=33392
    ✓ Antal_personer_1970-1979                                     sum=34345
    ✓ Antal_personer_1980-1989                                     sum=27551
    ✓ Antal_personer_1990-1999                                     sum=17033
    ✓ Antal_personer_2000-2009                                     sum=34473
    ✓ Antal_personer_2010-9999                                     sum=12423

CONCLUSION:
  ✓ USE underscore columns (Antal_boliger/Antal_personer)
    14 columns have data vs 2 spaced columns

================================================================================


================================================================================
CONSTRUCTION YEAR INSPECTION - Year 2021
================================================================================

Total columns found: 30

Columns with SPACE (e.g., 'Antal boliger_...'):
  Total: 16
  With data: 2
    ✗ Antal boliger_1940-1959                                      sum=0
    ✗ Antal boliger_1960-1969                                      sum=0
    ✗ Antal boliger_1970-1979                                      sum=0
    ✗ Antal boliger_1980-1989                                      sum=0
    ✗ Antal boliger_1990-1999                                      sum=0
    ✗ Antal boliger_2000-                                          sum=0
    ✗ Antal boliger_Før 1940                                       sum=0
    ✗ Antal personer_1940-1959                                     sum=0
    ✗ Antal personer_1960-1969                                     sum=0
    ✗ Antal personer_1970-1979                                     sum=0
    ✗ Antal personer_1980-1989                                     sum=0
    ✗ Antal personer_1990-1999                                     sum=0
    ✗ Antal personer_2000-                                         sum=0
    ✗ Antal personer_Før 1940                                      sum=0
    ✓ Antal_boliger_Før 1940                                       sum=222363
    ✓ Antal_personer_Før 1940                                      sum=454998

Columns with UNDERSCORE (e.g., 'Antal_boliger_...'):
  Total: 14
  With data: 14
    ✓ Antal_boliger_1940-1959                                      sum=45375
    ✓ Antal_boliger_1960-1969                                      sum=18949
    ✓ Antal_boliger_1970-1979                                      sum=19323
    ✓ Antal_boliger_1980-1989                                      sum=11460
    ✓ Antal_boliger_1990-1999                                      sum=8160
    ✓ Antal_boliger_2000-2009                                      sum=15674
    ✓ Antal_boliger_2010-9999                                      sum=22350
    ✓ Antal_personer_1940-1959                                     sum=83195
    ✓ Antal_personer_1960-1969                                     sum=34659
    ✓ Antal_personer_1970-1979                                     sum=33969
    ✓ Antal_personer_1980-1989                                     sum=26405
    ✓ Antal_personer_1990-1999                                     sum=16380
    ✓ Antal_personer_2000-2009                                     sum=34005
    ✓ Antal_personer_2010-9999                                     sum=53034

CONCLUSION:
  ✓ USE underscore columns (Antal_boliger/Antal_personer)
    14 columns have data vs 2 spaced columns

================================================================================

In [41]:
builtyear_2001 = cb.preprocess_builtyear(2001) 
builtyear_2005 = cb.preprocess_builtyear(2005) 
builtyear_2009 = cb.preprocess_builtyear(2009) 
builtyear_2013 = cb.preprocess_builtyear(2013)
builtyear_2017 = cb.preprocess_builtyear(2017)
builtyear_2021 = cb.preprocess_builtyear(2021)

    Construction year data: Using spaced format for year 2001
    Construction year data: Using spaced format for year 2005
    Construction year data: Using spaced format for year 2009
    Construction year data: Using underscored format for year 2013
    Construction year data: Using underscored format for year 2017
    Construction year data: Using underscored format for year 2021

In [42]:
print(f"{'='*80}\n  2001\n")
print(builtyear_2001.info())
print(f"\n{'='*80}\n  2005\n")
print(builtyear_2005.info())
print(f"\n{'='*80}\n  2009\n")
print(builtyear_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(builtyear_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(builtyear_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(builtyear_2021.info())

================================================================================
  2001

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Year built_Homes_Før 1940    58 non-null     float64
 6   Year built_Homes_1940-1959   58 non-null     float64
 7   Year built_Homes_1960-1969   58 non-null     float64
 8   Year built_Homes_1970-1979   58 non-null     float64
 9   Year built_Homes_1980-1989   58 non-null     float64
 10  Year built_Homes_1990-1999   58 non-null     float64
 11  Year built_Homes_2000-2009   0 non-null      float64
 12  Year built_Homes_2010-9999   0 non-null      float64
 13  Year built_Homes_2000-       0 non-null      float64
 14  Year built_People_Før 1940   58 non-null     float64
 15  Year built_People_1940-1959  58 non-null     float64
 16  Year built_People_1960-1969  58 non-null     float64
 17  Year built_People_1970-1979  58 non-null     float64
 18  Year built_People_1980-1989  58 non-null     float64
 19  Year built_People_1990-1999  58 non-null     float64
 20  Year built_People_2000-2009  0 non-null      float64
 21  Year built_People_2010-9999  0 non-null      float64
 22  Year built_People_2000-      0 non-null      float64
 23  Year built_Total people      58 non-null     float64
 24  Year built_Total homes       58 non-null     float64
dtypes: float64(20), object(5)
memory usage: 11.8+ KB
None

================================================================================
  2005

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Year built_Homes_Før 1940    58 non-null     float64
 6   Year built_Homes_1940-1959   58 non-null     float64
 7   Year built_Homes_1960-1969   58 non-null     float64
 8   Year built_Homes_1970-1979   58 non-null     float64
 9   Year built_Homes_1980-1989   58 non-null     float64
 10  Year built_Homes_1990-1999   58 non-null     float64
 11  Year built_Homes_2000-2009   0 non-null      float64
 12  Year built_Homes_2010-9999   0 non-null      float64
 13  Year built_Homes_2000-       58 non-null     float64
 14  Year built_People_Før 1940   58 non-null     float64
 15  Year built_People_1940-1959  58 non-null     float64
 16  Year built_People_1960-1969  58 non-null     float64
 17  Year built_People_1970-1979  58 non-null     float64
 18  Year built_People_1980-1989  58 non-null     float64
 19  Year built_People_1990-1999  58 non-null     float64
 20  Year built_People_2000-2009  0 non-null      float64
 21  Year built_People_2010-9999  0 non-null      float64
 22  Year built_People_2000-      58 non-null     float64
 23  Year built_Total people      58 non-null     float64
 24  Year built_Total homes       58 non-null     float64
dtypes: float64(20), object(5)
memory usage: 11.8+ KB
None

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Year built_Homes_Før 1940    58 non-null     float64
 6   Year built_Homes_1940-1959   58 non-null     float64
 7   Year built_Homes_1960-1969   58 non-null     float64
 8   Year built_Homes_1970-1979   58 non-null     float64
 9   Year built_Homes_1980-1989   58 non-null     float64
 10  Year built_Homes_1990-1999   58 non-null     float64
 11  Year built_Homes_2000-2009   0 non-null      float64
 12  Year built_Homes_2010-9999   0 non-null      float64
 13  Year built_Homes_2000-       58 non-null     float64
 14  Year built_People_Før 1940   58 non-null     float64
 15  Year built_People_1940-1959  58 non-null     float64
 16  Year built_People_1960-1969  58 non-null     float64
 17  Year built_People_1970-1979  58 non-null     float64
 18  Year built_People_1980-1989  58 non-null     float64
 19  Year built_People_1990-1999  58 non-null     float64
 20  Year built_People_2000-2009  0 non-null      float64
 21  Year built_People_2010-9999  0 non-null      float64
 22  Year built_People_2000-      58 non-null     float64
 23  Year built_Total people      58 non-null     float64
 24  Year built_Total homes       58 non-null     float64
dtypes: float64(20), object(5)
memory usage: 11.8+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Year built_Homes_Før 1940    58 non-null     float64
 6   Year built_Homes_1940-1959   58 non-null     float64
 7   Year built_Homes_1960-1969   58 non-null     float64
 8   Year built_Homes_1970-1979   58 non-null     float64
 9   Year built_Homes_1980-1989   58 non-null     float64
 10  Year built_Homes_1990-1999   58 non-null     float64
 11  Year built_Homes_2000-2009   58 non-null     float64
 12  Year built_Homes_2010-9999   58 non-null     float64
 13  Year built_Homes_2000-       0 non-null      float64
 14  Year built_People_Før 1940   58 non-null     float64
 15  Year built_People_1940-1959  58 non-null     float64
 16  Year built_People_1960-1969  58 non-null     float64
 17  Year built_People_1970-1979  58 non-null     float64
 18  Year built_People_1980-1989  58 non-null     float64
 19  Year built_People_1990-1999  58 non-null     float64
 20  Year built_People_2000-2009  58 non-null     float64
 21  Year built_People_2010-9999  58 non-null     float64
 22  Year built_People_2000-      0 non-null      float64
 23  Year built_Total people      58 non-null     float64
 24  Year built_Total homes       58 non-null     float64
dtypes: float64(20), object(5)
memory usage: 11.8+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Year built_Homes_Før 1940    58 non-null     float64
 6   Year built_Homes_1940-1959   58 non-null     float64
 7   Year built_Homes_1960-1969   58 non-null     float64
 8   Year built_Homes_1970-1979   58 non-null     float64
 9   Year built_Homes_1980-1989   58 non-null     float64
 10  Year built_Homes_1990-1999   58 non-null     float64
 11  Year built_Homes_2000-2009   58 non-null     float64
 12  Year built_Homes_2010-9999   58 non-null     float64
 13  Year built_Homes_2000-       0 non-null      float64
 14  Year built_People_Før 1940   58 non-null     float64
 15  Year built_People_1940-1959  58 non-null     float64
 16  Year built_People_1960-1969  58 non-null     float64
 17  Year built_People_1970-1979  58 non-null     float64
 18  Year built_People_1980-1989  58 non-null     float64
 19  Year built_People_1990-1999  58 non-null     float64
 20  Year built_People_2000-2009  58 non-null     float64
 21  Year built_People_2010-9999  58 non-null     float64
 22  Year built_People_2000-      0 non-null      float64
 23  Year built_Total people      58 non-null     float64
 24  Year built_Total homes       58 non-null     float64
dtypes: float64(20), object(5)
memory usage: 11.8+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Year built_Homes_Før 1940    58 non-null     int64
 6   Year built_Homes_1940-1959   58 non-null     float64
 7   Year built_Homes_1960-1969   58 non-null     float64
 8   Year built_Homes_1970-1979   58 non-null     float64
 9   Year built_Homes_1980-1989   58 non-null     float64
 10  Year built_Homes_1990-1999   58 non-null     float64
 11  Year built_Homes_2000-2009   58 non-null     float64
 12  Year built_Homes_2010-9999   58 non-null     float64
 13  Year built_Homes_2000-       0 non-null      float64
 14  Year built_People_Før 1940   58 non-null     int64
 15  Year built_People_1940-1959  58 non-null     float64
 16  Year built_People_1960-1969  58 non-null     float64
 17  Year built_People_1970-1979  58 non-null     float64
 18  Year built_People_1980-1989  58 non-null     float64
 19  Year built_People_1990-1999  58 non-null     float64
 20  Year built_People_2000-2009  58 non-null     float64
 21  Year built_People_2010-9999  58 non-null     float64
 22  Year built_People_2000-      0 non-null      float64
 23  Year built_Total people      58 non-null     float64
 24  Year built_Total homes       58 non-null     float64
dtypes: float64(18), int64(2), object(5)
memory usage: 11.8+ KB
None

In [43]:
builtyear_2021.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Gruppe                       58 non-null     object
 1   ValgstedId                   58 non-null     object
 2   KredsNr                      58 non-null     object
 3   StorKredsNr                  58 non-null     object
 4   LandsdelsNr                  58 non-null     object
 5   Year built_Homes_Før 1940    58 non-null     int64
 6   Year built_Homes_1940-1959   58 non-null     float64
 7   Year built_Homes_1960-1969   58 non-null     float64
 8   Year built_Homes_1970-1979   58 non-null     float64
 9   Year built_Homes_1980-1989   58 non-null     float64
 10  Year built_Homes_1990-1999   58 non-null     float64
 11  Year built_Homes_2000-2009   58 non-null     float64
 12  Year built_Homes_2010-9999   58 non-null     float64
 13  Year built_Homes_2000-       0 non-null      float64
 14  Year built_People_Før 1940   58 non-null     int64
 15  Year built_People_1940-1959  58 non-null     float64
 16  Year built_People_1960-1969  58 non-null     float64
 17  Year built_People_1970-1979  58 non-null     float64
 18  Year built_People_1980-1989  58 non-null     float64
 19  Year built_People_1990-1999  58 non-null     float64
 20  Year built_People_2000-2009  58 non-null     float64
 21  Year built_People_2010-9999  58 non-null     float64
 22  Year built_People_2000-      0 non-null      float64
 23  Year built_Total people      58 non-null     float64
 24  Year built_Total homes       58 non-null     float64
dtypes: float64(18), int64(2), object(5)
memory usage: 11.8+ KB

We want to split the columns into either two bins, three or four bins. For example 'before 1960', '1960-2010' and '2010-'

In [44]:
old_homes_cols = [
    'Year built_Homes_Før 1940',
    'Year built_Homes_1940-1959'
]
middle_homes_cols = [
    'Year built_Homes_1960-1969',
    'Year built_Homes_1970-1979',
    'Year built_Homes_1980-1989',    
    'Year built_Homes_1990-1999',
    'Year built_Homes_2000-2009',
]
old_people_cols = [
    'Year built_People_Før 1940',
    'Year built_People_1940-1959'
]
middle_people_cols = [
    'Year built_People_1960-1969',
    'Year built_People_1970-1979',
    'Year built_People_1980-1989',    
    'Year built_People_1990-1999',
    'Year built_People_2000-2009',
]

builtyear_2021["Year built_People_Before 1960"] = builtyear_2021[old_people_cols].sum(axis=1)
builtyear_2021["Year built_People_1960-2009"] = builtyear_2021[middle_people_cols].sum(axis=1)
builtyear_2021["Year built_Homes_Before 1960"] = builtyear_2021[old_homes_cols].sum(axis=1)
builtyear_2021["Year built_Homes_1960-2009"] = builtyear_2021[middle_homes_cols].sum(axis=1)

columns_to_keep = [
    "Gruppe",
    "ValgstedId",
    "KredsNr",
    "StorKredsNr",
    "LandsdelsNr",
    "Year built_People_Before 1960",
    "Year built_People_1960-2009",
    "Year built_Homes_Before 1960",
    "Year built_Homes_1960-2009",
    "Year built_People_2010-9999",
    "Year built_Homes_2010-9999",
    "Year built_Total people",
    "Year built_Total homes",
]

builtyear_2021 = builtyear_2021[columns_to_keep]

In [45]:
builtyear_2021.head(10)

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Year built_People_Before 1960,Year built_People_1960-2009,Year built_Homes_Before 1960,Year built_Homes_1960-2009,Year built_People_2010-9999,Year built_Homes_2010-9999,Year built_Total people,Year built_Total homes
0,101001,101001,1,1,1,13417.0,2055.0,6887.0,1117.0,90.0,40.0,15562.0,8044.0
1,101002,101002,1,1,1,6994.0,1235.0,3418.0,809.0,149.0,72.0,8378.0,4299.0
2,101003,101003,1,1,1,14942.0,904.0,7041.0,586.0,0.0,0.0,15846.0,7627.0
3,101005,101005,1,1,1,11810.0,3873.0,6119.0,2167.0,171.0,90.0,15854.0,8376.0
4,101006,101006,1,1,1,10028.0,3240.0,5283.0,1737.0,219.0,85.0,13487.0,7105.0
5,101007,101007,2,1,1,8275.0,5259.0,3950.0,2852.0,731.0,311.0,14265.0,7113.0
6,101008,101010;101008,2,1,1,19096.0,11105.0,9939.0,5533.0,3442.0,1289.0,33643.0,16761.0
7,101009,101009;101057,2,1,1,4452.0,13646.0,1659.0,6621.0,12964.0,5336.0,31062.0,13616.0
8,101011,101011,3,1,1,19560.0,690.0,7725.0,376.0,33.0,22.0,20283.0,8123.0
9,101012,101012,3,1,1,9040.0,136.0,4033.0,95.0,0.0,0.0,9176.0,4128.0

### Conclusion
Difference in data format: 2001, 2005 and 2009 used spaced, subsequent years use underscored.

It looks like the data for 2013 and 2017 is the same - do they have the same data? Check this. We should check this for other collected features as well.

Maybe we should only keep 2013, 2017 and 2021 - and if 2013 and 2017 are the same, then maybe only 2013 and 2021. Or just 2021? It is hard to compare across time since this column also is about time. Obviously, 2009 will not have any data on housing built after 2010.

# Combine everything

- socioeconomy
- citizenship (and age and sex)
- education
- immigrants
- tenure
- type
- simple (contains income, car, benefit type, arrests)
- builtyear (housing construction year)

In [46]:
names = [
    'socio',
    'citizenship',
    'immigrants',
    'education',
    'tenure',
    'type',
    'simple',
    'builtyear'
]
years = [2009, 2013, 2017, 2021]

combined_dfs = {}
for year in years:
    # start with first dataframe
    df_combined = globals()[f'{names[0]}_{year}'].copy()
    # merge subsequent dataframes
    for name in names[1:]:
        df_name = f'{name}_{year}'
        df_combined = df_combined.merge(
            globals()[df_name], 
            on=COMMON_COLS,
            how='outer',
            suffixes=('', f'_{name}')
        )
    combined_dfs[year] = df_combined

df_2009 = combined_dfs[2009]
df_2013 = combined_dfs[2013]
df_2017 = combined_dfs[2017]
df_2021 = combined_dfs[2021]

In [47]:
print(f"\n{'='*80}\n  2009\n")
print(df_2009.info())
print(f"\n{'='*80}\n  2013\n")
print(df_2013.info())
print(f"\n{'='*80}\n  2017\n")
print(df_2017.info())
print(f"\n{'='*80}\n  2021\n")
print(df_2021.info())

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Columns: 130 entries, Gruppe to Year built_Total homes
dtypes: float64(125), object(5)
memory usage: 64.1+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Columns: 130 entries, Gruppe to Year built_Total homes
dtypes: float64(125), object(5)
memory usage: 64.1+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Columns: 130 entries, Gruppe to Year built_Total homes
dtypes: float64(125), object(5)
memory usage: 64.1+ KB
None

================================================================================
  2021

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Columns: 118 entries, Gruppe to Year built_Total homes
dtypes: float64(113), object(5)
memory usage: 58.2+ KB
None

In [48]:
df_2021

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Socioeconomy_Self-employed,Socioeconomy_Top executives,Socioeconomy_Unemployed,Socioeconomy_Total,Sex_Male,...,Car_Households with 1 car,Car_Households with 2+ cars,Year built_People_Before 1960,Year built_People_1960-2009,Year built_Homes_Before 1960,Year built_Homes_1960-2009,Year built_People_2010-9999,Year built_Homes_2010-9999,Year built_Total people,Year built_Total homes
0,101001,101001,1,1,1,563.0,383.0,305.0,15540.0,7331.0,...,956.0,2032.0,13417.0,2055.0,6887.0,1117.0,90.0,40.0,15562.0,8044.0
1,101002,101002,1,1,1,357.0,221.0,137.0,8366.0,3908.0,...,658.0,1256.0,6994.0,1235.0,3418.0,809.0,149.0,72.0,8378.0,4299.0
2,101003,101003,1,1,1,632.0,401.0,277.0,15838.0,7640.0,...,807.0,2229.0,14942.0,904.0,7041.0,586.0,0.0,0.0,15846.0,7627.0
3,101005,101005,1,1,1,396.0,230.0,312.0,15817.0,7648.0,...,1057.0,1958.0,11810.0,3873.0,6119.0,2167.0,171.0,90.0,15854.0,8376.0
4,101006,101006,1,1,1,410.0,246.0,302.0,13473.0,6527.0,...,954.0,1802.0,10028.0,3240.0,5283.0,1737.0,219.0,85.0,13487.0,7105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,147004,147004,10,1,1,437.0,366.0,274.0,14633.0,6807.0,...,997.0,2273.0,10458.0,3690.0,5139.0,1896.0,428.0,354.0,14576.0,7389.0
59,147005,147005,11,1,1,383.0,287.0,302.0,14555.0,6845.0,...,1038.0,2092.0,10537.0,3303.0,5674.0,1874.0,445.0,301.0,14285.0,7849.0
60,147006,147006,11,1,1,344.0,250.0,202.0,12109.0,5532.0,...,1049.0,1960.0,8707.0,3142.0,4435.0,1999.0,289.0,262.0,12138.0,6696.0
61,147007,147007;147008,11,1,1,NaN,NaN,NaN,NaN,11310.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,147007,147008;147007,11,1,1,783.0,487.0,471.0,23847.0,NaN,...,1854.0,3570.0,18704.0,4957.0,9705.0,2891.0,129.0,69.0,23790.0,12665.0

In [49]:
common = df_2021[COMMON_COLS]
common.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gruppe       63 non-null     object
 1   ValgstedId   63 non-null     object
 2   KredsNr      63 non-null     object
 3   StorKredsNr  63 non-null     object
 4   LandsdelsNr  63 non-null     object
dtypes: object(5)
memory usage: 2.6+ KB

In [50]:
pd.set_option('display.max_rows', None)
print(df_2021[COMMON_COLS])
pd.reset_option('display.max_rows')

    Gruppe     ValgstedId KredsNr StorKredsNr LandsdelsNr
0   101001         101001       1           1           1
1   101002         101002       1           1           1
2   101003         101003       1           1           1
3   101005         101005       1           1           1
4   101006         101006       1           1           1
5   101007         101007       2           1           1
6   101008  101008;101010       2           1           1
7   101008  101010;101008       2           1           1
8   101009         101009       2           1           1
9   101009  101009;101057       2           1           1
10  101009  101057;101009       2           1           1
11  101011         101011       3           1           1
12  101012         101012       3           1           1
13  101013         101013       3           1           1
14  101014         101014       3           1           1
15  101014  101057;101014     2;3           1           1
16  101016         101016       4           1           1
17  101017         101017       4           1           1
18  101018         101018       4           1           1
19  101019         101019       4           1           1
20  101020         101020       5           1           1
21  101021         101021       5           1           1
22  101022         101022       5           1           1
23  101023         101023       5           1           1
24  101024         101024       5           1           1
25  101025         101025       5           1           1
26  101027         101027       6           1           1
27  101028         101028       6           1           1
28  101029         101029       6           1           1
29  101030         101030       6           1           1
30  101031         101031       7           1           1
31  101032         101032       7           1           1
32  101033         101033       7           1           1
33  101034         101034       7           1           1
34  101035         101035       7           1           1
35  101036         101036       7           1           1
36  101039         101039       7           1           1
37  101040         101040       7           1           1
38  101041         101041       7           1           1
39  101042         101042       8           1           1
40  101043         101043       8           1           1
41  101044         101044       8           1           1
42  101046         101046       8           1           1
43  101047         101047       8           1           1
44  101048         101048       8           1           1
45  101049         101049       9           1           1
46  101050         101050       9           1           1
47  101051         101051       9           1           1
48  101052         101052       9           1           1
49  101053         101053       9           1           1
50  101054         101054       9           1           1
51  101055         101055       9           1           1
52  101056         101056       1           1           1
53  101058         101058       5           1           1
54  101059         101059       6           1           1
55  147001         147001      10           1           1
56  147002         147002      10           1           1
57  147003         147003      10           1           1
58  147004         147004      10           1           1
59  147005         147005      11           1           1
60  147006         147006      11           1           1
61  147007  147007;147008      11           1           1
62  147007  147008;147007      11           1           1

There are duplicate 'Gruppe' values - we only want 58 rows, but we get 63, because we're merging on several common columns, and some of them are different. It is only the CSV 'PersonsBySocioeconomyIndustry.csv' that is causing some of them being different, I think. We'll merge just on 'Gruppe' instead, and then deal with duplicate common columns after.

In [51]:
names = [
    'socio',
    'citizenship',
    'immigrants',
    'education',
    'tenure',
    'type',
    'simple',
    'builtyear'
]
years = [2009, 2013, 2017, 2021]

combined_dfs = {}
for year in years:
    # start with first dataframe
    df_combined = globals()[f'{names[0]}_{year}'].copy()
    # merge subsequent dataframes
    for name in names[1:]:
        df_name = f'{name}_{year}'
        df_combined = df_combined.merge(
            globals()[df_name], 
            on='Gruppe',
            how='outer',
            suffixes=('', f'_{name}')
        )
    combined_dfs[year] = df_combined

df_2009 = combined_dfs[2009]
df_2013 = combined_dfs[2013]
df_2017 = combined_dfs[2017]
df_2021 = combined_dfs[2021]

print(f"df_2021 shape: {df_2021.shape}")
print(f"Unique Gruppe values: {df_2021['Gruppe'].nunique()}")

df_2021 shape: (58, 146)
Unique Gruppe values: 58

In [52]:
print(df_2021.columns)

Index(['Gruppe', 'ValgstedId', 'KredsNr', 'StorKredsNr', 'LandsdelsNr',
       'Socioeconomy_Self-employed', 'Socioeconomy_Top executives',
       'Socioeconomy_Unemployed', 'Socioeconomy_Total',
       'ValgstedId_citizenship',
       ...
       'StorKredsNr_builtyear', 'LandsdelsNr_builtyear',
       'Year built_People_Before 1960', 'Year built_People_1960-2009',
       'Year built_Homes_Before 1960', 'Year built_Homes_1960-2009',
       'Year built_People_2010-9999', 'Year built_Homes_2010-9999',
       'Year built_Total people', 'Year built_Total homes'],
      dtype='object', length=146)

In [53]:
# Remove duplicate common columns
for year in years:
    df = combined_dfs[year]
    
    # Keep only the first occurrence of each common column
    cols_to_drop = [col for col in df.columns 
                    if any(col.startswith(f'{common}_') 
                          for common in ['ValgstedId', 'KredsNr', 'StorKredsNr', 'LandsdelsNr'])]
    df = df.drop(columns=cols_to_drop)
    combined_dfs[year] = df

df_2009, df_2013, df_2017, df_2021 = [combined_dfs[year] for year in years]

In [54]:
print(f"\n{'='*80}\n  2009\n")
print(df_2009.info(verbose=True, show_counts=True))
print(f"\n{'='*80}\n  2013\n")
print(df_2013.info(verbose=True, show_counts=True))
print(f"\n{'='*80}\n  2017\n")
print(df_2017.info(verbose=True, show_counts=True))
print(f"\n{'='*80}\n  2021\n")
print(df_2021.info(verbose=True, show_counts=True))

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 130 columns):
 #    Column                                              Non-Null Count  Dtype
---   ------                                              --------------  -----
 0    Gruppe                                              58 non-null     object
 1    ValgstedId                                          58 non-null     object
 2    KredsNr                                             58 non-null     object
 3    StorKredsNr                                         58 non-null     object
 4    LandsdelsNr                                         58 non-null     object
 5    Socioeconomy_Self-employed                          58 non-null     float64
 6    Socioeconomy_Top executives                         58 non-null     float64
 7    Socioeconomy_Unemployed                             58 non-null     float64
 8    Socioeconomy_Total                                  58 non-null     float64
 9    Sex_Male                                            58 non-null     float64
 10   Sex_Female                                          58 non-null     float64
 11   Age_0-4 years                                       58 non-null     float64
 12   Age_5-9 years                                       58 non-null     float64
 13   Age_10-14 years                                     58 non-null     float64
 14   Age_15-17 years                                     58 non-null     float64
 15   Age_18-19 years                                     58 non-null     float64
 16   Age_20-24 years                                     58 non-null     float64
 17   Age_25-29 years                                     58 non-null     float64
 18   Age_30-34 years                                     58 non-null     float64
 19   Age_35-39 years                                     58 non-null     float64
 20   Age_40-44 years                                     58 non-null     float64
 21   Age_45-49 years                                     58 non-null     float64
 22   Age_50-54 years                                     58 non-null     float64
 23   Age_55-59 years                                     58 non-null     float64
 24   Age_60-64 years                                     58 non-null     float64
 25   Age_65-69 years                                     58 non-null     float64
 26   Age_70- years                                       58 non-null     float64
 27   Citizenship_Denmark                                 58 non-null     float64
 28   Citizenship_Nordic                                  58 non-null     float64
 29   Citizenship_Turkey                                  58 non-null     float64
 30   Citizenship_Former Yugoslavia                       58 non-null     float64
 31   Citizenship_Old EU countries                        58 non-null     float64
 32   Citizenship_New EU countries                        58 non-null     float64
 33   Citizenship_Other Europe                            58 non-null     float64
 34   Citizenship_Africa                                  58 non-null     float64
 35   Citizenship_North America                           58 non-null     float64
 36   Citizenship_South and Central America               58 non-null     float64
 37   Citizenship_Asia and Oceania                        58 non-null     float64
 38   Citizenship_Not specified                           0 non-null      float64
 39   Citizenship_Total                                   58 non-null     float64
 40   Immigrants_Denmark                                  0 non-null      float64
 41   Immigrants_Nordic                                   58 non-null     float64
 42   Immigrants_Turkey                                   58 non-null     float64
 43   Immigrants_Former Yugoslavia                        58 non-null     float64
 44   Immigrants_Old EU countries                         58 non-null     float64
 45   Immigrants_New EU countries                         58 non-null     float64
 46   Immigrants_Other Europe                             58 non-null     float64
 47   Immigrants_Africa                                   58 non-null     float64
 48   Immigrants_North America                            58 non-null     float64
 49   Immigrants_South and Central America                58 non-null     float64
 50   Immigrants_Asia and Oceania                         58 non-null     float64
 51   Immigrants_Not specified                            58 non-null     float64
 52   Immigrants_Total                                    58 non-null     float64
 53   Education_18-29 years_Primary and lower secondary   58 non-null     float64
 54   Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 55   Education_18-29 years_General upper secondary       58 non-null     float64
 56   Education_30-70+ years_General upper secondary      58 non-null     float64
 57   Education_18-29 years_Vocational upper secondary    58 non-null     float64
 58   Education_30-70+ years_Vocational upper secondary   58 non-null     float64
 59   Education_18-29 years_Vocational training           58 non-null     float64
 60   Education_30-70+ years_Vocational training          58 non-null     float64
 61   Education_18-29 years_Short higher education        58 non-null     float64
 62   Education_30-70+ years_Short higher education       58 non-null     float64
 63   Education_18-29 years_Medium higher education       58 non-null     float64
 64   Education_30-70+ years_Medium higher education      58 non-null     float64
 65   Education_18-29 years_Long higher education         58 non-null     float64
 66   Education_30-70+ years_Long higher education        58 non-null     float64
 67   Education_18-29 years_Not specified                 58 non-null     float64
 68   Education_30-70+ years_Not specified                58 non-null     float64
 69   Education_Total 18-29 years                         58 non-null     float64
 70   Education_Total 30-70+ years                        58 non-null     float64
 71   Education_Total                                     58 non-null     float64
 72   Housing tenure_Homes_Ejer                           58 non-null     float64
 73   Housing tenure_Homes_Andel                          58 non-null     float64
 74   Housing tenure_Homes_Almen                          58 non-null     float64
 75   Housing tenure_Homes_Private rental                 58 non-null     float64
 76   Housing tenure_People_Ejer                          58 non-null     float64
 77   Housing tenure_People_Andel                         58 non-null     float64
 78   Housing tenure_People_Almen                         58 non-null     float64
 79   Housing tenure_People_Private rental                58 non-null     float64
 80   Housing tenure_Total people                         58 non-null     float64
 81   Housing tenure_Total homes                          58 non-null     float64
 82   Housing type_Homes_Detached house                   58 non-null     float64
 83   Housing type_Homes_Terraced house                   58 non-null     float64
 84   Housing type_Homes_Apartment buildings              58 non-null     float64
 85   Housing type_Homes_Student halls                    58 non-null     float64
 86   Housing type_Homes_Holiday homes                    58 non-null     float64
 87   Housing type_Homes_Other homes                      58 non-null     float64
 88   Housing type_Homes_No BBR information               0 non-null      float64
 89   Housing type_People_Detached house                  58 non-null     float64
 90   Housing type_People_Terraced house                  58 non-null     float64
 91   Housing type_People_Apartment buildings             58 non-null     float64
 92   Housing type_People_Student halls                   58 non-null     float64
 93   Housing type_People_Holiday homes                   58 non-null     float64
 94   Housing type_People_Other homes                     58 non-null     float64
 95   Housing type_People_No BBR information              0 non-null      float64
 96   Housing type_Total people                           58 non-null     float64
 97   Housing type_Total homes                            58 non-null     float64
 98   Benefit type_Kontanthjaelp                          58 non-null     float64
 99   Benefit type_Foertidspension                        58 non-null     float64
 100  Benefit type_Folkepension                           58 non-null     float64
 101  Benefit type_Modtager ikke ydelser                  58 non-null     float64
 102  Benefit type_Antal personer i alt                   58 non-null     float64
 103  Crime_Number of arrests                             0 non-null      float64
 104  Income_Median household income                      58 non-null     float64
 105  Income_Total households                             58 non-null     float64
 106  Income_Gross income top20pct                        58 non-null     float64
 107  Car_Households with no car                          58 non-null     float64
 108  Car_Households with 1 car                           58 non-null     float64
 109  Car_Households with 2+ cars                         58 non-null     float64
 110  Year built_Homes_Før 1940                           58 non-null     float64
 111  Year built_Homes_1940-1959                          58 non-null     float64
 112  Year built_Homes_1960-1969                          58 non-null     float64
 113  Year built_Homes_1970-1979                          58 non-null     float64
 114  Year built_Homes_1980-1989                          58 non-null     float64
 115  Year built_Homes_1990-1999                          58 non-null     float64
 116  Year built_Homes_2000-2009                          0 non-null      float64
 117  Year built_Homes_2010-9999                          0 non-null      float64
 118  Year built_Homes_2000-                              58 non-null     float64
 119  Year built_People_Før 1940                          58 non-null     float64
 120  Year built_People_1940-1959                         58 non-null     float64
 121  Year built_People_1960-1969                         58 non-null     float64
 122  Year built_People_1970-1979                         58 non-null     float64
 123  Year built_People_1980-1989                         58 non-null     float64
 124  Year built_People_1990-1999                         58 non-null     float64
 125  Year built_People_2000-2009                         0 non-null      float64
 126  Year built_People_2010-9999                         0 non-null      float64
 127  Year built_People_2000-                             58 non-null     float64
 128  Year built_Total people                             58 non-null     float64
 129  Year built_Total homes                              58 non-null     float64
dtypes: float64(125), object(5)
memory usage: 59.0+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 130 columns):
 #    Column                                              Non-Null Count  Dtype
---   ------                                              --------------  -----
 0    Gruppe                                              58 non-null     object
 1    ValgstedId                                          58 non-null     object
 2    KredsNr                                             58 non-null     object
 3    StorKredsNr                                         58 non-null     object
 4    LandsdelsNr                                         58 non-null     object
 5    Socioeconomy_Self-employed                          58 non-null     float64
 6    Socioeconomy_Top executives                         58 non-null     float64
 7    Socioeconomy_Unemployed                             58 non-null     float64
 8    Socioeconomy_Total                                  58 non-null     float64
 9    Sex_Male                                            58 non-null     float64
 10   Sex_Female                                          58 non-null     float64
 11   Age_0-4 years                                       58 non-null     float64
 12   Age_5-9 years                                       58 non-null     float64
 13   Age_10-14 years                                     58 non-null     float64
 14   Age_15-17 years                                     58 non-null     float64
 15   Age_18-19 years                                     58 non-null     float64
 16   Age_20-24 years                                     58 non-null     float64
 17   Age_25-29 years                                     58 non-null     float64
 18   Age_30-34 years                                     58 non-null     float64
 19   Age_35-39 years                                     58 non-null     float64
 20   Age_40-44 years                                     58 non-null     float64
 21   Age_45-49 years                                     58 non-null     float64
 22   Age_50-54 years                                     58 non-null     float64
 23   Age_55-59 years                                     58 non-null     float64
 24   Age_60-64 years                                     58 non-null     float64
 25   Age_65-69 years                                     58 non-null     float64
 26   Age_70- years                                       58 non-null     float64
 27   Citizenship_Denmark                                 58 non-null     float64
 28   Citizenship_Nordic                                  58 non-null     float64
 29   Citizenship_Turkey                                  58 non-null     float64
 30   Citizenship_Former Yugoslavia                       58 non-null     float64
 31   Citizenship_Old EU countries                        58 non-null     float64
 32   Citizenship_New EU countries                        58 non-null     float64
 33   Citizenship_Other Europe                            58 non-null     float64
 34   Citizenship_Africa                                  58 non-null     float64
 35   Citizenship_North America                           58 non-null     float64
 36   Citizenship_South and Central America               58 non-null     float64
 37   Citizenship_Asia and Oceania                        58 non-null     float64
 38   Citizenship_Not specified                           58 non-null     float64
 39   Citizenship_Total                                   58 non-null     float64
 40   Immigrants_Denmark                                  0 non-null      float64
 41   Immigrants_Nordic                                   58 non-null     float64
 42   Immigrants_Turkey                                   58 non-null     float64
 43   Immigrants_Former Yugoslavia                        58 non-null     float64
 44   Immigrants_Old EU countries                         58 non-null     float64
 45   Immigrants_New EU countries                         58 non-null     float64
 46   Immigrants_Other Europe                             58 non-null     float64
 47   Immigrants_Africa                                   58 non-null     float64
 48   Immigrants_North America                            58 non-null     float64
 49   Immigrants_South and Central America                58 non-null     float64
 50   Immigrants_Asia and Oceania                         58 non-null     float64
 51   Immigrants_Not specified                            58 non-null     float64
 52   Immigrants_Total                                    58 non-null     float64
 53   Education_18-29 years_Primary and lower secondary   58 non-null     float64
 54   Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 55   Education_18-29 years_General upper secondary       58 non-null     float64
 56   Education_30-70+ years_General upper secondary      58 non-null     float64
 57   Education_18-29 years_Vocational upper secondary    58 non-null     float64
 58   Education_30-70+ years_Vocational upper secondary   58 non-null     float64
 59   Education_18-29 years_Vocational training           58 non-null     float64
 60   Education_30-70+ years_Vocational training          58 non-null     float64
 61   Education_18-29 years_Short higher education        58 non-null     float64
 62   Education_30-70+ years_Short higher education       58 non-null     float64
 63   Education_18-29 years_Medium higher education       58 non-null     float64
 64   Education_30-70+ years_Medium higher education      58 non-null     float64
 65   Education_18-29 years_Long higher education         58 non-null     float64
 66   Education_30-70+ years_Long higher education        58 non-null     float64
 67   Education_18-29 years_Not specified                 58 non-null     float64
 68   Education_30-70+ years_Not specified                58 non-null     float64
 69   Education_Total 18-29 years                         58 non-null     float64
 70   Education_Total 30-70+ years                        58 non-null     float64
 71   Education_Total                                     58 non-null     float64
 72   Housing tenure_Homes_Ejer                           58 non-null     float64
 73   Housing tenure_Homes_Andel                          58 non-null     float64
 74   Housing tenure_Homes_Almen                          58 non-null     float64
 75   Housing tenure_Homes_Private rental                 58 non-null     float64
 76   Housing tenure_People_Ejer                          58 non-null     float64
 77   Housing tenure_People_Andel                         58 non-null     float64
 78   Housing tenure_People_Almen                         58 non-null     float64
 79   Housing tenure_People_Private rental                58 non-null     float64
 80   Housing tenure_Total people                         58 non-null     float64
 81   Housing tenure_Total homes                          58 non-null     float64
 82   Housing type_Homes_Detached house                   58 non-null     float64
 83   Housing type_Homes_Terraced house                   58 non-null     float64
 84   Housing type_Homes_Apartment buildings              58 non-null     float64
 85   Housing type_Homes_Student halls                    58 non-null     float64
 86   Housing type_Homes_Holiday homes                    58 non-null     float64
 87   Housing type_Homes_Other homes                      58 non-null     float64
 88   Housing type_Homes_No BBR information               0 non-null      float64
 89   Housing type_People_Detached house                  58 non-null     float64
 90   Housing type_People_Terraced house                  58 non-null     float64
 91   Housing type_People_Apartment buildings             58 non-null     float64
 92   Housing type_People_Student halls                   58 non-null     float64
 93   Housing type_People_Holiday homes                   58 non-null     float64
 94   Housing type_People_Other homes                     58 non-null     float64
 95   Housing type_People_No BBR information              0 non-null      float64
 96   Housing type_Total people                           58 non-null     float64
 97   Housing type_Total homes                            58 non-null     float64
 98   Benefit type_Kontanthjaelp                          58 non-null     float64
 99   Benefit type_Foertidspension                        58 non-null     float64
 100  Benefit type_Folkepension                           58 non-null     float64
 101  Benefit type_Modtager ikke ydelser                  58 non-null     float64
 102  Benefit type_Antal personer i alt                   58 non-null     float64
 103  Crime_Number of arrests                             58 non-null     float64

In [55]:
df_2021

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,Socioeconomy_Self-employed,Socioeconomy_Top executives,Socioeconomy_Unemployed,Socioeconomy_Total,Sex_Male,...,Car_Households with 1 car,Car_Households with 2+ cars,Year built_People_Before 1960,Year built_People_1960-2009,Year built_Homes_Before 1960,Year built_Homes_1960-2009,Year built_People_2010-9999,Year built_Homes_2010-9999,Year built_Total people,Year built_Total homes
0,101001,101001,1,1,1,563.0,383.0,305.0,15540.0,7331.0,...,956,2032,13417.0,2055.0,6887.0,1117.0,90.0,40.0,15562.0,8044.0
1,101002,101002,1,1,1,357.0,221.0,137.0,8366.0,3908.0,...,658,1256,6994.0,1235.0,3418.0,809.0,149.0,72.0,8378.0,4299.0
2,101003,101003,1,1,1,632.0,401.0,277.0,15838.0,7640.0,...,807,2229,14942.0,904.0,7041.0,586.0,0.0,0.0,15846.0,7627.0
3,101005,101005,1,1,1,396.0,230.0,312.0,15817.0,7648.0,...,1057,1958,11810.0,3873.0,6119.0,2167.0,171.0,90.0,15854.0,8376.0
4,101006,101006,1,1,1,410.0,246.0,302.0,13473.0,6527.0,...,954,1802,10028.0,3240.0,5283.0,1737.0,219.0,85.0,13487.0,7105.0
5,101007,101007,2,1,1,377.0,202.0,293.0,14229.0,6970.0,...,856,2084,8275.0,5259.0,3950.0,2852.0,731.0,311.0,14265.0,7113.0
6,101008,101010;101008,2,1,1,1023.0,836.0,782.0,33823.0,16468.0,...,2049,4675,19096.0,11105.0,9939.0,5533.0,3442.0,1289.0,33643.0,16761.0
7,101009,101009,2,1,1,441.0,342.0,365.0,19097.0,15617.0,...,1193,4259,4452.0,13646.0,1659.0,6621.0,12964.0,5336.0,31062.0,13616.0
8,101011,101011,3,1,1,1062.0,520.0,381.0,20738.0,10914.0,...,916,1838,19560.0,690.0,7725.0,376.0,33.0,22.0,20283.0,8123.0
9,101012,101012,3,1,1,479.0,341.0,154.0,9173.0,4431.0,...,518,1565,9040.0,136.0,4033.0,95.0,0.0,0.0,9176.0,4128.0
10,101013,101013,3,1,1,673.0,355.0,259.0,13247.0,6582.0,...,836,1837,7759.0,3340.0,4091.0,1762.0,2116.0,756.0,13215.0,6609.0
11,101014,101057;101014,2;3,1,1,1215.0,692.0,459.0,28789.0,8134.0,...,1189,2273,15018.0,1673.0,7640.0,1178.0,23.0,11.0,16714.0,8829.0
12,101016,101016,4,1,1,380.0,229.0,346.0,14499.0,7069.0,...,889,1813,9981.0,2458.0,5470.0,1219.0,2119.0,863.0,14558.0,7552.0
13,101017,101017,4,1,1,530.0,217.0,504.0,20662.0,10080.0,...,1183,2177,14958.0,5140.0,8201.0,2721.0,505.0,196.0,20603.0,11118.0
14,101018,101018,4,1,1,302.0,202.0,249.0,11261.0,5654.0,...,800,1650,10571.0,619.0,5528.0,316.0,91.0,29.0,11281.0,5873.0
15,101019,101019,4,1,1,401.0,399.0,234.0,13370.0,6689.0,...,788,2449,8477.0,2815.0,3842.0,1390.0,2066.0,792.0,13358.0,6024.0
16,101020,101020,5,1,1,274.0,95.0,246.0,9044.0,4319.0,...,451,824,8470.0,637.0,4594.0,325.0,41.0,14.0,9148.0,4933.0
17,101021,101021,5,1,1,382.0,107.0,400.0,13706.0,6719.0,...,664,1151,9396.0,4116.0,5199.0,2348.0,239.0,167.0,13751.0,7714.0
18,101022,101022,5,1,1,349.0,118.0,243.0,8854.0,4284.0,...,367,908,5725.0,3051.0,2745.0,1259.0,33.0,10.0,8809.0,4014.0
19,101023,101023,5,1,1,461.0,157.0,259.0,9391.0,4507.0,...,438,921,8404.0,958.0,4019.0,647.0,21.0,8.0,9383.0,4674.0
20,101024,101024,5,1,1,305.0,134.0,308.0,10000.0,4837.0,...,485,1099,8624.0,1368.0,4260.0,529.0,0.0,0.0,9992.0,4789.0
21,101025,101025,5,1,1,537.0,128.0,461.0,14118.0,6835.0,...,648,1286,11592.0,2353.0,5972.0,1151.0,163.0,62.0,14108.0,7185.0
22,101027,101027,6,1,1,411.0,131.0,546.0,15625.0,7906.0,...,958,1417,11642.0,3267.0,6610.0,1458.0,816.0,404.0,15725.0,8472.0
23,101028,101028,6,1,1,293.0,159.0,231.0,10712.0,5369.0,...,760,1499,9359.0,1242.0,4997.0,617.0,77.0,21.0,10678.0,5635.0
24,101029,101029,6,1,1,143.0,68.0,143.0,6129.0,2967.0,...,408,831,5006.0,1059.0,2645.0,560.0,55.0,16.0,6120.0,3221.0
25,101030,101030,6,1,1,356.0,99.0,462.0,13679.0,6951.0,...,799,1240,11150.0,2145.0,5990.0,1030.0,438.0,230.0,13733.0,7250.0
26,101031,101031,7,1,1,171.0,130.0,84.0,5394.0,2612.0,...,376,1031,5062.0,243.0,2341.0,130.0,89.0,26.0,5394.0,2497.0
27,101032,101032,7,1,1,142.0,6.0,208.0,6721.0,3338.0,...,236,877,1997.0,4721.0,701.0,1909.0,0.0,0.0,6718.0,2610.0
28,101033,101033,7,1,1,264.0,176.0,228.0,9978.0,4895.0,...,701,1606,8849.0,779.0,4413.0,400.0,440.0,209.0,10068.0,5022.0
29,101034,101034,7,1,1,341.0,227.0,261.0,12647.0,6224.0,...,739,2111,11661.0,602.0,5164.0,327.0,385.0,139.0,12648.0,5630.0
30,101035,101035,7,1,1,264.0,129.0,198.0,10279.0,5076.0,...,633,1636,7701.0,2461.0,3614.0,1260.0,98.0,43.0,10260.0,4917.0
31,101036,101036,7,1,1,345.0,225.0,244.0,12571.0,6261.0,...,604,2470,10513.0,1736.0,4566.0,646.0,323.0,82.0,12572.0,5294.0
32,101039,101039,7,1,1,159.0,113.0,124.0,6215.0,3083.0,...,519,868,5488.0,276.0,2970.0,174.0,466.0,197.0,6230.0,3341.0
33,101040,101040,7,1,1,245.0,205.0,134.0,7901.0,3992.0,...,366,1585,6572.0,1054.0,2500.0,452.0,288.0,105.0,7914.0,3057.0
34,101041,101041,7,1,1,361.0,268.0,288.0,14185.0,6789.0,...,1059,2140,11421.0,2504.0,6023.0,1259.0,249.0,112.0,14174.0,7394.0
35,101042,101042,8,1,1,334.0,255.0,214.0,11850.0,5765.0,...,713,1984,10217.0,1547.0,4808.0,583.0,89.0,24.0,11853.0,5415.0
36,101043,101043,8,1,1,350.0,198.0,268.0,12064.0,5908.0,...,833,1560,9952.0,1768.0,5167.0,890.0,349.0,170.0,12069.0,6227.0
37,101044,101044,8,1,1,262.0,140.0,226.0,10304.0,5252.0,...,597,1591,4720.0,2988.0,2290.0,1454.0,2852.0,1132.0,10560.0,4876.0
38,101046,101046,8,1,1,142.0,94.0,190.0,7512.0,3897.0,...,510,1146,4695.0,2718.0,2307.0,1256.0,128.0,77.0,7541.0,3640.0
39,101047,101047,8,1,1,214.0,103.0,178.0,7159.0,3477.0,...,331,1000,3360.0,2184.0,1510.0,973.0,1642.0,835.0,7186.0,3318.0
40,101048,101048,8,1,1,229.0,203.0,250.0,11089.0,5511.0,...,627,1440,6286.0,1520.0,3283.0,684.0,3289.0,1401.0,11095.0,5368.0
41,101049,101049,9,1,1,450.0,185.0,283.0,10119.0,4986.0,...,538,1125,10132.0,0.0,4903.0,0.0,0.0,0.0,10132.0,4903.0
42,101050,101050,9,1,1,522.0,242.0,331.0,11762.0,5824.0,...,592,1231,10327.0,1417.0,4948.0,770.0,0.0,0.0,11744.0,5718.0
43,101051,101051,9,1,1,294.0,101.0,366.0,12049.0,6023.0,...,807,1303,10076.0,1800.0,5928.0,848.0,172.0,101.0,12048.0,6877.0
44,101052,101052,9,1,1,443.0,217.0,222.0,9279.0,4628.0,...,440,955,8398.0,765.0,3890.0,410.0,106.0,49.0,9269.0,4349.0
45,101053,101053,9,1,1,348.0,210.0,194.0,9305.0,4600.0,...,419,1206,7410.0,706.0,3447.0,364.0,1253.0,505.0,9369.0,4316.0
46,101054,101054,9,1,1,99.0,19.0,119.0,4284.0,2396.0,...,251,289,4265.0,4.0,2633.0,1.0,199.0,1.0,4468.0,2635.0
47,101055,101055,9,1,1,506.0,487.0,326.0,15477.0,8210.0,...,775,2247,1091.0,5356.0,577.0,2418.0,9209.0,3810.0,15656.0,6805.0
48,101056,101056,1,1,1,370.0,388.0,175.0,10617.0,5249.0,...,690,1665,5865.0,2100.0,3018.0,1125.0,2708.0,1178.0,10673.0,5321.0
49,101058,101058,5,1,1,394.0,111.0,435.0,15004.0,7202.0,...,655,1484,8231.0,6466.0,4469.0,2606.0,363.0,139.0,15060.0,7214.0
50,101059,101059,6,1,1,220.0,75.0,264.0,8843.0,4500.0,...,486,1112,7469.0,1249.0,3663.0,516.0,189.0,52.0,8907.0,4231.0
51,147001,147001,10,1,1,543.0,394.0,186.0,11939.0,5727.0,...,758,2118,10173.0,1744.0,4470.0,1003.0,0.0,0.0,11917.0,5473.0
52,147002,147002,10,1,1,548.0,422.0,153.0,11810.0,5804.0,...,857,2199,9991.0,1808.0,4549.0,1098.0,61.0,33.0,11860.0,5680.0
53,147003,147003,10,1,1,566.0,398.0,281.0,15733.0,7495.0,...,1037,2467,14119.0,1426.0,6776.0,947.0,194.0,120.0,15739.0,7843.0
54,147004,147004,10,1,1,437.0,366.0,274.0,14633.0,6807.0,...,997,2273,10458.0,3690.0,5139.0,1896.0,428.0,354.0,14576.0,7389.0
55,147005,147005,11,1,1,383.0,287.0,302.0,14555.0,6845.0,...,1038,2092,10537.0,3303.0,5674.0,1874.0,445.0,301.0,14285.0,7849.0
56,147006,147006,11,1,1,344.0,250.0,202.0,12109.0,5532.0,...,1049,1960,8707.0,3142.0,4435.0,1999.0,289.0,262.0,12138.0,6696.0
57,147007,147008;147007,11,1,1,783.0,487.0,471.0,23847.0,11310.0,...,1854,3570,18704.0,4957.0,9705.0,2891.0,129.0,69.0,23790.0,12665.0

## Drop columns

Now, we want to drop some columns:

- All 'Year built_[...]' columns for years 2009, 2013, 2017
- All columns with 0 non-null entries.
- All 'Education_[...]' columns that end with 'Medium higher education', 'Short higher education', 'Vocational upper secondary', 'General upper secondary' (keep all others).
- All 'Housing type_[...]' columns that don't end with 'Detached house', 'Terraced house' or 'Apartment buildings'

In [56]:
for year in years:
    df = combined_dfs[year]
    cols_to_drop = []
    
    # 1. Drop 'Year built_[...]' columns for 2009, 2013, 2017 (but not 2021)
    if year != 2021:
        cols_to_drop.extend([col for col in df.columns if col.startswith('Year built_')])
    
    # 2. Drop columns with 0 non-null entries
    cols_to_drop.extend([col for col in df.columns if df[col].notna().sum() == 0])

    # 3. Drop specific Education columns for all years
    education_suffixes = [
        'Medium higher education',
        'Short higher education',
        'Vocational upper secondary',
        'General upper secondary'
    ]
    cols_to_drop.extend([col for col in df.columns 
                        if col.startswith('Education_') and 
                        any(col.endswith(suffix) for suffix in education_suffixes)])
    
    # 3. Drop specific Housing type columns for all years
    housing_suffixes = [
        'Student halls',
        'Holiday homes',
        'Other homes',
    ]
    cols_to_drop.extend([col for col in df.columns 
                        if col.startswith('Housing type_') and 
                        any(col.endswith(suffix) for suffix in housing_suffixes)])
    
    # Remove duplicates and drop
    cols_to_drop = list(set(cols_to_drop))
    df = df.drop(columns=cols_to_drop)
    combined_dfs[year] = df

    print(f"Dropped {len(cols_to_drop)} columns from {year}, remaining: {df.shape[1]}")

# Reassign the cleaned dataframes
df_2009, df_2013, df_2017, df_2021 = [combined_dfs[year] for year in years]

Dropped 39 columns from 2009, remaining: 91
Dropped 37 columns from 2013, remaining: 93
Dropped 37 columns from 2017, remaining: 93
Dropped 17 columns from 2021, remaining: 101

In [57]:
print(f"\n{'='*80}\n  2009\n")
print(df_2009.info(verbose=True, show_counts=True))
print(f"\n{'='*80}\n  2013\n")
print(df_2013.info(verbose=True, show_counts=True))
print(f"\n{'='*80}\n  2017\n")
print(df_2017.info(verbose=True, show_counts=True))
print(f"\n{'='*80}\n  2021\n")
print(df_2021.info(verbose=True, show_counts=True))

================================================================================
  2009

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 91 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Socioeconomy_Self-employed                          58 non-null     float64
 6   Socioeconomy_Top executives                         58 non-null     float64
 7   Socioeconomy_Unemployed                             58 non-null     float64
 8   Socioeconomy_Total                                  58 non-null     float64
 9   Sex_Male                                            58 non-null     float64
 10  Sex_Female                                          58 non-null     float64
 11  Age_0-4 years                                       58 non-null     float64
 12  Age_5-9 years                                       58 non-null     float64
 13  Age_10-14 years                                     58 non-null     float64
 14  Age_15-17 years                                     58 non-null     float64
 15  Age_18-19 years                                     58 non-null     float64
 16  Age_20-24 years                                     58 non-null     float64
 17  Age_25-29 years                                     58 non-null     float64
 18  Age_30-34 years                                     58 non-null     float64
 19  Age_35-39 years                                     58 non-null     float64
 20  Age_40-44 years                                     58 non-null     float64
 21  Age_45-49 years                                     58 non-null     float64
 22  Age_50-54 years                                     58 non-null     float64
 23  Age_55-59 years                                     58 non-null     float64
 24  Age_60-64 years                                     58 non-null     float64
 25  Age_65-69 years                                     58 non-null     float64
 26  Age_70- years                                       58 non-null     float64
 27  Citizenship_Denmark                                 58 non-null     float64
 28  Citizenship_Nordic                                  58 non-null     float64
 29  Citizenship_Turkey                                  58 non-null     float64
 30  Citizenship_Former Yugoslavia                       58 non-null     float64
 31  Citizenship_Old EU countries                        58 non-null     float64
 32  Citizenship_New EU countries                        58 non-null     float64
 33  Citizenship_Other Europe                            58 non-null     float64
 34  Citizenship_Africa                                  58 non-null     float64
 35  Citizenship_North America                           58 non-null     float64
 36  Citizenship_South and Central America               58 non-null     float64
 37  Citizenship_Asia and Oceania                        58 non-null     float64
 38  Citizenship_Total                                   58 non-null     float64
 39  Immigrants_Nordic                                   58 non-null     float64
 40  Immigrants_Turkey                                   58 non-null     float64
 41  Immigrants_Former Yugoslavia                        58 non-null     float64
 42  Immigrants_Old EU countries                         58 non-null     float64
 43  Immigrants_New EU countries                         58 non-null     float64
 44  Immigrants_Other Europe                             58 non-null     float64
 45  Immigrants_Africa                                   58 non-null     float64
 46  Immigrants_North America                            58 non-null     float64
 47  Immigrants_South and Central America                58 non-null     float64
 48  Immigrants_Asia and Oceania                         58 non-null     float64
 49  Immigrants_Not specified                            58 non-null     float64
 50  Immigrants_Total                                    58 non-null     float64
 51  Education_18-29 years_Primary and lower secondary   58 non-null     float64
 52  Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 53  Education_18-29 years_Vocational training           58 non-null     float64
 54  Education_30-70+ years_Vocational training          58 non-null     float64
 55  Education_18-29 years_Long higher education         58 non-null     float64
 56  Education_30-70+ years_Long higher education        58 non-null     float64
 57  Education_18-29 years_Not specified                 58 non-null     float64
 58  Education_30-70+ years_Not specified                58 non-null     float64
 59  Education_Total 18-29 years                         58 non-null     float64
 60  Education_Total 30-70+ years                        58 non-null     float64
 61  Education_Total                                     58 non-null     float64
 62  Housing tenure_Homes_Ejer                           58 non-null     float64
 63  Housing tenure_Homes_Andel                          58 non-null     float64
 64  Housing tenure_Homes_Almen                          58 non-null     float64
 65  Housing tenure_Homes_Private rental                 58 non-null     float64
 66  Housing tenure_People_Ejer                          58 non-null     float64
 67  Housing tenure_People_Andel                         58 non-null     float64
 68  Housing tenure_People_Almen                         58 non-null     float64
 69  Housing tenure_People_Private rental                58 non-null     float64
 70  Housing tenure_Total people                         58 non-null     float64
 71  Housing tenure_Total homes                          58 non-null     float64
 72  Housing type_Homes_Detached house                   58 non-null     float64
 73  Housing type_Homes_Terraced house                   58 non-null     float64
 74  Housing type_Homes_Apartment buildings              58 non-null     float64
 75  Housing type_People_Detached house                  58 non-null     float64
 76  Housing type_People_Terraced house                  58 non-null     float64
 77  Housing type_People_Apartment buildings             58 non-null     float64
 78  Housing type_Total people                           58 non-null     float64
 79  Housing type_Total homes                            58 non-null     float64
 80  Benefit type_Kontanthjaelp                          58 non-null     float64
 81  Benefit type_Foertidspension                        58 non-null     float64
 82  Benefit type_Folkepension                           58 non-null     float64
 83  Benefit type_Modtager ikke ydelser                  58 non-null     float64
 84  Benefit type_Antal personer i alt                   58 non-null     float64
 85  Income_Median household income                      58 non-null     float64
 86  Income_Total households                             58 non-null     float64
 87  Income_Gross income top20pct                        58 non-null     float64
 88  Car_Households with no car                          58 non-null     float64
 89  Car_Households with 1 car                           58 non-null     float64
 90  Car_Households with 2+ cars                         58 non-null     float64
dtypes: float64(86), object(5)
memory usage: 41.4+ KB
None

================================================================================
  2013

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 93 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Socioeconomy_Self-employed                          58 non-null     float64
 6   Socioeconomy_Top executives                         58 non-null     float64
 7   Socioeconomy_Unemployed                             58 non-null     float64
 8   Socioeconomy_Total                                  58 non-null     float64
 9   Sex_Male                                            58 non-null     float64
 10  Sex_Female                                          58 non-null     float64
 11  Age_0-4 years                                       58 non-null     float64
 12  Age_5-9 years                                       58 non-null     float64
 13  Age_10-14 years                                     58 non-null     float64
 14  Age_15-17 years                                     58 non-null     float64
 15  Age_18-19 years                                     58 non-null     float64
 16  Age_20-24 years                                     58 non-null     float64
 17  Age_25-29 years                                     58 non-null     float64
 18  Age_30-34 years                                     58 non-null     float64
 19  Age_35-39 years                                     58 non-null     float64
 20  Age_40-44 years                                     58 non-null     float64
 21  Age_45-49 years                                     58 non-null     float64
 22  Age_50-54 years                                     58 non-null     float64
 23  Age_55-59 years                                     58 non-null     float64
 24  Age_60-64 years                                     58 non-null     float64
 25  Age_65-69 years                                     58 non-null     float64
 26  Age_70- years                                       58 non-null     float64
 27  Citizenship_Denmark                                 58 non-null     float64
 28  Citizenship_Nordic                                  58 non-null     float64
 29  Citizenship_Turkey                                  58 non-null     float64
 30  Citizenship_Former Yugoslavia                       58 non-null     float64
 31  Citizenship_Old EU countries                        58 non-null     float64
 32  Citizenship_New EU countries                        58 non-null     float64
 33  Citizenship_Other Europe                            58 non-null     float64
 34  Citizenship_Africa                                  58 non-null     float64
 35  Citizenship_North America                           58 non-null     float64
 36  Citizenship_South and Central America               58 non-null     float64
 37  Citizenship_Asia and Oceania                        58 non-null     float64
 38  Citizenship_Not specified                           58 non-null     float64
 39  Citizenship_Total                                   58 non-null     float64
 40  Immigrants_Nordic                                   58 non-null     float64
 41  Immigrants_Turkey                                   58 non-null     float64
 42  Immigrants_Former Yugoslavia                        58 non-null     float64
 43  Immigrants_Old EU countries                         58 non-null     float64
 44  Immigrants_New EU countries                         58 non-null     float64
 45  Immigrants_Other Europe                             58 non-null     float64
 46  Immigrants_Africa                                   58 non-null     float64
 47  Immigrants_North America                            58 non-null     float64
 48  Immigrants_South and Central America                58 non-null     float64
 49  Immigrants_Asia and Oceania                         58 non-null     float64
 50  Immigrants_Not specified                            58 non-null     float64
 51  Immigrants_Total                                    58 non-null     float64
 52  Education_18-29 years_Primary and lower secondary   58 non-null     float64
 53  Education_30-70+ years_Primary and lower secondary  58 non-null     float64
 54  Education_18-29 years_Vocational training           58 non-null     float64
 55  Education_30-70+ years_Vocational training          58 non-null     float64
 56  Education_18-29 years_Long higher education         58 non-null     float64
 57  Education_30-70+ years_Long higher education        58 non-null     float64
 58  Education_18-29 years_Not specified                 58 non-null     float64
 59  Education_30-70+ years_Not specified                58 non-null     float64
 60  Education_Total 18-29 years                         58 non-null     float64
 61  Education_Total 30-70+ years                        58 non-null     float64
 62  Education_Total                                     58 non-null     float64
 63  Housing tenure_Homes_Ejer                           58 non-null     float64
 64  Housing tenure_Homes_Andel                          58 non-null     float64
 65  Housing tenure_Homes_Almen                          58 non-null     float64
 66  Housing tenure_Homes_Private rental                 58 non-null     float64
 67  Housing tenure_People_Ejer                          58 non-null     float64
 68  Housing tenure_People_Andel                         58 non-null     float64
 69  Housing tenure_People_Almen                         58 non-null     float64
 70  Housing tenure_People_Private rental                58 non-null     float64
 71  Housing tenure_Total people                         58 non-null     float64
 72  Housing tenure_Total homes                          58 non-null     float64
 73  Housing type_Homes_Detached house                   58 non-null     float64
 74  Housing type_Homes_Terraced house                   58 non-null     float64
 75  Housing type_Homes_Apartment buildings              58 non-null     float64
 76  Housing type_People_Detached house                  58 non-null     float64
 77  Housing type_People_Terraced house                  58 non-null     float64
 78  Housing type_People_Apartment buildings             58 non-null     float64
 79  Housing type_Total people                           58 non-null     float64
 80  Housing type_Total homes                            58 non-null     float64
 81  Benefit type_Kontanthjaelp                          58 non-null     float64
 82  Benefit type_Foertidspension                        58 non-null     float64
 83  Benefit type_Folkepension                           58 non-null     float64
 84  Benefit type_Modtager ikke ydelser                  58 non-null     float64
 85  Benefit type_Antal personer i alt                   58 non-null     float64
 86  Crime_Number of arrests                             58 non-null     float64
 87  Income_Median household income                      58 non-null     float64
 88  Income_Total households                             58 non-null     float64
 89  Income_Gross income top20pct                        58 non-null     float64
 90  Car_Households with no car                          58 non-null     float64
 91  Car_Households with 1 car                           58 non-null     float64
 92  Car_Households with 2+ cars                         58 non-null     float64
dtypes: float64(88), object(5)
memory usage: 42.3+ KB
None

================================================================================
  2017

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 93 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              58 non-null     object
 1   ValgstedId                                          58 non-null     object
 2   KredsNr                                             58 non-null     object
 3   StorKredsNr                                         58 non-null     object
 4   LandsdelsNr                                         58 non-null     object
 5   Socioeconomy_Self-employed                          58 non-null     float64
 6   Socioeconomy_Top executives                         58 non-null     float64
 7   Socioeconomy_Unemployed                             58 non-null     float64
 8   Socioeconomy_Total                                  58 non-null     float64
 9   Sex_Male                                            58 non-null     float64
 10  Sex_Female                                          58 non-null     float64
 11  Age_0-4 years                                       58 non-null     float64
 12  Age_5-9 years                                       58 non-null     float64
 13  Age_10-14 years                                     58 non-null     float64
 14  Age_15-17 years                                     58 non-null     float64
 15  Age_18-19 years                                     58 non-null     float64
 16  Age_20-24 years                                     58 non-null     float64
 17  Age_25-29 years                                     58 non-null     float64
 18  Age_30-34 years                                     58 non-null     float64
 19  Age_35-39 years                                     58 non-null     float64
 20  Age_40-44 years                                     58 non-null     float64
 21  Age_45-49 years                                     58 non-null     float64
 22  Age_50-54 years                                     58 non-null     float64
 23  Age_55-59 years                                     58 non-null     float64
 24  Age_60-64 years                                     58 non-null     float64
 25  Age_65-69 years                                     58 non-null     float64
 26  Age_70- years                                       58 non-null     float64
 27  Citizenship_Denmark                                 58 non-null     float64
 28  Citizenship_Nordic                                  58 non-null     float64
 29  Citizenship_Turkey                                  58 non-null     float64
 30  Citizenship_Former Yugoslavia                       58 non-null     float64
 31  Citizenship_Old EU countries                        58 non-null     float64
 32  Citizenship_New EU countries                        58 non-null     float64
 33  Citizenship_Other Europe                            58 non-null     float64
 34  Citizenship_Africa                                  58 non-null     float64
 35  Citizenship_North America                           58 non-null     float64
 36  Citizenship_South and Central America               58 non-null     float64
 37  Citizenship_Asia and Oceania                        58 non-null     float64
 38  Citizenship_Not specified                           58 non-null     float64
 39  Citizenship_Total                                   58 non-null     float64
 40  Immigrants_Nordic                                   58 non-null     float64
 41  Immigrants_Turkey                                   58 non-null     float64
 42  Immigrants_Former Yugoslavia                        58 non-null     float64
 43  Immigrants_Old EU countries                         58 non-null     float64
 44  Immigrants_New EU countries                         58 non-null     float64
 45  Immigrants_Other Europe                             58 non-null     float64
 46  Immigrants_Africa                                   58 non-null     float64
 47  Immigrants_North America                            58 non-null     float64

Later, we might consider:

- In 'Housing type_[...]', combining 'detached' and 'terraced' into one feature.
- Dropping the 'Benefit type_Folkepension' feature.
- Removing or merging some columns in 'Citizenship_[...]' and 'Immigrants_[...]'. E.g. drop 'Not specified', merge 'Old EU countries' with 'New EU countries' and 'Other Europe' (or find out what the differences are)

Another thing to note is that for housing tenure, housing type and education, the column naming format was a tiny bit different for 2009 (and earlier years) than for the other years. Because of this, we might consider dropping those columns from 2009 - or we might assume that it's just a tiny difference in the column naming format and nothing else.

### Add and drop geography columns
I want to remove StorKredsNr and LandsdelsNr, but add 'Valgsted navn', 'Kreds navn' and 'Kommune navn'. Preferably, the first six columns will be 'Gruppe', 'ValgstedId', 'Valgsted navn' 'KredsNr', 'Kreds navn' and 'Kommune navn', in that order.

In [58]:
def add_geography_columns(df, geography_csv_path):
    """
    Add geography columns to dataframe by matching ValgstedId.
    
    Parameters:
    - df: DataFrame to add columns to
    - geography_csv_path: Path to Geography.csv
    
    Returns:
    - DataFrame with added geography columns
    """    
    # Read Geography.csv
    geo_df = pd.read_csv(geography_csv_path, sep=';', encoding='utf-8', quotechar='"')
    
    # Clean column names (remove any extra whitespace/quotes)
    geo_df.columns = geo_df.columns.str.strip().str.strip('"')

    # Filter for KommuneNr 101 or 147
    geo_df = geo_df[geo_df['KommuneNr'].astype(str).isin(['101', '147'])].copy()

    # Debug: print first few rows to see what we're working with
    print("Geography CSV columns:", geo_df.columns.tolist())
    print("First few Valgsted Ids:", geo_df['Valgsted Id'].head().tolist())

    # Create a dictionary for quick lookup
    geo_dict = {}
    for _, row in geo_df.iterrows():
        # Clean the ValgstedId (remove quotes, whitespace)
        valgsted_id = str(row['Valgsted Id']).strip().strip('"')
        geo_dict[valgsted_id] = {
            'Valgsted navn': str(row['Valgsted navn']).strip().strip('"'),
            'Kreds navn': str(row['Kreds navn']).strip().strip('"'),
            'Kommune navn': str(row['Kommune navn']).strip().strip('"')
        }
    
    print(f"Total entries in geo_dict: {len(geo_dict)}")
    print(f"Sample keys: {list(geo_dict.keys())[:5]}")
    
    # Create new columns
    df_result = df.copy()
    valgsted_navne = []
    kreds_navne = []
    kommune_navne = []
    
    for _, row in df_result.iterrows():
        valgsted_ids = str(row['ValgstedId']).split(';')
        
        # Collect names for each ValgstedId
        v_names = []
        k_names = []
        kom_names = []
        
        for vid in valgsted_ids:
            vid = vid.strip()
            if vid not in geo_dict:
                print(f"Missing ValgstedId: '{vid}' (length: {len(vid)})")
                print(f"Available keys starting with '101': {[k for k in geo_dict.keys() if k.startswith('101')][:10]}")
                raise ValueError(f"ValgstedId '{vid}' not found in Geography.csv")
            
            v_names.append(geo_dict[vid]['Valgsted navn'])
            k_names.append(geo_dict[vid]['Kreds navn'])
            kom_names.append(geo_dict[vid]['Kommune navn'])
        
        # Join with semicolons, remove duplicates while preserving order
        valgsted_navne.append(';'.join(v_names))
        
        # For Kreds and Kommune, use single value if all same, otherwise semicolon-separate
        if len(set(k_names)) == 1:
            kreds_navne.append(k_names[0])
        else:
            kreds_navne.append(';'.join(k_names))
            
        if len(set(kom_names)) == 1:
            kommune_navne.append(kom_names[0])
        else:
            kommune_navne.append(';'.join(kom_names))
    
    # Add the new columns
    df_result['Valgsted navn'] = valgsted_navne
    df_result['Kreds navn'] = kreds_navne
    df_result['Kommune navn'] = kommune_navne
    
    # Drop the columns we don't want
    df_result = df_result.drop(columns=['StorKredsNr', 'LandsdelsNr'])
    
    # Reorder columns to put the first 6 in the desired order
    first_cols = ['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn', 'Kommune navn']
    other_cols = [col for col in df_result.columns if col not in first_cols]
    df_result = df_result[first_cols + other_cols]
    
    return df_result

geography_path = ROOT + 'raw-data/historical-elections/election-results/Geography.csv'

for year in years:
    combined_dfs[year] = add_geography_columns(combined_dfs[year], geography_path)
    print(f"Added geography columns to {year}")

# Reassign
df_2009, df_2013, df_2017, df_2021 = [combined_dfs[year] for year in years]

# Check the result
print("\nFirst few rows of df_2021:")
print(df_2021[['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn', 'Kommune navn']].head(10))

Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2009
Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2013
Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2017
Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2021

First few rows of df_2021:
   Gruppe     ValgstedId    Valgsted navn KredsNr       Kreds navn  \
0  101001         101001      1. Østerbro       1      1. Østerbro
1  101002         101002          1. Nord       1      1. Østerbro
2  101003         101003           1. Syd       1      1. Østerbro
3  101005         101005          1. Vest       1      1. Østerbro
4  101006         101006      1. Nordvest       1      1. Østerbro
5  101007         101007  2. Sundbyvester       2  2. Sundbyvester
6  101008  101010;101008  2. Vest;2. Nord       2  2. Sundbyvester
7  101009         101009           2. Syd       2  2. Sundbyvester
8  101011         101011      3. Indre By       3      3. Indre By
9  101012         101012          3. Nord       3      3. Indre By

  Kommune navn
0    København
1    København
2    København
3    København
4    København
5    København
6    København
7    København
8    København
9    København

## Convert (some) floats to ints

In [59]:
def convert_floats_to_int(df):
    """Convert float columns to int if they have no fractional parts"""
    df_converted = df.copy()
    
    for col in df_converted.columns:
        # Check if column is float type
        if df_converted[col].dtype == 'float64':
            # Check if all non-null values have no fractional part
            non_null_values = df_converted[col].dropna()
            if len(non_null_values) > 0 and (non_null_values % 1 == 0).all():
                # Convert to Int64 (nullable integer type to preserve NaN if present)
                df_converted[col] = df_converted[col].astype('int64')
    
    return df_converted

for year in years:
    combined_dfs[year] = convert_floats_to_int(combined_dfs[year])
    print(f"Converted {year}")

print("\ndf_2021 dtypes before conversion:")
print(df_2021.dtypes.value_counts())

# Reassign
df_2009, df_2013, df_2017, df_2021 = [combined_dfs[year] for year in years]

# Check the result
print("\ndf_2021 dtypes after conversion:")
print(df_2021.dtypes.value_counts())

Converted 2009
Converted 2013
Converted 2017
Converted 2021

df_2021 dtypes before conversion:
float64    83
int64      13
object      6
Name: count, dtype: int64

df_2021 dtypes after conversion:
int64     96
object     6
Name: count, dtype: int64

## Check total columns

In [60]:
# Check if 'total' columns are similar for the same polling area

total_cols = [
    'Gruppe',
    'Socioeconomy_Total',
    'Citizenship_Total',
    'Education_Total',
    'Housing tenure_Total people',
    'Housing type_Total people',
    'Benefit type_Antal personer i alt',
    'Year built_Total people'
]

total_df = df_2021[total_cols].copy()
total_df.head(10)

,Gruppe,Socioeconomy_Total,Citizenship_Total,Education_Total,Housing tenure_Total people,Housing type_Total people,Benefit type_Antal personer i alt,Year built_Total people
0,101001,15540,15562,13042,11438,15562,15562,15562
1,101002,8366,8378,6982,7017,8378,8378,8378
2,101003,15838,15846,12819,12193,15846,15846,15846
3,101005,15817,15854,13448,12350,15854,15854,15854
4,101006,13473,13487,11252,11023,13487,13487,13487
5,101007,14229,14265,11588,12900,14265,14265,14265
6,101008,33823,33643,27862,28022,33643,33643,33643
7,101009,19097,31062,24375,19813,31062,31062,31062
8,101011,20738,20283,17987,10167,20283,20283,20283
9,101012,9173,9176,7495,6444,9176,9176,9176

In [61]:
# They LOOK very similar, but let's see some statistics

numeric_totals = total_df.drop(columns=['Gruppe'])

total_df['mean_across_totals'] = numeric_totals.mean(axis=1)
total_df['median_across_totals'] = numeric_totals.median(axis=1)
total_df['mode_across_totals'] = numeric_totals.mode(axis=1)
total_df['std_across_totals'] = numeric_totals.std(axis=1)
total_df['min_across_totals'] = numeric_totals.min(axis=1)
total_df['max_across_totals'] = numeric_totals.max(axis=1)
total_df['range_across_totals'] = total_df['max_across_totals'] - total_df['min_across_totals']
total_df['cv_across_totals'] = (numeric_totals.std(axis=1) / numeric_totals.mean(axis=1)) * 100
# CV is the Coefficient of Variation (CV) - the relative variation as a percentage of the mean.

In [62]:
# Show rows with the most variation
total_df.nlargest(10, 'cv_across_totals')

,Gruppe,Socioeconomy_Total,Citizenship_Total,Education_Total,Housing tenure_Total people,Housing type_Total people,Benefit type_Antal personer i alt,Year built_Total people,mean_across_totals,median_across_totals,mode_across_totals,std_across_totals,min_across_totals,max_across_totals,range_across_totals,cv_across_totals
11,101014,28789,16714,14963,10052,16714,16714,16714,17237.142857,16714.0,16714,5647.095431,10052,28789,18737,32.761203
47,101055,15477,15656,12611,5782,15656,15656,15656,13784.857143,15656.0,15656,3703.415380,5782,15656,9874,26.865823
7,101009,19097,31062,24375,19813,31062,31062,31062,26790.428571,31062.0,31062,5578.125995,19097,31062,11965,20.821339
8,101011,20738,20283,17987,10167,20283,20283,20283,18574.857143,20283.0,20283,3816.364606,10167,20738,10571,20.545862
55,147005,14555,14285,12148,7414,14285,14285,14285,13036.714286,14285.0,14285,2612.240080,7414,14555,7141,20.037565
40,101048,11089,11095,9038,6776,11095,11095,11095,10183.285714,11095.0,11095,1686.539130,6776,11095,4319,16.561836
46,101054,4284,4468,4012,2678,4468,4468,4468,4120.857143,4468.0,4468,658.576097,2678,4468,1790,15.981532
25,101030,13679,13733,12058,9134,13733,13733,13733,12829.000000,13733.0,13733,1743.503656,9134,13733,4599,13.590332
9,101012,9173,9176,7495,6444,9176,9176,9176,8545.142857,9176.0,9176,1118.311887,6444,9176,2732,13.087106
53,147003,15733,15739,12867,11112,15739,15739,15739,14666.857143,15739.0,15739,1897.854791,11112,15739,4627,12.939751

The reason why 'Socioeconomy_Total' is so much higher than the other totals for 'Gruppe' == 101014, is probably that that 'Gruppe' contains two polling areas in the socioeconomy csv (101014 and 101057), but in the other csv files, it only contains 101014 (itself). That is kind of weird.

It looks like the totals for 'Citizenship_Total', 'Housing type_Total people', 'Benefit type_Antal personer i alt' and 'Year built_Total people' are always the same. But let's check it.

In [63]:
# Check if specific columns are always equal

cols_to_check = [
    'Citizenship_Total',
    'Housing type_Total people',
    'Benefit type_Antal personer i alt',
    'Year built_Total people'
]

# Check if all values in each row are equal
all_equal = (total_df[cols_to_check].nunique(axis=1) == 1).all()
print(f"Are these columns always equal across all rows? {all_equal}")

# See which rows (if any) have different values
rows_with_differences = total_df[total_df[cols_to_check].nunique(axis=1) > 1]
print(f"\nRows where values differ: {len(rows_with_differences)}")
if len(rows_with_differences) > 0:
    print(rows_with_differences[['Gruppe'] + cols_to_check])

# Verify by looking at a sample
print("\nSample of the columns:")
print(total_df[['Gruppe'] + cols_to_check].head(10))

Are these columns always equal across all rows? True

Rows where values differ: 0

Sample of the columns:
   Gruppe  Citizenship_Total  Housing type_Total people  \
0  101001              15562                      15562
1  101002               8378                       8378
2  101003              15846                      15846
3  101005              15854                      15854
4  101006              13487                      13487
5  101007              14265                      14265
6  101008              33643                      33643
7  101009              31062                      31062
8  101011              20283                      20283
9  101012               9176                       9176

   Benefit type_Antal personer i alt  Year built_Total people
0                              15562                    15562
1                               8378                     8378
2                              15846                    15846
3                              15854                    15854
4                              13487                    13487
5                              14265                    14265
6                              33643                    33643
7                              31062                    31062
8                              20283                    20283
9                               9176                     9176

Since they are always equal, I think we should set that value to 'Population' in a new column, delete the totals that were equal, and keep the others.

In [64]:
# Add 'Population' column and remove the redundant total columns
for year in years:
    df = combined_dfs[year]
    
    # Add 'Population' column with values from 'Citizenship_Total'
    df['Population'] = df['Citizenship_Total']
    
    # Drop the 4 redundant total columns
    cols_to_drop = [
        'Citizenship_Total',
        'Housing type_Total people',
        'Benefit type_Antal personer i alt',
        'Year built_Total people'
    ]
    if year == 2021:
        df = df.drop(columns=cols_to_drop)
    else:
        df = df.drop(columns=cols_to_drop[:3]) # Year built_ cols already dropped for other years
    combined_dfs[year] = df
    print(f"Updated {year}: {df.shape}")

df_2009, df_2013, df_2017, df_2021 = [combined_dfs[year] for year in years]

Updated 2009: (58, 90)
Updated 2013: (58, 92)
Updated 2017: (58, 92)
Updated 2021: (58, 99)

When calculating relative numbers for:
        'Citizenship_
        'Housing type_People_
        'Benefit type_
        'Year built_
        'Sex_
        'Age_'
        'Crime_'
Use 'Population' as the total to get the relative

Socioeconomy_
- Use Socioeconomy_Total 

Immigrants_
- Use Immigrants_Total

Education_
- Use Education_Total

Housing tenure_People_
- Use Housing tenure_Total people

Housing tenure_Homes_
- Use Housing tenure_Total homes

Housing type_Homes
- Use Housing type_Total homes

Car_
- Calculate total households from all three car columns

Income_Median household income
- Leave as is (already relative)

Income_Gross income top20pct
- Don't know right now :D maybe use Population

## Reorder and save to csv

In [65]:
column_order_prefixes = [
    'Sex_',
    'Age_',
    'Citizenship_',
    'Income_',
    'Car_',
    'Crime_',
    'Benefit type_',
    'Housing type_',
    'Year built_',
    'Housing tenure_',
    'Education_',
    'Immigrants_',
    'Socioeconomy_'
]

for year in years:
    df = combined_dfs[year]
    
    # Start with the first 7 columns
    first_cols = ['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn', 'Kommune navn', 'Population']
    ordered_cols = first_cols.copy()
    
    # Add columns in the specified prefix order
    for prefix in column_order_prefixes:
        matching_cols = [col for col in df.columns if col.startswith(prefix) and col not in ordered_cols]
        ordered_cols.extend(sorted(matching_cols))  # Sort alphabetically within each group
    
    # Add any remaining columns that weren't caught (shouldn't be any, but just in case)
    remaining_cols = [col for col in df.columns if col not in ordered_cols]
    if remaining_cols:
        print(f"Warning: {year} has unexpected columns: {remaining_cols}")
        ordered_cols.extend(remaining_cols)
    
    # Reorder the dataframe
    df = df[ordered_cols]
    combined_dfs[year] = df
    print(f"Reordered {year}: {df.shape}")

# Reassign
df_2009, df_2013, df_2017, df_2021 = [combined_dfs[year] for year in years]

# Save to CSVs
for year in years:
    output_path = f'{OUTPUT_PATH}absolute_{year}.csv'
    combined_dfs[year].to_csv(output_path, index=False)
    print(f"Saved {output_path}")

# Verify the column order
print("\nColumn order for df_2021:")
for i, col in enumerate(df_2021.columns[:20], 1):
    print(f"{i}. {col}")

Reordered 2009: (58, 90)
Reordered 2013: (58, 92)
Reordered 2017: (58, 92)
Reordered 2021: (58, 99)
Saved ../../../processed-data/demographics/absolute_2009.csv
Saved ../../../processed-data/demographics/absolute_2013.csv
Saved ../../../processed-data/demographics/absolute_2017.csv
Saved ../../../processed-data/demographics/absolute_2021.csv

Column order for df_2021:
1. Gruppe
2. ValgstedId
3. Valgsted navn
4. KredsNr
5. Kreds navn
6. Kommune navn
7. Population
8. Sex_Female
9. Sex_Male
10. Age_0-4 years
11. Age_10-14 years
12. Age_15-17 years
13. Age_18-19 years
14. Age_20-24 years
15. Age_25-29 years
16. Age_30-34 years
17. Age_35-39 years
18. Age_40-44 years
19. Age_45-49 years
20. Age_5-9 years

And just like that, about 13,000 columns spread across 16 CSV files became less than 400 columns spread across 4 CSV files :-)