Notebook for creating relative_2021, where all data is % of the different totals for easier comparison across polling areas (instead of absolute numbers).

# Initial Steps

In [ ]:
import pandas as pd 

path = "../../../processed-data/demographics/absolute_2021.csv"

df = pd.read_csv(path)
df.head()

,Gruppe,PollingAreaID,Name,DistrictNo,District,Municipality,Population,Sex_Female,Sex_Male,Age_0-4 years,...,Immigrants_Not specified,Immigrants_Old EU countries,Immigrants_Other Europe,Immigrants_South and Central America,Immigrants_Total,Immigrants_Turkey,Socioeconomy_Self-employed,Socioeconomy_Top executives,Socioeconomy_Total,Socioeconomy_Unemployed
0,101001,101001,1. Østerbro,1,1. Østerbro,København,15562,8231,7331,853,...,1,895,88,161,2883,40,523,345,15457,364
1,101002,101002,1. Nord,1,1. Østerbro,København,8378,4470,3908,426,...,0,360,77,88,1664,57,350,219,8510,211
2,101003,101003,1. Syd,1,1. Østerbro,København,15846,8206,7640,920,...,1,729,83,212,2503,52,621,401,15765,407
3,101005,101005,1. Vest,1,1. Østerbro,København,15854,8206,7648,929,...,3,799,166,214,3947,136,385,226,15693,425
4,101006,101006,1. Nordvest,1,1. Østerbro,København,13487,6960,6527,801,...,0,579,118,130,3043,94,442,254,13752,383

In [2]:
print(df.columns)

Index(['Gruppe', 'PollingAreaID', 'Name', 'DistrictNo', 'District',
       'Municipality', 'Population', 'Sex_Female', 'Sex_Male', 'Age_0-4 years',
       'Age_10-14 years', 'Age_15-17 years', 'Age_18-19 years',
       'Age_20-24 years', 'Age_25-29 years', 'Age_30-34 years',
       'Age_35-39 years', 'Age_40-44 years', 'Age_45-49 years',
       'Age_5-9 years', 'Age_50-54 years', 'Age_55-59 years',
       'Age_60-64 years', 'Age_65-69 years', 'Age_70- years',
       'Citizenship_Africa', 'Citizenship_Asia and Oceania',
       'Citizenship_Denmark', 'Citizenship_Former Yugoslavia',
       'Citizenship_New EU countries', 'Citizenship_Nordic',
       'Citizenship_North America', 'Citizenship_Not specified',
       'Citizenship_Old EU countries', 'Citizenship_Other Europe',
       'Citizenship_South and Central America', 'Citizenship_Turkey',
       'Income_Gross income top20pct', 'Income_Median household income',
       'Income_Total households', 'Car_Households with 1 car',
       'Car_Households with 2+ cars', 'Car_Households with no car',
       'Crime_Number of arrests', 'Benefit type_Foertidspension',
       'Benefit type_Folkepension', 'Benefit type_Kontanthjaelp',
       'Benefit type_Modtager ikke ydelser',
       'Housing type_Homes_Apartment buildings',
       'Housing type_Homes_Detached house',
       'Housing type_Homes_Terraced house',
       'Housing type_People_Apartment buildings',
       'Housing type_People_Detached house',
       'Housing type_People_Terraced house', 'Housing type_Total homes',
       'Year built_Homes_1960-2009', 'Year built_Homes_2010-9999',
       'Year built_Homes_Before 1960', 'Year built_People_1960-2009',
       'Year built_People_2010-9999', 'Year built_People_Before 1960',
       'Year built_Total homes', 'Housing tenure_Homes_Almen',
       'Housing tenure_Homes_Andel', 'Housing tenure_Homes_Ejer',
       'Housing tenure_Homes_Private rental', 'Housing tenure_People_Almen',
       'Housing tenure_People_Andel', 'Housing tenure_People_Ejer',
       'Housing tenure_People_Private rental', 'Housing tenure_Total homes',
       'Housing tenure_Total people',
       'Education_18-29 years_Long higher education',
       'Education_18-29 years_Not specified',
       'Education_18-29 years_Primary and lower secondary',
       'Education_18-29 years_Vocational training',
       'Education_30-70+ years_Long higher education',
       'Education_30-70+ years_Not specified',
       'Education_30-70+ years_Primary and lower secondary',
       'Education_30-70+ years_Vocational training', 'Education_Total',
       'Education_Total 18-29 years', 'Education_Total 30-70+ years',
       'Immigrants_Africa', 'Immigrants_Asia and Oceania',
       'Immigrants_Former Yugoslavia', 'Immigrants_New EU countries',
       'Immigrants_Nordic', 'Immigrants_North America',
       'Immigrants_Not specified', 'Immigrants_Old EU countries',
       'Immigrants_Other Europe', 'Immigrants_South and Central America',
       'Immigrants_Total', 'Immigrants_Turkey', 'Socioeconomy_Self-employed',
       'Socioeconomy_Top executives', 'Socioeconomy_Total',
       'Socioeconomy_Unemployed'],
      dtype='object')

# Calculations

The results of the following will be floats, and omit "%" sign at the end of each value.

'Citizenship_ 'Housing type_People_ 'Benefit type_ 'Sex_ 'Age_' 'Crime_' 'Year built_' with 'Population' as the total to get the relative

In [3]:
df['Year built_People_1960-2009'] = (df['Year built_People_1960-2009']/df['Population'])*100
df['Year built_People_2010-9999'] = (df['Year built_People_2010-9999']/df['Population'])*100
df['Year built_People_Before 1960'] = (df['Year built_People_Before 1960']/df['Population'])*100

df['Crime_Number of arrests'] = (df['Crime_Number of arrests']/df['Population'])*100

df['Sex_Female'] = (df['Sex_Female']/df['Population'])*100
df['Sex_Male'] = (df['Sex_Male']/df['Population'])*100

df['Age_0-4 years'] = (df['Age_0-4 years']/df['Population'])*100
df['Age_10-14 years'] = (df['Age_10-14 years']/df['Population'])*100
df['Age_15-17 years'] = (df['Age_15-17 years']/df['Population'])*100
df['Age_18-19 years'] = (df['Age_18-19 years']/df['Population'])*100
df['Age_20-24 years'] = (df['Age_20-24 years']/df['Population'])*100
df['Age_25-29 years'] = (df['Age_25-29 years']/df['Population'])*100
df['Age_30-34 years'] = (df['Age_30-34 years']/df['Population'])*100
df['Age_35-39 years'] = (df['Age_35-39 years']/df['Population'])*100
df['Age_40-44 years'] = (df['Age_40-44 years']/df['Population'])*100
df['Age_45-49 years'] = (df['Age_45-49 years']/df['Population'])*100
df['Age_5-9 years'] = (df['Age_5-9 years']/df['Population'])*100
df['Age_50-54 years'] = (df['Age_50-54 years']/df['Population'])*100
df['Age_55-59 years'] = (df['Age_55-59 years']/df['Population'])*100
df['Age_60-64 years'] = (df['Age_60-64 years']/df['Population'])*100
df['Age_65-69 years'] = (df['Age_65-69 years']/df['Population'])*100
df['Age_70- years'] = (df['Age_70- years']/df['Population'])*100

df['Citizenship_Africa'] = (df['Citizenship_Africa']/df['Population'])*100
df['Citizenship_Asia and Oceania'] = (df['Citizenship_Asia and Oceania']/df['Population'])*100
df['Citizenship_Denmark'] = (df['Citizenship_Denmark']/df['Population'])*100
df['Citizenship_Former Yugoslavia'] = (df['Citizenship_Former Yugoslavia']/df['Population'])*100
df['Citizenship_New EU countries'] = (df['Citizenship_New EU countries']/df['Population'])*100
df['Citizenship_Nordic'] = (df['Citizenship_Nordic']/df['Population'])*100
df['Citizenship_North America'] = (df['Citizenship_North America']/df['Population'])*100
df['Citizenship_Old EU countries'] = (df['Citizenship_Old EU countries']/df['Population'])*100
df['Citizenship_Other Europe'] = (df['Citizenship_Other Europe']/df['Population'])*100
df['Citizenship_South and Central America'] = (df['Citizenship_South and Central America']/df['Population'])*100
df['Citizenship_Turkey'] = (df['Citizenship_Turkey']/df['Population'])*100
df['Citizenship_Not specified'] = (df['Citizenship_Not specified']/df['Population'])*100

df['Housing type_People_Apartment buildings'] = (df['Housing type_People_Apartment buildings']/df['Population'])*100
df['Housing type_People_Detached house'] = (df['Housing type_People_Detached house']/df['Population'])*100
df['Housing type_People_Terraced house'] = (df['Housing type_People_Terraced house']/df['Population'])*100

df['Benefit type_Foertidspension'] = (df['Benefit type_Foertidspension']/df['Population'])*100
df['Benefit type_Folkepension'] = (df['Benefit type_Folkepension']/df['Population'])*100
df['Benefit type_Kontanthjaelp'] = (df['Benefit type_Kontanthjaelp']/df['Population'])*100
df['Benefit type_Modtager ikke ydelser'] = (df['Benefit type_Modtager ikke ydelser']/df['Population'])*100

Year built_Homes with Year built_Total homes

In [4]:
df['Year built_Homes_1960-2009'] = (df['Year built_Homes_1960-2009']/df['Year built_Total homes'])*100
df['Year built_Homes_2010-9999'] = (df['Year built_Homes_2010-9999']/df['Year built_Total homes'])*100
df['Year built_Homes_Before 1960'] = (df['Year built_Homes_Before 1960']/df['Year built_Total homes'])*100

Socioeconomy_ with Socioeconomy_Total

In [5]:
df['Socioeconomy_Self-employed'] = (df['Socioeconomy_Self-employed']/df['Socioeconomy_Total'])*100
df['Socioeconomy_Top executives'] = (df['Socioeconomy_Top executives']/df['Socioeconomy_Total'])*100
df['Socioeconomy_Unemployed'] = (df['Socioeconomy_Unemployed']/df['Socioeconomy_Total'])*100

Immigrants_ with Immigrants_Total

In [6]:
df['Immigrants_Africa'] = (df['Immigrants_Africa']/df['Immigrants_Total'])*100
df['Immigrants_Asia and Oceania'] = (df['Immigrants_Asia and Oceania']/df['Immigrants_Total'])*100
df['Immigrants_Former Yugoslavia'] = (df['Immigrants_Former Yugoslavia']/df['Immigrants_Total'])*100
df['Immigrants_New EU countries'] = (df['Immigrants_New EU countries']/df['Immigrants_Total'])*100
df['Immigrants_Nordic'] = (df['Immigrants_Nordic']/df['Immigrants_Total'])*100
df['Immigrants_North America'] = (df['Immigrants_North America']/df['Immigrants_Total'])*100
df['Immigrants_Not specified'] = (df['Immigrants_Not specified']/df['Immigrants_Total'])*100
df['Immigrants_Old EU countries'] = (df['Immigrants_Old EU countries']/df['Immigrants_Total'])*100
df['Immigrants_Other Europe'] = (df['Immigrants_Other Europe']/df['Immigrants_Total'])*100
df['Immigrants_South and Central America'] = (df['Immigrants_South and Central America']/df['Immigrants_Total'])*100
df['Immigrants_Turkey'] = (df['Immigrants_Turkey']/df['Immigrants_Total'])*100

Education_ with Education_Total

In [7]:
df['Education_18-29 years_Long higher education'] = (df['Education_18-29 years_Long higher education']/df['Education_Total'])*100
df['Education_18-29 years_Not specified'] = (df['Education_18-29 years_Not specified']/df['Education_Total'])*100
df['Education_18-29 years_Primary and lower secondary'] = (df['Education_18-29 years_Primary and lower secondary']/df['Education_Total'])*100
df['Education_18-29 years_Vocational training'] = (df['Education_18-29 years_Vocational training']/df['Education_Total'])*100
df['Education_30-70+ years_Long higher education'] = (df['Education_30-70+ years_Long higher education']/df['Education_Total'])*100
df['Education_30-70+ years_Not specified'] = (df['Education_30-70+ years_Not specified']/df['Education_Total'])*100
df['Education_30-70+ years_Primary and lower secondary'] = (df['Education_30-70+ years_Primary and lower secondary']/df['Education_Total'])*100
df['Education_30-70+ years_Vocational training'] = (df['Education_30-70+ years_Vocational training']/df['Education_Total'])*100
df['Education_Total 18-29 years'] = (df['Education_Total 18-29 years']/df['Education_Total'])*100
df['Education_Total 30-70+ years'] = (df['Education_Total 30-70+ years']/df['Education_Total'])*100

Housing tenure_People_ with Housing tenure_Total people

In [8]:
df['Housing tenure_People_Almen'] = (df['Housing tenure_People_Almen']/df['Housing tenure_Total people'])*100
df['Housing tenure_People_Andel'] = (df['Housing tenure_People_Andel']/df['Housing tenure_Total people'])*100
df['Housing tenure_People_Ejer'] = (df['Housing tenure_People_Ejer']/df['Housing tenure_Total people'])*100
df['Housing tenure_People_Private rental'] = (df['Housing tenure_People_Private rental']/df['Housing tenure_Total people'])*100

Housing tenure_Homes_ with Housing tenure_Total homes

In [9]:
df['Housing tenure_Homes_Almen'] = (df['Housing tenure_Homes_Almen']/df['Housing tenure_Total homes'])*100
df['Housing tenure_Homes_Andel'] = (df['Housing tenure_Homes_Andel']/df['Housing tenure_Total homes'])*100
df['Housing tenure_Homes_Ejer'] = (df['Housing tenure_Homes_Ejer']/df['Housing tenure_Total homes'])*100
df['Housing tenure_Homes_Private rental'] = (df['Housing tenure_Homes_Private rental']/df['Housing tenure_Total homes'])*100

Housing type_Homes with Housing type_Total homes

In [10]:
df['Housing type_Homes_Apartment buildings'] = (df['Housing type_Homes_Apartment buildings']/df['Housing type_Total homes'])*100
df['Housing type_Homes_Detached house'] = (df['Housing type_Homes_Detached house']/df['Housing type_Total homes'])*100
df['Housing type_Homes_Terraced house'] = (df['Housing type_Homes_Terraced house']/df['Housing type_Total homes'])*100

Car_ with (pre-calculated) total households from all three car columns

In [11]:
df['Car total_households'] = (df['Car_Households with 1 car']+df['Car_Households with 2+ cars']+df['Car_Households with no car'])

In [12]:
df['Car_Households with 1 car'] = (df['Car_Households with 1 car']/df['Car total_households'])*100
df['Car_Households with 2+ cars'] = (df['Car_Households with 2+ cars']/df['Car total_households'])*100
df['Car_Households with no car'] = (df['Car_Households with no car']/df['Car total_households'])*100

Income_Median household income LEAVE AS IS

Income_Gross income top20pct with Income_Total households

In [13]:
df['Income_Gross income top20pct'] = (df['Income_Gross income top20pct']/df['Income_Total households'])*100

# Dropp Columns With Total Values

Note to self, keep all columns before 'Population' as they are.

In [14]:
df.drop(['Population', 'Year built_Total homes','Socioeconomy_Total','Immigrants_Total','Education_Total','Housing tenure_Total people','Housing tenure_Total homes','Housing type_Total homes','Car total_households','Income_Total households'], axis=1, inplace=True)
df.head()

,Gruppe,PollingAreaID,Name,DistrictNo,District,Municipality,Sex_Female,Sex_Male,Age_0-4 years,Age_10-14 years,...,Immigrants_Nordic,Immigrants_North America,Immigrants_Not specified,Immigrants_Old EU countries,Immigrants_Other Europe,Immigrants_South and Central America,Immigrants_Turkey,Socioeconomy_Self-employed,Socioeconomy_Top executives,Socioeconomy_Unemployed
0,101001,101001,1. Østerbro,1,1. Østerbro,København,52.891659,47.108341,5.481301,4.356766,...,13.458203,5.827263,0.034686,31.044051,3.052376,5.584461,1.387444,3.383580,2.231998,2.354920
1,101002,101002,1. Nord,1,1. Østerbro,København,53.354022,46.645978,5.084746,4.738601,...,8.894231,3.485577,0.000000,21.634615,4.627404,5.288462,3.425481,4.112808,2.573443,2.479436
2,101003,101003,1. Syd,1,1. Østerbro,København,51.785940,48.214060,5.805882,5.439859,...,14.342789,6.032761,0.039952,29.125050,3.316021,8.469836,2.077507,3.939106,2.543609,2.581668
3,101005,101005,1. Vest,1,1. Østerbro,København,51.759808,48.240192,5.859720,3.740381,...,7.676716,4.915125,0.076007,20.243223,4.205726,5.421839,3.445655,2.453323,1.440133,2.708214
4,101006,101006,1. Nordvest,1,1. Østerbro,København,51.605249,48.394751,5.939052,4.226292,...,7.755504,2.497535,0.000000,19.027276,3.877752,4.272100,3.089057,3.214078,1.847004,2.785049

In [15]:
print(df.columns)

Index(['Gruppe', 'PollingAreaID', 'Name', 'DistrictNo', 'District',
       'Municipality', 'Sex_Female', 'Sex_Male', 'Age_0-4 years',
       'Age_10-14 years', 'Age_15-17 years', 'Age_18-19 years',
       'Age_20-24 years', 'Age_25-29 years', 'Age_30-34 years',
       'Age_35-39 years', 'Age_40-44 years', 'Age_45-49 years',
       'Age_5-9 years', 'Age_50-54 years', 'Age_55-59 years',
       'Age_60-64 years', 'Age_65-69 years', 'Age_70- years',
       'Citizenship_Africa', 'Citizenship_Asia and Oceania',
       'Citizenship_Denmark', 'Citizenship_Former Yugoslavia',
       'Citizenship_New EU countries', 'Citizenship_Nordic',
       'Citizenship_North America', 'Citizenship_Not specified',
       'Citizenship_Old EU countries', 'Citizenship_Other Europe',
       'Citizenship_South and Central America', 'Citizenship_Turkey',
       'Income_Gross income top20pct', 'Income_Median household income',
       'Car_Households with 1 car', 'Car_Households with 2+ cars',
       'Car_Households with no car', 'Crime_Number of arrests',
       'Benefit type_Foertidspension', 'Benefit type_Folkepension',
       'Benefit type_Kontanthjaelp', 'Benefit type_Modtager ikke ydelser',
       'Housing type_Homes_Apartment buildings',
       'Housing type_Homes_Detached house',
       'Housing type_Homes_Terraced house',
       'Housing type_People_Apartment buildings',
       'Housing type_People_Detached house',
       'Housing type_People_Terraced house', 'Year built_Homes_1960-2009',
       'Year built_Homes_2010-9999', 'Year built_Homes_Before 1960',
       'Year built_People_1960-2009', 'Year built_People_2010-9999',
       'Year built_People_Before 1960', 'Housing tenure_Homes_Almen',
       'Housing tenure_Homes_Andel', 'Housing tenure_Homes_Ejer',
       'Housing tenure_Homes_Private rental', 'Housing tenure_People_Almen',
       'Housing tenure_People_Andel', 'Housing tenure_People_Ejer',
       'Housing tenure_People_Private rental',
       'Education_18-29 years_Long higher education',
       'Education_18-29 years_Not specified',
       'Education_18-29 years_Primary and lower secondary',
       'Education_18-29 years_Vocational training',
       'Education_30-70+ years_Long higher education',
       'Education_30-70+ years_Not specified',
       'Education_30-70+ years_Primary and lower secondary',
       'Education_30-70+ years_Vocational training',
       'Education_Total 18-29 years', 'Education_Total 30-70+ years',
       'Immigrants_Africa', 'Immigrants_Asia and Oceania',
       'Immigrants_Former Yugoslavia', 'Immigrants_New EU countries',
       'Immigrants_Nordic', 'Immigrants_North America',
       'Immigrants_Not specified', 'Immigrants_Old EU countries',
       'Immigrants_Other Europe', 'Immigrants_South and Central America',
       'Immigrants_Turkey', 'Socioeconomy_Self-employed',
       'Socioeconomy_Top executives', 'Socioeconomy_Unemployed'],
      dtype='object')

# Export as CSV

In [ ]:
df.to_csv("../../../processed-data/demographics/relative_2021.csv", index=False)