Notebook for creating relative_2013, where all data is % of the different totals for easier comparison across polling areas (instead of absolute numbers).

# Initial Steps

In [1]:
import pandas as pd 

path = "../../../processed-data/demographics/absolute_2013.csv"

df = pd.read_csv(path)
df.head()

,Gruppe,ValgstedId,Valgsted navn,KredsNr,Kreds navn,Kommune navn,Population,Sex_Female,Sex_Male,Age_0-4 years,...,Immigrants_Not specified,Immigrants_Old EU countries,Immigrants_Other Europe,Immigrants_South and Central America,Immigrants_Total,Immigrants_Turkey,Socioeconomy_Self-employed,Socioeconomy_Top executives,Socioeconomy_Total,Socioeconomy_Unemployed
0,101001,101001,1. Østerbro,1,1. Østerbro,København,14208.62,7477.66,6730.96,889.24,...,1.54,532.49,68.55,97.08,2012.52,42.35,532.47,317.48,14168.08,325.19
1,101002,101002,1. Nord,1,1. Østerbro,København,7955.00,4278.00,3677.00,439.00,...,1.00,329.00,53.00,41.00,1486.00,52.00,336.00,192.00,7936.00,178.00
2,101003,101003,1. Syd,1,1. Østerbro,København,16249.93,8369.10,7880.83,1058.14,...,2.43,660.02,101.56,112.07,2475.85,50.79,628.61,434.36,16217.55,345.72
3,101005,101005,1. Vest,1,1. Østerbro,København,15340.00,7919.00,7421.00,937.00,...,4.00,664.00,117.00,106.00,3258.00,151.00,398.00,201.00,15328.00,409.00
4,101006,101006,1. Nordvest,1,1. Østerbro,København,13207.00,6817.00,6390.00,817.00,...,0.00,391.00,100.00,91.00,2675.00,107.00,394.00,223.00,13159.00,336.00

In [2]:
print(df.columns)

Index(['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn',
       'Kommune navn', 'Population', 'Sex_Female', 'Sex_Male', 'Age_0-4 years',
       'Age_10-14 years', 'Age_15-17 years', 'Age_18-19 years',
       'Age_20-24 years', 'Age_25-29 years', 'Age_30-34 years',
       'Age_35-39 years', 'Age_40-44 years', 'Age_45-49 years',
       'Age_5-9 years', 'Age_50-54 years', 'Age_55-59 years',
       'Age_60-64 years', 'Age_65-69 years', 'Age_70- years',
       'Citizenship_Africa', 'Citizenship_Asia and Oceania',
       'Citizenship_Denmark', 'Citizenship_Former Yugoslavia',
       'Citizenship_New EU countries', 'Citizenship_Nordic',
       'Citizenship_North America', 'Citizenship_Not specified',
       'Citizenship_Old EU countries', 'Citizenship_Other Europe',
       'Citizenship_South and Central America', 'Citizenship_Turkey',
       'Income_Gross income top20pct', 'Income_Median household income',
       'Income_Total households', 'Car_Households with 1 car',
       'Car_Households with 2+ cars', 'Car_Households with no car',
       'Crime_Number of arrests', 'Benefit type_Foertidspension',
       'Benefit type_Folkepension', 'Benefit type_Kontanthjaelp',
       'Benefit type_Modtager ikke ydelser',
       'Housing type_Homes_Apartment buildings',
       'Housing type_Homes_Detached house',
       'Housing type_Homes_Terraced house',
       'Housing type_People_Apartment buildings',
       'Housing type_People_Detached house',
       'Housing type_People_Terraced house', 'Housing type_Total homes',
       'Housing tenure_Homes_Almen', 'Housing tenure_Homes_Andel',
       'Housing tenure_Homes_Ejer', 'Housing tenure_Homes_Private rental',
       'Housing tenure_People_Almen', 'Housing tenure_People_Andel',
       'Housing tenure_People_Ejer', 'Housing tenure_People_Private rental',
       'Housing tenure_Total homes', 'Housing tenure_Total people',
       'Education_18-29 years_Long higher education',
       'Education_18-29 years_Not specified',
       'Education_18-29 years_Primary and lower secondary',
       'Education_18-29 years_Vocational training',
       'Education_30-70+ years_Long higher education',
       'Education_30-70+ years_Not specified',
       'Education_30-70+ years_Primary and lower secondary',
       'Education_30-70+ years_Vocational training', 'Education_Total',
       'Education_Total 18-29 years', 'Education_Total 30-70+ years',
       'Immigrants_Africa', 'Immigrants_Asia and Oceania',
       'Immigrants_Former Yugoslavia', 'Immigrants_New EU countries',
       'Immigrants_Nordic', 'Immigrants_North America',
       'Immigrants_Not specified', 'Immigrants_Old EU countries',
       'Immigrants_Other Europe', 'Immigrants_South and Central America',
       'Immigrants_Total', 'Immigrants_Turkey', 'Socioeconomy_Self-employed',
       'Socioeconomy_Top executives', 'Socioeconomy_Total',
       'Socioeconomy_Unemployed'],
      dtype='object')

# Calculations

The results of the following will be floats, and omit "%" sign at the end of each value.

'Citizenship_ 'Housing type_People_ 'Benefit type_ 'Sex_ 'Age_' 'Crime_' with 'Population' as the total to get the relative

In [3]:
df['Crime_Number of arrests'] = (df['Crime_Number of arrests']/df['Population'])*100

df['Sex_Female'] = (df['Sex_Female']/df['Population'])*100
df['Sex_Male'] = (df['Sex_Male']/df['Population'])*100

df['Age_0-4 years'] = (df['Age_0-4 years']/df['Population'])*100
df['Age_10-14 years'] = (df['Age_10-14 years']/df['Population'])*100
df['Age_15-17 years'] = (df['Age_15-17 years']/df['Population'])*100
df['Age_18-19 years'] = (df['Age_18-19 years']/df['Population'])*100
df['Age_20-24 years'] = (df['Age_20-24 years']/df['Population'])*100
df['Age_25-29 years'] = (df['Age_25-29 years']/df['Population'])*100
df['Age_30-34 years'] = (df['Age_30-34 years']/df['Population'])*100
df['Age_35-39 years'] = (df['Age_35-39 years']/df['Population'])*100
df['Age_40-44 years'] = (df['Age_40-44 years']/df['Population'])*100
df['Age_45-49 years'] = (df['Age_45-49 years']/df['Population'])*100
df['Age_5-9 years'] = (df['Age_5-9 years']/df['Population'])*100
df['Age_50-54 years'] = (df['Age_50-54 years']/df['Population'])*100
df['Age_55-59 years'] = (df['Age_55-59 years']/df['Population'])*100
df['Age_60-64 years'] = (df['Age_60-64 years']/df['Population'])*100
df['Age_65-69 years'] = (df['Age_65-69 years']/df['Population'])*100
df['Age_70- years'] = (df['Age_70- years']/df['Population'])*100

df['Citizenship_Africa'] = (df['Citizenship_Africa']/df['Population'])*100
df['Citizenship_Asia and Oceania'] = (df['Citizenship_Asia and Oceania']/df['Population'])*100
df['Citizenship_Denmark'] = (df['Citizenship_Denmark']/df['Population'])*100
df['Citizenship_Former Yugoslavia'] = (df['Citizenship_Former Yugoslavia']/df['Population'])*100
df['Citizenship_New EU countries'] = (df['Citizenship_New EU countries']/df['Population'])*100
df['Citizenship_Nordic'] = (df['Citizenship_Nordic']/df['Population'])*100
df['Citizenship_North America'] = (df['Citizenship_North America']/df['Population'])*100
df['Citizenship_Old EU countries'] = (df['Citizenship_Old EU countries']/df['Population'])*100
df['Citizenship_Other Europe'] = (df['Citizenship_Other Europe']/df['Population'])*100
df['Citizenship_South and Central America'] = (df['Citizenship_South and Central America']/df['Population'])*100
df['Citizenship_Turkey'] = (df['Citizenship_Turkey']/df['Population'])*100
df['Citizenship_Not specified'] = (df['Citizenship_Not specified']/df['Population'])*100

df['Housing type_People_Apartment buildings'] = (df['Housing type_People_Apartment buildings']/df['Population'])*100
df['Housing type_People_Detached house'] = (df['Housing type_People_Detached house']/df['Population'])*100
df['Housing type_People_Terraced house'] = (df['Housing type_People_Terraced house']/df['Population'])*100

df['Benefit type_Foertidspension'] = (df['Benefit type_Foertidspension']/df['Population'])*100
df['Benefit type_Folkepension'] = (df['Benefit type_Folkepension']/df['Population'])*100
df['Benefit type_Kontanthjaelp'] = (df['Benefit type_Kontanthjaelp']/df['Population'])*100
df['Benefit type_Modtager ikke ydelser'] = (df['Benefit type_Modtager ikke ydelser']/df['Population'])*100

Socioeconomy_ with Socioeconomy_Total

In [4]:
df['Socioeconomy_Self-employed'] = (df['Socioeconomy_Self-employed']/df['Socioeconomy_Total'])*100
df['Socioeconomy_Top executives'] = (df['Socioeconomy_Top executives']/df['Socioeconomy_Total'])*100
df['Socioeconomy_Unemployed'] = (df['Socioeconomy_Unemployed']/df['Socioeconomy_Total'])*100

Immigrants_ with Immigrants_Total

In [5]:
df['Immigrants_Africa'] = (df['Immigrants_Africa']/df['Immigrants_Total'])*100
df['Immigrants_Asia and Oceania'] = (df['Immigrants_Asia and Oceania']/df['Immigrants_Total'])*100
df['Immigrants_Former Yugoslavia'] = (df['Immigrants_Former Yugoslavia']/df['Immigrants_Total'])*100
df['Immigrants_New EU countries'] = (df['Immigrants_New EU countries']/df['Immigrants_Total'])*100
df['Immigrants_Nordic'] = (df['Immigrants_Nordic']/df['Immigrants_Total'])*100
df['Immigrants_North America'] = (df['Immigrants_North America']/df['Immigrants_Total'])*100
df['Immigrants_Not specified'] = (df['Immigrants_Not specified']/df['Immigrants_Total'])*100
df['Immigrants_Old EU countries'] = (df['Immigrants_Old EU countries']/df['Immigrants_Total'])*100
df['Immigrants_Other Europe'] = (df['Immigrants_Other Europe']/df['Immigrants_Total'])*100
df['Immigrants_South and Central America'] = (df['Immigrants_South and Central America']/df['Immigrants_Total'])*100
df['Immigrants_Turkey'] = (df['Immigrants_Turkey']/df['Immigrants_Total'])*100

Education_ with Education_Total

In [6]:
df['Education_18-29 years_Long higher education'] = (df['Education_18-29 years_Long higher education']/df['Education_Total'])*100
df['Education_18-29 years_Not specified'] = (df['Education_18-29 years_Not specified']/df['Education_Total'])*100
df['Education_18-29 years_Primary and lower secondary'] = (df['Education_18-29 years_Primary and lower secondary']/df['Education_Total'])*100
df['Education_18-29 years_Vocational training'] = (df['Education_18-29 years_Vocational training']/df['Education_Total'])*100
df['Education_30-70+ years_Long higher education'] = (df['Education_30-70+ years_Long higher education']/df['Education_Total'])*100
df['Education_30-70+ years_Not specified'] = (df['Education_30-70+ years_Not specified']/df['Education_Total'])*100
df['Education_30-70+ years_Primary and lower secondary'] = (df['Education_30-70+ years_Primary and lower secondary']/df['Education_Total'])*100
df['Education_30-70+ years_Vocational training'] = (df['Education_30-70+ years_Vocational training']/df['Education_Total'])*100
df['Education_Total 18-29 years'] = (df['Education_Total 18-29 years']/df['Education_Total'])*100
df['Education_Total 30-70+ years'] = (df['Education_Total 30-70+ years']/df['Education_Total'])*100

Housing tenure_People_ with Housing tenure_Total people

In [7]:
df['Housing tenure_People_Almen'] = (df['Housing tenure_People_Almen']/df['Housing tenure_Total people'])*100
df['Housing tenure_People_Andel'] = (df['Housing tenure_People_Andel']/df['Housing tenure_Total people'])*100
df['Housing tenure_People_Ejer'] = (df['Housing tenure_People_Ejer']/df['Housing tenure_Total people'])*100
df['Housing tenure_People_Private rental'] = (df['Housing tenure_People_Private rental']/df['Housing tenure_Total people'])*100

Housing tenure_Homes_ with Housing tenure_Total homes

In [8]:
df['Housing tenure_Homes_Almen'] = (df['Housing tenure_Homes_Almen']/df['Housing tenure_Total homes'])*100
df['Housing tenure_Homes_Andel'] = (df['Housing tenure_Homes_Almen']/df['Housing tenure_Total homes'])*100
df['Housing tenure_Homes_Ejer'] = (df['Housing tenure_Homes_Almen']/df['Housing tenure_Total homes'])*100
df['Housing tenure_Homes_Private rental'] = (df['Housing tenure_Homes_Almen']/df['Housing tenure_Total homes'])*100

Housing type_Homes with Housing type_Total homes

In [9]:
df['Housing type_Homes_Apartment buildings'] = (df['Housing type_Homes_Apartment buildings']/df['Housing type_Total homes'])*100
df['Housing type_Homes_Detached house'] = (df['Housing type_Homes_Detached house']/df['Housing type_Total homes'])*100
df['Housing type_Homes_Terraced house'] = (df['Housing type_Homes_Terraced house']/df['Housing type_Total homes'])*100

Car_ with (pre-calculated) total households from all three car columns

In [10]:
df['Car total_households'] = (df['Car_Households with 1 car']+df['Car_Households with 2+ cars']+df['Car_Households with no car'])

In [11]:
df['Car_Households with 1 car'] = (df['Car_Households with 1 car']/df['Car total_households'])*100
df['Car_Households with 2+ cars'] = (df['Car_Households with 2+ cars']/df['Car total_households'])*100
df['Car_Households with no car'] = (df['Car_Households with no car']/df['Car total_households'])*100

Income_Median household income LEAVE AS IS

Income_Gross income top20pct with Income_Total households

In [12]:
df['Income_Gross income top20pct'] = (df['Income_Gross income top20pct']/df['Income_Total households'])*100

# Dropp Columns With Total Values

Note to self, keep all columns before 'Population' as they are.

In [13]:
df.drop(['Population', 'Socioeconomy_Total','Immigrants_Total','Education_Total','Housing tenure_Total people','Housing tenure_Total homes','Housing type_Total homes','Car total_households','Income_Total households'], axis=1, inplace=True)
df.head()

,Gruppe,ValgstedId,Valgsted navn,KredsNr,Kreds navn,Kommune navn,Sex_Female,Sex_Male,Age_0-4 years,Age_10-14 years,...,Immigrants_Nordic,Immigrants_North America,Immigrants_Not specified,Immigrants_Old EU countries,Immigrants_Other Europe,Immigrants_South and Central America,Immigrants_Turkey,Socioeconomy_Self-employed,Socioeconomy_Top executives,Socioeconomy_Unemployed
0,101001,101001,1. Østerbro,1,1. Østerbro,København,52.627630,47.372370,6.258454,4.018687,...,14.701469,6.085902,0.076521,26.458867,3.406177,4.823803,2.104327,3.758237,2.240812,2.295230
1,101002,101002,1. Nord,1,1. Østerbro,København,53.777498,46.222502,5.518542,4.399749,...,9.286676,3.230148,0.067295,22.139973,3.566622,2.759085,3.499327,4.233871,2.419355,2.242944
2,101003,101003,1. Syd,1,1. Østerbro,København,51.502376,48.497624,6.511659,4.637005,...,16.438799,5.988246,0.098148,26.658319,4.102026,4.526526,2.051417,3.876110,2.678333,2.131765
3,101005,101005,1. Vest,1,1. Østerbro,København,51.623207,48.376793,6.108214,3.487614,...,9.330878,5.033763,0.122775,20.380602,3.591160,3.253530,4.634745,2.596555,1.311326,2.668319
4,101006,101006,1. Nordvest,1,1. Østerbro,København,51.616567,48.383433,6.186113,4.050882,...,8.149533,3.028037,0.000000,14.616822,3.738318,3.401869,4.000000,2.994148,1.694658,2.553386

In [14]:
print(df.columns)

Index(['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn',
       'Kommune navn', 'Sex_Female', 'Sex_Male', 'Age_0-4 years',
       'Age_10-14 years', 'Age_15-17 years', 'Age_18-19 years',
       'Age_20-24 years', 'Age_25-29 years', 'Age_30-34 years',
       'Age_35-39 years', 'Age_40-44 years', 'Age_45-49 years',
       'Age_5-9 years', 'Age_50-54 years', 'Age_55-59 years',
       'Age_60-64 years', 'Age_65-69 years', 'Age_70- years',
       'Citizenship_Africa', 'Citizenship_Asia and Oceania',
       'Citizenship_Denmark', 'Citizenship_Former Yugoslavia',
       'Citizenship_New EU countries', 'Citizenship_Nordic',
       'Citizenship_North America', 'Citizenship_Not specified',
       'Citizenship_Old EU countries', 'Citizenship_Other Europe',
       'Citizenship_South and Central America', 'Citizenship_Turkey',
       'Income_Gross income top20pct', 'Income_Median household income',
       'Car_Households with 1 car', 'Car_Households with 2+ cars',
       'Car_Households with no car', 'Crime_Number of arrests',
       'Benefit type_Foertidspension', 'Benefit type_Folkepension',
       'Benefit type_Kontanthjaelp', 'Benefit type_Modtager ikke ydelser',
       'Housing type_Homes_Apartment buildings',
       'Housing type_Homes_Detached house',
       'Housing type_Homes_Terraced house',
       'Housing type_People_Apartment buildings',
       'Housing type_People_Detached house',
       'Housing type_People_Terraced house', 'Housing tenure_Homes_Almen',
       'Housing tenure_Homes_Andel', 'Housing tenure_Homes_Ejer',
       'Housing tenure_Homes_Private rental', 'Housing tenure_People_Almen',
       'Housing tenure_People_Andel', 'Housing tenure_People_Ejer',
       'Housing tenure_People_Private rental',
       'Education_18-29 years_Long higher education',
       'Education_18-29 years_Not specified',
       'Education_18-29 years_Primary and lower secondary',
       'Education_18-29 years_Vocational training',
       'Education_30-70+ years_Long higher education',
       'Education_30-70+ years_Not specified',
       'Education_30-70+ years_Primary and lower secondary',
       'Education_30-70+ years_Vocational training',
       'Education_Total 18-29 years', 'Education_Total 30-70+ years',
       'Immigrants_Africa', 'Immigrants_Asia and Oceania',
       'Immigrants_Former Yugoslavia', 'Immigrants_New EU countries',
       'Immigrants_Nordic', 'Immigrants_North America',
       'Immigrants_Not specified', 'Immigrants_Old EU countries',
       'Immigrants_Other Europe', 'Immigrants_South and Central America',
       'Immigrants_Turkey', 'Socioeconomy_Self-employed',
       'Socioeconomy_Top executives', 'Socioeconomy_Unemployed'],
      dtype='object')

# Export as CSV

In [15]:
df.to_csv("../../../processed-data/demographics/relative_2013.csv", index=False)