The point of this notebook is to explore what party letters/symbols belongs to which party names, this is done by looking at our processed election data and manually comparing it with 'kandidatlister' on valg.dk

In [18]:
import pandas as pd
ROOT = '../../../'
PATH = ROOT + 'processed-data/elections/'

In [19]:
filename = PATH + 'absolute_2013.csv'
cols = ['Gruppe', 'PollingAreaID', 'Name', 'District', 'Municipality', '01', '02', '03', '04', '05', '06']
df = pd.read_csv(filename, usecols=cols)
df.head(10)

,Gruppe,PollingAreaID,Name,District,Municipality,01,02,03,04,05,06
0,101001,101001,1. Østerbro,1. Østerbro,København,3.08,6.16,10.79,3.08,1.54,2.31
1,101002,101002,1. Nord,1. Østerbro,København,0.00,1.00,6.00,6.00,0.00,0.00
2,101003,101003,1. Syd,1. Østerbro,København,3.22,11.28,11.28,8.86,0.81,0.81
3,101005,101005,1. Vest,1. Østerbro,København,1.00,9.00,16.00,10.00,1.00,1.00
4,101006,101006,1. Nordvest,1. Østerbro,København,11.00,7.00,9.00,6.00,2.00,1.00
5,101007,101007,2. Sundbyvester,2. Sundbyvester,København,10.40,8.92,13.37,5.20,0.00,0.74
6,101008,101010;101008,2. Vest;2. Nord,2. Sundbyvester,København,5.00,24.00,27.00,12.00,13.00,2.00
7,101009,101009,2. Syd,2. Sundbyvester,København,1.70,7.67,10.22,3.41,3.41,0.85
8,101011,101011,3. Indre By,3. Indre By,København,3.00,7.00,12.00,7.00,3.00,3.00
9,101012,101012,3. Nord,3. Indre By,København,2.00,2.00,3.00,0.00,1.00,1.00

Crosschecked '1. Nordvest' votes on valg.dk and matched the weird numbers instead of party letters to:
```
2013;København;01;Copenhagen
2013;København;02;Det Grønne Parti/Danish Green Party
2013;København;03;Dovne Robert
2013;København;04;Forenede demokrater
2013;København;05;Havnefronten
2013;København;06;Sunshine Partiet
```
in parties.csv

In [20]:
filename = PATH + 'absolute_2009.csv'
cols = ['Gruppe', 'PollingAreaID', 'Name', 'District', 'Municipality', '1','2','3']
df = pd.read_csv(filename, usecols=cols)
df.head(10)

,Gruppe,PollingAreaID,Name,District,Municipality,1,2,3
0,101001,101001,1. Østerbro,1. Østerbro,København,0.78,2.35,0.78
1,101002,101002,1. Nord,1. Østerbro,København,0.00,0.00,2.00
2,101003,101003,1. Syd,1. Østerbro,København,2.00,2.65,2.29
3,101005,101005,1. Vest,1. Østerbro,København,4.00,2.00,1.00
4,101006,101006,1. Nordvest,1. Østerbro,København,5.00,1.00,0.00
5,101007,101007,2. Sundbyvester,2. Sundbyvester,København,4.45,0.00,0.74
6,101008,101010;101008,2. Vest;2. Nord,2. Sundbyvester,København,6.00,1.00,2.00
7,101009,101009,2. Syd,2. Sundbyvester,København,2.60,0.87,0.87
8,101011,101011,3. Indre By,3. Indre By,København,5.49,4.98,5.00
9,101012,101012,3. Nord,3. Indre By,København,5.00,1.00,2.00

Crosschecked '3. Nord' votes on valg.dk and matched the weird numbers instead of party letters to:
```
2009;København;1;Cykel Logisk Institut
2009;København;2;Gordon eller Kaos Lib.socialistern
2009;København;3;Sunshine Partiet
```
in parties.csv

In [21]:
PATH = ROOT + 'raw-data/historical-elections/election-results/'
filename = PATH + 'ElectionData.csv'
all_columns = pd.read_csv(filename, sep=';', nrows=0).columns.tolist()
cols = ['Gruppe', 'ValgstedId'] + [col for col in all_columns if col.startswith('KV2021')]
df = pd.read_csv(filename, sep=';', usecols=cols)
print(df.columns)

Index(['Gruppe', 'ValgstedId', 'KV2021 - Stemmeberettigede',
       'KV2021 - Afgivne stemmer', 'KV2021 - Blanke stemmer',
       'KV2021 - Andre ugyldige stemmer', 'KV2021 - Gyldige stemmer',
       'KV2021 - A', 'KV2021 - B', 'KV2021 - C', 'KV2021 - D', 'KV2021 - F',
       'KV2021 - I', 'KV2021 - J', 'KV2021 - G', 'KV2021 - K', 'KV2021 - N',
       'KV2021 - H', 'KV2021 - M', 'KV2021 - S', 'KV2021 - U', 'KV2021 - Y',
       'KV2021 - O', 'KV2021 - Z', 'KV2021 - L', 'KV2021 - Q', 'KV2021 - R',
       'KV2021 - V', 'KV2021 - P', 'KV2021 - E', 'KV2021 - Ø', 'KV2021 - Å',
       'KV2021 - 1', 'KV2021 - 2', 'KV2021 - 3', 'KV2021 - 4', 'KV2021 - 5',
       'KV2021 - 6', 'KV2021 - 0', 'KV2021 - 01', 'KV2021 - 02', 'KV2021 - 03',
       'KV2021 - 04', 'KV2021 - 05', 'KV2021 - 06', 'KV2021 - 7',
       'KV2021 - K1', 'KV2021 - K2', 'KV2021 - T', 'KV2021 - W', 'KV2021 - Æ',
       'KV2021 - Å1'],
      dtype='object')

In [ ]:
cols_to_drop = ['KV2021 - Stemmeberettigede','KV2021 - Afgivne stemmer','KV2021 - Blanke stemmer','KV2021 - Andre ugyldige stemmer','KV2021 - Gyldige stemmer']
df = df.drop(cols_to_drop, axis=1)

,Gruppe,ValgstedId,KV2021 - A,KV2021 - B,KV2021 - C,KV2021 - D,KV2021 - F,KV2021 - I,KV2021 - J,KV2021 - G,KV2021 - K,KV2021 - N,KV2021 - H,KV2021 - M,KV2021 - S,KV2021 - U,KV2021 - Y,KV2021 - O,KV2021 - Z,KV2021 - L,KV2021 - Q,KV2021 - R,KV2021 - V,KV2021 - P,KV2021 - E,KV2021 - Ø,KV2021 - Å,KV2021 - 1,KV2021 - 2,KV2021 - 3,KV2021 - 4,KV2021 - 5,KV2021 - 6,KV2021 - 0,KV2021 - 01,KV2021 - 02,KV2021 - 03,KV2021 - 04,KV2021 - 05,KV2021 - 06,KV2021 - 7,KV2021 - K1,KV2021 - K2,KV2021 - T,KV2021 - W,KV2021 - Æ,KV2021 - Å1
0,101001,101001,1321,1112,1612,145,851,280,13,42,32,7,8,18,-,68,12,117,11,31,10,16,731,2,2,1532,217,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,24,-,11,-
1,101002,101002,702,535,966,101,398,170,15,7,17,6,3,13,-,38,6,87,2,16,2,13,515,0,4,699,102,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,20,-,3,-
2,101003,101003,1401,1256,1652,146,967,255,9,37,33,2,5,24,-,115,9,85,4,35,6,23,757,1,6,1893,215,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,28,-,8,-
3,101005,101005,1392,888,1136,174,813,192,19,50,50,6,8,41,-,85,15,148,16,30,7,28,588,0,6,1599,185,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,24,-,8,-
4,101006,101006,1278,903,1141,163,734,222,9,54,23,6,5,30,-,71,8,132,9,25,5,15,581,3,5,1282,170,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,32,-,10,-
5,101007,101007,1323,547,567,184,609,133,9,31,25,11,8,25,-,40,18,242,6,37,9,23,401,2,7,1528,160,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,34,-,4,-
6,101008,101010;101008,2596,2032,2315,387,1711,465,23,73,61,29,15,59,-,127,37,301,23,146,17,57,1571,6,18,4304,535,-,-,-,-,-,-,6,-,-,-,-,-,-,-,-,-,67,-,14,-
7,101009,101009,1146,986,1069,216,761,342,9,68,31,4,11,42,-,64,10,113,15,44,15,28,1058,3,2,1372,225,-,-,-,-,-,-,73,-,-,-,-,-,-,-,-,-,31,-,3,-
8,101011,101011,1110,1255,1780,185,812,386,8,63,22,8,6,35,-,88,14,84,10,104,14,28,787,3,13,2212,276,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,27,-,13,-
9,101012,101012,675,698,1184,80,453,178,6,30,20,4,7,6,-,45,6,72,2,25,8,6,518,2,2,999,120,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,15,-,4,-
10,101013,101013,1115,759,855,136,650,181,35,52,22,15,6,16,-,74,22,87,9,62,18,28,464,2,54,2523,331,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,30,-,11,-
11,101014,101057;101014,2035,1672,2541,334,1385,565,7,69,48,16,11,42,-,108,18,245,20,110,19,28,1355,0,16,3093,392,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,33,-,8,-
12,101016,101016,1251,837,896,207,824,236,13,59,21,9,8,25,-,54,14,210,16,39,5,22,636,0,10,1654,219,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,34,-,13,-
13,101017,101017,1576,1041,988,195,1072,262,18,64,39,18,12,46,-,100,21,250,15,42,10,40,609,2,12,2425,328,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,58,-,12,-
14,101018,101018,1126,503,648,146,657,113,16,22,29,5,5,16,-,41,7,175,8,32,10,18,395,0,4,1267,152,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,28,-,8,-
15,101019,101019,1294,719,902,173,880,179,5,35,25,2,4,17,-,34,7,163,6,29,4,14,582,3,3,1238,177,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,19,-,7,-
16,101020,101020,677,542,294,44,604,48,10,46,27,7,2,36,-,56,4,60,14,20,8,29,211,1,9,1725,187,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,20,-,7,-
17,101021,101021,938,1099,599,84,969,163,25,51,27,8,5,76,-,126,13,77,14,23,21,38,450,3,8,2397,277,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,23,-,12,-
18,101022,101022,571,583,418,53,455,59,3,29,17,10,3,33,-,49,11,62,7,16,8,36,224,1,9,1688,133,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,15,-,11,-
19,101023,101023,621,754,533,48,562,129,14,30,9,5,4,21,-,79,6,35,8,19,10,30,333,1,0,1669,223,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,17,-,11,-
20,101024,101024,762,601,438,59,679,82,7,43,13,7,4,33,-,40,3,66,6,21,7,28,285,1,6,1788,178,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,12,-,9,-
21,101025,101025,761,1000,447,68,979,106,16,44,15,11,2,49,-,97,8,62,22,29,10,53,316,0,8,2618,281,-,-,-,-,-,-,5,-,-,-,-,-,-,-,-,-,23,-,8,-
22,101027,101027,1018,853,490,135,806,132,15,56,29,8,6,58,-,86,15,143,29,10,13,48,355,4,9,2302,270,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,21,-,13,-
23,101028,101028,1136,442,495,114,514,76,13,45,35,7,2,29,-,31,10,139,12,7,8,22,272,4,6,1136,92,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,23,-,7,-
24,101029,101029,710,246,276,89,300,64,4,17,11,5,2,22,-,20,2,84,1,1,4,8,140,1,4,542,50,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,20,-,6,-
25,101030,101030,1025,788,436,123,725,135,22,42,27,12,6,37,-,71,8,111,15,11,15,49,331,2,5,2140,233,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,38,-,8,-
26,101031,101031,720,263,460,65,336,60,8,20,10,2,1,7,-,25,4,75,3,5,2,9,151,1,0,556,54,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,7,-,2,-
27,101032,101032,343,175,76,24,156,10,2,5,8,1,1,35,-,11,1,44,0,2,0,3,28,2,2,481,20,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,6,-,2,-
28,101033,101033,1073,592,666,141,608,123,9,31,31,6,1,15,-,53,8,129,7,6,9,11,369,1,2,1057,123,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,18,-,4,-
29,101034,101034,1457,529,650,108,699,80,12,31,20,9,1,28,-,48,5,148,7,10,2,16,251,1,4,1400,109,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,14,-,5,-
30,101035,101035,1128,318,454,80,396,56,10,16,20,2,6,23,-,17,7,179,5,8,5,10,169,2,6,786,44,-,-,-,-,-,-,5,-,-,-,-,-,-,-,-,-,11,-,4,-
31,101036,101036,1669,437,838,161,614,69,16,23,29,4,2,29,-,33,2,201,0,14,6,26,267,1,5,952,81,-,-,-,-,-,-,4,-,-,-,-,-,-,-,-,-,15,-,6,-
32,101039,101039,698,378,475,94,371,99,5,14,9,4,1,7,-,24,3,66,4,4,3,11,286,0,3,642,88,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,7,-,5,-
33,101040,101040,870,426,563,107,463,89,9,17,19,5,1,11,-,38,5,91,0,13,1,10,284,0,4,752,78,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,6,-,1,-
34,101041,101041,1545,736,1033,180,772,212,12,38,46,6,3,24,-,52,6,204,8,18,8,22,572,2,4,1315,105,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,35,-,9,-
35,101042,101042,1150,632,799,177,744,155,10,25,16,4,7,17,-,46,7,113,3,12,9,20,503,1,0,1060,147,-,-,-,-,-,-,4,-,-,-,-,-,-,-,-,-,27,-,8,-
36,101043,101043,1226,743,845,122,736,162,15,37,29,2,0,7,-,52,17,126,4,20,2,21,537,0,3,1243,164,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,21,-,6,-
37,101044,101044,1182,639,724,136,574,170,6,27,17,5,2,36,-,28,13,130,6,11,6,21,522,1,3,899,122,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,24,-,6,-
38,101046,101046,701,276,351,91,336,63,2,22,23,1,1,18,-,21,4,124,8,14,3,12,221,0,1,495,64,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,16,-,4,-
39,101047,101047,685,352,310,95,352,84,7,16,11,7,5,21,-,47,6,70,1,8,1,11,230,2,5,718,78,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,11,-,7,-
40,101048,101048,980,650,779,130,591,183,8,25,28,4,4,25,-,51,5,112,7,24,6,20,475,0,5,1025,121,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,28,-,3,-
41,101049,101049,826,656,530,58,767,99,11,32,8,7,7,12,-,79,10,66,5,27,7,19,288,1,4,1873,251,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,12,-,6,-
42,101050,101050,790,869,653,79,742,145,16,23,9,10,2,19,-,90,11,51,4,27,9,17,374,4,8,1836,245,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,20,-,6,-
43,101051,101051,1104,360,299,177,476,89,18,33,22,12,5,36,-,48,18,193,8,31,10,114,229,5,7,1803,151,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,24,-,11,-
44,101052,101052,654,661,570,61,604,131,7,40,20,2,4,10,-,62,8,46,8,29,9,16,380,0,8,1465,229,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,14,-,7,-
45,101053,101053,787,777,654,68,632,153,12,23,15,5,4,17,-,75,9,58,11,33,7,21,388,0,2,1472,181,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,13,-,4,-
46,101054,101054,318,237,151,49,263,56,8,16,9,3,2,15,-,26,6,37,6,1,5,18,144,0,1,687,78,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,13,-,7,-
47,101055,101055,1145,1299,1581,179,665,486,11,60,19,5,3,23,-,75,8,76,7,41,4,11,1158,2,3,1228,236,-,-,-,-,-,-,4,-,-,-,-,-,-,-,-,-,15,-,7,-
48,101056,101056,762,766,1360,132,484,336,6,24,18,3,3,7,-,51,6,62,5,39,8,6,813,0,2,822,134,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,22,-,4,-
49,101058,101058,866,904,403,69,879,132,6,56,23,8,3,90,-,83,11,73,10,9,16,41,318,3,8,2473,270,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,26,-,10,-

In [27]:
pd.set_option('display.max_columns', None)  # None means no limit
df.head(58)

,Gruppe,ValgstedId,KV2021 - A,KV2021 - B,KV2021 - C,KV2021 - D,KV2021 - F,KV2021 - I,KV2021 - J,KV2021 - G,KV2021 - K,KV2021 - N,KV2021 - H,KV2021 - M,KV2021 - S,KV2021 - U,KV2021 - Y,KV2021 - O,KV2021 - Z,KV2021 - L,KV2021 - Q,KV2021 - R,KV2021 - V,KV2021 - P,KV2021 - E,KV2021 - Ø,KV2021 - Å,KV2021 - 1,KV2021 - 2,KV2021 - 3,KV2021 - 4,KV2021 - 5,KV2021 - 6,KV2021 - 0,KV2021 - 01,KV2021 - 02,KV2021 - 03,KV2021 - 04,KV2021 - 05,KV2021 - 06,KV2021 - 7,KV2021 - K1,KV2021 - K2,KV2021 - T,KV2021 - W,KV2021 - Æ,KV2021 - Å1
0,101001,101001,1321,1112,1612,145,851,280,13,42,32,7,8,18,-,68,12,117,11,31,10,16,731,2,2,1532,217,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,24,-,11,-
1,101002,101002,702,535,966,101,398,170,15,7,17,6,3,13,-,38,6,87,2,16,2,13,515,0,4,699,102,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,20,-,3,-
2,101003,101003,1401,1256,1652,146,967,255,9,37,33,2,5,24,-,115,9,85,4,35,6,23,757,1,6,1893,215,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,28,-,8,-
3,101005,101005,1392,888,1136,174,813,192,19,50,50,6,8,41,-,85,15,148,16,30,7,28,588,0,6,1599,185,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,24,-,8,-
4,101006,101006,1278,903,1141,163,734,222,9,54,23,6,5,30,-,71,8,132,9,25,5,15,581,3,5,1282,170,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,32,-,10,-
5,101007,101007,1323,547,567,184,609,133,9,31,25,11,8,25,-,40,18,242,6,37,9,23,401,2,7,1528,160,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,34,-,4,-
6,101008,101010;101008,2596,2032,2315,387,1711,465,23,73,61,29,15,59,-,127,37,301,23,146,17,57,1571,6,18,4304,535,-,-,-,-,-,-,6,-,-,-,-,-,-,-,-,-,67,-,14,-
7,101009,101009,1146,986,1069,216,761,342,9,68,31,4,11,42,-,64,10,113,15,44,15,28,1058,3,2,1372,225,-,-,-,-,-,-,73,-,-,-,-,-,-,-,-,-,31,-,3,-
8,101011,101011,1110,1255,1780,185,812,386,8,63,22,8,6,35,-,88,14,84,10,104,14,28,787,3,13,2212,276,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,27,-,13,-
9,101012,101012,675,698,1184,80,453,178,6,30,20,4,7,6,-,45,6,72,2,25,8,6,518,2,2,999,120,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,15,-,4,-
10,101013,101013,1115,759,855,136,650,181,35,52,22,15,6,16,-,74,22,87,9,62,18,28,464,2,54,2523,331,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,30,-,11,-
11,101014,101057;101014,2035,1672,2541,334,1385,565,7,69,48,16,11,42,-,108,18,245,20,110,19,28,1355,0,16,3093,392,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,33,-,8,-
12,101016,101016,1251,837,896,207,824,236,13,59,21,9,8,25,-,54,14,210,16,39,5,22,636,0,10,1654,219,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,34,-,13,-
13,101017,101017,1576,1041,988,195,1072,262,18,64,39,18,12,46,-,100,21,250,15,42,10,40,609,2,12,2425,328,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,58,-,12,-
14,101018,101018,1126,503,648,146,657,113,16,22,29,5,5,16,-,41,7,175,8,32,10,18,395,0,4,1267,152,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,28,-,8,-
15,101019,101019,1294,719,902,173,880,179,5,35,25,2,4,17,-,34,7,163,6,29,4,14,582,3,3,1238,177,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,19,-,7,-
16,101020,101020,677,542,294,44,604,48,10,46,27,7,2,36,-,56,4,60,14,20,8,29,211,1,9,1725,187,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,20,-,7,-
17,101021,101021,938,1099,599,84,969,163,25,51,27,8,5,76,-,126,13,77,14,23,21,38,450,3,8,2397,277,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,23,-,12,-
18,101022,101022,571,583,418,53,455,59,3,29,17,10,3,33,-,49,11,62,7,16,8,36,224,1,9,1688,133,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,15,-,11,-
19,101023,101023,621,754,533,48,562,129,14,30,9,5,4,21,-,79,6,35,8,19,10,30,333,1,0,1669,223,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,17,-,11,-
20,101024,101024,762,601,438,59,679,82,7,43,13,7,4,33,-,40,3,66,6,21,7,28,285,1,6,1788,178,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,12,-,9,-
21,101025,101025,761,1000,447,68,979,106,16,44,15,11,2,49,-,97,8,62,22,29,10,53,316,0,8,2618,281,-,-,-,-,-,-,5,-,-,-,-,-,-,-,-,-,23,-,8,-
22,101027,101027,1018,853,490,135,806,132,15,56,29,8,6,58,-,86,15,143,29,10,13,48,355,4,9,2302,270,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,21,-,13,-
23,101028,101028,1136,442,495,114,514,76,13,45,35,7,2,29,-,31,10,139,12,7,8,22,272,4,6,1136,92,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,23,-,7,-
24,101029,101029,710,246,276,89,300,64,4,17,11,5,2,22,-,20,2,84,1,1,4,8,140,1,4,542,50,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,20,-,6,-
25,101030,101030,1025,788,436,123,725,135,22,42,27,12,6,37,-,71,8,111,15,11,15,49,331,2,5,2140,233,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,38,-,8,-
26,101031,101031,720,263,460,65,336,60,8,20,10,2,1,7,-,25,4,75,3,5,2,9,151,1,0,556,54,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,7,-,2,-
27,101032,101032,343,175,76,24,156,10,2,5,8,1,1,35,-,11,1,44,0,2,0,3,28,2,2,481,20,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,6,-,2,-
28,101033,101033,1073,592,666,141,608,123,9,31,31,6,1,15,-,53,8,129,7,6,9,11,369,1,2,1057,123,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,18,-,4,-
29,101034,101034,1457,529,650,108,699,80,12,31,20,9,1,28,-,48,5,148,7,10,2,16,251,1,4,1400,109,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,14,-,5,-
30,101035,101035,1128,318,454,80,396,56,10,16,20,2,6,23,-,17,7,179,5,8,5,10,169,2,6,786,44,-,-,-,-,-,-,5,-,-,-,-,-,-,-,-,-,11,-,4,-
31,101036,101036,1669,437,838,161,614,69,16,23,29,4,2,29,-,33,2,201,0,14,6,26,267,1,5,952,81,-,-,-,-,-,-,4,-,-,-,-,-,-,-,-,-,15,-,6,-
32,101039,101039,698,378,475,94,371,99,5,14,9,4,1,7,-,24,3,66,4,4,3,11,286,0,3,642,88,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,7,-,5,-
33,101040,101040,870,426,563,107,463,89,9,17,19,5,1,11,-,38,5,91,0,13,1,10,284,0,4,752,78,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,6,-,1,-
34,101041,101041,1545,736,1033,180,772,212,12,38,46,6,3,24,-,52,6,204,8,18,8,22,572,2,4,1315,105,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,35,-,9,-
35,101042,101042,1150,632,799,177,744,155,10,25,16,4,7,17,-,46,7,113,3,12,9,20,503,1,0,1060,147,-,-,-,-,-,-,4,-,-,-,-,-,-,-,-,-,27,-,8,-
36,101043,101043,1226,743,845,122,736,162,15,37,29,2,0,7,-,52,17,126,4,20,2,21,537,0,3,1243,164,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,21,-,6,-
37,101044,101044,1182,639,724,136,574,170,6,27,17,5,2,36,-,28,13,130,6,11,6,21,522,1,3,899,122,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,24,-,6,-
38,101046,101046,701,276,351,91,336,63,2,22,23,1,1,18,-,21,4,124,8,14,3,12,221,0,1,495,64,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,16,-,4,-
39,101047,101047,685,352,310,95,352,84,7,16,11,7,5,21,-,47,6,70,1,8,1,11,230,2,5,718,78,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,11,-,7,-
40,101048,101048,980,650,779,130,591,183,8,25,28,4,4,25,-,51,5,112,7,24,6,20,475,0,5,1025,121,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,28,-,3,-
41,101049,101049,826,656,530,58,767,99,11,32,8,7,7,12,-,79,10,66,5,27,7,19,288,1,4,1873,251,-,-,-,-,-,-,3,-,-,-,-,-,-,-,-,-,12,-,6,-
42,101050,101050,790,869,653,79,742,145,16,23,9,10,2,19,-,90,11,51,4,27,9,17,374,4,8,1836,245,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,20,-,6,-
43,101051,101051,1104,360,299,177,476,89,18,33,22,12,5,36,-,48,18,193,8,31,10,114,229,5,7,1803,151,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,24,-,11,-
44,101052,101052,654,661,570,61,604,131,7,40,20,2,4,10,-,62,8,46,8,29,9,16,380,0,8,1465,229,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,14,-,7,-
45,101053,101053,787,777,654,68,632,153,12,23,15,5,4,17,-,75,9,58,11,33,7,21,388,0,2,1472,181,-,-,-,-,-,-,1,-,-,-,-,-,-,-,-,-,13,-,4,-
46,101054,101054,318,237,151,49,263,56,8,16,9,3,2,15,-,26,6,37,6,1,5,18,144,0,1,687,78,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,13,-,7,-
47,101055,101055,1145,1299,1581,179,665,486,11,60,19,5,3,23,-,75,8,76,7,41,4,11,1158,2,3,1228,236,-,-,-,-,-,-,4,-,-,-,-,-,-,-,-,-,15,-,7,-
48,101056,101056,762,766,1360,132,484,336,6,24,18,3,3,7,-,51,6,62,5,39,8,6,813,0,2,822,134,-,-,-,-,-,-,2,-,-,-,-,-,-,-,-,-,22,-,4,-
49,101058,101058,866,904,403,69,879,132,6,56,23,8,3,90,-,83,11,73,10,9,16,41,318,3,8,2473,270,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,26,-,10,-
50,101059,101059,635,362,270,83,394,33,4,26,20,7,6,45,-,25,6,83,18,11,4,21,156,0,7,1033,87,-,-,-,-,-,-,0,-,-,-,-,-,-,-,-,-,13,-,3,-
51,147001,147001,1072,752,2683,39,348,109,40,22,18,-,3,-,-,-,7,47,-,-,-,-,412,-,4,1359,47,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,22,-,15,-
52,147002,147002,1120,707,3149,48,302,98,41,20,8,-,2,-,-,-,1,32,-,-,-,-,448,-,3,1258,48,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,16,-,9,-
53,147003,147003,1484,1041,3486,64,482,100,51,31,10,-,7,-,-,-,4,43,-,-,-,-,550,-,7,1822,78,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,20,-,14,-
54,147004,147004,1333,919,3279,61,427,101,31,18,12,-,6,-,-,-,5,56,-,-,-,-,592,-,7,1451,70,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,9,-,17,-
55,147005,147005,1575,548,2912,87,370,113,63,32,17,-,5,-,-,-,3,78,-,-,-,-,444,-,11,1345,55,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,9,-,37,-
56,147006,147006,1361,552,3019,66,270,69,47,21,16,-,16,-,-,-,5,81,-,-,-,-,372,-,9,1127,52,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,9,-,16,-
57,147007,147008;147007,2473,1167,6079,119,653,179,101,57,24,-,10,-,-,-,8,88,-,-,-,-,785,-,12,2358,132,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,20,-,26,-