author: loua

Idea:

1. Split historical elections data by year
2. Use these as first columns: 'Gruppe,ValgstedId,Valgsted navn,KredsNr,Kreds navn,Kommune navn,'
3. Drop columns where all are null/0

## Setup

In [ ]:
import pandas as pd

ROOT = '../../../'
PARENT_PATH = ROOT + 'raw-data/historical-elections/election-results/'
FILENAME = PARENT_PATH + 'ElectionData.csv'
OUTPUT_PATH = ROOT + 'processed-data/elections/'
YEARS = [2009, 2013, 2017, 2021]
MUNICIPALITY_IDS = [101, 147]  # Copenhagen and Frederiksberg
COMMON_COLS = ['Gruppe', 'ValgstedId', 'KredsNr', 'StorKredsNr', 'LandsdelsNr']
PREFIX = 'KV'

def find_polling_areas():
    df_geo = pd.read_csv(PARENT_PATH + 'Geography.csv', sep=';')
    cph_areas = set(df_geo[df_geo['KommuneNr'].isin(MUNICIPALITY_IDS)]['Valgsted Id'].astype(str))
    return cph_areas

CPH_AREAS = find_polling_areas()

In [16]:
df = pd.read_csv(FILENAME, sep=';', dtype=str)
df = df[df['Gruppe'].isin(CPH_AREAS)]
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 305 columns):
 #    Column                           Non-Null Count  Dtype
---   ------                           --------------  -----
 0    Gruppe                           58 non-null     object
 1    ValgstedId                       58 non-null     object
 2    KredsNr                          58 non-null     object
 3    StorKredsNr                      58 non-null     object
 4    LandsdelsNr                      58 non-null     object
 5    KV2009 - Stemmeberettigede       58 non-null     object
 6    KV2009 - Afgivne stemmer         58 non-null     object
 7    KV2009 - Blanke stemmer          58 non-null     object
 8    KV2009 - Andre ugyldige stemmer  58 non-null     object
 9    KV2009 - Gyldige stemmer         58 non-null     object
 10   KV2009 - A                       58 non-null     object
 11   KV2009 - B                       58 non-null     object
 12   KV2009 - C                       58 non-null     object
 13   KV2009 - D                       58 non-null     object
 14   KV2009 - F                       58 non-null     object
 15   KV2009 - I                       58 non-null     object
 16   KV2009 - J                       58 non-null     object
 17   KV2009 - G                       58 non-null     object
 18   KV2009 - K                       58 non-null     object
 19   KV2009 - N                       58 non-null     object
 20   KV2009 - H                       58 non-null     object
 21   KV2009 - M                       58 non-null     object
 22   KV2009 - S                       58 non-null     object
 23   KV2009 - U                       58 non-null     object
 24   KV2009 - Y                       58 non-null     object
 25   KV2009 - O                       58 non-null     object
 26   KV2009 - Z                       58 non-null     object
 27   KV2009 - L                       58 non-null     object
 28   KV2009 - Q                       58 non-null     object
 29   KV2009 - R                       58 non-null     object
 30   KV2009 - V                       58 non-null     object
 31   KV2009 - P                       58 non-null     object
 32   KV2009 - E                       58 non-null     object
 33   KV2009 - Ø                       58 non-null     object
 34   KV2009 - Å                       58 non-null     object
 35   KV2009 - 1                       58 non-null     object
 36   KV2009 - 2                       58 non-null     object
 37   KV2009 - 3                       58 non-null     object
 38   KV2009 - 4                       58 non-null     object
 39   KV2009 - 5                       58 non-null     object
 40   KV2009 - 6                       58 non-null     object
 41   KV2009 - 0                       58 non-null     object
 42   KV2009 - 01                      58 non-null     object
 43   KV2009 - 02                      58 non-null     object
 44   KV2009 - 03                      58 non-null     object
 45   KV2009 - 04                      58 non-null     object
 46   KV2009 - 05                      58 non-null     object
 47   KV2009 - 06                      58 non-null     object
 48   KV2009 - 7                       58 non-null     object
 49   KV2009 - K1                      58 non-null     object
 50   KV2009 - K2                      58 non-null     object
 51   KV2009 - T                       58 non-null     object
 52   KV2009 - W                       58 non-null     object
 53   KV2009 - Æ                       58 non-null     object
 54   KV2009 - Å1                      58 non-null     object
 55   KV2013 - Stemmeberettigede       58 non-null     object
 56   KV2013 - Afgivne stemmer         58 non-null     object
 57   KV2013 - Blanke stemmer          58 non-null     object
 58   KV2013 - Andre ugyldige stemmer  58 non-null     object
 59   KV2013 - Gyldige stemmer         58 non-null     object
 60   KV2013 - A                       58 non-null     object
 61   KV2013 - B                       58 non-null     object
 62   KV2013 - C                       58 non-null     object
 63   KV2013 - D                       58 non-null     object
 64   KV2013 - F                       58 non-null     object
 65   KV2013 - I                       58 non-null     object
 66   KV2013 - J                       58 non-null     object
 67   KV2013 - G                       58 non-null     object
 68   KV2013 - K                       58 non-null     object
 69   KV2013 - N                       58 non-null     object
 70   KV2013 - H                       58 non-null     object
 71   KV2013 - M                       58 non-null     object
 72   KV2013 - S                       58 non-null     object
 73   KV2013 - U                       58 non-null     object
 74   KV2013 - Y                       58 non-null     object
 75   KV2013 - O                       58 non-null     object
 76   KV2013 - Z                       58 non-null     object
 77   KV2013 - L                       58 non-null     object
 78   KV2013 - Q                       58 non-null     object
 79   KV2013 - R                       58 non-null     object
 80   KV2013 - V                       58 non-null     object
 81   KV2013 - P                       58 non-null     object
 82   KV2013 - E                       58 non-null     object
 83   KV2013 - Ø                       58 non-null     object
 84   KV2013 - Å                       58 non-null     object
 85   KV2013 - 1                       58 non-null     object
 86   KV2013 - 2                       58 non-null     object
 87   KV2013 - 3                       58 non-null     object
 88   KV2013 - 4                       58 non-null     object
 89   KV2013 - 5                       58 non-null     object
 90   KV2013 - 6                       58 non-null     object
 91   KV2013 - 0                       58 non-null     object
 92   KV2013 - 01                      58 non-null     object
 93   KV2013 - 02                      58 non-null     object
 94   KV2013 - 03                      58 non-null     object
 95   KV2013 - 04                      58 non-null     object
 96   KV2013 - 05                      58 non-null     object
 97   KV2013 - 06                      58 non-null     object
 98   KV2013 - 7                       58 non-null     object
 99   KV2013 - K1                      58 non-null     object
 100  KV2013 - K2                      58 non-null     object
 101  KV2013 - T                       58 non-null     object
 102  KV2013 - W                       58 non-null     object
 103  KV2013 - Æ                       58 non-null     object
 104  KV2013 - Å1                      58 non-null     object
 105  KV2001 - Stemmeberettigede       58 non-null     object
 106  KV2001 - Afgivne stemmer         58 non-null     object
 107  KV2001 - Blanke stemmer          58 non-null     object
 108  KV2001 - Andre ugyldige stemmer  58 non-null     object
 109  KV2001 - Gyldige stemmer         58 non-null     object
 110  KV2001 - A                       58 non-null     object
 111  KV2001 - B                       58 non-null     object
 112  KV2001 - C                       58 non-null     object
 113  KV2001 - D                       58 non-null     object
 114  KV2001 - F                       58 non-null     object
 115  KV2001 - I                       58 non-null     object
 116  KV2001 - J                       58 non-null     object
 117  KV2001 - G                       58 non-null     object
 118  KV2001 - K                       58 non-null     object
 119  KV2001 - N                       58 non-null     object
 120  KV2001 - H                       58 non-null     object
 121  KV2001 - M                       58 non-null     object
 122  KV2001 - S                       58 non-null     object
 123  KV2001 - U                       58 non-null     object
 124  KV2001 - Y                       58 non-null     object
 125  KV2001 - O                       58 non-null     object
 126  KV2001 - Z                       58 non-null     object
 127  KV2001 - L                       58 non-null     object
 128  KV2001 - Q                       58 non-null     object
 129  KV2001 - R                       58 non-null     object
 130  KV2001 - V                       58 non-null     object
 131  KV2001 - P                       58 non-null     object
 132  KV2001 - E                       58 non-null     object
 133  KV2001 - Ø                       58 non-null     object
 134  KV2001 - Å                       58 non-null     object
 135  KV2001 - 1                       58 non-null     object
 136  KV2001 - 2                       58 non-null     object
 137  KV2001 - 3                       58 non-null     object
 138  KV2001 - 4                       58 non-null     object
 139  KV2001 - 5                       58 non-null     object
 140  KV2001 - 6                       58 non-null     object
 141  KV2001 - 0                       58 non-null     object
 142  KV2001 - 01                      58 non-null     object
 143  KV2001 - 02                      58 non-null     object
 144  KV2001 - 03                      58 non-null     object
 145  KV2001 - 04                      58 non-null     object
 146  KV2001 - 05                      58 non-null     object
 147  KV2001 - 06                      58 non-null     object
 148  KV2001 - 7                       58 non-null     object
 149  KV2001 - K1                      58 non-null     object
 150  KV2001 - K2                      58 non-null     object
 151  KV2001 - T                       58 non-null     object
 152  KV2001 - W                       58 non-null     object
 153  KV2001 - Æ                       58 non-null     object
 154  KV2001 - Å1                      58 non-null     object
 155  KV2005 - Stemmeberettigede       58 non-null     object
 156  KV2005 - Afgivne stemmer         58 non-null     object
 157  KV2005 - Blanke stemmer          58 non-null     object
 158  KV2005 - Andre ugyldige stemmer  58 non-null     object
 159  KV2005 - Gyldige stemmer         58 non-null     object
 160  KV2005 - A                       58 non-null     object
 161  KV2005 - B                       58 non-null     object
 162  KV2005 - C                       58 non-null     object
 163  KV2005 - D                       58 non-null     object
 164  KV2005 - F                       58 non-null     object
 165  KV2005 - I                       58 non-null     object
 166  KV2005 - J                       58 non-null     object
 167  KV2005 - G                       58 non-null     object
 168  KV2005 - K                       58 non-null     object
 169  KV2005 - N                       58 non-null     object
 170  KV2005 - H                       58 non-null     object
 171  KV2005 - M                       58 non-null     object
 172  KV2005 - S                       58 non-null     object
 173  KV2005 - U                       58 non-null     object
 174  KV2005 - Y                       58 non-null     object
 175  KV2005 - O                       58 non-null     object
 176  KV2005 - Z                       58 non-null     object
 177  KV2005 - L                       58 non-null     object
 178  KV2005 - Q                       58 non-null     object
 179  KV2005 - R                       58 non-null     object
 180  KV2005 - V                       58 non-null     object
 181  KV2005 - P                       58 non-null     object
 182  KV2005 - E                       58 non-null     object
 183  KV2005 - Ø                       58 non-null     object
 184  KV2005 - Å                       58 non-null     object
 185  KV2005 - 1                       58 non-null     object
 186  KV2005 - 2                       58 non-null     object
 187  KV2005 - 3                       58 non-null     object
 188  KV2005 - 4                       58 non-null     object
 189  KV2005 - 5                       58 non-null     object
 190  KV2005 - 6                       58 non-null     object
 191  KV2005 - 0                       58 non-null     object
 192  KV2005 - 01                      58 non-null     object
 193  KV2005 - 02                      58 non-null     object
 194  KV2005 - 03                      58 non-null     object
 195  KV2005 - 04                      58 non-null     object
 196  KV2005 - 05                      58 non-null     object
 197  KV2005 - 06                      58 non-null     object
 198  KV2005 - 7                       58 non-null     object
 199  KV2005 - K1                      58 non-null     object
 200  KV2005 - K2                      58 non-null     object
 201  KV2005 - T                       58 non-null     object
 202  KV2005 - W                       58 non-null     object
 203  KV2005 - Æ                       58 non-null     object
 204  KV2005 - Å1                      58 non-null     object
 205  KV2017 - Stemmeberettigede       58 non-null     object
 206  KV2017 - Afgivne stemmer         58 non-null     object
 207  KV2017 - Blanke stemmer          58 non-null     object
 208  KV2017 - Andre ugyldige stemmer  58 non-null     object
 209  KV2017 - Gyldige stemmer         58 non-null     object
 210  KV2017 - A                       58 non-null     object
 211  KV2017 - B                       58 non-null     object
 212  KV2017 - C                       58 non-null     object
 213  KV2017 - D                       58 non-null     object
 214  KV2017 - F                       58 non-null     object
 215  KV2017 - I                       58 non-null     object
 216  KV2017 - J                       58 non-null     object
 217  KV2017 - G                       58 non-null     object
 218  KV2017 - K                       58 non-null     object
 219  KV2017 - N                       58 non-null     object
 220  KV2017 - H                       58 non-null     object
 221  KV2017 - M                       58 non-null     object
 222  KV2017 - S                       58 non-null     object
 223  KV2017 - U                       58 non-null     object
 224  KV2017 - Y                       58 non-null     object
 225  KV2017 - O                       58 non-null     object
 226  KV2017 - Z                       58 non-null     object
 227  KV2017 - L                       58 non-null     object
 228  KV2017 - Q                       58 non-null     object
 229  KV2017 - R                       58 non-null     object
 230  KV2017 - V                       58 non-null     object
 231  KV2017 - P                       58 non-null     object
 232  KV2017 - E                       58 non-null     object
 233  KV2017 - Ø                       58 non-null     object
 234  KV2017 - Å                       58 non-null     object
 235  KV2017 - 1                       58 non-null     object
 236  KV2017 - 2                       58 non-null     object
 237  KV2017 - 3                       58 non-null     object
 238  KV2017 - 4                       58 non-null     object
 239  KV2017 - 5                       58 non-null     object
 240  KV2017 - 6                       58 non-null     object
 241  KV2017 - 0                       58 non-null     object
 242  KV2017 - 01                      58 non-null     object
 243  KV2017 - 02                      58 non-null     object
 244  KV2017 - 03                      58 non-null     object
 245  KV2017 - 04                      58 non-null     object
 246  KV2017 - 05                      58 non-null     object
 247  KV2017 - 06                      58 non-null     object
 248  KV2017 - 7                       58 non-null     object
 249  KV2017 - K1                      58 non-null     object
 250  KV2017 - K2                      58 non-null     object
 251  KV2017 - T                       58 non-null     object
 252  KV2017 - W                       58 non-null     object
 253  KV2017 - Æ                       58 non-null     object
 254  KV2017 - Å1                      58 non-null     object
 255  KV2021 - Stemmeberettigede       58 non-null     object
 256  KV2021 - Afgivne stemmer         58 non-null     object
 257  KV2021 - Blanke stemmer          58 non-null     object
 258  KV2021 - Andre ugyldige stemmer  58 non-null     object
 259  KV2021 - Gyldige stemmer         58 non-null     object
 260  KV2021 - A                       58 non-null     object
 261  KV2021 - B                       58 non-null     object
 262  KV2021 - C                       58 non-null     object
 263  KV2021 - D                       58 non-null     object
 264  KV2021 - F                       58 non-null     object
 265  KV2021 - I                       58 non-null     object
 266  KV2021 - J                       58 non-null     object
 267  KV2021 - G                       58 non-null     object
 268  KV2021 - K                       58 non-null     object
 269  KV2021 - N                       58 non-null     object
 270  KV2021 - H                       58 non-null     object
 271  KV2021 - M                       58 non-null     object
 272  KV2021 - S                       58 non-null     object
 273  KV2021 - U                       58 non-null     object
 274  KV2021 - Y                       58 non-null     object
 275  KV2021 - O                       58 non-null     object
 276  KV2021 - Z                       58 non-null     object
 277  KV2021 - L                       58 non-null     object
 278  KV2021 - Q                       58 non-null     object
 279  KV2021 - R                       58 non-null     object
 280  KV2021 - V                       58 non-null     object
 281  KV2021 - P                       58 non-null     object
 282  KV2021 - E                       58 non-null     object
 283  KV2021 - Ø                       58 non-null     object
 284  KV2021 - Å                       58 non-null     object
 285  KV2021 - 1                       58 non-null     object
 286  KV2021 - 2                       58 non-null     object
 287  KV2021 - 3                       58 non-null     object
 288  KV2021 - 4                       58 non-null     object
 289  KV2021 - 5                       58 non-null     object
 290  KV2021 - 6                       58 non-null     object
 291  KV2021 - 0                       58 non-null     object
 292  KV2021 - 01                      58 non-null     object
 293  KV2021 - 02                      58 non-null     object
 294  KV2021 - 03                      58 non-null     object
 295  KV2021 - 04                      58 non-null     object
 296  KV2021 - 05                      58 non-null     object
 297  KV2021 - 06                      58 non-null     object
 298  KV2021 - 7                       58 non-null     object
 299  KV2021 - K1                      58 non-null     object
 300  KV2021 - K2                      58 non-null     object
 301  KV2021 - T                       58 non-null     object
 302  KV2021 - W                       58 non-null     object
 303  KV2021 - Æ                       58 non-null     object
 304  KV2021 - Å1                      58 non-null     object
dtypes: object(305)
memory usage: 138.7+ KB

## Convert dtypes to numeric

In [17]:
party_cols = [col for col in df.columns if col.startswith(PREFIX) and any(f'{PREFIX}{year} - ' in col for year in YEARS)]

# To numeric
for col in party_cols:
    df[col] = df[col].replace('-', '')
    df[col] = df[col].str.replace(',', '.', regex=False)
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Drop columns with no non-null values
df = df.dropna(axis=1, how='all')
party_cols = [col for col in df.columns if col.startswith(PREFIX) and any(f'{PREFIX}{year} - ' in col for year in YEARS)]

# Fill NaN with 0 for party columns
for col in party_cols:
    df[col] = df[col].fillna(0)

# Convert to int if no fractional part
for col in party_cols:
    if (df[col].dropna() % 1 == 0).all():
        df[col] = df[col].astype('int64')

df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 239 columns):
 #    Column                           Non-Null Count  Dtype
---   ------                           --------------  -----
 0    Gruppe                           58 non-null     object
 1    ValgstedId                       58 non-null     object
 2    KredsNr                          58 non-null     object
 3    StorKredsNr                      58 non-null     object
 4    LandsdelsNr                      58 non-null     object
 5    KV2009 - Stemmeberettigede       58 non-null     float64
 6    KV2009 - Afgivne stemmer         58 non-null     float64
 7    KV2009 - Blanke stemmer          58 non-null     float64
 8    KV2009 - Andre ugyldige stemmer  58 non-null     float64
 9    KV2009 - Gyldige stemmer         58 non-null     float64
 10   KV2009 - A                       58 non-null     float64
 11   KV2009 - B                       58 non-null     float64
 12   KV2009 - C                       58 non-null     float64
 13   KV2009 - D                       58 non-null     float64
 14   KV2009 - F                       58 non-null     float64
 15   KV2009 - I                       58 non-null     float64
 16   KV2009 - J                       58 non-null     float64
 17   KV2009 - G                       58 non-null     float64
 18   KV2009 - K                       58 non-null     float64
 19   KV2009 - N                       58 non-null     float64
 20   KV2009 - H                       58 non-null     float64
 21   KV2009 - M                       58 non-null     float64
 22   KV2009 - U                       58 non-null     float64
 23   KV2009 - Y                       58 non-null     float64
 24   KV2009 - O                       58 non-null     float64
 25   KV2009 - Z                       58 non-null     float64
 26   KV2009 - L                       58 non-null     float64
 27   KV2009 - Q                       58 non-null     float64
 28   KV2009 - R                       58 non-null     float64
 29   KV2009 - V                       58 non-null     float64
 30   KV2009 - P                       58 non-null     float64
 31   KV2009 - E                       58 non-null     float64
 32   KV2009 - Ø                       58 non-null     float64
 33   KV2009 - Å                       58 non-null     float64
 34   KV2009 - 1                       58 non-null     float64
 35   KV2009 - 2                       58 non-null     float64
 36   KV2009 - 3                       58 non-null     float64
 37   KV2009 - T                       58 non-null     float64
 38   KV2009 - Æ                       58 non-null     float64
 39   KV2013 - Stemmeberettigede       58 non-null     float64
 40   KV2013 - Afgivne stemmer         58 non-null     float64
 41   KV2013 - Blanke stemmer          58 non-null     float64
 42   KV2013 - Andre ugyldige stemmer  58 non-null     float64
 43   KV2013 - Gyldige stemmer         58 non-null     float64
 44   KV2013 - A                       58 non-null     float64
 45   KV2013 - B                       58 non-null     float64
 46   KV2013 - C                       58 non-null     float64
 47   KV2013 - D                       58 non-null     float64
 48   KV2013 - F                       58 non-null     float64
 49   KV2013 - I                       58 non-null     float64
 50   KV2013 - J                       58 non-null     float64
 51   KV2013 - G                       58 non-null     float64
 52   KV2013 - K                       58 non-null     float64
 53   KV2013 - N                       58 non-null     float64
 54   KV2013 - H                       58 non-null     float64
 55   KV2013 - M                       58 non-null     float64
 56   KV2013 - U                       58 non-null     float64
 57   KV2013 - Y                       58 non-null     float64
 58   KV2013 - O                       58 non-null     float64
 59   KV2013 - Z                       58 non-null     float64
 60   KV2013 - L                       58 non-null     float64
 61   KV2013 - Q                       58 non-null     float64
 62   KV2013 - R                       58 non-null     float64
 63   KV2013 - V                       58 non-null     float64
 64   KV2013 - P                       58 non-null     float64
 65   KV2013 - E                       58 non-null     float64
 66   KV2013 - Ø                       58 non-null     float64
 67   KV2013 - Å                       58 non-null     float64
 68   KV2013 - 01                      58 non-null     float64
 69   KV2013 - 02                      58 non-null     float64
 70   KV2013 - 03                      58 non-null     float64
 71   KV2013 - 04                      58 non-null     float64
 72   KV2013 - 05                      58 non-null     float64
 73   KV2013 - 06                      58 non-null     float64
 74   KV2013 - T                       58 non-null     float64
 75   KV2013 - Æ                       58 non-null     float64
 76   KV2001 - Stemmeberettigede       58 non-null     object
 77   KV2001 - Afgivne stemmer         58 non-null     object
 78   KV2001 - Blanke stemmer          58 non-null     object
 79   KV2001 - Andre ugyldige stemmer  58 non-null     object
 80   KV2001 - Gyldige stemmer         58 non-null     object
 81   KV2001 - A                       58 non-null     object
 82   KV2001 - B                       58 non-null     object
 83   KV2001 - C                       58 non-null     object
 84   KV2001 - D                       58 non-null     object
 85   KV2001 - F                       58 non-null     object
 86   KV2001 - I                       58 non-null     object
 87   KV2001 - J                       58 non-null     object
 88   KV2001 - G                       58 non-null     object
 89   KV2001 - K                       58 non-null     object
 90   KV2001 - N                       58 non-null     object
 91   KV2001 - H                       58 non-null     object
 92   KV2001 - M                       58 non-null     object
 93   KV2001 - S                       58 non-null     object
 94   KV2001 - U                       58 non-null     object
 95   KV2001 - Y                       58 non-null     object
 96   KV2001 - O                       58 non-null     object
 97   KV2001 - Z                       58 non-null     object
 98   KV2001 - L                       58 non-null     object
 99   KV2001 - Q                       58 non-null     object
 100  KV2001 - R                       58 non-null     object
 101  KV2001 - V                       58 non-null     object
 102  KV2001 - P                       58 non-null     object
 103  KV2001 - E                       58 non-null     object
 104  KV2001 - Ø                       58 non-null     object
 105  KV2001 - Å                       58 non-null     object
 106  KV2001 - 1                       58 non-null     object
 107  KV2001 - 2                       58 non-null     object
 108  KV2001 - 3                       58 non-null     object
 109  KV2001 - 4                       58 non-null     object
 110  KV2001 - 5                       58 non-null     object
 111  KV2001 - 6                       58 non-null     object
 112  KV2001 - 0                       58 non-null     object
 113  KV2001 - 01                      58 non-null     object
 114  KV2001 - 02                      58 non-null     object
 115  KV2001 - 03                      58 non-null     object
 116  KV2001 - 04                      58 non-null     object
 117  KV2001 - 05                      58 non-null     object
 118  KV2001 - 06                      58 non-null     object
 119  KV2001 - 7                       58 non-null     object
 120  KV2001 - K1                      58 non-null     object
 121  KV2001 - K2                      58 non-null     object
 122  KV2001 - T                       58 non-null     object
 123  KV2001 - W                       58 non-null     object
 124  KV2001 - Æ                       58 non-null     object
 125  KV2001 - Å1                      58 non-null     object
 126  KV2005 - Stemmeberettigede       58 non-null     object
 127  KV2005 - Afgivne stemmer         58 non-null     object
 128  KV2005 - Blanke stemmer          58 non-null     object
 129  KV2005 - Andre ugyldige stemmer  58 non-null     object
 130  KV2005 - Gyldige stemmer         58 non-null     object
 131  KV2005 - A                       58 non-null     object
 132  KV2005 - B                       58 non-null     object
 133  KV2005 - C                       58 non-null     object
 134  KV2005 - D                       58 non-null     object
 135  KV2005 - F                       58 non-null     object
 136  KV2005 - I                       58 non-null     object
 137  KV2005 - J                       58 non-null     object
 138  KV2005 - G                       58 non-null     object
 139  KV2005 - K                       58 non-null     object
 140  KV2005 - N                       58 non-null     object
 141  KV2005 - H                       58 non-null     object
 142  KV2005 - M                       58 non-null     object
 143  KV2005 - S                       58 non-null     object
 144  KV2005 - U                       58 non-null     object
 145  KV2005 - Y                       58 non-null     object
 146  KV2005 - O                       58 non-null     object
 147  KV2005 - Z                       58 non-null     object
 148  KV2005 - L                       58 non-null     object
 149  KV2005 - Q                       58 non-null     object
 150  KV2005 - R                       58 non-null     object
 151  KV2005 - V                       58 non-null     object
 152  KV2005 - P                       58 non-null     object
 153  KV2005 - E                       58 non-null     object
 154  KV2005 - Ø                       58 non-null     object
 155  KV2005 - Å                       58 non-null     object
 156  KV2005 - 1                       58 non-null     object
 157  KV2005 - 2                       58 non-null     object
 158  KV2005 - 3                       58 non-null     object
 159  KV2005 - 4                       58 non-null     object
 160  KV2005 - 5                       58 non-null     object
 161  KV2005 - 6                       58 non-null     object
 162  KV2005 - 0                       58 non-null     object
 163  KV2005 - 01                      58 non-null     object
 164  KV2005 - 02                      58 non-null     object
 165  KV2005 - 03                      58 non-null     object
 166  KV2005 - 04                      58 non-null     object
 167  KV2005 - 05                      58 non-null     object
 168  KV2005 - 06                      58 non-null     object
 169  KV2005 - 7                       58 non-null     object
 170  KV2005 - K1                      58 non-null     object
 171  KV2005 - K2                      58 non-null     object
 172  KV2005 - T                       58 non-null     object
 173  KV2005 - W                       58 non-null     object
 174  KV2005 - Æ                       58 non-null     object
 175  KV2005 - Å1                      58 non-null     object
 176  KV2017 - Stemmeberettigede       58 non-null     float64
 177  KV2017 - Afgivne stemmer         58 non-null     float64
 178  KV2017 - Blanke stemmer          58 non-null     float64
 179  KV2017 - Andre ugyldige stemmer  58 non-null     float64
 180  KV2017 - Gyldige stemmer         58 non-null     float64
 181  KV2017 - A                       58 non-null     float64
 182  KV2017 - B                       58 non-null     float64
 183  KV2017 - C                       58 non-null     float64
 184  KV2017 - D                       58 non-null     float64
 185  KV2017 - F                       58 non-null     float64
 186  KV2017 - I                       58 non-null     float64
 187  KV2017 - J                       58 non-null     float64
 188  KV2017 - G                       58 non-null     float64
 189  KV2017 - K                       58 non-null     float64
 190  KV2017 - N                       58 non-null     float64
 191  KV2017 - H                       58 non-null     float64
 192  KV2017 - M                       58 non-null     float64
 193  KV2017 - U                       58 non-null     float64
 194  KV2017 - Y                       58 non-null     float64
 195  KV2017 - O                       58 non-null     float64
 196  KV2017 - Z                       58 non-null     float64
 197  KV2017 - L                       58 non-null     float64
 198  KV2017 - Q                       58 non-null     float64
 199  KV2017 - R                       58 non-null     float64
 200  KV2017 - V                       58 non-null     float64
 201  KV2017 - P                       58 non-null     float64
 202  KV2017 - E                       58 non-null     float64
 203  KV2017 - Ø                       58 non-null     float64
 204  KV2017 - Å                       58 non-null     float64
 205  KV2017 - T                       58 non-null     float64
 206  KV2017 - Æ                       58 non-null     float64
 207  KV2021 - Stemmeberettigede       58 non-null     int64
 208  KV2021 - Afgivne stemmer         58 non-null     int64
 209  KV2021 - Blanke stemmer          58 non-null     int64
 210  KV2021 - Andre ugyldige stemmer  58 non-null     int64
 211  KV2021 - Gyldige stemmer         58 non-null     int64
 212  KV2021 - A                       58 non-null     int64
 213  KV2021 - B                       58 non-null     int64
 214  KV2021 - C                       58 non-null     int64
 215  KV2021 - D                       58 non-null     int64
 216  KV2021 - F                       58 non-null     int64
 217  KV2021 - I                       58 non-null     int64
 218  KV2021 - J                       58 non-null     int64
 219  KV2021 - G                       58 non-null     int64
 220  KV2021 - K                       58 non-null     int64
 221  KV2021 - N                       58 non-null     int64
 222  KV2021 - H                       58 non-null     int64
 223  KV2021 - M                       58 non-null     int64
 224  KV2021 - U                       58 non-null     int64
 225  KV2021 - Y                       58 non-null     int64
 226  KV2021 - O                       58 non-null     int64
 227  KV2021 - Z                       58 non-null     int64
 228  KV2021 - L                       58 non-null     int64
 229  KV2021 - Q                       58 non-null     int64
 230  KV2021 - R                       58 non-null     int64
 231  KV2021 - V                       58 non-null     int64
 232  KV2021 - P                       58 non-null     int64
 233  KV2021 - E                       58 non-null     int64
 234  KV2021 - Ø                       58 non-null     int64
 235  KV2021 - Å                       58 non-null     int64
 236  KV2021 - 0                       58 non-null     int64
 237  KV2021 - T                       58 non-null     int64
 238  KV2021 - Æ                       58 non-null     int64
dtypes: float64(102), int64(32), object(105)
memory usage: 108.8+ KB

In [18]:
df.head()

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,KV2009 - Stemmeberettigede,KV2009 - Afgivne stemmer,KV2009 - Blanke stemmer,KV2009 - Andre ugyldige stemmer,KV2009 - Gyldige stemmer,...,KV2021 - Q,KV2021 - R,KV2021 - V,KV2021 - P,KV2021 - E,KV2021 - Ø,KV2021 - Å,KV2021 - 0,KV2021 - T,KV2021 - Æ
0,101001,101001,1,1,1,11209.98,6883.60,83.98,12.56,6787.05,...,10,16,731,2,2,1532,217,0,24,11
1,101002,101002,1,1,1,6096.00,3507.00,35.00,12.00,3460.00,...,2,13,515,0,4,699,102,0,20,3
2,101003,101003,1,1,1,12272.62,7353.23,65.52,13.12,7274.60,...,6,23,757,1,6,1893,215,0,28,8
3,101005,101005,1,1,1,11459.00,6247.00,57.00,20.00,6170.00,...,7,28,588,0,6,1599,185,0,24,8
4,101006,101006,1,1,1,9866.00,5683.00,72.00,14.00,5597.00,...,5,15,581,3,5,1282,170,2,32,10

## Split by year

In [19]:
year_dfs = {}
for year in YEARS:
    pattern = f'{PREFIX}{year} - '
    year_cols = [col for col in df.columns if col.startswith(pattern)]
    year_df = df[COMMON_COLS + year_cols].copy()
    rename_dict = {col: col.replace(pattern, '') for col in year_cols}
    year_df.rename(columns=rename_dict, inplace=True)
    year_dfs[year] = year_df

df_2009 = year_dfs[2009]
df_2013 = year_dfs[2013]
df_2017 = year_dfs[2017]
df_2021 = year_dfs[2021]

# verify
for year in YEARS:
    print(f"\n{year} shape: {year_dfs[year].shape}")
    print(f"Columns: {len(year_dfs[year].columns)}")

2009 shape: (58, 39)
Columns: 39

2013 shape: (58, 42)
Columns: 42

2017 shape: (58, 36)
Columns: 36

2021 shape: (58, 37)
Columns: 37

In [20]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gruppe                  58 non-null     object
 1   ValgstedId              58 non-null     object
 2   KredsNr                 58 non-null     object
 3   StorKredsNr             58 non-null     object
 4   LandsdelsNr             58 non-null     object
 5   Stemmeberettigede       58 non-null     int64
 6   Afgivne stemmer         58 non-null     int64
 7   Blanke stemmer          58 non-null     int64
 8   Andre ugyldige stemmer  58 non-null     int64
 9   Gyldige stemmer         58 non-null     int64
 10  A                       58 non-null     int64
 11  B                       58 non-null     int64
 12  C                       58 non-null     int64
 13  D                       58 non-null     int64
 14  F                       58 non-null     int64
 15  I                       58 non-null     int64
 16  J                       58 non-null     int64
 17  G                       58 non-null     int64
 18  K                       58 non-null     int64
 19  N                       58 non-null     int64
 20  H                       58 non-null     int64
 21  M                       58 non-null     int64
 22  U                       58 non-null     int64
 23  Y                       58 non-null     int64
 24  O                       58 non-null     int64
 25  Z                       58 non-null     int64
 26  L                       58 non-null     int64
 27  Q                       58 non-null     int64
 28  R                       58 non-null     int64
 29  V                       58 non-null     int64
 30  P                       58 non-null     int64
 31  E                       58 non-null     int64
 32  Ø                       58 non-null     int64
 33  Å                       58 non-null     int64
 34  0                       58 non-null     int64
 35  T                       58 non-null     int64
 36  Æ                       58 non-null     int64
dtypes: int64(32), object(5)
memory usage: 17.2+ KB

In [21]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gruppe                  58 non-null     object
 1   ValgstedId              58 non-null     object
 2   KredsNr                 58 non-null     object
 3   StorKredsNr             58 non-null     object
 4   LandsdelsNr             58 non-null     object
 5   Stemmeberettigede       58 non-null     int64
 6   Afgivne stemmer         58 non-null     int64
 7   Blanke stemmer          58 non-null     int64
 8   Andre ugyldige stemmer  58 non-null     int64
 9   Gyldige stemmer         58 non-null     int64
 10  A                       58 non-null     int64
 11  B                       58 non-null     int64
 12  C                       58 non-null     int64
 13  D                       58 non-null     int64
 14  F                       58 non-null     int64
 15  I                       58 non-null     int64
 16  J                       58 non-null     int64
 17  G                       58 non-null     int64
 18  K                       58 non-null     int64
 19  N                       58 non-null     int64
 20  H                       58 non-null     int64
 21  M                       58 non-null     int64
 22  U                       58 non-null     int64
 23  Y                       58 non-null     int64
 24  O                       58 non-null     int64
 25  Z                       58 non-null     int64
 26  L                       58 non-null     int64
 27  Q                       58 non-null     int64
 28  R                       58 non-null     int64
 29  V                       58 non-null     int64
 30  P                       58 non-null     int64
 31  E                       58 non-null     int64
 32  Ø                       58 non-null     int64
 33  Å                       58 non-null     int64
 34  0                       58 non-null     int64
 35  T                       58 non-null     int64
 36  Æ                       58 non-null     int64
dtypes: int64(32), object(5)
memory usage: 17.2+ KB

## Add some geography cols, drop others

In [22]:
def add_geography_columns(df):
    geo_df = pd.read_csv(PARENT_PATH + 'Geography.csv', sep=';', encoding='utf-8', quotechar='"')
    geo_df.columns = geo_df.columns.str.strip().str.strip('"')
    geo_df = geo_df[geo_df['KommuneNr'].astype(str).isin(['101', '147'])].copy()
    
    print("Geography CSV columns:", geo_df.columns.tolist())
    print("First few Valgsted Ids:", geo_df['Valgsted Id'].head().tolist())

    geo_dict = {}
    for _, row in geo_df.iterrows():
        valgsted_id = str(row['Valgsted Id']).strip().strip('"')
        geo_dict[valgsted_id] = {
            'Valgsted navn': str(row['Valgsted navn']).strip().strip('"'),
            'Kreds navn': str(row['Kreds navn']).strip().strip('"'),
            'Kommune navn': str(row['Kommune navn']).strip().strip('"')
        }

    print(f"Total entries in geo_dict: {len(geo_dict)}")
    print(f"Sample keys: {list(geo_dict.keys())[:5]}")
    
    df_result = df.copy()
    valgsted_navne = []
    kreds_navne = []
    kommune_navne = []
    
    for _, row in df_result.iterrows():
        valgsted_ids = str(row['ValgstedId']).split(';')
        v_names = []
        k_names = []
        kom_names = []

        for vid in valgsted_ids:
            vid = vid.strip()
            if vid not in geo_dict:
                print(f"Missing ValgstedId: '{vid}' (length: {len(vid)})")
                print(f"Available keys starting with '101': {[k for k in geo_dict.keys() if k.startswith('101')][:10]}")
                raise ValueError(f"ValgstedId '{vid}' not found in Geography.csv")
            
            v_names.append(geo_dict[vid]['Valgsted navn'])
            k_names.append(geo_dict[vid]['Kreds navn'])
            kom_names.append(geo_dict[vid]['Kommune navn'])

        # Join with semicolons, remove duplicates while preserving order
        valgsted_navne.append(';'.join(v_names))
        
        # For Kreds and Kommune, use single value if all same, otherwise semicolon-separate
        if len(set(k_names)) == 1:
            kreds_navne.append(k_names[0])
        else:
            kreds_navne.append(';'.join(k_names))
            
        if len(set(kom_names)) == 1:
            kommune_navne.append(kom_names[0])
        else:
            kommune_navne.append(';'.join(kom_names))

    df_result['Valgsted navn'] = valgsted_navne
    df_result['Kreds navn'] = kreds_navne
    df_result['Kommune navn'] = kommune_navne
    df_result = df_result.drop(columns=['StorKredsNr', 'LandsdelsNr'])
    
    # Reorder columns
    first_cols = ['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn', 'Kommune navn']
    other_cols = [col for col in df_result.columns if col not in first_cols]
    df_result = df_result[first_cols + other_cols]
    
    return df_result

for year in YEARS:
    year_dfs[year] = add_geography_columns(year_dfs[year])
    print(f"Added geography columns to {year}")

df_2009, df_2013, df_2017, df_2021 = [year_dfs[year] for year in YEARS]

# Check the result
print("\nFirst few rows of df_2021:")
print(df_2021[['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn', 'Kommune navn']].head(10))

Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2009
Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2013
Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2017
Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2021

First few rows of df_2021:
   Gruppe     ValgstedId    Valgsted navn KredsNr       Kreds navn  \
0  101001         101001      1. Østerbro       1      1. Østerbro
1  101002         101002          1. Nord       1      1. Østerbro
2  101003         101003           1. Syd       1      1. Østerbro
3  101005         101005          1. Vest       1      1. Østerbro
4  101006         101006      1. Nordvest       1      1. Østerbro
5  101007         101007  2. Sundbyvester       2  2. Sundbyvester
6  101008  101010;101008  2. Vest;2. Nord       2  2. Sundbyvester
7  101009         101009           2. Syd       2  2. Sundbyvester
8  101011         101011      3. Indre By       3      3. Indre By
9  101012         101012          3. Nord       3      3. Indre By

  Kommune navn
0    København
1    København
2    København
3    København
4    København
5    København
6    København
7    København
8    København
9    København

In [23]:
df_2021.head()

,Gruppe,ValgstedId,Valgsted navn,KredsNr,Kreds navn,Kommune navn,Stemmeberettigede,Afgivne stemmer,Blanke stemmer,Andre ugyldige stemmer,...,Q,R,V,P,E,Ø,Å,0,T,Æ
0,101001,101001,1. Østerbro,1,1. Østerbro,København,12518,8360,110,25,...,10,16,731,2,2,1532,217,0,24,11
1,101002,101002,1. Nord,1,1. Østerbro,København,6859,4504,50,14,...,2,13,515,0,4,699,102,0,20,3
2,101003,101003,1. Syd,1,1. Østerbro,København,12504,9094,99,23,...,6,23,757,1,6,1893,215,0,28,8
3,101005,101005,1. Vest,1,1. Østerbro,København,12953,7643,117,18,...,7,28,588,0,6,1599,185,0,24,8
4,101006,101006,1. Nordvest,1,1. Østerbro,København,11149,7039,92,29,...,5,15,581,3,5,1282,170,2,32,10

In [24]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gruppe                  58 non-null     object
 1   ValgstedId              58 non-null     object
 2   Valgsted navn           58 non-null     object
 3   KredsNr                 58 non-null     object
 4   Kreds navn              58 non-null     object
 5   Kommune navn            58 non-null     object
 6   Stemmeberettigede       58 non-null     int64
 7   Afgivne stemmer         58 non-null     int64
 8   Blanke stemmer          58 non-null     int64
 9   Andre ugyldige stemmer  58 non-null     int64
 10  Gyldige stemmer         58 non-null     int64
 11  A                       58 non-null     int64
 12  B                       58 non-null     int64
 13  C                       58 non-null     int64
 14  D                       58 non-null     int64
 15  F                       58 non-null     int64
 16  I                       58 non-null     int64
 17  J                       58 non-null     int64
 18  G                       58 non-null     int64
 19  K                       58 non-null     int64
 20  N                       58 non-null     int64
 21  H                       58 non-null     int64
 22  M                       58 non-null     int64
 23  U                       58 non-null     int64
 24  Y                       58 non-null     int64
 25  O                       58 non-null     int64
 26  Z                       58 non-null     int64
 27  L                       58 non-null     int64
 28  Q                       58 non-null     int64
 29  R                       58 non-null     int64
 30  V                       58 non-null     int64
 31  P                       58 non-null     int64
 32  E                       58 non-null     int64
 33  Ø                       58 non-null     int64
 34  Å                       58 non-null     int64
 35  0                       58 non-null     int64
 36  T                       58 non-null     int64
 37  Æ                       58 non-null     int64
dtypes: int64(32), object(6)
memory usage: 17.7+ KB

## Translate Danish columns

In [25]:
DFS = [df_2009, df_2013, df_2017, df_2021]

translations = {
    'ValgstedId': 'PollingAreaID',
    'Valgsted navn': 'Name',
    'KredsNr': 'DistrictNo',
    'Kreds navn': 'District',
    'Kommune navn': 'Municipality',
    'Stemmeberettigede': 'Eligible voters',
    'Afgivne stemmer': 'Voter turnout',
    'Blanke stemmer': 'Blank votes',
    'Andre ugyldige stemmer': 'Other invalid votes',
    'Gyldige stemmer': 'Valid votes'
}

for i, year in enumerate(YEARS):
    DFS[i] = DFS[i].rename(columns=translations)
df_2009, df_2013, df_2017, df_2021 = DFS

In [26]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 57
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gruppe               58 non-null     object
 1   PollingAreaID        58 non-null     object
 2   Name                 58 non-null     object
 3   DistrictNo           58 non-null     object
 4   District             58 non-null     object
 5   Municipality         58 non-null     object
 6   Eligible voters      58 non-null     int64
 7   Voter turnout        58 non-null     int64
 8   Blank votes          58 non-null     int64
 9   Other invalid votes  58 non-null     int64
 10  Valid votes          58 non-null     int64
 11  A                    58 non-null     int64
 12  B                    58 non-null     int64
 13  C                    58 non-null     int64
 14  D                    58 non-null     int64
 15  F                    58 non-null     int64
 16  I                    58 non-null     int64
 17  J                    58 non-null     int64
 18  G                    58 non-null     int64
 19  K                    58 non-null     int64
 20  N                    58 non-null     int64
 21  H                    58 non-null     int64
 22  M                    58 non-null     int64
 23  U                    58 non-null     int64
 24  Y                    58 non-null     int64
 25  O                    58 non-null     int64
 26  Z                    58 non-null     int64
 27  L                    58 non-null     int64
 28  Q                    58 non-null     int64
 29  R                    58 non-null     int64
 30  V                    58 non-null     int64
 31  P                    58 non-null     int64
 32  E                    58 non-null     int64
 33  Ø                    58 non-null     int64
 34  Å                    58 non-null     int64
 35  0                    58 non-null     int64
 36  T                    58 non-null     int64
 37  Æ                    58 non-null     int64
dtypes: int64(32), object(6)
memory usage: 17.7+ KB

## Save to CSVs

In [27]:
for i, year in enumerate(YEARS):
    filename = f'{OUTPUT_PATH}absolute_{year}.csv'
    DFS[i].to_csv(filename, index=False)
    print(f"Saved {filename}")

Saved ../../../processed-data/elections/absolute_2009.csv
Saved ../../../processed-data/elections/absolute_2013.csv
Saved ../../../processed-data/elections/absolute_2017.csv
Saved ../../../processed-data/elections/absolute_2021.csv

## Convert to percentages and save to new CSVs

In [28]:
for i, year in enumerate(YEARS):
    df_rel = DFS[i].copy()
    gyldige_idx = df_rel.columns.get_loc('Valid votes')
    party_cols = df_rel.columns[gyldige_idx + 1:].tolist()
    
    # Convert party columns to percentage of 'Gyldige stemmer'
    df_rel[party_cols] = df_rel[party_cols].div(df_rel['Valid votes'], axis=0) * 100

    # Convert 'Blanke stemmer', 'Andre ugyldige stemmer', 'Gyldige stemmer' to percentage of 'Afgivne stemmer'
    for col in ['Blank votes', 'Other invalid votes', 'Valid votes']:
        df_rel[col] = df_rel[col].div(df_rel['Voter turnout'], axis=0) * 100
    
    # Convert 'Afgivne stemmer' to percentage of 'Stemmeberettigede'
    df_rel['Voter turnout'] = df_rel['Voter turnout'].div(df_rel['Eligible voters'], axis=0) * 100
    
    # Save to CSV
    filename = f'{OUTPUT_PATH}relative_{year}.csv'
    df_rel.to_csv(filename, index=False)
    print(f"Saved {filename}")

Saved ../../../processed-data/elections/relative_2009.csv
Saved ../../../processed-data/elections/relative_2013.csv
Saved ../../../processed-data/elections/relative_2017.csv
Saved ../../../processed-data/elections/relative_2021.csv