In [1]:
import pandas as pd
import preprocess_data as cb

# Configuration
from preprocess_data import ROOT, PATH, ELECTION_PATH, DEMO_PATH, OUTPUT_PATH, MUNICIPALITY_IDS, COMMON_COLS, PREFIX, CPH_AREAS

In [2]:
df = pd.read_csv(DEMO_PATH, sep=';', dtype=str)
df.columns.tolist()

['Gruppe',
 'ValgstedId',
 'KredsNr',
 'StorKredsNr',
 'LandsdelsNr',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 0-4 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 10-14 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 15-17 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 18-19 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 20-24 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 25-29 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 30-34 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 35-39 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 40-44 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 45-49 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 50-54 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 55-59 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 5-9 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_08. Afrika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_09. Nordamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_10. Syd- og Mellemamerika',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_11. Asien og Oceanien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 60-64 år_12. Uoplyst',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år_01. Danmark',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år_02. Nordiske lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år_03. Tyrkiet',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år_04. Tidligere Jugoslavien',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år_05. Gamle EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år_06. Nye EU-lande',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år_07. Øvrige Europa',
 'KV2021 - Antal personer opgjort efter statsborgerskab køn og aldersgrupper_Kvinder 65-69 år_08. Afrika',

## Socioeconomy

In [3]:
cb.inspect_socioeconomy_duplicates(df, 2021, 20)

================================================================================
SOCIOECONOMY DUPLICATE INSPECTION - Year 2021
================================================================================


01. Selvstændig og medhj.:
  Found 22 columns
  Industries with duplicates: 11
  Industries with single column: 0

  Analyzing 11 duplicate pairs:

  Industry: Landbrug skovbrug og fiskeri
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 125.00, Mean: 2.66
      Sample values: [3.0, 6.0, 6.0]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 133.00, Mean: 2.61
      Sample values: [3.0, 4.0, 5.0]
    Comparison:
      Identical: False
      Correlation: 0.8778
      Sum difference: 8.00

  Industry: Industri råstofindvinding og forsyningsvirksomhed
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 756.00, Mean: 12.39
      Sample values: [15, 5, 8]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 738.00, Mean: 12.10
      Sample values: [14, 7, 15]
    Comparison:
      Identical: False
      Correlation: 0.8995
      Sum difference: 18.00

  Industry: Bygge og anlæg
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 1162.00, Mean: 19.05
      Sample values: [26, 14, 20]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 1184.00, Mean: 19.41
      Sample values: [25, 15, 23]
    Comparison:
      Identical: False
      Correlation: 0.9205
      Sum difference: 22.00

  Industry: Handel og transport mv.
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 3636.00, Mean: 59.61
      Sample values: [41, 34, 61]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 3596.00, Mean: 58.95
      Sample values: [51, 32, 68]
    Comparison:
      Identical: False
      Correlation: 0.9666
      Sum difference: 40.00

  Industry: Information og kommunikation
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 2884.00, Mean: 47.28
      Sample values: [69, 40, 78]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 2912.00, Mean: 47.74
      Sample values: [74, 43, 76]
    Comparison:
      Identical: False
      Correlation: 0.9697
      Sum difference: 28.00

  Industry: Finansiering og forsikring
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 103.00, Mean: 2.29
      Sample values: [nan, 6.0, 3.0]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 73.00, Mean: 1.97
      Sample values: [1.0, 2.0, 2.0]
    Comparison:
      Identical: False
      Correlation: 0.7871
      Sum difference: 30.00

  Industry: Ejendomshandel og udlejning
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 366.00, Mean: 6.54
      Sample values: [7.0, 9.0, 12.0]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 377.00, Mean: 6.73
      Sample values: [11.0, 10.0, 13.0]
    Comparison:
      Identical: False
      Correlation: 0.9744
      Sum difference: 11.00

  Industry: Erhvervsservice
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 7087.00, Mean: 116.18
      Sample values: [184, 128, 219]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 7199.00, Mean: 118.02
      Sample values: [203, 131, 219]
    Comparison:
      Identical: False
      Correlation: 0.9866
      Sum difference: 112.00

  Industry: Offentlig administration undervisning og sundhed
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 3471.00, Mean: 56.90
      Sample values: [91, 51, 104]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 3495.00, Mean: 57.30
      Sample values: [95, 50, 100]
    Comparison:
      Identical: False
      Correlation: 0.9739
      Sum difference: 24.00

  Industry: Kultur fritid og anden service
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 3512.00, Mean: 57.57
      Sample values: [71, 35, 99]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 3545.00, Mean: 58.11
      Sample values: [73, 41, 88]
    Comparison:
      Identical: False
      Correlation: 0.9799
      Sum difference: 33.00

  Industry: Ikke beskæftiget
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 536.00, Mean: 8.79
      Sample values: [16, 22, 11]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 573.00, Mean: 9.55
      Sample values: [13.0, 22.0, 23.0]
    Comparison:
      Identical: False
      Correlation: 0.9106
      Sum difference: 37.00


02. Topledere:
  Found 22 columns
  Industries with duplicates: 11
  Industries with single column: 0

  Analyzing 11 duplicate pairs:

  Industry: Landbrug skovbrug og fiskeri
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 10.00, Mean: 1.25
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 7.00, Mean: 1.00
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: False
      Correlation: 0.4402
      Sum difference: 3.00

  Industry: Industri råstofindvinding og forsyningsvirksomhed
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 1067.00, Mean: 17.78
      Sample values: [31.0, 26.0, 29.0]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 1008.00, Mean: 17.08
      Sample values: [36.0, 28.0, 27.0]
    Comparison:
      Identical: False
      Correlation: 0.9556
      Sum difference: 59.00

  Industry: Bygge og anlæg
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 494.00, Mean: 8.10
      Sample values: [8, 4, 10]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 511.00, Mean: 8.38
      Sample values: [7, 5, 11]
    Comparison:
      Identical: False
      Correlation: 0.9197
      Sum difference: 17.00

  Industry: Handel og transport mv.
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 3539.00, Mean: 58.02
      Sample values: [81, 55, 89]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 3557.00, Mean: 58.31
      Sample values: [92, 47, 93]
    Comparison:
      Identical: False
      Correlation: 0.9793
      Sum difference: 18.00

  Industry: Information og kommunikation
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 1472.00, Mean: 24.13
      Sample values: [36, 18, 43]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 1487.00, Mean: 24.78
      Sample values: [41.0, 18.0, 41.0]
    Comparison:
      Identical: False
      Correlation: 0.9576
      Sum difference: 15.00

  Industry: Finansiering og forsikring
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 1077.00, Mean: 17.95
      Sample values: [23.0, 19.0, 25.0]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 1058.00, Mean: 17.93
      Sample values: [23.0, 21.0, 32.0]
    Comparison:
      Identical: False
      Correlation: 0.9753
      Sum difference: 19.00

  Industry: Ejendomshandel og udlejning
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 257.00, Mean: 4.85
      Sample values: [8.0, 6.0, 6.0]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 249.00, Mean: 4.61
      Sample values: [7.0, 5.0, 6.0]
    Comparison:
      Identical: False
      Correlation: 0.9000
      Sum difference: 8.00

  Industry: Erhvervsservice
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 2012.00, Mean: 32.98
      Sample values: [49, 38, 71]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 2024.00, Mean: 33.73
      Sample values: [55.0, 38.0, 64.0]
    Comparison:
      Identical: False
      Correlation: 0.9842
      Sum difference: 12.00

  Industry: Offentlig administration undervisning og sundhed
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 3207.00, Mean: 53.45
      Sample values: [91.0, 41.0, 98.0]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 3195.00, Mean: 53.25
      Sample values: [100.0, 38.0, 93.0]
    Comparison:
      Identical: False
      Correlation: 0.9885
      Sum difference: 12.00

  Industry: Kultur fritid og anden service
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 1084.00, Mean: 18.07
      Sample values: [18.0, 12.0, 30.0]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 1027.00, Mean: 16.84
      Sample values: [22, 21, 34]
    Comparison:
      Identical: False
      Correlation: 0.8882
      Sum difference: 57.00

  Industry: Ikke beskæftiget
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 0.00, Mean: nan
      Sample values: [nan, nan, nan]
    Comparison:
      Identical: True
      Correlation: Cannot calculate (no variation in data)
      Sum difference: 0.00


07. Arbejdsløse:
  Found 2 columns
  Industries with duplicates: 1
  Industries with single column: 0

  Analyzing 1 duplicate pairs:

  Industry: Uoplyst aktivitet
    Version 1 (numbered):
      Non-null: 61/61, Non-zero: 61, Sum: 22030.00, Mean: 361.15
      Sample values: [364, 211, 407]
    Version 2 (no number):
      Non-null: 61/61, Non-zero: 61, Sum: 16337.00, Mean: 267.82
      Sample values: [305, 137, 277]
    Comparison:
      Identical: False
      Correlation: 0.9613
      Sum difference: 5693.00

{'01. Selvstændig og medhj.': ['KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._01. Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._02. Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._03. Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._04. Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._05. Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._06. Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._07. Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._08. Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._09. Offentlig administration undervisning og sundhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._10. Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._11. Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_01. Selvstændig og medhj._Offentlig administration undervisning og sundhed'],
 '02. Topledere': ['KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_01. Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_02. Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_03. Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_04. Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_05. Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_06. Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_07. Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_08. Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_09. Offentlig administration undervisning og sundhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_10. Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_11. Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Bygge og anlæg',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Ejendomshandel og udlejning',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Erhvervsservice',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Finansiering og forsikring',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Handel og transport mv.',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Ikke beskæftiget',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Industri råstofindvinding og forsyningsvirksomhed',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Information og kommunikation',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Kultur fritid og anden service',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Landbrug skovbrug og fiskeri',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_02. Topledere_Offentlig administration undervisning og sundhed'],
 '07. Arbejdsløse': ['KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_12. Uoplyst aktivitet',
  'KV2021 - Socio-økonomisk status og brancher fordelt på afstemningsområder_07. Arbejdsløse_Uoplyst aktivitet']}

In [4]:
socio = cb.preprocess_socioeconomy2(df, 2021)
socio.head(15)

2021

,Gruppe,ValgstedId,KredsNr,Socioeconomy_Self-employed,Socioeconomy_Top executives,Socioeconomy_Unemployed,Socioeconomy_Total
0,101001,101001,1,523.0,345.0,364,15457.0
1,101002,101002,1,350.0,219.0,211,8510.0
2,101003,101003,1,621.0,401.0,407,15765.0
3,101005,101005,1,385.0,226.0,425,15693.0
4,101006,101006,1,442.0,254.0,383,13752.0
5,101007,101007,2,375.0,204.0,447,14134.0
6,101008,101008,2,465.0,247.0,635,18419.0
7,101009,101009,2,499.0,356.0,598,20972.0
8,101010,101010,2,575.0,605.0,386,15610.0
9,101011,101011,3,1043.0,533.0,541,21124.0
10,101012,101012,3,485.0,337.0,205,9173.0
11,101013,101013,3,657.0,354.0,346,13257.0
12,101014,101014,3,863.0,528.0,368,16816.0
13,101016,101016,4,438.0,245.0,498,15673.0
14,101017,101017,4,508.0,207.0,752,20345.0

## Citizenship

In [5]:
cb.inspect_citizenship_duplicates_simple(df, 2021, 20)

================================================================================
CITIZENSHIP DUPLICATE INSPECTION - Year 2021
================================================================================

Total columns found: 384
  With space (e.g. '01. Danmark'): 384
  Without space (e.g. '01.Danmark'): 0

SUMMARY:
  Columns WITH space:
    Columns with data: 384/384
    Total sum across all: 736645.00
  Columns WITHOUT space:
    Columns with data: 0/0
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

In [6]:
citizenship = cb.preprocess_citizenship_sex_age(df, 2021)
pd.set_option('display.max_rows', None)
citizenship.head(15)

    Citizenship data: Using with-space format for year 2021

,Gruppe,ValgstedId,KredsNr,Sex_Male,Sex_Female,Age_0-4 years,Age_5-9 years,Age_10-14 years,Age_15-17 years,Age_18-19 years,...,Citizenship_Former Yugoslavia,Citizenship_Old EU countries,Citizenship_New EU countries,Citizenship_Other Europe,Citizenship_Africa,Citizenship_North America,Citizenship_South and Central America,Citizenship_Asia and Oceania,Citizenship_Not specified,Citizenship_Total
0,101001,101001,1,7331.0,8231.0,853.0,657.0,678.0,385.0,298.0,...,39.0,934.0,202.0,46.0,62.0,147.0,87.0,325.0,8.0,15562.0
1,101002,101002,1,3908.0,4470.0,426.0,383.0,397.0,200.0,175.0,...,27.0,372.0,106.0,41.0,45.0,52.0,49.0,271.0,6.0,8378.0
2,101003,101003,1,7640.0,8206.0,920.0,771.0,862.0,493.0,351.0,...,19.0,763.0,143.0,46.0,39.0,120.0,147.0,309.0,1.0,15846.0
3,101005,101005,1,7648.0,8206.0,929.0,639.0,593.0,301.0,258.0,...,133.0,827.0,297.0,95.0,110.0,178.0,132.0,677.0,3.0,15854.0
4,101006,101006,1,6527.0,6960.0,801.0,563.0,570.0,317.0,246.0,...,82.0,575.0,252.0,67.0,126.0,67.0,70.0,406.0,10.0,13487.0
5,101007,101007,2,6970.0,7295.0,790.0,782.0,705.0,391.0,272.0,...,67.0,435.0,359.0,23.0,177.0,39.0,75.0,681.0,18.0,14265.0
6,101008,101008,2,8807.0,9385.0,1035.0,708.0,637.0,374.0,293.0,...,93.0,664.0,320.0,58.0,214.0,102.0,98.0,698.0,18.0,18192.0
7,101009,101009,2,9721.0,9467.0,1702.0,1109.0,807.0,332.0,327.0,...,139.0,1392.0,1121.0,202.0,140.0,150.0,266.0,1215.0,5.0,19188.0
8,101010,101010,2,7661.0,7790.0,1300.0,896.0,747.0,325.0,210.0,...,23.0,673.0,178.0,61.0,41.0,104.0,92.0,274.0,2.0,15451.0
9,101011,101011,3,10914.0,9369.0,910.0,649.0,617.0,399.0,386.0,...,73.0,1692.0,441.0,103.0,196.0,316.0,233.0,612.0,21.0,20283.0
10,101012,101012,3,4431.0,4745.0,465.0,452.0,517.0,306.0,219.0,...,14.0,569.0,81.0,39.0,30.0,114.0,46.0,159.0,0.0,9176.0
11,101013,101013,3,6582.0,6633.0,760.0,538.0,447.0,292.0,214.0,...,18.0,748.0,173.0,40.0,37.0,132.0,90.0,186.0,4.0,13215.0
12,101014,101014,3,8134.0,8580.0,730.0,478.0,523.0,351.0,283.0,...,27.0,1225.0,261.0,106.0,51.0,303.0,141.0,450.0,2.0,16714.0
13,101016,101016,4,7069.0,7489.0,992.0,543.0,471.0,282.0,212.0,...,55.0,746.0,358.0,78.0,98.0,91.0,111.0,421.0,7.0,14558.0
14,101017,101017,4,10080.0,10523.0,1195.0,669.0,629.0,332.0,310.0,...,109.0,924.0,623.0,76.0,196.0,112.0,159.0,845.0,21.0,20603.0

## Education

In [7]:
cb.inspect_education_duplicates(df, 2021, 20)

================================================================================
EDUCATION DUPLICATE INSPECTION - Year 2021
================================================================================

Age variant '70- år': 8 columns found
  Columns with data: 8/8
  Total sum: 58022.00
Age variant '70 år -': 0 columns found

CONCLUSION:
  ✓ Use '70- år' format (only one available)

In [8]:
education = cb.preprocess_education(df, 2021)
education.head()

    Education data: Using '70- år' for 70+ age group

,Gruppe,ValgstedId,KredsNr,Education_18-29 years_Primary and lower secondary,Education_30-70+ years_Primary and lower secondary,Education_18-29 years_General upper secondary,Education_30-70+ years_General upper secondary,Education_18-29 years_Vocational upper secondary,Education_30-70+ years_Vocational upper secondary,Education_18-29 years_Vocational training,...,Education_30-70+ years_Short higher education,Education_18-29 years_Medium higher education,Education_30-70+ years_Medium higher education,Education_18-29 years_Long higher education,Education_30-70+ years_Long higher education,Education_18-29 years_Not specified,Education_30-70+ years_Not specified,Education_Total 18-29 years,Education_Total 30-70+ years,Education_Total
0,101001,101001,1,453.0,885.0,1243.0,569.0,153.0,94.0,181.0,...,401.0,415.0,1927.0,1433.0,3497.0,21.0,154.0,4060.0,8982.0,13042.0
1,101002,101002,1,249.0,653.0,519.0,323.0,70.0,72.0,119.0,...,224.0,195.0,1014.0,577.0,1834.0,17.0,106.0,1837.0,5145.0,6982.0
2,101003,101003,1,447.0,779.0,1169.0,583.0,126.0,93.0,146.0,...,387.0,362.0,1964.0,1205.0,3930.0,16.0,139.0,3615.0,9204.0,12819.0
3,101005,101005,1,438.0,1423.0,1138.0,553.0,167.0,87.0,220.0,...,403.0,718.0,1709.0,1266.0,2814.0,21.0,220.0,4251.0,9197.0,13448.0
4,101006,101006,1,479.0,1087.0,980.0,431.0,177.0,93.0,234.0,...,374.0,407.0,1450.0,1115.0,2466.0,17.0,169.0,3532.0,7720.0,11252.0

## Immigrants and descendants

In [9]:
cb.inspect_immigrants_duplicates(df, 2021, 20)

================================================================================
IMMIGRANTS/DESCENDANTS DUPLICATE INSPECTION - Year 2021
================================================================================

Total columns found: 352
  With space (e.g. '01. Danmark'): 352
  Without space (e.g. '01.Danmark'): 0

SUMMARY:
  Columns WITH space:
    Columns with data: 350/352
    Total sum across all: 181923.00
  Columns WITHOUT space:
    Columns with data: 0/0
    Total sum across all: 0.00

CONCLUSION:
  USE columns WITH space
  IGNORE columns WITHOUT space (they are empty)

In [10]:
immigrants = cb.preprocess_immigrants(df, 2021)
immigrants.head()

    Immigrants/descendants data: Using with-space format for year 2021

,Gruppe,ValgstedId,KredsNr,Immigrants_Denmark,Immigrants_Nordic,Immigrants_Turkey,Immigrants_Former Yugoslavia,Immigrants_Old EU countries,Immigrants_New EU countries,Immigrants_Other Europe,Immigrants_Africa,Immigrants_North America,Immigrants_South and Central America,Immigrants_Asia and Oceania,Immigrants_Not specified,Immigrants_Total
0,101001,101001,1,NaN,388.0,40.0,80.0,895.0,275.0,88.0,201.0,168.0,161.0,586.0,1.0,2883.0
1,101002,101002,1,NaN,148.0,57.0,78.0,360.0,153.0,77.0,120.0,58.0,88.0,525.0,0.0,1664.0
2,101003,101003,1,NaN,359.0,52.0,39.0,729.0,189.0,83.0,128.0,151.0,212.0,560.0,1.0,2503.0
3,101005,101005,1,NaN,303.0,136.0,306.0,799.0,406.0,166.0,307.0,194.0,214.0,1113.0,3.0,3947.0
4,101006,101006,1,NaN,236.0,94.0,199.0,579.0,326.0,118.0,301.0,76.0,130.0,984.0,0.0,3043.0

## Housing tenure

In [11]:
cb.inspect_housingtenure_duplicates(df, 2021, 20)

================================================================================
HOUSING TENURE DUPLICATE INSPECTION - Year 2021
================================================================================

Total columns found: 12

  Spaced columns     (e.g. 'Antal boliger'):   0
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 0/0
    Total sum across all: 0.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 12/12
    Total sum across all: 1100299.00

CONCLUSION:
  USE columns with UNDERSCORES ('Antal_boliger', 'Antal_personer').
  IGNORE columns with spaces (they appear empty).

================================================================================

In [12]:
tenure = cb.preprocess_housingtenure(df, 2021)

    Housing tenure data: Using underscored format for year 2021

## Housing type

In [13]:
cb.inspect_housingtype_duplicates(df, 2021, 20)

================================================================================
HOUSING TYPE DUPLICATE INSPECTION - Year 2021
================================================================================

Total columns found: 12

  Spaced columns     (e.g. 'Antal boliger'):   0
  Underscore columns (e.g. 'Antal_boliger'):  12

SUMMARY:
  Columns using SPACE ('Antal boliger' or 'Antal personer'):
    Columns with data: 0/0
    Total sum across all: 0.00
  Columns using UNDERSCORE ('Antal_boliger' or 'Antal_personer'):
    Columns with data: 12/12
    Total sum across all: 1100299.00

CONCLUSION:
  USE columns with UNDERSCORES ('Antal_boliger', 'Antal_personer').
  IGNORE columns with spaces (they appear empty).

================================================================================

In [14]:
housingtype = cb.preprocess_housingtype(df, 2021)
housingtype.head()

    Housing type data: Using underscored format for year 2021

,Gruppe,ValgstedId,KredsNr,Housing type_Homes_Detached house,Housing type_Homes_Terraced house,Housing type_Homes_Apartment buildings,Housing type_Homes_Student halls,Housing type_Homes_Holiday homes,Housing type_Homes_Other homes,Housing type_Homes_No BBR information,Housing type_People_Detached house,Housing type_People_Terraced house,Housing type_People_Apartment buildings,Housing type_People_Student halls,Housing type_People_Holiday homes,Housing type_People_Other homes,Housing type_People_No BBR information,Housing type_Total people,Housing type_Total homes
0,101001,101001,1,2.0,46.0,7986,0.0,0.0,10.0,NaN,8.0,142.0,15374,0.0,0.0,38.0,NaN,15562.0,8044.0
1,101002,101002,1,220.0,93.0,3884,7.0,0.0,95.0,NaN,785.0,266.0,7107,7.0,0.0,213.0,NaN,8378.0,4299.0
2,101003,101003,1,22.0,9.0,7303,268.0,1.0,24.0,NaN,79.0,23.0,15316,287.0,1.0,140.0,NaN,15846.0,7627.0
3,101005,101005,1,4.0,145.0,7883,196.0,0.0,148.0,NaN,5.0,532.0,14657,413.0,0.0,247.0,NaN,15854.0,8376.0
4,101006,101006,1,16.0,371.0,6589,98.0,1.0,30.0,NaN,43.0,1134.0,12150,108.0,1.0,51.0,NaN,13487.0,7105.0

## Housing, year built

In [15]:
cb.inspect_constructionyear_duplicates(df, 2021, 20)

================================================================================
CONSTRUCTION YEAR INSPECTION - Year 2021
================================================================================

Total columns found: 16

Columns with SPACE (e.g., 'Antal boliger_...'):
  Total: 2
  With data: 2
    ✓ Antal_boliger_Før 1940                                       sum=222363
    ✓ Antal_personer_Før 1940                                      sum=454998

Columns with UNDERSCORE (e.g., 'Antal_boliger_...'):
  Total: 14
  With data: 14
    ✓ Antal_boliger_1940-1959                                      sum=45375
    ✓ Antal_boliger_1960-1969                                      sum=18949
    ✓ Antal_boliger_1970-1979                                      sum=19323
    ✓ Antal_boliger_1980-1989                                      sum=11460
    ✓ Antal_boliger_1990-1999                                      sum=8160
    ✓ Antal_boliger_2000-2009                                      sum=15674
    ✓ Antal_boliger_2010-9999                                      sum=22350
    ✓ Antal_personer_1940-1959                                     sum=83195
    ✓ Antal_personer_1960-1969                                     sum=34659
    ✓ Antal_personer_1970-1979                                     sum=33969
    ✓ Antal_personer_1980-1989                                     sum=26405
    ✓ Antal_personer_1990-1999                                     sum=16380
    ✓ Antal_personer_2000-2009                                     sum=34005
    ✓ Antal_personer_2010-9999                                     sum=53034

CONCLUSION:
  ✓ USE underscore columns (Antal_boliger/Antal_personer)
    14 columns have data vs 2 spaced columns

================================================================================

In [16]:
builtyear = cb.preprocess_builtyear(df, 2021)

    Construction year data: Using underscored format for year 2021

In [17]:
old_homes_cols = [
    'Year built_Homes_Før 1940',
    'Year built_Homes_1940-1959'
]
middle_homes_cols = [
    'Year built_Homes_1960-1969',
    'Year built_Homes_1970-1979',
    'Year built_Homes_1980-1989',    
    'Year built_Homes_1990-1999',
    'Year built_Homes_2000-2009',
]
old_people_cols = [
    'Year built_People_Før 1940',
    'Year built_People_1940-1959'
]
middle_people_cols = [
    'Year built_People_1960-1969',
    'Year built_People_1970-1979',
    'Year built_People_1980-1989',    
    'Year built_People_1990-1999',
    'Year built_People_2000-2009',
]

builtyear["Year built_People_Before 1960"] = builtyear[old_people_cols].sum(axis=1)
builtyear["Year built_People_1960-2009"] = builtyear[middle_people_cols].sum(axis=1)
builtyear["Year built_Homes_Before 1960"] = builtyear[old_homes_cols].sum(axis=1)
builtyear["Year built_Homes_1960-2009"] = builtyear[middle_homes_cols].sum(axis=1)

columns_to_keep = [
    "Gruppe",
    "ValgstedId",
    "KredsNr",
    "Year built_People_Before 1960",
    "Year built_People_1960-2009",
    "Year built_Homes_Before 1960",
    "Year built_Homes_1960-2009",
    "Year built_People_2010-9999",
    "Year built_Homes_2010-9999",
    "Year built_Total people",
    "Year built_Total homes",
]

builtyear = builtyear[columns_to_keep]
builtyear.head()

,Gruppe,ValgstedId,KredsNr,Year built_People_Before 1960,Year built_People_1960-2009,Year built_Homes_Before 1960,Year built_Homes_1960-2009,Year built_People_2010-9999,Year built_Homes_2010-9999,Year built_Total people,Year built_Total homes
0,101001,101001,1,13417.0,2055.0,6887.0,1117.0,90.0,40.0,15562.0,8044.0
1,101002,101002,1,6994.0,1235.0,3418.0,809.0,149.0,72.0,8378.0,4299.0
2,101003,101003,1,14942.0,904.0,7041.0,586.0,0.0,0.0,15846.0,7627.0
3,101005,101005,1,11810.0,3873.0,6119.0,2167.0,171.0,90.0,15854.0,8376.0
4,101006,101006,1,10028.0,3240.0,5283.0,1737.0,219.0,85.0,13487.0,7105.0

## Income, benefit type, cars, crime

In [18]:
simple = cb.preprocess_simple(df, 2021)
simple.head()

    Extracting from Benefit type...
    Extracting from Crime...
    Extracting from Income...
    Extracting from Car...

,Gruppe,ValgstedId,KredsNr,Benefit type_Kontanthjaelp,Benefit type_Foertidspension,Benefit type_Folkepension,Benefit type_Modtager ikke ydelser,Benefit type_Antal personer i alt,Crime_Number of arrests,Income_Median household income,Income_Total households,Income_Gross income top20pct,Car_Households with no car,Car_Households with 1 car,Car_Households with 2+ cars
0,101001,101001,1,259.0,244.0,1646.0,11236.0,15562.0,40.0,491202.0,7928.0,2.353964e+09,5056.0,956.0,2032.0
1,101002,101002,1,184.0,160.0,1307.0,5669.0,8378.0,29.0,469505.0,4351.0,1.813280e+09,2385.0,658.0,1256.0
2,101003,101003,1,170.0,177.0,1579.0,11748.0,15846.0,41.0,542786.0,7547.0,2.551615e+09,4591.0,807.0,2229.0
3,101005,101005,1,314.0,376.0,2038.0,10767.0,15854.0,68.0,438719.0,8208.0,1.974027e+09,5361.0,1057.0,1958.0
4,101006,101006,1,307.0,372.0,1617.0,9086.0,13487.0,38.0,449840.0,7164.0,1.844543e+09,4349.0,954.0,1802.0

## Combine

In [19]:
names = [
    'socio',
    'citizenship',
    'immigrants',
    'education',
    'tenure',
    'housingtype',
    'simple',
    'builtyear'
]

combined_dfs = {}
# start with first dataframe
df_combined = globals()[f'{names[0]}'].copy()
# merge subsequent dataframes
for name in names[1:]:
    df_name = f'{name}'
    df_combined = df_combined.merge(
        globals()[df_name], 
        on=COMMON_COLS,
        how='outer',
        suffixes=('', f'_{name}')
    )
combined_dfs[2021] = df_combined

df_2021 = combined_dfs[2021]
df_2021.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 116 columns):
 #    Column                                              Dtype
---   ------                                              -----
 0    Gruppe                                              object
 1    ValgstedId                                          object
 2    KredsNr                                             object
 3    Socioeconomy_Self-employed                          float64
 4    Socioeconomy_Top executives                         float64
 5    Socioeconomy_Unemployed                             int64
 6    Socioeconomy_Total                                  float64
 7    Sex_Male                                            float64
 8    Sex_Female                                          float64
 9    Age_0-4 years                                       float64
 10   Age_5-9 years                                       float64
 11   Age_10-14 years                                     float64
 12   Age_15-17 years                                     float64
 13   Age_18-19 years                                     float64
 14   Age_20-24 years                                     float64
 15   Age_25-29 years                                     float64
 16   Age_30-34 years                                     float64
 17   Age_35-39 years                                     float64
 18   Age_40-44 years                                     float64
 19   Age_45-49 years                                     float64
 20   Age_50-54 years                                     float64
 21   Age_55-59 years                                     float64
 22   Age_60-64 years                                     float64
 23   Age_65-69 years                                     float64
 24   Age_70- years                                       float64
 25   Citizenship_Denmark                                 float64
 26   Citizenship_Nordic                                  float64
 27   Citizenship_Turkey                                  float64
 28   Citizenship_Former Yugoslavia                       float64
 29   Citizenship_Old EU countries                        float64
 30   Citizenship_New EU countries                        float64
 31   Citizenship_Other Europe                            float64
 32   Citizenship_Africa                                  float64
 33   Citizenship_North America                           float64
 34   Citizenship_South and Central America               float64
 35   Citizenship_Asia and Oceania                        float64
 36   Citizenship_Not specified                           float64
 37   Citizenship_Total                                   float64
 38   Immigrants_Denmark                                  float64
 39   Immigrants_Nordic                                   float64
 40   Immigrants_Turkey                                   float64
 41   Immigrants_Former Yugoslavia                        float64
 42   Immigrants_Old EU countries                         float64
 43   Immigrants_New EU countries                         float64
 44   Immigrants_Other Europe                             float64
 45   Immigrants_Africa                                   float64
 46   Immigrants_North America                            float64
 47   Immigrants_South and Central America                float64
 48   Immigrants_Asia and Oceania                         float64
 49   Immigrants_Not specified                            float64
 50   Immigrants_Total                                    float64
 51   Education_18-29 years_Primary and lower secondary   float64
 52   Education_30-70+ years_Primary and lower secondary  float64
 53   Education_18-29 years_General upper secondary       float64
 54   Education_30-70+ years_General upper secondary      float64
 55   Education_18-29 years_Vocational upper secondary    float64
 56   Education_30-70+ years_Vocational upper secondary   float64
 57   Education_18-29 years_Vocational training           float64
 58   Education_30-70+ years_Vocational training          float64
 59   Education_18-29 years_Short higher education        float64
 60   Education_30-70+ years_Short higher education       float64
 61   Education_18-29 years_Medium higher education       float64
 62   Education_30-70+ years_Medium higher education      float64
 63   Education_18-29 years_Long higher education         float64
 64   Education_30-70+ years_Long higher education        float64
 65   Education_18-29 years_Not specified                 float64
 66   Education_30-70+ years_Not specified                float64
 67   Education_Total 18-29 years                         float64
 68   Education_Total 30-70+ years                        float64
 69   Education_Total                                     float64
 70   Housing tenure_Homes_Ejer                           float64
 71   Housing tenure_Homes_Andel                          float64
 72   Housing tenure_Homes_Almen                          float64
 73   Housing tenure_Homes_Private rental                 float64
 74   Housing tenure_People_Ejer                          float64
 75   Housing tenure_People_Andel                         float64
 76   Housing tenure_People_Almen                         float64
 77   Housing tenure_People_Private rental                float64
 78   Housing tenure_Total people                         float64
 79   Housing tenure_Total homes                          float64
 80   Housing type_Homes_Detached house                   float64
 81   Housing type_Homes_Terraced house                   float64
 82   Housing type_Homes_Apartment buildings              int64
 83   Housing type_Homes_Student halls                    float64
 84   Housing type_Homes_Holiday homes                    float64
 85   Housing type_Homes_Other homes                      float64
 86   Housing type_Homes_No BBR information               float64
 87   Housing type_People_Detached house                  float64
 88   Housing type_People_Terraced house                  float64
 89   Housing type_People_Apartment buildings             int64
 90   Housing type_People_Student halls                   float64
 91   Housing type_People_Holiday homes                   float64
 92   Housing type_People_Other homes                     float64
 93   Housing type_People_No BBR information              float64
 94   Housing type_Total people                           float64
 95   Housing type_Total homes                            float64
 96   Benefit type_Kontanthjaelp                          float64
 97   Benefit type_Foertidspension                        float64
 98   Benefit type_Folkepension                           float64
 99   Benefit type_Modtager ikke ydelser                  float64
 100  Benefit type_Antal personer i alt                   float64
 101  Crime_Number of arrests                             float64
 102  Income_Median household income                      float64
 103  Income_Total households                             float64
 104  Income_Gross income top20pct                        float64
 105  Car_Households with no car                          float64
 106  Car_Households with 1 car                           float64
 107  Car_Households with 2+ cars                         float64
 108  Year built_People_Before 1960                       float64
 109  Year built_People_1960-2009                         float64
 110  Year built_Homes_Before 1960                        float64
 111  Year built_Homes_1960-2009                          float64
 112  Year built_People_2010-9999                         float64
 113  Year built_Homes_2010-9999                          float64
 114  Year built_Total people                             float64
 115  Year built_Total homes                              float64
dtypes: float64(110), int64(3), object(3)
memory usage: 55.4+ KB

In [20]:
nan_columns = df_2021.isna().any()
print(nan_columns[nan_columns])

Immigrants_Denmark                        True
Housing type_Homes_No BBR information     True
Housing type_People_No BBR information    True
dtype: bool

## Drop and add columns

In [21]:
df = combined_dfs[2021]
cols_to_drop = []

# 1. Drop columns with 0 non-null entries
cols_to_drop.extend([col for col in df.columns if df[col].notna().sum() == 0])

# 2. Drop specific Education columns
education_suffixes = [
    'Medium higher education',
    'Short higher education',
    'Vocational upper secondary',
    'General upper secondary'
]
cols_to_drop.extend([col for col in df.columns 
                    if col.startswith('Education_') and 
                    any(col.endswith(suffix) for suffix in education_suffixes)])

# 3. Drop specific Housing type columns
housing_suffixes = [
    'Student halls',
    'Holiday homes',
    'Other homes',
]
cols_to_drop.extend([col for col in df.columns 
                    if col.startswith('Housing type_') and 
                    any(col.endswith(suffix) for suffix in housing_suffixes)])

# Remove duplicates and drop
cols_to_drop = list(set(cols_to_drop))
df = df.drop(columns=cols_to_drop)
combined_dfs[2021] = df

print(f"Dropped {len(cols_to_drop)} columns from 2021, remaining: {df.shape[1]}")

# Reassign
df_2021 = combined_dfs[2021]
df_2021.info(verbose=True)

Dropped 17 columns from 2021, remaining: 99
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 99 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              61 non-null     object
 1   ValgstedId                                          61 non-null     object
 2   KredsNr                                             61 non-null     object
 3   Socioeconomy_Self-employed                          61 non-null     float64
 4   Socioeconomy_Top executives                         61 non-null     float64
 5   Socioeconomy_Unemployed                             61 non-null     int64
 6   Socioeconomy_Total                                  61 non-null     float64
 7   Sex_Male                                            61 non-null     float64
 8   Sex_Female                                          61 non-null     float64
 9   Age_0-4 years                                       61 non-null     float64
 10  Age_5-9 years                                       61 non-null     float64
 11  Age_10-14 years                                     61 non-null     float64
 12  Age_15-17 years                                     61 non-null     float64
 13  Age_18-19 years                                     61 non-null     float64
 14  Age_20-24 years                                     61 non-null     float64
 15  Age_25-29 years                                     61 non-null     float64
 16  Age_30-34 years                                     61 non-null     float64
 17  Age_35-39 years                                     61 non-null     float64
 18  Age_40-44 years                                     61 non-null     float64
 19  Age_45-49 years                                     61 non-null     float64
 20  Age_50-54 years                                     61 non-null     float64
 21  Age_55-59 years                                     61 non-null     float64
 22  Age_60-64 years                                     61 non-null     float64
 23  Age_65-69 years                                     61 non-null     float64
 24  Age_70- years                                       61 non-null     float64
 25  Citizenship_Denmark                                 61 non-null     float64
 26  Citizenship_Nordic                                  61 non-null     float64
 27  Citizenship_Turkey                                  61 non-null     float64
 28  Citizenship_Former Yugoslavia                       61 non-null     float64
 29  Citizenship_Old EU countries                        61 non-null     float64
 30  Citizenship_New EU countries                        61 non-null     float64
 31  Citizenship_Other Europe                            61 non-null     float64
 32  Citizenship_Africa                                  61 non-null     float64
 33  Citizenship_North America                           61 non-null     float64
 34  Citizenship_South and Central America               61 non-null     float64
 35  Citizenship_Asia and Oceania                        61 non-null     float64
 36  Citizenship_Not specified                           61 non-null     float64
 37  Citizenship_Total                                   61 non-null     float64
 38  Immigrants_Nordic                                   61 non-null     float64
 39  Immigrants_Turkey                                   61 non-null     float64
 40  Immigrants_Former Yugoslavia                        61 non-null     float64
 41  Immigrants_Old EU countries                         61 non-null     float64
 42  Immigrants_New EU countries                         61 non-null     float64
 43  Immigrants_Other Europe                             61 non-null     float64
 44  Immigrants_Africa                                   61 non-null     float64
 45  Immigrants_North America                            61 non-null     float64
 46  Immigrants_South and Central America                61 non-null     float64
 47  Immigrants_Asia and Oceania                         61 non-null     float64
 48  Immigrants_Not specified                            61 non-null     float64
 49  Immigrants_Total                                    61 non-null     float64
 50  Education_18-29 years_Primary and lower secondary   61 non-null     float64
 51  Education_30-70+ years_Primary and lower secondary  61 non-null     float64
 52  Education_18-29 years_Vocational training           61 non-null     float64
 53  Education_30-70+ years_Vocational training          61 non-null     float64
 54  Education_18-29 years_Long higher education         61 non-null     float64
 55  Education_30-70+ years_Long higher education        61 non-null     float64
 56  Education_18-29 years_Not specified                 61 non-null     float64
 57  Education_30-70+ years_Not specified                61 non-null     float64
 58  Education_Total 18-29 years                         61 non-null     float64
 59  Education_Total 30-70+ years                        61 non-null     float64
 60  Education_Total                                     61 non-null     float64
 61  Housing tenure_Homes_Ejer                           61 non-null     float64
 62  Housing tenure_Homes_Andel                          61 non-null     float64
 63  Housing tenure_Homes_Almen                          61 non-null     float64
 64  Housing tenure_Homes_Private rental                 61 non-null     float64
 65  Housing tenure_People_Ejer                          61 non-null     float64
 66  Housing tenure_People_Andel                         61 non-null     float64
 67  Housing tenure_People_Almen                         61 non-null     float64
 68  Housing tenure_People_Private rental                61 non-null     float64
 69  Housing tenure_Total people                         61 non-null     float64
 70  Housing tenure_Total homes                          61 non-null     float64
 71  Housing type_Homes_Detached house                   61 non-null     float64
 72  Housing type_Homes_Terraced house                   61 non-null     float64
 73  Housing type_Homes_Apartment buildings              61 non-null     int64
 74  Housing type_People_Detached house                  61 non-null     float64
 75  Housing type_People_Terraced house                  61 non-null     float64
 76  Housing type_People_Apartment buildings             61 non-null     int64
 77  Housing type_Total people                           61 non-null     float64
 78  Housing type_Total homes                            61 non-null     float64
 79  Benefit type_Kontanthjaelp                          61 non-null     float64
 80  Benefit type_Foertidspension                        61 non-null     float64
 81  Benefit type_Folkepension                           61 non-null     float64
 82  Benefit type_Modtager ikke ydelser                  61 non-null     float64
 83  Benefit type_Antal personer i alt                   61 non-null     float64
 84  Crime_Number of arrests                             61 non-null     float64
 85  Income_Median household income                      61 non-null     float64
 86  Income_Total households                             61 non-null     float64
 87  Income_Gross income top20pct                        61 non-null     float64
 88  Car_Households with no car                          61 non-null     float64
 89  Car_Households with 1 car                           61 non-null     float64
 90  Car_Households with 2+ cars                         61 non-null     float64
 91  Year built_People_Before 1960                       61 non-null     float64
 92  Year built_People_1960-2009                         61 non-null     float64
 93  Year built_Homes_Before 1960                        61 non-null     float64
 94  Year built_Homes_1960-2009                          61 non-null     float64
 95  Year built_People_2010-9999                         61 non-null     float64
 96  Year built_Homes_2010-9999                          61 non-null     float64
 97  Year built_Total people                             61 non-null     float64
 98  Year built_Total homes                              61 non-null     float64
dtypes: float64(93), int64(3), object(3)
memory usage: 47.3+ KB

In [22]:
def add_geography_columns(df, geography_csv_path):
    """
    Add geography columns to dataframe by matching ValgstedId.
    
    Parameters:
    - df: DataFrame to add columns to
    - geography_csv_path: Path to Geography.csv
    
    Returns:
    - DataFrame with added geography columns
    """    
    # Read Geography.csv
    geo_df = pd.read_csv(geography_csv_path, sep=';', encoding='utf-8', quotechar='"')
    
    # Clean column names (remove any extra whitespace/quotes)
    geo_df.columns = geo_df.columns.str.strip().str.strip('"')

    # Filter for KommuneNr 101 or 147
    geo_df = geo_df[geo_df['KommuneNr'].astype(str).isin(['101', '147'])].copy()

    # Debug: print first few rows to see what we're working with
    print("Geography CSV columns:", geo_df.columns.tolist())
    print("First few Valgsted Ids:", geo_df['Valgsted Id'].head().tolist())

    # Create a dictionary for quick lookup
    geo_dict = {}
    for _, row in geo_df.iterrows():
        # Clean the ValgstedId (remove quotes, whitespace)
        valgsted_id = str(row['Valgsted Id']).strip().strip('"')
        geo_dict[valgsted_id] = {
            'Valgsted navn': str(row['Valgsted navn']).strip().strip('"'),
            'Kreds navn': str(row['Kreds navn']).strip().strip('"'),
            'Kommune navn': str(row['Kommune navn']).strip().strip('"')
        }
    
    print(f"Total entries in geo_dict: {len(geo_dict)}")
    print(f"Sample keys: {list(geo_dict.keys())[:5]}")
    
    # Create new columns
    df_result = df.copy()
    valgsted_navne = []
    kreds_navne = []
    kommune_navne = []
    
    for _, row in df_result.iterrows():
        valgsted_ids = str(row['ValgstedId']).split(';')
        
        # Collect names for each ValgstedId
        v_names = []
        k_names = []
        kom_names = []
        
        for vid in valgsted_ids:
            vid = vid.strip()
            if vid not in geo_dict:
                print(f"Missing ValgstedId: '{vid}' (length: {len(vid)})")
                print(f"Available keys starting with '101': {[k for k in geo_dict.keys() if k.startswith('101')][:10]}")
                raise ValueError(f"ValgstedId '{vid}' not found in Geography.csv")
            
            v_names.append(geo_dict[vid]['Valgsted navn'])
            k_names.append(geo_dict[vid]['Kreds navn'])
            kom_names.append(geo_dict[vid]['Kommune navn'])
        
        # Join with semicolons, remove duplicates while preserving order
        valgsted_navne.append(';'.join(v_names))
        
        # For Kreds and Kommune, use single value if all same, otherwise semicolon-separate
        if len(set(k_names)) == 1:
            kreds_navne.append(k_names[0])
        else:
            kreds_navne.append(';'.join(k_names))
            
        if len(set(kom_names)) == 1:
            kommune_navne.append(kom_names[0])
        else:
            kommune_navne.append(';'.join(kom_names))
    
    # Add the new columns
    df_result['Polling area'] = valgsted_navne
    df_result['District'] = kreds_navne
    df_result['Municipality'] = kommune_navne
        
    # Reorder columns to put the first 6 in the desired order
    first_cols = ['Gruppe', 'ValgstedId', 'Polling area', 'KredsNr', 'District', 'Municipality']
    other_cols = [col for col in df_result.columns if col not in first_cols]
    df_result = df_result[first_cols + other_cols]
    
    return df_result

geography_path = PATH + 'Geography.csv'


combined_dfs[2021] = add_geography_columns(combined_dfs[2021], geography_path)
print(f"Added geography columns to 2021")

# Reassign
df_2021 = combined_dfs[2021]

# Check the result
print("\nFirst few rows of df_2021:")
print(df_2021[['Gruppe', 'ValgstedId', 'Polling area', 'KredsNr', 'District', 'Municipality']].head(10))

Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2021

First few rows of df_2021:
   Gruppe ValgstedId     Polling area KredsNr         District Municipality
0  101001     101001      1. Østerbro       1      1. Østerbro    København
1  101002     101002          1. Nord       1      1. Østerbro    København
2  101003     101003           1. Syd       1      1. Østerbro    København
3  101005     101005          1. Vest       1      1. Østerbro    København
4  101006     101006      1. Nordvest       1      1. Østerbro    København
5  101007     101007  2. Sundbyvester       2  2. Sundbyvester    København
6  101008     101008          2. Nord       2  2. Sundbyvester    København
7  101009     101009           2. Syd       2  2. Sundbyvester    København
8  101010     101010          2. Vest       2  2. Sundbyvester    København
9  101011     101011      3. Indre By       3      3. Indre By    København

## Convert (some) floats to ints

In [23]:
def convert_floats_to_int(df):
    """Convert float columns to int if they have no fractional parts"""
    df_converted = df.copy()
    
    for col in df_converted.columns:
        # Check if column is float type
        if df_converted[col].dtype == 'float64':
            # Check if all non-null values have no fractional part
            non_null_values = df_converted[col].dropna()
            if len(non_null_values) > 0 and (non_null_values % 1 == 0).all():
                # Convert to Int64 (nullable integer type to preserve NaN if present)
                df_converted[col] = df_converted[col].astype('int64')
    
    return df_converted


combined_dfs[2021] = convert_floats_to_int(combined_dfs[2021])
print(f"Converted 2021")

print("\ndf_2021 dtypes before conversion:")
print(df_2021.dtypes.value_counts())

# Reassign
df_2021 = combined_dfs[2021]

# Check the result
print("\ndf_2021 dtypes after conversion:")
print(df_2021.dtypes.value_counts())

Converted 2021

df_2021 dtypes before conversion:
float64    93
object      6
int64       3
Name: count, dtype: int64

df_2021 dtypes after conversion:
int64     96
object     6
Name: count, dtype: int64

## Check total columns

In [24]:
# Check if 'total' columns are similar for the same polling area

total_cols = [
    'Gruppe',
    'Socioeconomy_Total',
    'Citizenship_Total',
    'Education_Total',
    'Housing tenure_Total people',
    'Housing type_Total people',
    'Benefit type_Antal personer i alt',
    'Year built_Total people'
]

total_df = df_2021[total_cols].copy()
total_df.head(10)

,Gruppe,Socioeconomy_Total,Citizenship_Total,Education_Total,Housing tenure_Total people,Housing type_Total people,Benefit type_Antal personer i alt,Year built_Total people
0,101001,15457,15562,13042,11438,15562,15562,15562
1,101002,8510,8378,6982,7017,8378,8378,8378
2,101003,15765,15846,12819,12193,15846,15846,15846
3,101005,15693,15854,13448,12350,15854,15854,15854
4,101006,13752,13487,11252,11023,13487,13487,13487
5,101007,14134,14265,11588,12900,14265,14265,14265
6,101008,18419,18192,15746,15006,18192,18192,18192
7,101009,20972,19188,14993,10575,19188,19188,19188
8,101010,15610,15451,12116,13016,15451,15451,15451
9,101011,21124,20283,17987,10167,20283,20283,20283

In [25]:
# They LOOK very similar, but let's see some statistics

numeric_totals = total_df.drop(columns=['Gruppe'])

total_df['mean_across_totals'] = numeric_totals.mean(axis=1)
total_df['median_across_totals'] = numeric_totals.median(axis=1)
total_df['mode_across_totals'] = numeric_totals.mode(axis=1)
total_df['std_across_totals'] = numeric_totals.std(axis=1)
total_df['min_across_totals'] = numeric_totals.min(axis=1)
total_df['max_across_totals'] = numeric_totals.max(axis=1)
total_df['range_across_totals'] = total_df['max_across_totals'] - total_df['min_across_totals']
total_df['cv_across_totals'] = (numeric_totals.std(axis=1) / numeric_totals.mean(axis=1)) * 100
# CV is the Coefficient of Variation (CV) - the relative variation as a percentage of the mean.

In [26]:
# Show rows with the most variation
total_df.nlargest(10, 'cv_across_totals')

,Gruppe,Socioeconomy_Total,Citizenship_Total,Education_Total,Housing tenure_Total people,Housing type_Total people,Benefit type_Antal personer i alt,Year built_Total people,mean_across_totals,median_across_totals,mode_across_totals,std_across_totals,min_across_totals,max_across_totals,range_across_totals,cv_across_totals
48,101055,17438,15656,12611,5782,15656,15656,15656,14065.000000,15656.0,15656,3920.553915,5782,17438,11656,27.874539
9,101011,21124,20283,17987,10167,20283,20283,20283,18630.000000,20283.0,20283,3855.418049,10167,21124,10957,20.694676
7,101009,20972,19188,14993,10575,19188,19188,19188,17613.142857,19188.0,19188,3596.369115,10575,20972,10397,20.418668
57,147005,14187,14285,12148,7414,14285,14285,14285,12984.142857,14285.0,14285,2580.097183,7414,14285,6871,19.871140
41,101048,11232,11095,9038,6776,11095,11095,11095,10203.714286,11095.0,11095,1700.149377,6776,11232,4456,16.662064
47,101054,4458,4468,4012,2678,4468,4468,4468,4145.714286,4468.0,4468,668.961811,2678,4468,1790,16.136226
12,101014,16816,16714,14963,10052,16714,16714,16714,15526.714286,16714.0,16714,2503.035405,10052,16816,6764,16.120831
38,101044,12049,10560,8072,8041,10560,10560,10560,10057.428571,10560.0,10560,1471.086884,8041,12049,4008,14.626869
59,147007,13087,13084,11102,8772,13084,13084,13084,12185.285714,13084.0,13084,1676.696426,8772,13087,4315,13.760009
26,101030,13462,13733,12058,9134,13733,13733,13733,12798.000000,13733.0,13733,1727.729338,9134,13733,4599,13.499995

In [27]:
# Check if specific columns are always equal

cols_to_check = [
    'Citizenship_Total',
    'Housing type_Total people',
    'Benefit type_Antal personer i alt',
    'Year built_Total people'
]

# Check if all values in each row are equal
all_equal = (total_df[cols_to_check].nunique(axis=1) == 1).all()
print(f"Are these columns always equal across all rows? {all_equal}")

# See which rows (if any) have different values
rows_with_differences = total_df[total_df[cols_to_check].nunique(axis=1) > 1]
print(f"\nRows where values differ: {len(rows_with_differences)}")
if len(rows_with_differences) > 0:
    print(rows_with_differences[['Gruppe'] + cols_to_check])

# Verify by looking at a sample
print("\nSample of the columns:")
print(total_df[['Gruppe'] + cols_to_check].head(10))

Are these columns always equal across all rows? True

Rows where values differ: 0

Sample of the columns:
   Gruppe  Citizenship_Total  Housing type_Total people  \
0  101001              15562                      15562
1  101002               8378                       8378
2  101003              15846                      15846
3  101005              15854                      15854
4  101006              13487                      13487
5  101007              14265                      14265
6  101008              18192                      18192
7  101009              19188                      19188
8  101010              15451                      15451
9  101011              20283                      20283

   Benefit type_Antal personer i alt  Year built_Total people
0                              15562                    15562
1                               8378                     8378
2                              15846                    15846
3                              15854                    15854
4                              13487                    13487
5                              14265                    14265
6                              18192                    18192
7                              19188                    19188
8                              15451                    15451
9                              20283                    20283

In [28]:
# Add 'Population' column and remove the redundant total columns
df = combined_dfs[2021]

# Add 'Population' column with values from 'Citizenship_Total'
df['Population'] = df['Citizenship_Total']

# Drop the 4 redundant total columns
cols_to_drop = [
    'Citizenship_Total',
    'Housing type_Total people',
    'Benefit type_Antal personer i alt',
    'Year built_Total people'
]
df = df.drop(columns=cols_to_drop)
combined_dfs[2021] = df
print(f"Updated 2021: {df.shape}")

df_2021 = combined_dfs[2021]

Updated 2021: (61, 99)

In [29]:
df_2021.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 99 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Gruppe                                              61 non-null     object
 1   ValgstedId                                          61 non-null     object
 2   Polling area                                        61 non-null     object
 3   KredsNr                                             61 non-null     object
 4   District                                            61 non-null     object
 5   Municipality                                        61 non-null     object
 6   Socioeconomy_Self-employed                          61 non-null     int64
 7   Socioeconomy_Top executives                         61 non-null     int64
 8   Socioeconomy_Unemployed                             61 non-null     int64
 9   Socioeconomy_Total                                  61 non-null     int64
 10  Sex_Male                                            61 non-null     int64
 11  Sex_Female                                          61 non-null     int64
 12  Age_0-4 years                                       61 non-null     int64
 13  Age_5-9 years                                       61 non-null     int64
 14  Age_10-14 years                                     61 non-null     int64
 15  Age_15-17 years                                     61 non-null     int64
 16  Age_18-19 years                                     61 non-null     int64
 17  Age_20-24 years                                     61 non-null     int64
 18  Age_25-29 years                                     61 non-null     int64
 19  Age_30-34 years                                     61 non-null     int64
 20  Age_35-39 years                                     61 non-null     int64
 21  Age_40-44 years                                     61 non-null     int64
 22  Age_45-49 years                                     61 non-null     int64
 23  Age_50-54 years                                     61 non-null     int64
 24  Age_55-59 years                                     61 non-null     int64
 25  Age_60-64 years                                     61 non-null     int64
 26  Age_65-69 years                                     61 non-null     int64
 27  Age_70- years                                       61 non-null     int64
 28  Citizenship_Denmark                                 61 non-null     int64
 29  Citizenship_Nordic                                  61 non-null     int64
 30  Citizenship_Turkey                                  61 non-null     int64
 31  Citizenship_Former Yugoslavia                       61 non-null     int64
 32  Citizenship_Old EU countries                        61 non-null     int64
 33  Citizenship_New EU countries                        61 non-null     int64
 34  Citizenship_Other Europe                            61 non-null     int64
 35  Citizenship_Africa                                  61 non-null     int64
 36  Citizenship_North America                           61 non-null     int64
 37  Citizenship_South and Central America               61 non-null     int64
 38  Citizenship_Asia and Oceania                        61 non-null     int64
 39  Citizenship_Not specified                           61 non-null     int64
 40  Immigrants_Nordic                                   61 non-null     int64
 41  Immigrants_Turkey                                   61 non-null     int64
 42  Immigrants_Former Yugoslavia                        61 non-null     int64
 43  Immigrants_Old EU countries                         61 non-null     int64
 44  Immigrants_New EU countries                         61 non-null     int64
 45  Immigrants_Other Europe                             61 non-null     int64
 46  Immigrants_Africa                                   61 non-null     int64
 47  Immigrants_North America                            61 non-null     int64
 48  Immigrants_South and Central America                61 non-null     int64
 49  Immigrants_Asia and Oceania                         61 non-null     int64
 50  Immigrants_Not specified                            61 non-null     int64
 51  Immigrants_Total                                    61 non-null     int64
 52  Education_18-29 years_Primary and lower secondary   61 non-null     int64
 53  Education_30-70+ years_Primary and lower secondary  61 non-null     int64
 54  Education_18-29 years_Vocational training           61 non-null     int64
 55  Education_30-70+ years_Vocational training          61 non-null     int64
 56  Education_18-29 years_Long higher education         61 non-null     int64
 57  Education_30-70+ years_Long higher education        61 non-null     int64
 58  Education_18-29 years_Not specified                 61 non-null     int64
 59  Education_30-70+ years_Not specified                61 non-null     int64
 60  Education_Total 18-29 years                         61 non-null     int64
 61  Education_Total 30-70+ years                        61 non-null     int64
 62  Education_Total                                     61 non-null     int64
 63  Housing tenure_Homes_Ejer                           61 non-null     int64
 64  Housing tenure_Homes_Andel                          61 non-null     int64
 65  Housing tenure_Homes_Almen                          61 non-null     int64
 66  Housing tenure_Homes_Private rental                 61 non-null     int64
 67  Housing tenure_People_Ejer                          61 non-null     int64
 68  Housing tenure_People_Andel                         61 non-null     int64
 69  Housing tenure_People_Almen                         61 non-null     int64
 70  Housing tenure_People_Private rental                61 non-null     int64
 71  Housing tenure_Total people                         61 non-null     int64
 72  Housing tenure_Total homes                          61 non-null     int64
 73  Housing type_Homes_Detached house                   61 non-null     int64
 74  Housing type_Homes_Terraced house                   61 non-null     int64
 75  Housing type_Homes_Apartment buildings              61 non-null     int64
 76  Housing type_People_Detached house                  61 non-null     int64
 77  Housing type_People_Terraced house                  61 non-null     int64
 78  Housing type_People_Apartment buildings             61 non-null     int64
 79  Housing type_Total homes                            61 non-null     int64
 80  Benefit type_Kontanthjaelp                          61 non-null     int64
 81  Benefit type_Foertidspension                        61 non-null     int64
 82  Benefit type_Folkepension                           61 non-null     int64
 83  Benefit type_Modtager ikke ydelser                  61 non-null     int64
 84  Crime_Number of arrests                             61 non-null     int64
 85  Income_Median household income                      61 non-null     int64
 86  Income_Total households                             61 non-null     int64
 87  Income_Gross income top20pct                        61 non-null     int64
 88  Car_Households with no car                          61 non-null     int64
 89  Car_Households with 1 car                           61 non-null     int64
 90  Car_Households with 2+ cars                         61 non-null     int64
 91  Year built_People_Before 1960                       61 non-null     int64
 92  Year built_People_1960-2009                         61 non-null     int64
 93  Year built_Homes_Before 1960                        61 non-null     int64
 94  Year built_Homes_1960-2009                          61 non-null     int64
 95  Year built_People_2010-9999                         61 non-null     int64
 96  Year built_Homes_2010-9999                          61 non-null     int64
 97  Year built_Total homes                              61 non-null     int64
 98  Population                                          61 non-null     int64
dtypes: int64(93), object(6)
memory usage: 47.3+ KB

## Translate id columns

In [30]:
translations = {
    'ValgstedId': 'PollingAreaID',
    'Polling area': 'Name',
    'KredsNr': 'DistrictNo'
}
df_2021.rename(columns=translations, inplace=True)

## Reorder and save to csv

In [31]:
column_order_prefixes = [
    'Sex_',
    'Age_',
    'Citizenship_',
    'Income_',
    'Car_',
    'Crime_',
    'Benefit type_',
    'Housing type_',
    'Year built_',
    'Housing tenure_',
    'Education_',
    'Immigrants_',
    'Socioeconomy_'
]

df = combined_dfs[2021]

# Start with the first 7 columns
first_cols = ['Gruppe', 'PollingAreaID', 'Name', 'DistrictNo', 'District', 'Municipality', 'Population']
ordered_cols = first_cols.copy()

# Add columns in the specified prefix order
for prefix in column_order_prefixes:
    matching_cols = [col for col in df.columns if col.startswith(prefix) and col not in ordered_cols]
    ordered_cols.extend(sorted(matching_cols))  # Sort alphabetically within each group

# Add any remaining columns that weren't caught (shouldn't be any, but just in case)
remaining_cols = [col for col in df.columns if col not in ordered_cols]
if remaining_cols:
    print(f"Warning: 2021 has unexpected columns: {remaining_cols}")
    ordered_cols.extend(remaining_cols)

# Reorder the dataframe
df = df[ordered_cols]
combined_dfs[2021] = df
print(f"Reordered 2021: {df.shape}")

# Reassign
df_2021 = combined_dfs[2021]
    
# Save to CSV
output_path = f'{OUTPUT_PATH}absolute_{2021}.csv'
df_2021.to_csv(output_path, index=False)
print(f"Saved {output_path}")

# Verify the column order
print("\nColumn order for df_2021:")
for i, col in enumerate(df_2021.columns[:20], 1):
    print(f"{i}. {col}")

Reordered 2021: (61, 99)
Saved ../../../processed-data/2021-special/absolute_2021.csv

Column order for df_2021:
1. Gruppe
2. PollingAreaID
3. Name
4. DistrictNo
5. District
6. Municipality
7. Population
8. Sex_Female
9. Sex_Male
10. Age_0-4 years
11. Age_10-14 years
12. Age_15-17 years
13. Age_18-19 years
14. Age_20-24 years
15. Age_25-29 years
16. Age_30-34 years
17. Age_35-39 years
18. Age_40-44 years
19. Age_45-49 years
20. Age_5-9 years

## Election data

In [32]:
votes = pd.read_csv(ELECTION_PATH, sep=';', dtype=str)
votes = votes[votes['Gruppe'].isin(CPH_AREAS)]
votes.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 60
Data columns (total 75 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gruppe                             61 non-null     object
 1   ValgstedId                         61 non-null     object
 2   KredsNr                            61 non-null     object
 3   StorKredsNr                        61 non-null     object
 4   LandsdelsNr                        61 non-null     object
 5   KV2021 - Stemmeberettigede         61 non-null     object
 6   KV2021 - Afgivne stemmer           61 non-null     object
 7   KV2021 - Blanke stemmer            61 non-null     object
 8   KV2021 - Andre ugyldige stemmer    61 non-null     object
 9   KV2021 - Gyldige stemmer           61 non-null     object
 10  KV2021 - A                         61 non-null     object
 11  KV2021 - B                         61 non-null     object
 12  KV2021 - C                         61 non-null     object
 13  KV2021 - D                         61 non-null     object
 14  KV2021 - F                         61 non-null     object
 15  KV2021 - I                         61 non-null     object
 16  KV2021 - J                         61 non-null     object
 17  KV2021 - G                         61 non-null     object
 18  KV2021 - K                         61 non-null     object
 19  KV2021 - N                         61 non-null     object
 20  KV2021 - H                         61 non-null     object
 21  KV2021 - M                         61 non-null     object
 22  KV2021 - S                         61 non-null     object
 23  KV2021 - U                         61 non-null     object
 24  KV2021 - O                         61 non-null     object
 25  KV2021 - Z                         61 non-null     object
 26  KV2021 - L                         61 non-null     object
 27  KV2021 - R                         61 non-null     object
 28  KV2021 - V                         61 non-null     object
 29  KV2021 - P                         61 non-null     object
 30  KV2021 - E                         61 non-null     object
 31  KV2021 - Ø                         61 non-null     object
 32  KV2021 - Å                         61 non-null     object
 33  KV2021 - K1                        61 non-null     object
 34  KV2021 - K2                        61 non-null     object
 35  KV2021 - Q                         61 non-null     object
 36  KV2021 - T                         61 non-null     object
 37  KV2021 - W                         61 non-null     object
 38  KV2021 - Y                         61 non-null     object
 39  KV2021 - Æ                         61 non-null     object
 40  KV2021 - Å1                        61 non-null     object
 41  KV2021 - Stemmeberettigede.1       61 non-null     object
 42  KV2021 - Afgivne stemmer.1         61 non-null     object
 43  KV2021 - Blanke stemmer.1          61 non-null     object
 44  KV2021 - Andre ugyldige stemmer.1  61 non-null     object
 45  KV2021 - Gyldige stemmer.1         61 non-null     object
 46  KV2021 - A.1                       61 non-null     object
 47  KV2021 - B.1                       61 non-null     object
 48  KV2021 - C.1                       61 non-null     object
 49  KV2021 - D.1                       61 non-null     object
 50  KV2021 - F.1                       61 non-null     object
 51  KV2021 - I.1                       61 non-null     object
 52  KV2021 - J.1                       61 non-null     object
 53  KV2021 - G.1                       61 non-null     object
 54  KV2021 - K.1                       61 non-null     object
 55  KV2021 - N.1                       61 non-null     object
 56  KV2021 - H.1                       61 non-null     object
 57  KV2021 - M.1                       61 non-null     object
 58  KV2021 - S.1                       61 non-null     object
 59  KV2021 - U.1                       61 non-null     object
 60  KV2021 - O.1                       61 non-null     object
 61  KV2021 - Z.1                       61 non-null     object
 62  KV2021 - L.1                       61 non-null     object
 63  KV2021 - R.1                       61 non-null     object
 64  KV2021 - V.1                       61 non-null     object
 65  KV2021 - P.1                       61 non-null     object
 66  KV2021 - E.1                       61 non-null     object
 67  KV2021 - Ø.1                       61 non-null     object
 68  KV2021 - Å.1                       61 non-null     object
 69  KV2021 - 0                         61 non-null     object
 70  KV2021 - Q.1                       61 non-null     object
 71  KV2021 - T.1                       61 non-null     object
 72  KV2021 - W.1                       61 non-null     object
 73  KV2021 - Y.1                       61 non-null     object
 74  KV2021 - Æ.1                       61 non-null     object
dtypes: object(75)
memory usage: 36.2+ KB

### Convert dtypes to numeric

In [33]:
party_cols = [col for col in votes.columns if col.startswith(PREFIX) and any(f'{PREFIX}2021 - ')]

# To numeric
for col in party_cols:
    votes[col] = votes[col].replace('-', '')
    votes[col] = votes[col].str.replace(',', '.', regex=False)
    votes[col] = pd.to_numeric(votes[col], errors='coerce')

# Drop columns with no non-null values
votes = votes.dropna(axis=1, how='all')
party_cols = [col for col in votes.columns if col.startswith(PREFIX) and any(f'{PREFIX}2021 - ')]

# Fill NaN with 0 for party columns
for col in party_cols:
    votes[col] = votes[col].fillna(0)

# Convert to int if no fractional part
for col in party_cols:
    if (votes[col].dropna() % 1 == 0).all():
        votes[col] = votes[col].astype('int64')

votes.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 60
Data columns (total 68 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Gruppe                             61 non-null     object
 1   ValgstedId                         61 non-null     object
 2   KredsNr                            61 non-null     object
 3   StorKredsNr                        61 non-null     object
 4   LandsdelsNr                        61 non-null     object
 5   KV2021 - Stemmeberettigede         61 non-null     int64
 6   KV2021 - Afgivne stemmer           61 non-null     int64
 7   KV2021 - Blanke stemmer            61 non-null     int64
 8   KV2021 - Andre ugyldige stemmer    61 non-null     int64
 9   KV2021 - Gyldige stemmer           61 non-null     int64
 10  KV2021 - A                         61 non-null     int64
 11  KV2021 - B                         61 non-null     int64
 12  KV2021 - C                         61 non-null     int64
 13  KV2021 - D                         61 non-null     int64
 14  KV2021 - F                         61 non-null     int64
 15  KV2021 - I                         61 non-null     int64
 16  KV2021 - J                         61 non-null     int64
 17  KV2021 - G                         61 non-null     int64
 18  KV2021 - K                         61 non-null     int64
 19  KV2021 - N                         61 non-null     int64
 20  KV2021 - H                         61 non-null     int64
 21  KV2021 - M                         61 non-null     int64
 22  KV2021 - U                         61 non-null     int64
 23  KV2021 - O                         61 non-null     int64
 24  KV2021 - Z                         61 non-null     int64
 25  KV2021 - L                         61 non-null     int64
 26  KV2021 - R                         61 non-null     int64
 27  KV2021 - V                         61 non-null     int64
 28  KV2021 - P                         61 non-null     int64
 29  KV2021 - E                         61 non-null     int64
 30  KV2021 - Ø                         61 non-null     int64
 31  KV2021 - Å                         61 non-null     int64
 32  KV2021 - Q                         61 non-null     int64
 33  KV2021 - T                         61 non-null     int64
 34  KV2021 - Y                         61 non-null     int64
 35  KV2021 - Æ                         61 non-null     int64
 36  KV2021 - Stemmeberettigede.1       61 non-null     int64
 37  KV2021 - Afgivne stemmer.1         61 non-null     int64
 38  KV2021 - Blanke stemmer.1          61 non-null     int64
 39  KV2021 - Andre ugyldige stemmer.1  61 non-null     int64
 40  KV2021 - Gyldige stemmer.1         61 non-null     int64
 41  KV2021 - A.1                       61 non-null     int64
 42  KV2021 - B.1                       61 non-null     int64
 43  KV2021 - C.1                       61 non-null     int64
 44  KV2021 - D.1                       61 non-null     int64
 45  KV2021 - F.1                       61 non-null     int64
 46  KV2021 - I.1                       61 non-null     int64
 47  KV2021 - J.1                       61 non-null     int64
 48  KV2021 - G.1                       61 non-null     int64
 49  KV2021 - K.1                       61 non-null     int64
 50  KV2021 - N.1                       61 non-null     int64
 51  KV2021 - H.1                       61 non-null     int64
 52  KV2021 - M.1                       61 non-null     int64
 53  KV2021 - U.1                       61 non-null     int64
 54  KV2021 - O.1                       61 non-null     int64
 55  KV2021 - Z.1                       61 non-null     int64
 56  KV2021 - L.1                       61 non-null     int64
 57  KV2021 - R.1                       61 non-null     int64
 58  KV2021 - V.1                       61 non-null     int64
 59  KV2021 - P.1                       61 non-null     int64
 60  KV2021 - E.1                       61 non-null     int64
 61  KV2021 - Ø.1                       61 non-null     int64
 62  KV2021 - Å.1                       61 non-null     int64
 63  KV2021 - 0                         61 non-null     int64
 64  KV2021 - Q.1                       61 non-null     int64
 65  KV2021 - T.1                       61 non-null     int64
 66  KV2021 - Y.1                       61 non-null     int64
 67  KV2021 - Æ.1                       61 non-null     int64
dtypes: int64(63), object(5)
memory usage: 32.9+ KB

In [34]:
votes.head()

,Gruppe,ValgstedId,KredsNr,StorKredsNr,LandsdelsNr,KV2021 - Stemmeberettigede,KV2021 - Afgivne stemmer,KV2021 - Blanke stemmer,KV2021 - Andre ugyldige stemmer,KV2021 - Gyldige stemmer,...,KV2021 - V.1,KV2021 - P.1,KV2021 - E.1,KV2021 - Ø.1,KV2021 - Å.1,KV2021 - 0,KV2021 - Q.1,KV2021 - T.1,KV2021 - Y.1,KV2021 - Æ.1
0,101001,101001,1,1,1,12518,8360,110,25,8225,...,731,2,2,1532,217,0,10,24,12,11
1,101002,101002,1,1,1,6859,4504,50,14,4440,...,515,0,4,699,102,0,2,20,6,3
2,101003,101003,1,1,1,12504,9094,99,23,8972,...,757,1,6,1893,215,0,6,28,9,8
3,101005,101005,1,1,1,12953,7643,117,18,7508,...,588,0,6,1599,185,0,7,24,15,8
4,101006,101006,1,1,1,11149,7039,92,29,6918,...,581,3,5,1282,170,2,5,32,8,10

### Add some geography columns, drop others

In [35]:
def add_geography_columns(df):
    geo_df = pd.read_csv(PATH + 'Geography.csv', sep=';', encoding='utf-8', quotechar='"')
    geo_df.columns = geo_df.columns.str.strip().str.strip('"')
    geo_df = geo_df[geo_df['KommuneNr'].astype(str).isin(['101', '147'])].copy()
    
    print("Geography CSV columns:", geo_df.columns.tolist())
    print("First few Valgsted Ids:", geo_df['Valgsted Id'].head().tolist())

    geo_dict = {}
    for _, row in geo_df.iterrows():
        valgsted_id = str(row['Valgsted Id']).strip().strip('"')
        geo_dict[valgsted_id] = {
            'Valgsted navn': str(row['Valgsted navn']).strip().strip('"'),
            'Kreds navn': str(row['Kreds navn']).strip().strip('"'),
            'Kommune navn': str(row['Kommune navn']).strip().strip('"')
        }

    print(f"Total entries in geo_dict: {len(geo_dict)}")
    print(f"Sample keys: {list(geo_dict.keys())[:5]}")
    
    df_result = df.copy()
    valgsted_navne = []
    kreds_navne = []
    kommune_navne = []
    
    for _, row in df_result.iterrows():
        valgsted_ids = str(row['ValgstedId']).split(';')
        v_names = []
        k_names = []
        kom_names = []

        for vid in valgsted_ids:
            vid = vid.strip()
            if vid not in geo_dict:
                print(f"Missing ValgstedId: '{vid}' (length: {len(vid)})")
                print(f"Available keys starting with '101': {[k for k in geo_dict.keys() if k.startswith('101')][:10]}")
                raise ValueError(f"ValgstedId '{vid}' not found in Geography.csv")
            
            v_names.append(geo_dict[vid]['Valgsted navn'])
            k_names.append(geo_dict[vid]['Kreds navn'])
            kom_names.append(geo_dict[vid]['Kommune navn'])

        # Join with semicolons, remove duplicates while preserving order
        valgsted_navne.append(';'.join(v_names))
        
        # For Kreds and Kommune, use single value if all same, otherwise semicolon-separate
        if len(set(k_names)) == 1:
            kreds_navne.append(k_names[0])
        else:
            kreds_navne.append(';'.join(k_names))
            
        if len(set(kom_names)) == 1:
            kommune_navne.append(kom_names[0])
        else:
            kommune_navne.append(';'.join(kom_names))

    df_result['Valgsted navn'] = valgsted_navne
    df_result['Kreds navn'] = kreds_navne
    df_result['Kommune navn'] = kommune_navne
    df_result = df_result.drop(columns=['StorKredsNr', 'LandsdelsNr'])
    
    # Reorder columns
    first_cols = ['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn', 'Kommune navn']
    other_cols = [col for col in df_result.columns if col not in first_cols]
    df_result = df_result[first_cols + other_cols]
    
    return df_result

votes = add_geography_columns(votes)
print(f"Added geography columns to 2021")

# Check the result
print("\nFirst few rows of votes:")
print(votes[['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn', 'Kommune navn']].head(10))

Geography CSV columns: ['Valgsted Id', 'KommuneNr', 'Kreds Nr', 'Storkreds Nr', 'Landsdels Nr', 'Valgsted navn', 'Kommune navn', 'Kreds navn', 'Storkreds navn', 'Landsdels navn', 'Valgsted start', 'Valgsted stop']
First few Valgsted Ids: [101001, 101002, 101003, 101005, 101006]
Total entries in geo_dict: 61
Sample keys: ['101001', '101002', '101003', '101005', '101006']
Added geography columns to 2021

First few rows of votes:
   Gruppe ValgstedId    Valgsted navn KredsNr       Kreds navn Kommune navn
0  101001     101001      1. Østerbro       1      1. Østerbro    København
1  101002     101002          1. Nord       1      1. Østerbro    København
2  101003     101003           1. Syd       1      1. Østerbro    København
3  101005     101005          1. Vest       1      1. Østerbro    København
4  101006     101006      1. Nordvest       1      1. Østerbro    København
5  101007     101007  2. Sundbyvester       2  2. Sundbyvester    København
6  101008     101008          2. Nord       2  2. Sundbyvester    København
7  101009     101009           2. Syd       2  2. Sundbyvester    København
8  101010     101010          2. Vest       2  2. Sundbyvester    København
9  101011     101011      3. Indre By       3      3. Indre By    København

### Check duplicate votes column

In [36]:
print(votes.columns.tolist())

['Gruppe', 'ValgstedId', 'Valgsted navn', 'KredsNr', 'Kreds navn', 'Kommune navn', 'KV2021 - Stemmeberettigede', 'KV2021 - Afgivne stemmer', 'KV2021 - Blanke stemmer', 'KV2021 - Andre ugyldige stemmer', 'KV2021 - Gyldige stemmer', 'KV2021 - A', 'KV2021 - B', 'KV2021 - C', 'KV2021 - D', 'KV2021 - F', 'KV2021 - I', 'KV2021 - J', 'KV2021 - G', 'KV2021 - K', 'KV2021 - N', 'KV2021 - H', 'KV2021 - M', 'KV2021 - U', 'KV2021 - O', 'KV2021 - Z', 'KV2021 - L', 'KV2021 - R', 'KV2021 - V', 'KV2021 - P', 'KV2021 - E', 'KV2021 - Ø', 'KV2021 - Å', 'KV2021 - Q', 'KV2021 - T', 'KV2021 - Y', 'KV2021 - Æ', 'KV2021 - Stemmeberettigede.1', 'KV2021 - Afgivne stemmer.1', 'KV2021 - Blanke stemmer.1', 'KV2021 - Andre ugyldige stemmer.1', 'KV2021 - Gyldige stemmer.1', 'KV2021 - A.1', 'KV2021 - B.1', 'KV2021 - C.1', 'KV2021 - D.1', 'KV2021 - F.1', 'KV2021 - I.1', 'KV2021 - J.1', 'KV2021 - G.1', 'KV2021 - K.1', 'KV2021 - N.1', 'KV2021 - H.1', 'KV2021 - M.1', 'KV2021 - U.1', 'KV2021 - O.1', 'KV2021 - Z.1', 'KV2021 - L.1', 'KV2021 - R.1', 'KV2021 - V.1', 'KV2021 - P.1', 'KV2021 - E.1', 'KV2021 - Ø.1', 'KV2021 - Å.1', 'KV2021 - 0', 'KV2021 - Q.1', 'KV2021 - T.1', 'KV2021 - Y.1', 'KV2021 - Æ.1']

In [37]:
votes.columns = votes.columns.str.replace('^KV2021 - ', '', regex=True)
votes.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 60
Data columns (total 69 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Gruppe                    61 non-null     object
 1   ValgstedId                61 non-null     object
 2   Valgsted navn             61 non-null     object
 3   KredsNr                   61 non-null     object
 4   Kreds navn                61 non-null     object
 5   Kommune navn              61 non-null     object
 6   Stemmeberettigede         61 non-null     int64
 7   Afgivne stemmer           61 non-null     int64
 8   Blanke stemmer            61 non-null     int64
 9   Andre ugyldige stemmer    61 non-null     int64
 10  Gyldige stemmer           61 non-null     int64
 11  A                         61 non-null     int64
 12  B                         61 non-null     int64
 13  C                         61 non-null     int64
 14  D                         61 non-null     int64
 15  F                         61 non-null     int64
 16  I                         61 non-null     int64
 17  J                         61 non-null     int64
 18  G                         61 non-null     int64
 19  K                         61 non-null     int64
 20  N                         61 non-null     int64
 21  H                         61 non-null     int64
 22  M                         61 non-null     int64
 23  U                         61 non-null     int64
 24  O                         61 non-null     int64
 25  Z                         61 non-null     int64
 26  L                         61 non-null     int64
 27  R                         61 non-null     int64
 28  V                         61 non-null     int64
 29  P                         61 non-null     int64
 30  E                         61 non-null     int64
 31  Ø                         61 non-null     int64
 32  Å                         61 non-null     int64
 33  Q                         61 non-null     int64
 34  T                         61 non-null     int64
 35  Y                         61 non-null     int64
 36  Æ                         61 non-null     int64
 37  Stemmeberettigede.1       61 non-null     int64
 38  Afgivne stemmer.1         61 non-null     int64
 39  Blanke stemmer.1          61 non-null     int64
 40  Andre ugyldige stemmer.1  61 non-null     int64
 41  Gyldige stemmer.1         61 non-null     int64
 42  A.1                       61 non-null     int64
 43  B.1                       61 non-null     int64
 44  C.1                       61 non-null     int64
 45  D.1                       61 non-null     int64
 46  F.1                       61 non-null     int64
 47  I.1                       61 non-null     int64
 48  J.1                       61 non-null     int64
 49  G.1                       61 non-null     int64
 50  K.1                       61 non-null     int64
 51  N.1                       61 non-null     int64
 52  H.1                       61 non-null     int64
 53  M.1                       61 non-null     int64
 54  U.1                       61 non-null     int64
 55  O.1                       61 non-null     int64
 56  Z.1                       61 non-null     int64
 57  L.1                       61 non-null     int64
 58  R.1                       61 non-null     int64
 59  V.1                       61 non-null     int64
 60  P.1                       61 non-null     int64
 61  E.1                       61 non-null     int64
 62  Ø.1                       61 non-null     int64
 63  Å.1                       61 non-null     int64
 64  0                         61 non-null     int64
 65  Q.1                       61 non-null     int64
 66  T.1                       61 non-null     int64
 67  Y.1                       61 non-null     int64
 68  Æ.1                       61 non-null     int64
dtypes: int64(63), object(6)
memory usage: 33.4+ KB

In [38]:
# Identify columns that have duplicates
base_columns = {col[:-2] for col in votes.columns if col.endswith('.1')}

# Check for equality of duplicate columns
duplicate_checks = {}
for base in base_columns:
    col1 = f"{base}"
    col2 = f"{base}.1"
    if votes[col1].equals(votes[col2]):
        duplicate_checks[base] = True
    else:
        duplicate_checks[base] = False

# Display results
for base, are_equal in duplicate_checks.items():
    if are_equal:
        print(f"Columns '{base}' and '{base}.1' are identical.")
    else:
        print(f"Columns '{base}' and '{base}.1' are NOT identical.")

Columns 'L' and 'L.1' are identical.
Columns 'A' and 'A.1' are identical.
Columns 'Gyldige stemmer' and 'Gyldige stemmer.1' are identical.
Columns 'N' and 'N.1' are identical.
Columns 'E' and 'E.1' are identical.
Columns 'H' and 'H.1' are identical.
Columns 'Afgivne stemmer' and 'Afgivne stemmer.1' are identical.
Columns 'K' and 'K.1' are identical.
Columns 'Ø' and 'Ø.1' are identical.
Columns 'Å' and 'Å.1' are identical.
Columns 'Æ' and 'Æ.1' are identical.
Columns 'Stemmeberettigede' and 'Stemmeberettigede.1' are identical.
Columns 'P' and 'P.1' are identical.
Columns 'M' and 'M.1' are identical.
Columns 'U' and 'U.1' are identical.
Columns 'F' and 'F.1' are identical.
Columns 'O' and 'O.1' are identical.
Columns 'T' and 'T.1' are identical.
Columns 'B' and 'B.1' are identical.
Columns 'R' and 'R.1' are identical.
Columns 'J' and 'J.1' are identical.
Columns 'I' and 'I.1' are identical.
Columns 'C' and 'C.1' are identical.
Columns 'V' and 'V.1' are identical.
Columns 'Q' and 'Q.1' are identical.
Columns 'D' and 'D.1' are identical.
Columns 'Andre ugyldige stemmer' and 'Andre ugyldige stemmer.1' are identical.
Columns 'Blanke stemmer' and 'Blanke stemmer.1' are identical.
Columns 'G' and 'G.1' are identical.
Columns 'Z' and 'Z.1' are identical.
Columns 'Y' and 'Y.1' are identical.

In [39]:
# Drop columns ending with '.1'
votes = votes.loc[:, ~votes.columns.str.endswith('.1')]
votes.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 60
Data columns (total 38 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gruppe                  61 non-null     object
 1   ValgstedId              61 non-null     object
 2   Valgsted navn           61 non-null     object
 3   KredsNr                 61 non-null     object
 4   Kreds navn              61 non-null     object
 5   Kommune navn            61 non-null     object
 6   Stemmeberettigede       61 non-null     int64
 7   Afgivne stemmer         61 non-null     int64
 8   Blanke stemmer          61 non-null     int64
 9   Andre ugyldige stemmer  61 non-null     int64
 10  Gyldige stemmer         61 non-null     int64
 11  A                       61 non-null     int64
 12  B                       61 non-null     int64
 13  C                       61 non-null     int64
 14  D                       61 non-null     int64
 15  F                       61 non-null     int64
 16  I                       61 non-null     int64
 17  J                       61 non-null     int64
 18  G                       61 non-null     int64
 19  K                       61 non-null     int64
 20  N                       61 non-null     int64
 21  H                       61 non-null     int64
 22  M                       61 non-null     int64
 23  U                       61 non-null     int64
 24  O                       61 non-null     int64
 25  Z                       61 non-null     int64
 26  L                       61 non-null     int64
 27  R                       61 non-null     int64
 28  V                       61 non-null     int64
 29  P                       61 non-null     int64
 30  E                       61 non-null     int64
 31  Ø                       61 non-null     int64
 32  Å                       61 non-null     int64
 33  Q                       61 non-null     int64
 34  T                       61 non-null     int64
 35  Y                       61 non-null     int64
 36  Æ                       61 non-null     int64
 37  0                       61 non-null     int64
dtypes: int64(32), object(6)
memory usage: 18.6+ KB

### Translate Danish columns

In [40]:
translations = {
    'ValgstedId': 'PollingAreaID',
    'Valgsted navn': 'Name',
    'KredsNr': 'DistrictNo',
    'Kreds navn': 'District',
    'Kommune navn': 'Municipality',
    'Stemmeberettigede': 'Eligible voters',
    'Afgivne stemmer': 'Voter turnout',
    'Blanke stemmer': 'Blank votes',
    'Andre ugyldige stemmer': 'Other invalid votes',
    'Gyldige stemmer': 'Valid votes'
}

votes.rename(columns=translations, inplace=True)
votes.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 60
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gruppe               61 non-null     object
 1   PollingAreaID        61 non-null     object
 2   Name                 61 non-null     object
 3   DistrictNo           61 non-null     object
 4   District             61 non-null     object
 5   Municipality         61 non-null     object
 6   Eligible voters      61 non-null     int64
 7   Voter turnout        61 non-null     int64
 8   Blank votes          61 non-null     int64
 9   Other invalid votes  61 non-null     int64
 10  Valid votes          61 non-null     int64
 11  A                    61 non-null     int64
 12  B                    61 non-null     int64
 13  C                    61 non-null     int64
 14  D                    61 non-null     int64
 15  F                    61 non-null     int64
 16  I                    61 non-null     int64
 17  J                    61 non-null     int64
 18  G                    61 non-null     int64
 19  K                    61 non-null     int64
 20  N                    61 non-null     int64
 21  H                    61 non-null     int64
 22  M                    61 non-null     int64
 23  U                    61 non-null     int64
 24  O                    61 non-null     int64
 25  Z                    61 non-null     int64
 26  L                    61 non-null     int64
 27  R                    61 non-null     int64
 28  V                    61 non-null     int64
 29  P                    61 non-null     int64
 30  E                    61 non-null     int64
 31  Ø                    61 non-null     int64
 32  Å                    61 non-null     int64
 33  Q                    61 non-null     int64
 34  T                    61 non-null     int64
 35  Y                    61 non-null     int64
 36  Æ                    61 non-null     int64
 37  0                    61 non-null     int64
dtypes: int64(32), object(6)
memory usage: 18.6+ KB

### Save to CSV

In [41]:
filename = f'{OUTPUT_PATH}votes_absolute_2021.csv'
votes.to_csv(filename, index=False)
print(f"Saved {filename}")

Saved ../../../processed-data/2021-special/votes_absolute_2021.csv

### Convert to % and save to new CSV

In [42]:
votes_rel = votes.copy()
gyldige_idx = votes_rel.columns.get_loc('Valid votes')
party_cols = votes_rel.columns[gyldige_idx + 1:].tolist()

# Convert party columns to percentage of 'Gyldige stemmer'
votes_rel[party_cols] = votes_rel[party_cols].div(votes_rel['Valid votes'], axis=0) * 100

# Convert 'Blanke stemmer', 'Andre ugyldige stemmer', 'Gyldige stemmer' to percentage of 'Afgivne stemmer'
for col in ['Blank votes', 'Other invalid votes', 'Valid votes']:
    votes_rel[col] = votes_rel[col].div(votes_rel['Voter turnout'], axis=0) * 100

# Convert 'Afgivne stemmer' to percentage of 'Stemmeberettigede'
votes_rel['Voter turnout'] = votes_rel['Voter turnout'].div(votes_rel['Eligible voters'], axis=0) * 100

# Save to CSV
filename = f'{OUTPUT_PATH}votes_relative_2021.csv'
votes_rel.to_csv(filename, index=False)
print(f"Saved {filename}")

Saved ../../../processed-data/2021-special/votes_relative_2021.csv